CREATE TABLE abs_mdi."Accessories_Liners" (
  "LinerId" NUMBER(10) NOT NULL,
  "BuildingNumber" NUMBER(10) NOT NULL,
  "ProjectId" NUMBER(10) NOT NULL,
  "Elevation" VARCHAR2(50 BYTE) DEFAULT '',
  "BayNumber" NUMBER(10) DEFAULT 0,
  "DistFromLeftCorner" NUMBER(10,4) DEFAULT 0,
  "DistFromLeftCol" NUMBER(10,4) DEFAULT 0,
  "FullHeight" NUMBER(10) DEFAULT 0,
  "Height" NUMBER(10,4) DEFAULT 0,
  "Length" NUMBER(10,4) DEFAULT 0,
  "PanelType" NUMBER(10) DEFAULT 0,
  "PanelGauge" NUMBER(10) DEFAULT 0,
  "PanelColor" VARCHAR2(100 BYTE) DEFAULT '',
  "JambTrim" CHAR DEFAULT 'N',
  "FramedOpeningTrim" CHAR DEFAULT 'N',
  "CapTrim" CHAR DEFAULT 'N',
  "ColTrim" CHAR DEFAULT 'N',
  "BaseAngle" CHAR DEFAULT 'N',
  "SheetAngle" CHAR DEFAULT 'N',
  "BaseChannel" CHAR DEFAULT 'N',
  "Weight" NUMBER(10,2) DEFAULT 0,
  "Price" NUMBER(10,2) DEFAULT 0,
  "IsPriced" CHAR DEFAULT 'N',
  "ErrorCode" NUMBER(10) DEFAULT 0,
  "FlashColor" VARCHAR2(100 BYTE) DEFAULT '',
  "OptionalLinerFlash" NUMBER(10) DEFAULT 0,
  "BaseType" VARCHAR2(100 BYTE) DEFAULT '',
  "CapTrimColor" VARCHAR2(100 BYTE) DEFAULT '',
  "PurlinTrimColor" VARCHAR2(100 BYTE) DEFAULT '',
  "InsideCornerTrimColor" VARCHAR2(100 BYTE) DEFAULT '',
  "ColumnTieTrimColor" VARCHAR2(100 BYTE) DEFAULT '',
  "RidgeTrimGauge" NUMBER(10) DEFAULT 0,
  "RidgeTrimFinish" VARCHAR2(100 BYTE) DEFAULT '',
  "RidgeTrimColor" VARCHAR2(100 BYTE) DEFAULT '',
  "RafterTieTrimGauge" NUMBER(10) DEFAULT 0,
  "RafterTieTrimFinish" VARCHAR2(100 BYTE) DEFAULT '',
  "RafterTieTrimColor" VARCHAR2(100 BYTE) DEFAULT '',
  "EaveToWallTrimGauge" NUMBER(10) DEFAULT 0,
  "EaveToWallTrimFinish" VARCHAR2(100 BYTE) DEFAULT '',
  "EaveToWallTrimColor" VARCHAR2(100 BYTE) DEFAULT '',
  "PanelFinish" VARCHAR2(100 BYTE) DEFAULT '',
  "Width" NUMBER(10,2) DEFAULT 0,
  "LinerCoverage" NUMBER(10) DEFAULT 0,
  "StartColumn" NUMBER(10) DEFAULT 0,
  "StopColumn" NUMBER(10) DEFAULT 0,
  "XFrom" VARCHAR2(50 BYTE) DEFAULT '',
  "XTo" VARCHAR2(50 BYTE) DEFAULT '',
  "YFrom" VARCHAR2(50 BYTE) DEFAULT '',
  "YTo" VARCHAR2(50 BYTE) DEFAULT '',
  "ReverseRoll" VARCHAR2(20 BYTE) DEFAULT 'N',
  "WeightMBCI" NUMBER(10,2) DEFAULT 0,
  "PriceMBCI" NUMBER(10,2) DEFAULT 0,
  "TopTermination" VARCHAR2(100 BYTE) DEFAULT '',
  "PartitionNumber" NUMBER(10) DEFAULT 0,
  "FullLength" NUMBER(10) DEFAULT 0,
  "GirtNote" NUMBER(10) DEFAULT 0,
  "FastenerHeadFinish" NUMBER(10) DEFAULT 0,
  "FastenerLength" NUMBER(10) DEFAULT 0,
  "PanelColorValsparCode" VARCHAR2(100 BYTE) DEFAULT '',
  "PanelColorSpecialName" VARCHAR2(100 BYTE) DEFAULT '',
  "FlashColorValsparCode" VARCHAR2(100 BYTE) DEFAULT '',
  "FlashColorSpecialName" VARCHAR2(100 BYTE) DEFAULT '',
  "CapTrimColorValsparCode" VARCHAR2(100 BYTE) DEFAULT '',
  "CapTrimColorSpecialName" VARCHAR2(100 BYTE) DEFAULT '',
  "PurlinTrimColorValsparCode" VARCHAR2(100 BYTE) DEFAULT '',
  "PurlinTrimColorSpecialName" VARCHAR2(100 BYTE) DEFAULT '',
  "InsideCornerTrimColorValsparCode" VARCHAR2(100 BYTE) DEFAULT '',
  "InsideCornerTrimColorSpecialName" VARCHAR2(100 BYTE) DEFAULT '',
  "ColumnTieTrimColorValsparCode" VARCHAR2(100 BYTE) DEFAULT '',
  "ColumnTieTrimColorSpecialName" VARCHAR2(100 BYTE) DEFAULT '',
  "RidgeTrimColorValsparCode" VARCHAR2(100 BYTE) DEFAULT '',
  "RidgeTrimColorSpecialName" VARCHAR2(100 BYTE) DEFAULT '',
  "RafterTieTrimColorValsparCode" VARCHAR2(100 BYTE) DEFAULT '',
  "RafterTieTrimColorSpecialName" VARCHAR2(100 BYTE) DEFAULT '',
  "EaveToWallTrimColorValsparCode" VARCHAR2(100 BYTE) DEFAULT '',
  "EaveToWallTrimColorSpecialName" VARCHAR2(100 BYTE) DEFAULT '',
  "CreatedBy" NUMBER,
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER,
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDelete" CHAR DEFAULT 'N',
  "Qty" NUMBER(5) DEFAULT 0,
  CONSTRAINT "Accessories_Liners_PK" PRIMARY KEY ("LinerId")
);