CREATE TABLE abs_mdi."Accesories_Partition" (
  "PartitionId" NUMBER(10) NOT NULL,
  "BuildingNumber" NUMBER(10),
  "Type" NUMBER(5),
  "Length" VARCHAR2(10 BYTE),
  "Height" VARCHAR2(10 BYTE),
  "DistFromEndWall" VARCHAR2(10 BYTE),
  "DistFromSideWall" VARCHAR2(10 BYTE),
  "FullHeight" CHAR,
  "PanelType" NUMBER(5),
  "Width" NUMBER(5),
  "Thickness" NUMBER(5),
  "ReverseRoll" CHAR,
  "ExteriorProfile" NUMBER,
  "ExteriorGuage" NUMBER,
  "ExteriorTexture" NUMBER,
  "ExteriorColor" VARCHAR2(100 BYTE),
  "ExteriorColorSpecialName" VARCHAR2(100 BYTE),
  "ExteriorColorValsparCode" VARCHAR2(100 BYTE),
  "InteriorProfile" NUMBER(5),
  "InteriorGuage" NUMBER(5),
  "InteriorTexture" NUMBER(5),
  "InteriorColor" VARCHAR2(100 BYTE),
  "InteriorColorSpecialName" VARCHAR2(100 BYTE),
  "InteriorColorValsparCode" VARCHAR2(100 BYTE),
  "FactoryAppliedSealant" NUMBER(5),
  "SheeterSide" VARCHAR2(100 BYTE),
  "ExteriorWall" VARCHAR2(10 BYTE),
  "RecessFoundation" CHAR,
  "BaseClosureStrips" CHAR,
  "PurlinTrimColor" VARCHAR2(100 BYTE),
  "PurlinTrimColorSpecialName" VARCHAR2(100 BYTE),
  "PurlinTrimColorValsparCode" VARCHAR2(100 BYTE),
  "CornerTrimColor" VARCHAR2(100 BYTE),
  "CornerTrimColorSpecialName" VARCHAR2(100 BYTE),
  "CornerTrimColorValsparCode" VARCHAR2(100 BYTE),
  "FramingByOthers" CHAR,
  "BaseCondition" NUMBER(5),
  "FastenerHeadFinish" NUMBER(5),
  "FastenerLength" NUMBER(5),
  "GirtSpacing" VARCHAR2(20 BYTE),
  "IsDelete" CHAR DEFAULT 'N',
  "CreatedBy" NUMBER(10),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "ProjectId" NUMBER(10),
  "GirtDepth" NUMBER,
  "GirtType" NUMBER,
  "StructuralPrice" NUMBER(10,2),
  "Elevation" VARCHAR2(20 BYTE),
  "BaseHeight" NUMBER(10,2),
  "DistFromWall" NUMBER(10,2),
  "PanelFinish" VARCHAR2(20 BYTE),
  "Weight" NUMBER(10,2),
  "Price" NUMBER(10,2),
  "IsPriced" CHAR,
  "ErrorCode" NUMBER(10),
  "PriceInsulation" CHAR,
  "InsulationFacing" VARCHAR2(20 BYTE) DEFAULT '0',
  "IMPLoads" NUMBER(10,2),
  "IMPPlant" CHAR,
  "PanelColor" VARCHAR2(20 BYTE),
  "SheetBothSides" CHAR,
  "ByEstimating" CHAR,
  "QuoteNumber" VARCHAR2(20 BYTE),
  "QuoteYear" VARCHAR2(20 BYTE),
  "EstimatorInitials" VARCHAR2(20 BYTE),
  "ExpiresOn" VARCHAR2(20 BYTE),
  "Expired" CHAR,
  "StartLoc" VARCHAR2(20 BYTE),
  "StopLoc" VARCHAR2(20 BYTE),
  "EstPrice" NUMBER(10,2),
  "EstWeight" NUMBER(10,2),
  "ShowComplete" CHAR,
  "WeightMBCI" NUMBER(10,2),
  "PriceMBCI" NUMBER(10,2),
  "StructuralWeight" NUMBER(10,2),
  "SquareFeet" NUMBER(10,2),
  PRIMARY KEY ("PartitionId")
);