CREATE TABLE abs_mdi."Accessories_Canopy" (
  "AccessoriesCanopyId" NUMBER DEFAULT (null),
  "BuildingNumber" NUMBER(10),
  "Select_Elevation" VARCHAR2(20 BYTE),
  "StartColumn" NUMBER(10),
  "StopColumn" NUMBER(10),
  "CanopyType" VARCHAR2(100 BYTE),
  "Projection" NUMBER(20,8),
  "Slope" NUMBER(20,8),
  "Panel" VARCHAR2(100 BYTE),
  "SoffitPanelColor" VARCHAR2(100 BYTE),
  "SoffitGaudge" NUMBER(10),
  "ReturnDownspouts" CHAR,
  "Gutter" CHAR,
  "RoofTieTrimColor" VARCHAR2(100 BYTE),
  "CanopyCornerTrimColor" VARCHAR2(100 BYTE),
  "CanopySillCapTrimColor" VARCHAR2(100 BYTE),
  "SoffitTrimColor" VARCHAR2(100 BYTE),
  "SoffitPanelType" VARCHAR2(50 BYTE),
  "CanopyPanelColor" VARCHAR2(50 BYTE),
  "CanopyPanelGauge" NUMBER(10),
  "CanopySSClipType" VARCHAR2(50 BYTE),
  "ThermalBlockType" VARCHAR2(50 BYTE),
  "ExtendRoofInsulation" CHAR,
  "GutterType" NUMBER(10),
  "GutterSize" NUMBER(10),
  "DownspoutDrops" NUMBER(10,4),
  "IncludeElbow" CHAR,
  "DownspoutHeight" NUMBER(20,8),
  "GutterColor" VARCHAR2(100 BYTE),
  "DownspoutColor" VARCHAR2(100 BYTE),
  "SoffitFramingClearance" NUMBER(20,8),
  "HasSnowRetentionSystem" CHAR,
  "IncludeSnowClipPerPanel" CHAR,
  "SnowClipQuantity" NUMBER(10,4),
  "ColorStripQuantity" NUMBER(10,5),
  "RoofPanelType" VARCHAR2(100 BYTE),
  "ReverseRollSoffit" CHAR,
  "ReverseRollFace" CHAR,
  "DistFromLeftCorner" NUMBER(20,8),
  "Length" NUMBER(20,8),
  "HeightLocation" NUMBER(20,8),
  "SoffitPanel" NUMBER(10),
  "SoffitTrim" NUMBER(10),
  "AtEave" CHAR,
  "PanelFinish" VARCHAR2(50 BYTE),
  "CanopyFacingSpecial" NUMBER(10),
  "CanopyFacingWeight" NUMBER(20,8),
  "CanopyFacingDeflection" NUMBER(10,4),
  "SoffitFacingSpecial" NUMBER(10),
  "SoffitFacingWeight" NUMBER(20,8),
  "SoffitFacingDeflection" NUMBER(10,4),
  "Price" NUMBER(20,8),
  "Weight" NUMBER(20,8),
  "ErrorCode" NUMBER(10),
  "PriceMBCI" NUMBER(20,8),
  "WeightMBCI" NUMBER(20,8),
  "DesignIndex" NUMBER(10),
  "MainBuildingGutter" NUMBER(10),
  "RoofSquareFeet" NUMBER(20,8),
  "WallSquareFeet" NUMBER(20,8),
  "SoffitSquareFeet" NUMBER(20,8),
  "HeightOfFace" NUMBER(20,8),
  "SoffitPanelColorValsparCode" VARCHAR2(100 BYTE),
  "SoffitPanelColorSpecialName" VARCHAR2(100 BYTE),
  "RoofTieTrimColorValsparCode" VARCHAR2(100 BYTE),
  "RoofTieTrimColorSpecialName" VARCHAR2(100 BYTE),
  "CanopyCornerTrimColorValsparCode" VARCHAR2(100 BYTE),
  "CanopyCornerTrimColorSpecialName" VARCHAR2(100 BYTE),
  "CanopySillTrimColorValsparCode" VARCHAR2(100 BYTE),
  "CanopySillTrimColorSpecialName" VARCHAR2(100 BYTE),
  "SoffitTrimColorValsparCode" VARCHAR2(100 BYTE),
  "SoffitTrimColorSpecialName" VARCHAR2(100 BYTE),
  "PanelColorValsparCode" VARCHAR2(100 BYTE),
  "PanelColorSpecialName" VARCHAR2(100 BYTE),
  "GutterColorValsparCode" VARCHAR2(100 BYTE),
  "GutterColorSpecialName" VARCHAR2(100 BYTE),
  "DownspoutColorValsparCode" VARCHAR2(100 BYTE),
  "DownspoutColorSpecialName" VARCHAR2(100 BYTE),
  "IncludeSagAngles" CHAR,
  "SnowLoad" NUMBER(20,8),
  "CreatedDate" TIMESTAMP,
  "CreatedBy" NUMBER(10),
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDelete" CHAR,
  "ProjectId" NUMBER,
  "SoffitPanelColorValsparText" VARCHAR2(100 BYTE),
  "SoffitPanelColorValsparHashCode" VARCHAR2(100 BYTE),
  "RoofTieTrimColorValsparText" VARCHAR2(100 BYTE),
  "RoofTieTrimColorValsparHashCode" VARCHAR2(100 BYTE),
  "CanopyCornerTrimColorValsparText" VARCHAR2(100 BYTE),
  "CanopyCornerTrimColorValsparHashCode" VARCHAR2(100 BYTE),
  "CanopySillCapTrimColorValsparText" VARCHAR2(100 BYTE),
  "CanopySillCapTrimColorValsparHashCode" VARCHAR2(100 BYTE),
  "SoffitTrimColorValsparText" VARCHAR2(100 BYTE),
  "SoffitTrimColorValsparHashCode" VARCHAR2(100 BYTE),
  "PanelColorValsparText" VARCHAR2(100 BYTE),
  "PanelColorValsparHashCode" VARCHAR2(100 BYTE),
  "GutterColorValsparText" VARCHAR2(100 BYTE),
  "GutterColorValsparHashCode" VARCHAR2(100 BYTE),
  "DownspoutColorValsparText" VARCHAR2(100 BYTE),
  "DownspoutColorValsparHashCode" VARCHAR2(100 BYTE),
  "IsValid" NUMBER DEFAULT 1
);