CREATE TABLE abs_mdi."Accesories_WallLTP" (
  "WallLTPId" NUMBER(10) NOT NULL,
  "BuildingInformationId" NUMBER(10),
  "Quantity" NUMBER(10),
  "Elevation" VARCHAR2(20 BYTE),
  "Type" VARCHAR2(20 BYTE),
  "Size" NUMBER,
  "DistFromLeftCorner" NUMBER,
  "DistFromLeftCol" NUMBER,
  "PatternPerBay" NUMBER,
  "EaveCondition" VARCHAR2(20 BYTE),
  "Continuous" CHAR,
  "TopElevation" NUMBER(10,2),
  "LTPSize" VARCHAR2(20 BYTE),
  "AccessoryConflictOverride" CHAR,
  "InsulationTrim" CHAR,
  "CreatedBy" NUMBER,
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER,
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDelete" CHAR,
  "Length" NUMBER(10,2),
  "PartitionNumber" NUMBER(10),
  "ProjectId" NUMBER,
  "StopValue" NUMBER(10,2),
  "IsLocate" CHAR,
  "Insulated" CHAR,
  "TrimFlashing" CHAR,
  ul90 CHAR,
  "IsPriced" CHAR,
  "ErrorCode" NUMBER(10),
  "QuantityA" NUMBER(10),
  "QuantityB" NUMBER(10),
  "QuantityC" NUMBER(10),
  "QuantityD" NUMBER(10),
  "Location" VARCHAR2(20 BYTE),
  "Weight" NUMBER(10,2),
  "Price" NUMBER(10,2),
  CONSTRAINT "Accesories_WallLTP_PK" PRIMARY KEY ("WallLTPId"),
  CONSTRAINT "FK_WallLTPBuildingId" FOREIGN KEY ("BuildingInformationId") REFERENCES abs_mdi."BuildingInformation" ("BuildingInformationId"),
  CONSTRAINT "FK_WallLTP_PartitionNumber" FOREIGN KEY ("PartitionNumber") REFERENCES abs_mdi."Accesories_Partition" ("PartitionId")
);