CREATE TABLE abs_mdi."Accessories_FramedOpening" (
  "FramedOpeningId" NUMBER NOT NULL,
  "BuildingNumber" NUMBER NOT NULL,
  "ProjectId" NUMBER NOT NULL,
  "Elevation" CHAR,
  "BayNumber" NUMBER,
  "Material" VARCHAR2(20 BYTE),
  "Type" VARCHAR2(20 BYTE),
  "Width" NUMBER(10,5) NOT NULL,
  "Height" NUMBER(10,5) NOT NULL,
  "DistFromLeftCorner" NUMBER,
  "DistFromLeftCol" NUMBER(10,5),
  "SillHeight" NUMBER,
  "HeaderHeight" NUMBER(10,5),
  "HeaderType" VARCHAR2(20 BYTE),
  "JambType" VARCHAR2(20 BYTE),
  "CeeDepth" NUMBER,
  "InsideFlangeWidth" NUMBER,
  "InsideFlangeThick" NUMBER,
  "OutsideFlangeWidth" NUMBER,
  "OutsideFlangeThick" NUMBER,
  "WebDepth" NUMBER,
  "WebThick" NUMBER,
  "DoubleJambs" CHAR,
  "FourSided" CHAR,
  "TrimOnly" CHAR,
  "PanelCredit" CHAR,
  "Clearance" NUMBER,
  "Weight" NUMBER,
  "Price" NUMBER,
  "IsPriced" CHAR,
  "ErrorCode" NUMBER,
  "ClosureTrim" NUMBER,
  "ClosureTrimSize" NUMBER,
  "ClosureTrimColor" VARCHAR2(20 BYTE),
  "ClosureTrimColorValsparCode" VARCHAR2(20 BYTE),
  "ClosureTrimColorSpecialName" VARCHAR2(20 BYTE),
  "DoNotCutGirts" CHAR,
  "OverheadDoor" CHAR,
  "Quantity" NUMBER NOT NULL,
  "PreGalvanizedFraming" CHAR,
  "FullCoverHeadTrim" CHAR,
  "DoubleHeader" CHAR,
  "DoNotCutPanel" CHAR,
  "LocatedInLiner" CHAR,
  "LeftSteelLine" CHAR,
  "PartitionNumber" NUMBER,
  "ClipAttachment" VARCHAR2(20 BYTE),
  "BracingBay" NUMBER,
  "CreatedBy" NUMBER,
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER,
  "ModifiedDate" TIMESTAMP,
  "IsDelete" CHAR,
  "IpAddress" VARCHAR2(20 BYTE),
  "ForVerticalLiftDoor" CHAR,
  CONSTRAINT "Accessories_FramedOpening_PK" PRIMARY KEY ("FramedOpeningId")
);