CREATE TABLE abs_mdi."Accesories_Windows" (
  "WindowId" NUMBER NOT NULL,
  "BuildingNumber" NUMBER(10),
  "Quantity" NUMBER(10),
  "Elevation" VARCHAR2(20 BYTE),
  "BayNumber" NUMBER,
  "Type" VARCHAR2(100 BYTE),
  "SillHeight" NUMBER(*,9),
  "HeaderHeight" NUMBER(*,9),
  "Width" NUMBER,
  "DistFromLeftCorner" NUMBER,
  "DistFromLeftCol" NUMBER,
  "TrimColor" VARCHAR2(200 BYTE),
  "WindowColor" VARCHAR2(20 BYTE),
  "SubFraming" NUMBER,
  "GlassType" VARCHAR2(20 BYTE),
  "Quality" VARCHAR2(20 BYTE),
  "IsBuyout" NUMBER,
  "Weight" NUMBER,
  "Price" NUMBER,
  "IsPriced" NUMBER,
  "ErrorCode" NUMBER,
  "InsulatedGlass" CHAR,
  "FrameFinish" VARCHAR2(20 BYTE),
  "LocatedInLiner" CHAR,
  "LeftSteelLine" CHAR,
  "PartitionNumber" NUMBER,
  "WindowCategory" VARCHAR2(100 BYTE),
  "InsulationRetainerKit" CHAR,
  "CWindowRating" CHAR,
  "WindowSize" VARCHAR2(20 BYTE),
  "BracedBay" NUMBER,
  "IsDelete" CHAR DEFAULT 'N',
  "CreatedBy" NUMBER,
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER,
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "ProjectId" NUMBER,
  "IncludeFramedOpening" CHAR,
  "IsLocate" CHAR,
  "TrimColorValsparCode" VARCHAR2(200 BYTE),
  "TrimColorSpecialName" VARCHAR2(200 BYTE),
  CONSTRAINT "Accesories_Windows_PK" PRIMARY KEY ("WindowId")
);