CREATE TABLE abs_mdi."Accessories_Liner_Wall" (
  "WallLinerId" NUMBER(10) NOT NULL,
  "ProjectId" NUMBER(10) NOT NULL,
  "BuildingNumber" NUMBER(10) NOT NULL,
  "Elevation" VARCHAR2(100 BYTE),
  "BayNumber" NUMBER(10),
  "DistFromLeftCorner" NUMBER(10,4),
  "DistFromLeftCol" NUMBER(10,4),
  "FullHeight" CHAR,
  "Length" VARCHAR2(10 BYTE),
  "Height" VARCHAR2(10 BYTE),
  "PanelType" NUMBER(10),
  "PanelGauge" NUMBER(10),
  "PanelColor" VARCHAR2(100 BYTE),
  "PanelColorValsparCode" VARCHAR2(100 BYTE),
  "PanelColorSpecialName" VARCHAR2(100 BYTE),
  "BaseType" NUMBER(10),
  "ReverseRoll" CHAR,
  "CapTrimColor" VARCHAR2(100 BYTE),
  "CapTrimColorValsparCode" VARCHAR2(100 BYTE),
  "CapTrimColorSpecialName" VARCHAR2(100 BYTE),
  "PurlinTrimColor" VARCHAR2(100 BYTE),
  "PurlinTrimColorValsparCode" VARCHAR2(100 BYTE),
  "PurlinTrimColorSpecialName" VARCHAR2(100 BYTE),
  "InsideCornerTrimColor" VARCHAR2(100 BYTE),
  "InsideCornerTrimColorValsparCode" VARCHAR2(100 BYTE),
  "InsideCornerTrimColorSpecialName" VARCHAR2(100 BYTE),
  "ColumnTieTrimColor" VARCHAR2(100 BYTE),
  "ColumnTieTrimColorValsparCode" VARCHAR2(100 BYTE),
  "ColumnTieTrimColorSpecialName" VARCHAR2(100 BYTE),
  "FastenerHeadFinish" NUMBER(10),
  "FastenerLength" NUMBER(10),
  "CreatedBy" NUMBER,
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER,
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDelete" CHAR
);