CREATE TABLE abs_mdi."Accessories_DBCIDoor" (
  "DbciDoorId" NUMBER NOT NULL,
  "ProjectId" NUMBER,
  "BuildingId" NUMBER,
  "BayNumber" NUMBER,
  "Quantity" NUMBER,
  "Elevation" VARCHAR2(100 BYTE),
  "DistFromLeftCorner" NUMBER(10,4),
  "DistFromLeftCol" NUMBER(10,4),
  "DoorSeries" VARCHAR2(100 BYTE),
  "DoorSize" VARCHAR2(100 BYTE),
  "DoorColor" VARCHAR2(100 BYTE),
  "Width" NUMBER(*,0),
  "Heigth" NUMBER(*,0),
  "ResistWind" CHAR,
  "Insulated" CHAR,
  "LockType" VARCHAR2(100 BYTE),
  "LocateInLiner" CHAR,
  "Seal" VARCHAR2(100 BYTE),
  "OperatorType" VARCHAR2(100 BYTE),
  "RemoteTransmitter" CHAR,
  "Hood" CHAR,
  "Weigth" NUMBER,
  "Price" NUMBER(*,0),
  "IsPriced" CHAR,
  "LeftSteelLine" CHAR,
  "PartitionNumber" NUMBER(*,0),
  "DistFromFloor" NUMBER(10,4),
  "CoverTrim" CHAR,
  "ColorValsparCode" VARCHAR2(100 BYTE),
  "ColorSpecialName" VARCHAR2(100 BYTE),
  "PreGalvanizedFraming" CHAR,
  "ClipAttachment" VARCHAR2(100 BYTE),
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDelete" CHAR,
  "CreatedBy" NUMBER,
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER,
  "ModifiedDate" TIMESTAMP,
  "TrimColor" VARCHAR2(100 BYTE),
  "Type" VARCHAR2(20 BYTE),
  "TrimColorValsparCode" VARCHAR2(100 BYTE),
  "TrimColorSpecialName" VARCHAR2(100 BYTE),
  "SillHeight" NUMBER(10,4),
  "ErrorCode" NUMBER
);