CREATE TABLE abs_mdi."Accessories_AddLines" (
  "AddLinesId" NUMBER(10,2) NOT NULL,
  "ProjectId" NUMBER(20),
  "BuildingId" NUMBER(10,2),
  "Description" VARCHAR2(200 BYTE),
  "Quantity" NUMBER(10),
  "UnitWeight" NUMBER(10,2),
  "UnitPrice" NUMBER(10,2),
  "TaxApplied" CHAR,
  "AdjustmentFactor" NUMBER(10,2),
  "ListOrNet" VARCHAR2(10 BYTE),
  "Internal" CHAR,
  "ExpiresOn" TIMESTAMP,
  "Expired" CHAR,
  "QuoteNumber" VARCHAR2(20 BYTE),
  "QuoteYear" VARCHAR2(20 BYTE),
  "EstInitials" VARCHAR2(20 BYTE),
  "Category" VARCHAR2(20 BYTE),
  "IncludeFreight" VARCHAR2(10 BYTE),
  "BuiltupWeight" NUMBER(10,2),
  "BuiltupPrice" NUMBER(10,2),
  "HotrolledWeight" NUMBER(10,2),
  "HotrolledPrice" NUMBER(10,2),
  "ColdformWeight" NUMBER(10,2),
  "ColdformPrice" NUMBER(10,2),
  "FabColdformWeight" NUMBER(10,2),
  "FabColdformPrice" NUMBER(10,2),
  "RoofpanelWeight" NUMBER(10,2),
  "RoofpanelPrice" NUMBER(10,2),
  "WallpanelWeight" NUMBER(10,2),
  "WallpanelPrice" NUMBER(10,2),
  "TrimWeight" NUMBER(10,2),
  "TrimPrice" NUMBER(10,2),
  "BuyoutsWeight" NUMBER(10,2),
  "BuyoutsPrice" NUMBER(10,2),
  column1 VARCHAR2(20 BYTE),
  CONSTRAINT "Accessories_AddLines_PK" PRIMARY KEY ("AddLinesId")
);