CREATE TABLE abs_mdi."Accesories_TopMountedSlideDoor" (
  "TopMountedSlideDoorId" NUMBER(10) NOT NULL,
  "BuildingNumber" NUMBER(10) DEFAULT 0,
  "Elevation" VARCHAR2(50 BYTE),
  "BayNumber" NUMBER(10),
  "Material" VARCHAR2(50 BYTE),
  "Type" VARCHAR2(20 BYTE),
  "Width" NUMBER(10,4) NOT NULL,
  "Height" NUMBER(10,4),
  "DistFromLeftCorner" NUMBER(10,4),
  "DistFromLeftCol" NUMBER(10,4),
  "HeaderHeight" NUMBER(10,4),
  "TrimColor" VARCHAR2(50 BYTE),
  "JambType" VARCHAR2(20 BYTE),
  "CeeDepth" NUMBER(10,4),
  "InsideFlangeWidth" NUMBER(10,4),
  "InsideFlangeThick" NUMBER(10,4),
  "OutsideFlangeWidth" NUMBER(10,4),
  "OutsideFlangeThick" NUMBER(10,4),
  "WebDepth" NUMBER(10,4),
  "WebThick" NUMBER(10,4),
  "DoubleJambs" CHAR,
  "TrimOnly" CHAR,
  "PanelCredit" CHAR,
  "Clearance" NUMBER(10),
  "Slide" VARCHAR2(50 BYTE),
  "Direction" VARCHAR2(50 BYTE),
  "HoodFlash" CHAR,
  "Weight" NUMBER(10,4),
  "Price" NUMBER(10,4),
  "IsPriced" CHAR,
  "ErrorCode" NUMBER(10),
  "Quantity" NUMBER(10),
  "LeftSteelLine" NUMBER(10),
  "PartitionNumber" NUMBER(10),
  "LocateRightSideBay" CHAR,
  "TrimColorValsparCode" VARCHAR2(50 BYTE),
  "TrimColorSpecialName" VARCHAR2(50 BYTE),
  "IsBuyout" CHAR,
  "CreatedBy" NUMBER(10),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDelete" CHAR,
  "ProjectId" NUMBER(10),
  "DoorSizeId" NUMBER(10),
  CONSTRAINT "Accesories_TopMountedSlideDoor_PK" PRIMARY KEY ("TopMountedSlideDoorId")
);
COMMENT ON COLUMN abs_mdi."Accesories_TopMountedSlideDoor"."Elevation" IS 'The side of bulding the accessory is on';
COMMENT ON COLUMN abs_mdi."Accesories_TopMountedSlideDoor"."BayNumber" IS 'The bay where the accessory is located';
COMMENT ON COLUMN abs_mdi."Accesories_TopMountedSlideDoor"."Material" IS 'Material of slide door';
COMMENT ON COLUMN abs_mdi."Accesories_TopMountedSlideDoor"."Type" IS 'Type of slide door';
COMMENT ON COLUMN abs_mdi."Accesories_TopMountedSlideDoor"."Width" IS 'Width of slide door';
COMMENT ON COLUMN abs_mdi."Accesories_TopMountedSlideDoor"."Height" IS 'Height of slide door';
COMMENT ON COLUMN abs_mdi."Accesories_TopMountedSlideDoor"."DistFromLeftCorner" IS 'Distance from the left side of elevation';
COMMENT ON COLUMN abs_mdi."Accesories_TopMountedSlideDoor"."DistFromLeftCol" IS 'Distance from the left column of bay';
COMMENT ON COLUMN abs_mdi."Accesories_TopMountedSlideDoor"."HeaderHeight" IS 'Header height';
COMMENT ON COLUMN abs_mdi."Accesories_TopMountedSlideDoor"."JambType" IS 'Jamb type';
COMMENT ON COLUMN abs_mdi."Accesories_TopMountedSlideDoor"."CeeDepth" IS 'Cee depth';
COMMENT ON COLUMN abs_mdi."Accesories_TopMountedSlideDoor"."InsideFlangeWidth" IS 'Inside flange width';
COMMENT ON COLUMN abs_mdi."Accesories_TopMountedSlideDoor"."InsideFlangeThick" IS 'Inside flange thick';
COMMENT ON COLUMN abs_mdi."Accesories_TopMountedSlideDoor"."OutsideFlangeWidth" IS 'Outside flange width';
COMMENT ON COLUMN abs_mdi."Accesories_TopMountedSlideDoor"."OutsideFlangeThick" IS 'Outside flange thick';
COMMENT ON COLUMN abs_mdi."Accesories_TopMountedSlideDoor"."WebDepth" IS 'Web depth';
COMMENT ON COLUMN abs_mdi."Accesories_TopMountedSlideDoor"."WebThick" IS 'Web Thick';
COMMENT ON COLUMN abs_mdi."Accesories_TopMountedSlideDoor"."DoubleJambs" IS '-bool-';
COMMENT ON COLUMN abs_mdi."Accesories_TopMountedSlideDoor"."TrimOnly" IS '-bool-';
COMMENT ON COLUMN abs_mdi."Accesories_TopMountedSlideDoor"."PanelCredit" IS '-bool-';
COMMENT ON COLUMN abs_mdi."Accesories_TopMountedSlideDoor"."Clearance" IS 'Clearance';
COMMENT ON COLUMN abs_mdi."Accesories_TopMountedSlideDoor"."Slide" IS 'Single slide or Double slide?';
COMMENT ON COLUMN abs_mdi."Accesories_TopMountedSlideDoor"."Direction" IS 'Slide left or Slide right';
COMMENT ON COLUMN abs_mdi."Accesories_TopMountedSlideDoor"."HoodFlash" IS '-bool-';
COMMENT ON COLUMN abs_mdi."Accesories_TopMountedSlideDoor"."Weight" IS 'Calculated by BSPrice';
COMMENT ON COLUMN abs_mdi."Accesories_TopMountedSlideDoor"."Price" IS 'Calculated by BSPrice';
COMMENT ON COLUMN abs_mdi."Accesories_TopMountedSlideDoor"."IsPriced" IS '-bool-';
COMMENT ON COLUMN abs_mdi."Accesories_TopMountedSlideDoor"."ErrorCode" IS 'Generated by BSPrice';
COMMENT ON COLUMN abs_mdi."Accesories_TopMountedSlideDoor"."Quantity" IS 'NEW v11';
COMMENT ON COLUMN abs_mdi."Accesories_TopMountedSlideDoor"."LeftSteelLine" IS 'new v30';
COMMENT ON COLUMN abs_mdi."Accesories_TopMountedSlideDoor"."PartitionNumber" IS 'new v30';
COMMENT ON COLUMN abs_mdi."Accesories_TopMountedSlideDoor"."LocateRightSideBay" IS '-bool- locate between right X-brace anchor and right column of bay';
COMMENT ON COLUMN abs_mdi."Accesories_TopMountedSlideDoor"."IsBuyout" IS '-bool- new v53';