CREATE TABLE abs_mdi."Accessories_WalkDoors" (
  "WalkDoorId" NUMBER(10) NOT NULL,
  "ProjectId" NUMBER,
  "BuildingId" NUMBER,
  "Quantity" NUMBER,
  "Elevation" VARCHAR2(20 BYTE),
  "BayNumber" NUMBER,
  "Type" VARCHAR2(200 BYTE),
  "HeaderHeight" NUMBER,
  "Width" NUMBER,
  "DistFromLeftCorner" NUMBER(10,4),
  "DistFromLeftCol" NUMBER(10,4),
  "TrimColor" VARCHAR2(100 BYTE),
  "DoorColor" VARCHAR2(100 BYTE),
  "SwingDirection" VARCHAR2(200 BYTE),
  "LatchGuard" CHAR,
  "SubFraming" CHAR,
  "Skin" VARCHAR2(200 BYTE),
  "Lite" VARCHAR2(200 BYTE),
  "Closer" VARCHAR2(100 BYTE),
  "Locktype" VARCHAR2(200 BYTE),
  "Quality" VARCHAR2(200 BYTE),
  "LeafType" VARCHAR2(200 BYTE),
  "StyleSet" VARCHAR2(200 BYTE),
  "IsBuyout" CHAR,
  "Weight" NUMBER,
  "Price" NUMBER(10,4),
  "IsPriced" CHAR,
  "ErrorCode" NUMBER,
  "KnockDown" NUMBER,
  "Style" VARCHAR2(200 BYTE),
  "WindRated" VARCHAR2(200 BYTE),
  "Size" VARCHAR2(200 BYTE),
  "KeyedAlike" CHAR,
  "PanicHardware" CHAR,
  "ChainStop" CHAR,
  "Insulated" CHAR,
  "FloridaApproval" NUMBER,
  "LocatedInLiner" CHAR,
  "Glazing" VARCHAR2(200 BYTE),
  "KickPlate" CHAR,
  "LeftSteelLine" CHAR,
  "PartitionNumber" NUMBER,
  "LocateRightSideBay" CHAR,
  "DistanceFromFloor" NUMBER(10,4),
  "DadeBrowardApproved" CHAR,
  "SsbHinges" CHAR,
  "AddAnchors" NUMBER,
  "LeafInsulated" CHAR,
  "LeafsBothActive" NUMBER,
  "Alabel3hour" CHAR,
  "AdaCompliant" CHAR,
  "AdditionalAnchorsQty" NUMBER,
  "TrimColorValsparCode" VARCHAR2(100 BYTE),
  "TrimColorSpecialName" VARCHAR2(100 BYTE),
  "CreatedBy" NUMBER(5),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(5),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(100 BYTE),
  "IsDelete" CHAR,
  "Gauge" NUMBER,
  "FireRated" CHAR,
  "InterChangeableLockKit" CHAR,
  "ExistingOpeningMasonryAnchor" CHAR,
  "InActiveLeaf" CHAR,
  "WireMasonryAnchor" CHAR,
  "Masonry" CHAR,
  "AnodizedFrame" VARCHAR2(200 BYTE),
  "DoorGlass" VARCHAR2(200 BYTE),
  "Glass" VARCHAR2(200 BYTE),
  "Closure" VARCHAR2(200 BYTE),
  "MasonaryApplication" CHAR,
  "BottomRail" CHAR,
  "IsLocate" CHAR,
  "LocateLeftSideBay" CHAR,
  CONSTRAINT "Accessories_WalkDoors_PK" PRIMARY KEY ("WalkDoorId")
);