CREATE TABLE abs_mdi."Accessories_RubberPipeFlash" (
  "RubberPipeFlashId" NUMBER(10) NOT NULL,
  "BuildingId" NUMBER(10),
  "ProjectId" NUMBER(10),
  "Quantity" NUMBER(10),
  "OutsideDiameter" VARCHAR2(20 BYTE),
  "CreatedBy" NUMBER(10),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDelete" CHAR,
  "Type" VARCHAR2(20 BYTE),
  "Weight" NUMBER(10) DEFAULT 0 NOT NULL,
  "Price" NUMBER(10) DEFAULT 0 NOT NULL,
  "IsPriced" CHAR DEFAULT null,
  "ErrorCode" NUMBER(10) DEFAULT 0 NOT NULL,
  "Elevation" VARCHAR2(20 BYTE),
  "BayNumber" NUMBER(10) DEFAULT 0 NOT NULL,
  "DistFromLeftCorner" NUMBER(10) DEFAULT 0 NOT NULL,
  "DistFromLeftCol" NUMBER(10) DEFAULT 0 NOT NULL,
  "DistFromWall" NUMBER(10) DEFAULT 0 NOT NULL,
  CONSTRAINT "Accessories_RubberPipeFlash_PK" PRIMARY KEY ("RubberPipeFlashId")
);