CREATE TABLE abs_mdi."Accessories_Cranes" (
  "CraneId" NUMBER NOT NULL,
  "ProjectId" NUMBER,
  "BuildingId" NUMBER,
  "StartFrameline" NUMBER,
  "StopFrameLine" NUMBER,
  "SType" VARCHAR2(50 BYTE),
  "Control" VARCHAR2(50 BYTE),
  "Quantity" NUMBER,
  "Tonnage1" NUMBER(10,5),
  "Tonnage2" NUMBER(10,5),
  "CraneClass" VARCHAR2(50 BYTE),
  "Brackets" CHAR,
  "RunwayBeam" CHAR,
  "Rail" CHAR,
  "RoofSupportBeams" CHAR,
  "SeperateSupportCol" CHAR,
  "Stops" CHAR,
  "Bracing" CHAR,
  "NameBrand" VARCHAR2(50 BYTE),
  "GirderType" VARCHAR2(50 BYTE),
  "BridgeWeight1" NUMBER(10,5),
  "BridgeWeight2" NUMBER(10,5),
  "WheelSpacing1" NUMBER(10,5),
  "WheelSpacing2" NUMBER(10,5),
  "HoistWeight1" NUMBER(10,5),
  "HoistWeight2" NUMBER(10,5),
  "BracketLength" NUMBER(10,5),
  "RunwayBeamSize" NUMBER(10,5),
  "DistanceBetweenCranes" NUMBER(10,5),
  "CenterlineOfRunwayBeamToSteelline" NUMBER(10,5),
  "CenterlineToCenterlineOfRails" NUMBER(10,5),
  "ColBaseToTopOfRail" NUMBER(10,5),
  "ClearanceFromTopRailToBottomRafter" NUMBER(10,5),
  "ClearanceFromRailToInsideFlangeCol" NUMBER(10,5),
  "ManufacturerRailSize" NUMBER(10,5),
  "TruckWheelDiameter" NUMBER(10,5),
  "VerticalDeflection" NUMBER(10,5),
  "HorizontalDeflection" NUMBER(10,5),
  "FutureLineStart1" NUMBER,
  "FutureLinestart2" NUMBER,
  "DistanceToBack" NUMBER(10,5),
  "SteelYield" NUMBER(10,5),
  "RailWeight" NUMBER(10,5),
  "CecoStandard" NUMBER,
  "ModuleNumber" NUMBER,
  "UsingMfgCraneData" NUMBER,
  "AuxiliaryHoist1" NUMBER(10,5),
  "AuxiliaryHoist2" NUMBER(10,5),
  "TrolleyType" VARCHAR2(50 BYTE),
  "HoistType" VARCHAR2(50 BYTE),
  "UserAccept" NUMBER,
  "MinimumHookDistance" NUMBER(10,5),
  "LeftOverhang1" NUMBER(10,5),
  "LeftOverhang2" NUMBER(10,5),
  "RightOverhang1" NUMBER(10,5),
  "RightOverhang2" NUMBER(10,5),
  "CreatedBy" NUMBER,
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER,
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDelete" CHAR,
  "CraneNumber1" NUMBER,
  "CraneNumber2" NUMBER,
  CONSTRAINT "Accessories_Cranes_PK" PRIMARY KEY ("CraneId")
);