CREATE TABLE abs_mdi."BuildingQuoteVariable" (
  "BuildingQuoteVariableId" NUMBER(5) NOT NULL,
  "DefaultPurlinPeakSpace" NUMBER(10,4),
  "DefaultPurlinMaxSpace" NUMBER(10,4),
  "DefaultPurlinGirtLocation" NUMBER(10,4),
  "DefaultPurlinLowGirtLocation" NUMBER(10,4),
  "DefaultBearingFrameSetback" NUMBER(10,4),
  "DefaultMainFrameSetback" NUMBER(10,4),
  "CreatedBy" NUMBER(10),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  "IsActive" CHAR,
  "IsDelete" CHAR,
  "IpAddress" VARCHAR2(20 BYTE),
  "FramedOpeningClearanceTop" NUMBER(10,4),
  "FramedOpeningClearanceBottom" NUMBER(10,4),
  "FramedOpeningClearanceSides" NUMBER(10,4),
  "FramedOpeningSideClearenceForMainFrameEndwalls" NUMBER(10,4),
  "TopClearenceForMainFrameEndwallsForFramedOpening" NUMBER(10,4),
  "FramedOpeningSideClearanceForBearingFrameEndwalls" NUMBER(10,4),
  "FramedOpeningTopClearanceForBearingFrameEndwalls" NUMBER(10,4),
  "MinValueForEndwallBSpecialSetback" NUMBER(10,4),
  "MaxValueForEndwallBSpecialSetback" NUMBER(10,4),
  "MinValueForEndwallDSpecialSetback" NUMBER(10,4),
  "MaxValueForEndwallDSpecialSetback" NUMBER(10,4),
  "TopClearenceForMainFrameEndwallsForDbciDoor" NUMBER(10,4),
  "DbciDoorClearanceTop" NUMBER(10,4),
  "DbciDoorClearanceBottom" NUMBER(10,4),
  "DbciDoorClearanceSides" NUMBER(10,4),
  "DbciDoorTopClearanceForBearingFrameEndwalls" NUMBER(10,4),
  "DBCIDoorSideClearanceMainFrame" NUMBER(10,4),
  "DBCIDoorSideClearanceBearingFrame" NUMBER(10,4),
  "PortalFrameColumnDepth" NUMBER(10,4),
  "PortalFrameBeamDepth" NUMBER(10,4),
  "FerryFee" NUMBER(10,2),
  "ThreeWeekFee" NUMBER(10,2),
  "NumberOfItemsPerPage" NUMBER(10),
  "AgoraPurchaseOrderVersion" VARCHAR2(20 BYTE),
  "ComponentPurchaseOrderVersion" VARCHAR2(20 BYTE),
  "ComponentPricingVersion" VARCHAR2(20 BYTE),
  "BuildingPricingVersionNumber" VARCHAR2(20 BYTE),
  "FurthestShippingDaysForComponent" NUMBER(10,4),
  "FurthestShippingDaysBuilding" NUMBER(10,4),
  CONSTRAINT "BuildingQuoteVariable_PK" PRIMARY KEY ("BuildingQuoteVariableId")
);