CREATE TABLE abs_mdi."BuilderInformation" (
  "BuilderID" NUMBER(10) NOT NULL,
  "BuilderName" VARCHAR2(100 BYTE) NOT NULL,
  "Website" VARCHAR2(100 BYTE),
  "Phone" VARCHAR2(20 BYTE),
  "Fax" VARCHAR2(20 BYTE),
  "BillToAddress" VARCHAR2(200 BYTE) NOT NULL,
  "BillToCity" VARCHAR2(100 BYTE),
  "BillToState" VARCHAR2(100 BYTE),
  "BillToPostalCode" VARCHAR2(20 BYTE),
  "BillToCountry" VARCHAR2(100 BYTE),
  "ShipToAddress" VARCHAR2(200 BYTE) NOT NULL,
  "ShipToCity" VARCHAR2(100 BYTE),
  "ShipToState" VARCHAR2(100 BYTE),
  "ShipToPostalCode" VARCHAR2(20 BYTE),
  "ShipToCountry" VARCHAR2(100 BYTE),
  "PrimaryContact" VARCHAR2(100 BYTE),
  "CustomerNo" VARCHAR2(100 BYTE) NOT NULL,
  "CreatedBy" NUMBER(10) NOT NULL,
  "CreatedDate" TIMESTAMP NOT NULL,
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "CompanyId" NUMBER(5) NOT NULL,
  CONSTRAINT "BuilderInformation_PK" PRIMARY KEY ("BuilderID")
);