CREATE TABLE abs_mdi."BuildingInformation_Copy" (
  "BuildingInformationId" NUMBER(10) NOT NULL,
  "BuildingLabel" VARCHAR2(1 BYTE) NOT NULL,
  "Structure" VARCHAR2(1 BYTE),
  "BuildingName" VARCHAR2(50 BYTE) NOT NULL,
  "BuildingType" VARCHAR2(1 BYTE) NOT NULL,
  "Elevation" VARCHAR2(1 BYTE) NOT NULL,
  "FrameType" VARCHAR2(20 BYTE),
  "ProjectId" NUMBER(10) NOT NULL,
  "CreatedBy" VARCHAR2(50 BYTE) NOT NULL,
  "CreatedDate" TIMESTAMP NOT NULL,
  "ModifiedBy" VARCHAR2(50 BYTE),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDelete" VARCHAR2(1 BYTE),
  "AttachmentElevation" VARCHAR2(4 BYTE),
  "HighSideWallElevation" VARCHAR2(4 BYTE),
  "ParentBuildingId" NUMBER(10),
  "BuildingHasInsulation" NUMBER(1),
  "InsulationByBrand" NUMBER(1),
  "ComCheck" NUMBER(1),
  "IsComplete" CHAR,
  "UseSeismicDesignCategory" CHAR
);