CREATE TABLE abs_mdi."CAD_Options" (
  "Id" NUMBER(10) NOT NULL,
  "ProjectId" NUMBER(10),
  "OptionsDimScaleAdd" NUMBER(10),
  "OptionsIsMasonryHighDetail" NUMBER(10),
  "OptionsIsPanelHighDetail" NUMBER(10),
  "OptionsIsSteelHighDetail" NUMBER(10),
  "OptionsWantMasonry" NUMBER(10),
  "OptionsWantPanel" NUMBER(10),
  "OptionsWantSteel" NUMBER(10),
  "OptionsWantLandscape" NUMBER(10),
  "OptionsWantAccessories" NUMBER(10),
  "Options3dDetail" NUMBER(10),
  "OptionsTitleBlockType" NUMBER(10),
  "OptionsTitleBlockSize" NUMBER(10),
  "Options3dViewHeight" NUMBER(10),
  "Options3dViewOrientation" NUMBER(10),
  "OptionsCadProgram" NUMBER(10),
  "OptionsDimScheme" NUMBER(10),
  "OptionsDimType" NUMBER(10),
  "OptionsCustomPaperHeight" NUMBER(10),
  "OptionsCustomPaperWidth" NUMBER(10),
  "OptionsCustomBorderHeight" NUMBER(10),
  "OptionsCustomBorderWidth" NUMBER(10),
  "OptionsCustomTitleBlockLocation" NUMBER(10),
  "OptoinsCustomBackGroundLocation" NUMBER(10),
  "OptionsDrawingsScaleFactor" NUMBER(10),
  "OptionsDWGSaveDirectory" VARCHAR2(250 BYTE),
  "CreatedBy" NUMBER(10),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDelete" VARCHAR2(1 BYTE),
  PRIMARY KEY ("Id")
);