CREATE TABLE abs_mdi."CL_MinimumsCanada" (
  "MinimumsCanadaId" NUMBER NOT NULL,
  "BuildingCode" VARCHAR2(50 BYTE),
  "JobsiteProvince" VARCHAR2(50 BYTE),
  "JobsiteCity" VARCHAR2(50 BYTE),
  "LiveLoad" NUMBER(20),
  "GroundSnowLoad" NUMBER(20),
  "YearWind10" NUMBER(20),
  "YearWind50" NUMBER(20),
  "YearWind100" NUMBER(20),
  "UpwindExtentXr" NUMBER(20),
  "RainLoad" NUMBER(20),
  "AcceleratedZoneZA" NUMBER(20),
  "VelocityZoneZV" NUMBER(20),
  "PeakGrndAccelPGA" NUMBER(20),
  "SpectralResponseSs" NUMBER(20),
  "SpectralResponseSh" NUMBER(20),
  "SpectralResponseS1" NUMBER(20),
  "SpectralResponseS2" NUMBER(20),
  "ValidLiveLoad" NUMBER(20),
  "ValidGroundSnowLoad" NUMBER(20),
  "ValidYearWind10" NUMBER(20),
  "ValidYearWind50" NUMBER(20),
  "ValidYearWind100" NUMBER(20),
  "ValidUpwindExtentXr" NUMBER(20),
  "ValidRainLoad" NUMBER(20),
  "ValidAcceleratedZoneZA" NUMBER(20),
  "ValidVelocityZoneZV" NUMBER(20),
  "ValidPeakGrndAccelPGA" NUMBER(20),
  "ValidSpectralResponseSs" NUMBER(20),
  "ValidSpectralResponseSh" NUMBER(20),
  "ValidSpectralResponseS1" NUMBER(20),
  "ValidSpectralResponseS2" NUMBER(20),
  "RainIntensity" NUMBER(20),
  "IsDeleted" VARCHAR2(1 BYTE),
  CONSTRAINT "CL_MinimumsCanada_PK" PRIMARY KEY ("MinimumsCanadaId")
);