CREATE TABLE abs_mdi."CL_Minimums" (
  "BuildingCode" VARCHAR2(50 BYTE),
  "JobsiteState" VARCHAR2(50 BYTE),
  "JobsiteCounty" VARCHAR2(50 BYTE),
  "JobsiteCity" VARCHAR2(50 BYTE),
  "LiveLoad" NUMBER(10),
  "WindLoad1" NUMBER(10,2),
  "WindLoad2" NUMBER(10,2),
  "WindLoad3" NUMBER(10,2),
  "WindLoad4" NUMBER(10,2),
  "Wind10" NUMBER(10,2),
  "Elevation" NUMBER(10,2),
  "GroundSnowLoad" NUMBER(10,2),
  "MinRoofSnowLoad" NUMBER(10,2),
  "RainIntensity" NUMBER(10,2),
  "SpectralResponseSS" NUMBER(10,2),
  "SpectralResponseS1" NUMBER(10,2),
  "AcceleratedCoefficientAA" NUMBER(10,2),
  "VelocityCoefficientAV" NUMBER(10,2),
  "SeismicZone" VARCHAR2(50 BYTE),
  "ValidLiveLoad" NUMBER(10),
  "ValidWindLoad" NUMBER(10),
  "ValidGroundSnowLoad" NUMBER(10),
  "ValidRainIntensity" NUMBER(10),
  "ValidSpectralResponseSS" NUMBER(10),
  "ValidSpectralResponseS1" NUMBER(10),
  "ValidAcceleratedCoefficientAA" NUMBER(10),
  "ValidVelocityCoefficientAV" NUMBER(10),
  "ValidSeismicZone" NUMBER(10),
  "IsDeleted" CHAR
);