CREATE TABLE abs_mdi."CLM_USGSSeismicValuesCopy" (
  "Id" NUMBER(10) GENERATED AS IDENTITY,
  "DesignCodeID" NUMBER(10) NOT NULL,
  "Lat" FLOAT NOT NULL,
  "Lon" FLOAT NOT NULL,
  ss FLOAT NOT NULL,
  s1 FLOAT NOT NULL,
  "PGa" FLOAT NOT NULL,
  PRIMARY KEY ("Id")
);