CREATE TABLE abs_mdi."CLM_LoadValues_Copy" (
  "LoadValueGUID" CHAR(255 BYTE) NOT NULL,
  "GoverningCodeGUID" CHAR(255 BYTE) NOT NULL,
  "LoadTypeID" NUMBER NOT NULL,
  "IsValueUnknown" VARCHAR2(40 BYTE) DEFAULT 0 NOT NULL,
  "IsImperial" VARCHAR2(40 BYTE) DEFAULT 1 NOT NULL,
  "Value_01" NUMBER(22) DEFAULT 0 NOT NULL,
  "Value_02" NUMBER(22) DEFAULT 0 NOT NULL,
  "Value_03" NUMBER(22) DEFAULT 0 NOT NULL,
  "Value_04" NUMBER(22) DEFAULT 0 NOT NULL,
  "Elevation_01" NUMBER(22) DEFAULT 0 NOT NULL,
  "Elevation_02" NUMBER(22) DEFAULT 0 NOT NULL,
  "Elevation_03" NUMBER(22) DEFAULT 0 NOT NULL,
  "Elevation_04" NUMBER(22) DEFAULT 0 NOT NULL,
  "RefDesignCodeID" NUMBER DEFAULT 0 NOT NULL,
  PRIMARY KEY ("LoadValueGUID")
);