CREATE TABLE abs_mdi."Collaterals" (
  "CollateralId" NUMBER(10) NOT NULL,
  "ProjectId" NUMBER(10),
  "BuildingNumber" NUMBER(10),
  "CeilingLoad" NUMBER(5,2),
  "SprinklerLoad" NUMBER(5) DEFAULT 0,
  "OtherLoad" NUMBER(5,2),
  "PlasterSheetrock" NUMBER(5),
  "RoofLoad" NUMBER(5),
  "FrameLoad" NUMBER(5),
  "BuildingCode" VARCHAR2(50 BYTE),
  "Occupancy" VARCHAR2(50 BYTE),
  "ThermalFactor" VARCHAR2(50 BYTE),
  "BurLoad" NUMBER(5),
  "CalcRoofSnowLoad" NUMBER(5),
  "ProjectNumber" NUMBER(10),
  "BuildingCodeDesign" VARCHAR2(50 BYTE),
  "ImportanceWind" NUMBER(5),
  "ImportanceSnow" NUMBER(5),
  "ImportanceSeismic" NUMBER(5),
  "WindEnclosureInput" VARCHAR2(50 BYTE),
  "WindEnclosureDesign" VARCHAR2(50 BYTE),
  "Escarpment" NUMBER(5),
  "SnowDrift" NUMBER(5),
  "StorageBuilding" NUMBER(5),
  "SlipperyRoof" NUMBER(5),
  "SeismicDesignCategory" VARCHAR2(50 BYTE),
  "Figure6_6Frame" NUMBER(5),
  "BaseWindElevation" NUMBER(5),
  "TempString1" VARCHAR2(5 BYTE),
  "TempString2" VARCHAR2(50 BYTE),
  "TempString3" VARCHAR2(50 BYTE),
  "TempDouble1" NUMBER(5),
  "TempDouble2" NUMBER(5),
  "TempDouble3" NUMBER(5),
  "TempInteger1" NUMBER(5),
  "TempInteger2" NUMBER(5),
  "TempInteger3" NUMBER(5),
  "Sw1SnowDrift" NUMBER(5),
  "Sw2SnowDrift" NUMBER(5),
  "Ew3SnowDrift" NUMBER(5),
  "Ew4SnowDrift" NUMBER(5),
  "HasSwSnowDrift" NUMBER(5),
  "HasEwSnowDrift" NUMBER(5),
  "SnowExposure" VARCHAR2(50 BYTE),
  "UnobstructedFlow" NUMBER(5),
  "WindLoad" NUMBER(10,5),
  "BelowWindMin" NUMBER(5),
  "DeflectionWindSpeed" NUMBER(10,5) DEFAULT 0,
  "SdsOverride" NUMBER(5),
  "Sd1Override" NUMBER(5),
  "CreatedBy" NUMBER(10),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDeleted" VARCHAR2(1 BYTE)
);