CREATE TABLE abs_mdi."CS_LayerColor" (
  "LayerColorId" NUMBER(10) NOT NULL,
  "LayerColorGlaz" NUMBER(10),
  "LayerColorWall" NUMBER(10),
  "LayerColorAnnoTb" NUMBER(10),
  "LayerColorDoor" NUMBER(10),
  "LayerColorRoof" NUMBER(10),
  "LayerColorGrid" NUMBER(10),
  "LayerColorElevSymbl" NUMBER(10),
  "LayerColorAreaId" NUMBER(10),
  "LayerColorParking" NUMBER(10),
  "LayerColorCar" NUMBER(10),
  "LayerColorAnnoLegn" NUMBER(10),
  "LayerColorSite" NUMBER(10),
  "LayerColorSiteUtil" NUMBER(10),
  "LayerColorPlant" NUMBER(10),
  "LayerColorDetailIdent" NUMBER(10),
  "LayerColorNotes" NUMBER(10),
  "LayerColorSectIdent" NUMBER(10),
  "LayerColorDims" NUMBER(10),
  "LayerColorTrim" NUMBER(10),
  "LayerColorColumn" NUMBER(10),
  "LayerColorRafter" NUMBER(10),
  "LayerColorSecondary" NUMBER(10),
  "LayerColorBracing" NUMBER(10),
  "LayerColorBolt" NUMBER(10),
  "LayerColorGridLayout" NUMBER(10),
  "LayerColorSlab" NUMBER(10),
  CONSTRAINT "CS_LayerColor_PK" PRIMARY KEY ("LayerColorId")
);