CREATE TABLE abs_mdi.ddp_buildingloads (
  buildingloadsid NUMBER DEFAULT abs_mdi."DDP_BUILDINGLOADS_SEQ"."NEXTVAL" NOT NULL,
  buildingname VARCHAR2(100 BYTE),
  loadapplicationcategory VARCHAR2(100 BYTE),
  loadindex NUMBER,
  planename VARCHAR2(100 BYTE),
  framename VARCHAR2(100 BYTE),
  btype VARCHAR2(100 BYTE),
  memberid VARCHAR2(100 BYTE),
  coordinatesystem VARCHAR2(100 BYTE),
  groupname VARCHAR2(100 BYTE),
  direction VARCHAR2(100 BYTE),
  xlocation NUMBER(*,5),
  ylocation NUMBER(*,5),
  blength NUMBER(*,5),
  width NUMBER(*,5),
  startintensity NUMBER(*,5),
  endintensity NUMBER(*,5),
  applyframes VARCHAR2(100 BYTE),
  applysecondary VARCHAR2(100 BYTE),
  applypanels VARCHAR2(100 BYTE),
  orientation VARCHAR2(100 BYTE),
  eccentricity NUMBER,
  eccentricitytype VARCHAR2(100 BYTE),
  comments VARCHAR2(1000 BYTE),
  createdby NUMBER(5),
  createddate TIMESTAMP,
  modifiedby NUMBER(5),
  modifieddate TIMESTAMP,
  isdelete CHAR DEFAULT 'N',
  ipaddress VARCHAR2(20 BYTE),
  edsdbbldgverid NUMBER,
  "ID" VARCHAR2(20 BYTE),
  CONSTRAINT ddp_buildingloads_pk PRIMARY KEY (buildingloadsid),
  CONSTRAINT ddp_buildingloads_fk1 FOREIGN KEY (edsdbbldgverid) REFERENCES abs_mdi.ddp_edsdb_building_version (edsdbbldgverid)
);