CREATE TABLE abs_mdi.ddp_history (
  historyeventid NUMBER(18) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  userdetailid NUMBER(10),
  eventdate TIMESTAMP,
  tablename VARCHAR2(128 BYTE),
  columnname VARCHAR2(128 BYTE),
  ipaddress VARCHAR2(20 BYTE),
  oldvalue VARCHAR2(4000 BYTE),
  newvalue VARCHAR2(4000 BYTE),
  olddate TIMESTAMP,
  newdate TIMESTAMP,
  CONSTRAINT ddp_history_pk PRIMARY KEY (historyeventid)
);