CREATE TABLE abs_mdi.ddp_edsdb_boxlaygeom (
  boxlaygeomid NUMBER DEFAULT abs_mdi."DDP_EDSDB_BOXLAYGEOM_SEQ"."NEXTVAL" NOT NULL,
  building_name VARCHAR2(100 BYTE),
  bldg_width VARCHAR2(100 BYTE),
  bldg_length VARCHAR2(100 BYTE),
  bldg_eave_ht1 VARCHAR2(100 BYTE),
  bldg_eave_ht2 VARCHAR2(100 BYTE),
  bldg_description VARCHAR2(100 BYTE),
  bldg_ew_framing1 VARCHAR2(100 BYTE),
  bldg_ew_framing2 VARCHAR2(100 BYTE),
  bldg_ew_setback1 VARCHAR2(100 BYTE),
  bldg_ew_setback2 VARCHAR2(100 BYTE),
  bldg_finished_floor VARCHAR2(100 BYTE),
  bldg_leanto_fline_or_dist VARCHAR2(100 BYTE),
  bldg_leanto_on_bldg VARCHAR2(100 BYTE),
  bldg_leanto_on_bldg_wall VARCHAR2(100 BYTE),
  column1bldg_leanto_on_bldg_wall_index VARCHAR2(100 BYTE),
  bldg_leanto_start_dist VARCHAR2(100 BYTE),
  bldg_leanto_start_frameline VARCHAR2(100 BYTE),
  bldg_leanto_stop_dist VARCHAR2(100 BYTE),
  bldg_leanto_stop_frameline VARCHAR2(100 BYTE),
  bldg_location_x VARCHAR2(100 BYTE),
  bldg_location_y VARCHAR2(100 BYTE),
  bldg_ridge_dist1 VARCHAR2(100 BYTE),
  bldg_rotation VARCHAR2(100 BYTE),
  bldg_slope1 VARCHAR2(100 BYTE),
  bldg_slope2 VARCHAR2(100 BYTE),
  building_shape_type VARCHAR2(100 BYTE),
  expandable_ew1 VARCHAR2(100 BYTE),
  expandable_ew2 VARCHAR2(100 BYTE),
  standard_setback_ew1 VARCHAR2(100 BYTE),
  standard_setback_ew2 VARCHAR2(100 BYTE),
  try_coldform_columns_ew1 VARCHAR2(100 BYTE),
  try_coldform_columns_ew2 VARCHAR2(100 BYTE),
  roofflangebraceattachment VARCHAR2(100 BYTE),
  wallflangebraceattachment VARCHAR2(100 BYTE),
  "ID" VARCHAR2(100 BYTE),
  createdby NUMBER(5),
  createddate TIMESTAMP,
  modifiedby NUMBER(5),
  modifieddate TIMESTAMP,
  isdelete CHAR DEFAULT 'N',
  ipaddress VARCHAR2(20 BYTE),
  edsdbbldgverid NUMBER NOT NULL,
  CONSTRAINT ddp_edsdb_boxlaygeom_pk PRIMARY KEY (boxlaygeomid,edsdbbldgverid),
  CONSTRAINT ddp_edsdb_boxlaygeom_fk1 FOREIGN KEY (edsdbbldgverid) REFERENCES abs_mdi.ddp_edsdb_building_version (edsdbbldgverid)
);