CREATE TABLE abs_mdi.ddp_engineerjudgement (
  engineeringjudgementsid NUMBER DEFAULT abs_mdi."DDP_ENGINEERJUDGEMENT_SEQ"."NEXTVAL" NOT NULL,
  jobnumber VARCHAR2(20 BYTE),
  designcriteriacomment NCLOB,
  isdesigncriteriayes CHAR,
  designcriteriasigningengineer CHAR,
  orderrequirementcomment NCLOB,
  orderrequirementsigningengineer CHAR,
  systemgenerateddesignchangecomment NCLOB,
  systemgenerateddesignchangesigningengineer CHAR,
  workdoneoutsidecomment NCLOB,
  workdoneoutsidesigningengineer CHAR,
  systemmessagecomment NCLOB,
  systemmessagesigningengineer CHAR,
  checkingengineername VARCHAR2(50 BYTE),
  checkingengineerdate TIMESTAMP,
  projectengineername VARCHAR2(50 BYTE),
  projectengineerdate TIMESTAMP,
  signingengineername VARCHAR2(50 BYTE),
  signingengineerdate TIMESTAMP,
  createdby NUMBER,
  createddate TIMESTAMP,
  modifiedby NUMBER,
  modifieddate TIMESTAMP,
  ipaddress VARCHAR2(20 BYTE),
  isdesigncriteriano CHAR,
  ddpsserverid NUMBER(5),
  CONSTRAINT ddp_engineerjudgement_pk PRIMARY KEY (engineeringjudgementsid)
);