CREATE TABLE abs_mdi.ddp_edsdb_settings (
  settingid NUMBER DEFAULT abs_mdi."DDP_EDS_SETTINGS_SEQ"."NEXTVAL" NOT NULL,
  mbg_brand VARCHAR2(100 BYTE),
  createdby NUMBER(5),
  createddate TIMESTAMP,
  modifiedby NUMBER(5),
  modifieddate TIMESTAMP,
  isdelete CHAR DEFAULT 'N',
  ipaddress VARCHAR2(100 BYTE),
  setting_index NUMBER,
  building_name VARCHAR2(100 BYTE),
  mbg_division VARCHAR2(100 BYTE),
  mbg_fab_plant VARCHAR2(100 BYTE),
  mbg_detailing_system VARCHAR2(100 BYTE),
  work_order_number VARCHAR2(100 BYTE),
  phase VARCHAR2(100 BYTE),
  fabrication_date VARCHAR2(100 BYTE),
  ship_date VARCHAR2(100 BYTE),
  bracing_type VARCHAR2(100 BYTE),
  primer_color VARCHAR2(100 BYTE),
  customer_drawings VARCHAR2(100 BYTE),
  metric_output VARCHAR2(100 BYTE),
  simplified_sec_des VARCHAR2(100 BYTE),
  attempt_one_sided_fb VARCHAR2(100 BYTE),
  northern_climate VARCHAR2(100 BYTE),
  percent_trib_if VARCHAR2(100 BYTE),
  percent_trib_mf VARCHAR2(100 BYTE),
  gcontdes VARCHAR2(100 BYTE),
  gdisteave VARCHAR2(100 BYTE),
  gdistext VARCHAR2(100 BYTE),
  gdisthead VARCHAR2(100 BYTE),
  gdistlap VARCHAR2(100 BYTE),
  gdistmin VARCHAR2(100 BYTE),
  pullover VARCHAR2(100 BYTE),
  coldform_connection_type VARCHAR2(100 BYTE),
  stiffened_frame_connections VARCHAR2(100 BYTE),
  galvanized_secondary VARCHAR2(100 BYTE),
  frame_second_order_method VARCHAR2(100 BYTE),
  fo_try_cf_unlipped_cee VARCHAR2(100 BYTE),
  bolt_finish VARCHAR2(100 BYTE),
  min_anchor_diameter VARCHAR2(100 BYTE),
  hot_dipped_galvanized VARCHAR2(100 BYTE),
  minframemomentboltdia VARCHAR2(100 BYTE),
  edsdbbldgverid NUMBER,
  CONSTRAINT ddp_settings_pk PRIMARY KEY (settingid),
  CONSTRAINT ddp_edsdb_settings_fk1 FOREIGN KEY (edsdbbldgverid) REFERENCES abs_mdi.ddp_edsdb_building_version (edsdbbldgverid)
);