CREATE TABLE abs_mdi."Deflections" (
  "DeflectionId" NUMBER(10) NOT NULL,
  "ProjectId" NUMBER(10),
  "BuildingNumber" NUMBER(10),
  "PurlinsLive" NUMBER(5),
  "PurlinsSnow" NUMBER(5),
  "PurlinsWind" NUMBER(5),
  "PurlinsGravity" NUMBER(5),
  "PurlinsUplift" NUMBER(5),
  "RaftersLive" NUMBER(5),
  "RaftersSnow" NUMBER(5),
  "RaftersWind" NUMBER(5),
  "RaftersGravity" NUMBER(5),
  "RaftersUplift" NUMBER(5),
  "WallGirts" NUMBER(5),
  "WallCol" NUMBER(5),
  "WallWind" NUMBER(5),
  "RoofLive" NUMBER(5),
  "RoofSnow" NUMBER(5),
  "RoofWind" NUMBER(5),
  "RoofGravity" NUMBER(5),
  "RoofUplift" NUMBER(5),
  "FrameLive" NUMBER(5),
  "FrameSnow" NUMBER(5),
  "FrameWind" NUMBER(5),
  "FrameSeismic" NUMBER(5),
  "FrameCrane" NUMBER(5),
  "FrameTotalWind" NUMBER(5),
  "FrameTotalSeismic" NUMBER(5),
  "FrameTotalGravity" NUMBER(5),
  "FramePortalWind" NUMBER(5),
  "FramePortalSeismic" NUMBER(5),
  "SuspendedCeiling" NUMBER(5),
  "FaceBrickWall" NUMBER(5),
  "DryvitFinish" NUMBER(5),
  "PurlinsLiveFlag" NUMBER(1),
  "PurlinsSnowFlag" NUMBER(1),
  "PurlinsWindFlag" NUMBER(1),
  "PurlinsGravityFlag" NUMBER(1),
  "PurlinsUpliftFlag" NUMBER(1),
  "RaftersLiveFlag" NUMBER(1),
  "RaftersSnowFlag" NUMBER(1),
  "RaftersWindFlag" NUMBER(1),
  "RaftersGravityFlag" NUMBER(1),
  "RaftersUpliftFlag" NUMBER(1),
  "WallGirtsFlag" NUMBER(1),
  "WallColFlag" NUMBER(1),
  "WallWindFlag" NUMBER(1),
  "RoofLiveFlag" NUMBER(1),
  "RoofSnowFlag" NUMBER(1),
  "RoofWindFlag" NUMBER(1),
  "RoofGravityFlag" NUMBER(1),
  "RoofUpliftFlag" NUMBER(1),
  "FrameLiveFlag" NUMBER(1),
  "FrameSnowFlag" NUMBER(1),
  "FrameWindFlag" NUMBER(1),
  "FrameSeismicFlag" NUMBER(1),
  "FrameCraneFlag" NUMBER(1),
  "FrameTotalWindFlag" NUMBER(1),
  "FrameTotalSeismicFlag" NUMBER(1),
  "FrameTotalGravityFlag" NUMBER(1),
  "FramePortalWindFlag" NUMBER(1),
  "FramePortalSeismicFlag" NUMBER(1),
  "RoofPanelLive" NUMBER(5),
  "RoofPanelSnow" NUMBER(5),
  "RoofPanelWind" NUMBER(5),
  "RoofPanelGravity" NUMBER(5),
  "RoofPanelUplift" NUMBER(5),
  "WallPanel" NUMBER(5),
  "RoofPanelLiveFlag" NUMBER(1),
  "RoofPanelSnowFlag" NUMBER(1),
  "RoofPanelWindFlag" NUMBER(1),
  "RoofPanelGravityFlag" NUMBER(1),
  "RoofPanelUpliftFlag" NUMBER(1),
  "WallPanelFlag" NUMBER(1),
  "UserAccept" NUMBER(1),
  "AdvFrames" NUMBER(1),
  "AdvPurlins" NUMBER(1),
  "AdvRafters" NUMBER(1),
  "TempInteger1" NUMBER(5),
  "TempInteger2" NUMBER(5),
  "TempInteger3" NUMBER(5),
  "TempDouble1" NUMBER(5),
  "TempDouble2" NUMBER(5),
  "TempDouble3" NUMBER(5),
  "TempString1" VARCHAR2(50 BYTE),
  "TempString2" VARCHAR2(50 BYTE),
  "TempString3" VARCHAR2(50 BYTE),
  "CreatedBy" NUMBER(10),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDeleted" VARCHAR2(1 BYTE),
  CONSTRAINT "Deflections_PK" PRIMARY KEY ("DeflectionId")
);