CREATE TABLE abs_mdi."EDSPrice_O_PortalFrames" (
  "PortalFramesId" NUMBER(10) NOT NULL,
  "BuildingNumber" NUMBER(10),
  "Elevation" VARCHAR2(50 BYTE),
  "BayNumber" NUMBER(10),
  "Type" VARCHAR2(50 BYTE),
  "InSteelLine" NUMBER(10),
  "ColStartWebDepthRight" NUMBER(10,2),
  "ColStartWebDepthLeft" NUMBER(10,2),
  "ColEndWebDepthRight" NUMBER(10,2),
  "ColEndWebDepthLeft" NUMBER(10,2),
  "ColWebThickRight" NUMBER(10,2),
  "ColWebThickLeft" NUMBER(10,2),
  "ColFlangeWidthRightInside" NUMBER(10,2),
  "ColFlangeWidthLeftInside" NUMBER(10,2),
  "ColFlangeThickRightInside" NUMBER(10,2),
  "ColFlangeThickLeftInside" NUMBER(10,2),
  "ColFlangeWidthRightOutside" NUMBER(10,2),
  "ColFlangeWidthLeftOutside" NUMBER(10,2),
  "ColFlangeThickRightOutside" NUMBER(10,2),
  "ColFlangeThickLeftOutside" NUMBER(10,2),
  "RafterWebDepth" NUMBER(10,2),
  "RafterWebThick" NUMBER(10,2),
  "RafterFlangeWidthInside" NUMBER(10,2),
  "RafterFlangeWidthOutside" NUMBER(10,2),
  "RafterFlangeThickInside" NUMBER(10,2),
  "RafterFlangeThickOutside" NUMBER(10,2),
  "NumberABoltRight" NUMBER(10),
  "NumberABoltLeft" NUMBER(10),
  "ABoltDiameterRight" NUMBER(10,2),
  "ABoltDiameterLeft" NUMBER(10,2),
  "ABoltGaugeRight" NUMBER(10,2),
  "ABoltGaugeLeft" NUMBER(10,2),
  "ABoltSpaceRight" NUMBER(10,2),
  "ABoltSpaceLeft" NUMBER(10,2),
  "BasePlateWidthRight" NUMBER(10,2),
  "BasePlateWidthLeft" NUMBER(10,2),
  "BasePlateLengthRight" NUMBER(10,2),
  "BasePlateLengthLeft" NUMBER(10,2),
  "BasePlateThickRight" NUMBER(10,2),
  "BasePlateThickLeft" NUMBER(10,2),
  "ColCapPlateWidthRight" NUMBER(10,2),
  "ColCapPlateWidthLeft" NUMBER(10,2),
  "ColCapPlateThickRight" NUMBER(10,2),
  "ColCapPlateThickLeft" NUMBER(10,2),
  "ColKneeStiffenerWidthRight" NUMBER(10,2),
  "ColKneeStiffenerWidthLeft" NUMBER(10,2),
  "ColKneeStiffenerThickRight" NUMBER(10,2),
  "ColKneeStiffenerThickLeft" NUMBER(10,2),
  "ColKneePlateWidthRight" NUMBER(10,2),
  "ColKneePlateWidthLeft" NUMBER(10,2),
  "ColKneePlateThickRight" NUMBER(10,2),
  "ColKneePlateThickLeft" NUMBER(10,2),
  "ColKneeBoltDiameterRight" NUMBER(10,2),
  "ColKneeBoltDiameterLeft" NUMBER(10,2),
  "ColKneeConnectionCodeRight" VARCHAR2(50 BYTE),
  "ColKneeConnectionCodeLeft" VARCHAR2(50 BYTE),
  "Height" NUMBER(10,2),
  "Moment" NUMBER(10,2),
  "CreatedBy" NUMBER(10),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDeleted" VARCHAR2(1 BYTE),
  "ProjectId" NUMBER(10),
  CONSTRAINT "Pk_EDSPrice_O_PortalFrames_ProjectId" PRIMARY KEY ("PortalFramesId"),
  CONSTRAINT eds_price_o_portalframes_fk FOREIGN KEY ("BuildingNumber") REFERENCES abs_mdi."BuildingInformation" ("BuildingInformationId")
);