CREATE TABLE abs_mdi."EDSPrice_O_ProjectTotal" (
  "ProjectTotalId" NUMBER(10) NOT NULL,
  "ProjectNumber" NUMBER(10),
  "BaseTotalWeight" NUMBER(10,2),
  "BaseTotalPrice" NUMBER(10,2),
  "AccessoryTotalWeight" NUMBER(10,2),
  "AccessoryTotalPrice" NUMBER(10,2),
  "ListAddlinesWeight" NUMBER(10,2),
  "ListAddlinesPrice" NUMBER(10,2),
  "NetAddlinesWeight" NUMBER(10,2),
  "NetAddlinesPrice" NUMBER(10,2),
  "BuyoutsWeight" NUMBER(10,2),
  "BuyoutsPrice" NUMBER(10,2),
  "DiscountWeight" NUMBER(10,2),
  "DiscountPrice" NUMBER(10,2),
  "MultiplierWeight" NUMBER(10,2),
  "MultiplierPrice" NUMBER(10,2),
  "InsulationWeight" NUMBER(10,2),
  "InsulationPrice" NUMBER(10),
  "IncompletePricing" NUMBER(10,2),
  "ProcessingCharges" NUMBER(10,2),
  "Surcharge" NUMBER(10,2),
  "MezzNetWeight" NUMBER(10,2),
  "MezzNetPrice" NUMBER(10,2),
  "MezzListWeight" NUMBER(10,2),
  "MezzListPrice" NUMBER(10,2),
  "ComponentsWeight" NUMBER(10,2),
  "ComponentsPrice" NUMBER(10,2),
  "FreightPrice" NUMBER(10,2),
  "FreightWeight" NUMBER(10,2),
  "FreightRate1" NUMBER(10,2),
  "FreightRate2" NUMBER(10,2),
  "FreightLoads1" NUMBER(10,2),
  "FreightLoads2" NUMBER(10,2),
  "SalesTax" NUMBER(10,2),
  "FreightMiles1" NUMBER(10,2),
  "FreightMiles2" NUMBER(10,2),
  "SalesTaxPercent" NUMBER(10,2),
  "DunnageWeight" NUMBER(10,2),
  "ErectionPrice" NUMBER(10,2),
  "AdditionalCut" NUMBER(10,2),
  "SingleArticleTax" NUMBER(10,2),
  "FreightTaxable" NUMBER(10),
  "TotalSellFobPlant" NUMBER(10,2),
  "TotalFreight" NUMBER(10,2),
  "TotalTax" NUMBER(10,2),
  "GrandTotal" NUMBER(10,2),
  "StandardMultiplier" NUMBER(10),
  "SellingPrice" NUMBER(10,2),
  "TransferCost" NUMBER(10,2),
  "NetAddlinesWeightFreight" NUMBER(10,2),
  "SubmittalPackagesPrice" NUMBER(10,2),
  "RegionalAdjustment" NUMBER(10,2),
  "IPSFreightPrice" NUMBER(10,2),
  "IPSFreightWeight" NUMBER(10,2),
  "IPSFreightRate" NUMBER(10,2),
  "IPSFreightLoads" NUMBER(10,2),
  "AuthorizedAdjustment" NUMBER(10,2),
  "TotalGrossMargin" NUMBER(10,2),
  "ComponentsListWeight" NUMBER(10,2),
  "ComponentsListPrice" NUMBER(10,2),
  "ListMargin" NUMBER(10,2),
  "NetMargin" NUMBER(10,2),
  "LBPFreightPrice" NUMBER(10,2),
  "LBPFreightWeight" NUMBER(10,2),
  "LBPFreightRate" NUMBER(10,2),
  "LBPFreightLoads" NUMBER(10,2),
  "ListMarginPercentage" NUMBER(10,2),
  "NetMarginPercentage" NUMBER(10,2),
  "CreatedBy" NUMBER(10),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDeleted" VARCHAR2(1 BYTE),
  "ProjectId" NUMBER(10) NOT NULL,
  CONSTRAINT "Pk_EDSPrice_O_ProjectTotal_ProjectId" PRIMARY KEY ("ProjectId","ProjectTotalId")
);