CREATE TABLE abs_mdi."EDSPrice_I_Order" (
  "OrderId" NUMBER(10) NOT NULL,
  "ProjectId" NUMBER(10) NOT NULL,
  "TermsConditions" NUMBER(10),
  "Committed" NUMBER(10),
  "CommitmentNumber" VARCHAR2(50 BYTE),
  "CommitmentDescription" VARCHAR2(255 BYTE),
  rbs1 NUMBER(10),
  rbs2 NUMBER(10),
  "RBS2a" NUMBER(10),
  rbs3 NUMBER(10),
  rbs4 NUMBER(10),
  "RBS4a" NUMBER(10),
  rbs5 NUMBER(10),
  "RBS5a" NUMBER(10),
  "RBS5b" NUMBER(10),
  rbs6 NUMBER(10),
  "RBS6a" NUMBER(10),
  "RBS6b" NUMBER(10),
  rbs7 NUMBER(10),
  "RBS7a" NUMBER(10),
  rbs8 NUMBER(10),
  "RBS8a" NUMBER(10),
  rbs9 NUMBER(10),
  "RBS9a" NUMBER(10),
  "CreatedBy" NUMBER(10),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDeleted" VARCHAR2(1 BYTE),
  CONSTRAINT "Pk_EDSPrice_I_Order_ProjectId" PRIMARY KEY ("ProjectId")
);