CREATE TABLE abs_mdi."EDSPrice_I_OrderRequests" (
  "OrderRequestsId" NUMBER(10),
  "ScheduledByManufacturer" NUMBER(10),
  "AnchorRodDrawingsFlag" NUMBER(10),
  "AnchorRodDrawings" VARCHAR2(50 BYTE),
  "NormalDrawingsFlag" NUMBER(10),
  "NormalDrawings" VARCHAR2(50 BYTE),
  "ReleaseFromApprovalFlag" NUMBER(10),
  "ReleaseFromApproval" VARCHAR2(50 BYTE),
  "RequestedDeliveryFlag" NUMBER(10),
  "RequestedDelivery" VARCHAR2(50 BYTE),
  "ClarificationRequest" NUMBER(10),
  "ClarificationName" VARCHAR2(50 BYTE),
  "ClarificationEmail" VARCHAR2(50 BYTE),
  "ClarificationPhone" VARCHAR2(50 BYTE),
  "TCDateTime" VARCHAR2(50 BYTE),
  "CreatedBy" NUMBER(10),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDeleted" VARCHAR2(1 BYTE),
  "ProjectId" NUMBER(10) NOT NULL,
  CONSTRAINT "EDSPrice_I_OrderRequests_PK" PRIMARY KEY ("ProjectId")
);