CREATE TABLE abs_mdi."EDSPrice_I_Cranes" (
  "CranesId" NUMBER(10) NOT NULL,
  "ProjectId" NUMBER(10),
  "BuildingNumber" NUMBER(10),
  "CraneDesignID" VARCHAR2(50 BYTE),
  "StartFrameline" NUMBER(10),
  "StopFrameline" NUMBER(10),
  "Type" VARCHAR2(50 BYTE),
  "Control" VARCHAR2(50 BYTE),
  "Quantity" NUMBER(10),
  "Tonnage1" NUMBER(10,2),
  "Tonnage2" NUMBER(10,2),
  "CraneClass" VARCHAR2(50 BYTE),
  "IncludeBrackets" NUMBER(10),
  "IncludeRunwayBeams" NUMBER(10),
  "IncludeRail" NUMBER(10),
  "IncludeRoofSupportBeams" NUMBER(10),
  "IncludeSeperateSupportCol" NUMBER(10),
  "IncludeStops" NUMBER(10),
  "IncludeBracing" NUMBER(10),
  "NameBrand" VARCHAR2(50 BYTE),
  "GirderType" VARCHAR2(50 BYTE),
  "BridgeWeight1" NUMBER(10,2),
  "BridgeWeight2" NUMBER(10,2),
  "WheelSpacing1" NUMBER(10,2),
  "WheelSpacing2" NUMBER(10,2),
  "HoistWeight1" NUMBER(10,2),
  "HoistWeight2" NUMBER(10,2),
  "BracketLength" NUMBER(10,2),
  "RunwayBeamSize" NUMBER(10,2),
  "DistanceBetweenCranes" NUMBER(10,2),
  "CenterlineOfRunwayBeamToSteelLine" NUMBER(10,2),
  "CenterlineToCenterlineOfRails" NUMBER(10,2),
  "ColBaseToTopOfRail" NUMBER(10,2),
  "ClearanceFromTopRailToBottomRafter" NUMBER(10,2),
  "ClearanceFromRailToInsideFlangeCol" NUMBER(10,2),
  "ManufacturerRailSize" NUMBER(10,2),
  "TruckWheelDiameter" NUMBER(10,2),
  "VerticalDeflection" NUMBER(10,2),
  "HorizontalDeflection" NUMBER(10,2),
  "FutureLineStart" NUMBER(10),
  "FutureLineEnd" NUMBER(10),
  "DistanceToBack" NUMBER(10,2),
  "SteelYield" NUMBER(10,2),
  "RailWeight" NUMBER(10,2),
  "CecoStandard" NUMBER(10),
  "ModuleNumber" NUMBER(10),
  "UsingMfgCraneData" NUMBER(10),
  "AuxiliaryHoist1" NUMBER(10,2),
  "AuxiliaryHoist2" NUMBER(10,2),
  "TrolleyType" VARCHAR2(50 BYTE),
  "HoistType" VARCHAR2(50 BYTE),
  "UserAccept" NUMBER(10),
  "MinimumHookDistance" NUMBER(10,2),
  "LeftOverhang1" NUMBER(10,2),
  "LeftOverhang2" NUMBER(10,2),
  "RightOverhang1" NUMBER(10,2),
  "RightOverhang2" NUMBER(10,2),
  "CreatedBy" NUMBER(10),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDeleted" VARCHAR2(1 BYTE),
  CONSTRAINT "Pk_EDSPrice_I_Cranes_ProjectId" PRIMARY KEY ("CranesId")
);