CREATE TABLE abs_mdi."EDSPrice_O_OpenAreas" (
  "OpenAreasId" NUMBER(10) NOT NULL,
  "ProjectId" NUMBER(10),
  "BuildingNumber" NUMBER(10),
  "Elevation" VARCHAR2(50 BYTE),
  "StartDistance" NUMBER(10,2),
  "Width" NUMBER(10,2),
  "Height" NUMBER(10,2),
  "Type" VARCHAR2(50 BYTE),
  "Weight" NUMBER(10,2),
  "ChannelHeader" NUMBER(10),
  "ParapetYN" NUMBER(10),
  "HasSupportBeam" NUMBER(10),
  "BeamHeight" NUMBER(10,2),
  "BeamMemberType" VARCHAR2(50 BYTE),
  "BeamFlangeBracing" VARCHAR2(50 BYTE),
  "BeamForMasonry" NUMBER(10),
  "BeamDeflectionLimit" NUMBER(10),
  "CreatedBy" NUMBER(10),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDeleted" VARCHAR2(1 BYTE),
  CONSTRAINT "EDSPrice_O_OpenAreas_PK" PRIMARY KEY ("OpenAreasId")
);