CREATE TABLE abs_mdi."EDSPrice_O_Purlins" (
  "PurlinsId" NUMBER NOT NULL,
  "BuildingNumber" NUMBER(10),
  "Elevation" VARCHAR2(50 BYTE),
  "BayNumber" NUMBER(10),
  "PurlinNumber" NUMBER(10),
  "LinearOffset" NUMBER(10,2),
  "Thick" NUMBER(10,2),
  "LapLeft" NUMBER(10,2),
  "LapRight" NUMBER(10,2),
  "SnowDriftPurlin" NUMBER(10),
  "LBPDepth" NUMBER(10,2),
  "LBPWebType" VARCHAR2(50 BYTE),
  "LBPNumOfPanels" NUMBER(10),
  "LBPCenterVerWeb" NUMBER(10),
  "CreatedBy" NUMBER(10),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDeleted" VARCHAR2(1 BYTE),
  "ProjectId" NUMBER(10),
  CONSTRAINT "Pk_EDSPrice_O_Purlins_ProjectId" PRIMARY KEY ("PurlinsId")
);