CREATE TABLE abs_mdi."EDSPrice_I_Owner" (
  "OwnerId" NUMBER DEFAULT abs_mdi."EDSPrice_I_Owner_SEQ"."NEXTVAL" NOT NULL,
  "ProjectId" NUMBER(10),
  "BuildingOwner" VARCHAR2(50 BYTE),
  "Attention" VARCHAR2(50 BYTE),
  "Country" VARCHAR2(50 BYTE),
  "State" VARCHAR2(50 BYTE),
  "County" VARCHAR2(50 BYTE),
  "City" VARCHAR2(50 BYTE),
  "Address1" VARCHAR2(50 BYTE),
  "Address2" VARCHAR2(50 BYTE),
  "ZipCode" VARCHAR2(50 BYTE),
  "BusinessName" VARCHAR2(50 BYTE),
  "EndUseOfBuilding" VARCHAR2(255 BYTE),
  "LeadSource" VARCHAR2(50 BYTE),
  "InternationalSite" VARCHAR2(50 BYTE),
  "ProjectNumber" NUMBER(10),
  "PhoneNumber" VARCHAR2(50 BYTE),
  naics VARCHAR2(255 BYTE),
  "SubmittalPackage" NUMBER(10),
  "OverrideIncompletePrice" NUMBER(10),
  "CrmOpportunityNumber" VARCHAR2(255 BYTE),
  "CreatedBy" VARCHAR2(50 BYTE),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" VARCHAR2(50 BYTE),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDeleted" VARCHAR2(1 BYTE),
  CONSTRAINT "Pk_EDSPrice_I_Owner_OwnerId" PRIMARY KEY ("OwnerId")
);