CREATE TABLE abs_mdi."EDSPrice_IO_GlassFront" (
  "GlassFrontId" NUMBER(10) NOT NULL,
  "BuildingNumber" NUMBER(10),
  "Quantity" NUMBER(10),
  "Elevation" VARCHAR2(50 BYTE),
  "BayNumber" NUMBER(10),
  "HeaderHeight" NUMBER(10,2),
  "Width" NUMBER(10,2),
  "DistFromLeftCorner" NUMBER(10,2),
  "DistFromLeftCol" NUMBER(10,2),
  "GlassType" VARCHAR2(50 BYTE),
  "FrameColor" VARCHAR2(50 BYTE),
  "LeftSidelite" NUMBER(10),
  "RightSidelite" NUMBER(10),
  "BottomRail" NUMBER(10),
  "PanicDevice" NUMBER(10),
  "TintedGlass" NUMBER(10),
  "IsBuyout" NUMBER(10),
  "Weight" NUMBER(10,2),
  "Price" NUMBER(10,2),
  "IsPriced" NUMBER(10),
  "ErrorCode" NUMBER(10),
  "LeftSteelLine" NUMBER(10),
  "PartitionNumber" NUMBER(10),
  "LocateRightSideBay" NUMBER(10),
  "DistanceFromFloor" NUMBER(10,2),
  "DoorType" VARCHAR2(50 BYTE),
  "Closer" VARCHAR2(50 BYTE),
  "SwingDirection" VARCHAR2(50 BYTE),
  "LockType" VARCHAR2(100 BYTE),
  "SideliteGlass" VARCHAR2(50 BYTE),
  "MasonryApp" NUMBER(10),
  "CreatedBy" NUMBER(10),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDeleted" VARCHAR2(1 BYTE),
  "ProjectId" NUMBER(10),
  CONSTRAINT "Pk_EDSPrice_IO_GlassFront_ProjectId" PRIMARY KEY ("GlassFrontId")
);