CREATE TABLE abs_mdi."EDSPrice_I_DrawingsStar" (
  "DrawingsStarId" NUMBER(10) NOT NULL,
  "DrawingNumber" NUMBER(10),
  "Quantity" NUMBER(10),
  "Type" VARCHAR2(50 BYTE),
  "Purpose" VARCHAR2(50 BYTE),
  "Seal" VARCHAR2(50 BYTE),
  "Enhanced" NUMBER(10),
  "Mailed" VARCHAR2(50 BYTE),
  "Carrier" VARCHAR2(50 BYTE),
  "Account" VARCHAR2(50 BYTE),
  "Country" VARCHAR2(50 BYTE),
  "State" VARCHAR2(50 BYTE),
  "InternationalSite" VARCHAR2(50 BYTE),
  "ProjectNumber" NUMBER(10),
  "ShipTo" VARCHAR2(50 BYTE),
  "AnchorRodDate" VARCHAR2(50 BYTE),
  "ApprovalDate" VARCHAR2(50 BYTE),
  "PermitDate" VARCHAR2(50 BYTE),
  "MinQuantity" NUMBER(10),
  "CorpEngineers" NUMBER(10),
  "DrawingSize" VARCHAR2(50 BYTE),
  "CreatedBy" NUMBER(10),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDeleted" VARCHAR2(1 BYTE),
  "ProjectId" NUMBER(10),
  CONSTRAINT "Pk_EDSPrice_I_DrawingsStar_ProjectId" PRIMARY KEY ("DrawingsStarId")
);