CREATE TABLE abs_mdi."EDSPrice_IO_Doors" (
  "DoorsId" NUMBER(10) NOT NULL,
  "BuildingNumber" NUMBER(10),
  "Quantity" NUMBER(10),
  "Elevation" VARCHAR2(50 BYTE),
  "BayNumber" NUMBER(10),
  "Type" VARCHAR2(50 BYTE),
  "HeaderHeight" NUMBER(10,2),
  "Width" NUMBER(10,2),
  "DistFromLeftCorner" NUMBER(10,2),
  "DistFromLeftCol" NUMBER(10,2),
  "TrimColor" VARCHAR2(50 BYTE),
  "DoorColor" VARCHAR2(50 BYTE),
  "SwingDirection" VARCHAR2(50 BYTE),
  "LatchGuard" NUMBER(10),
  "Gauge" NUMBER(10),
  "SubFraming" NUMBER(10),
  "Skin" VARCHAR2(50 BYTE),
  "Lite" VARCHAR2(50 BYTE),
  "Closer" VARCHAR2(50 BYTE),
  "LockType" VARCHAR2(100 BYTE),
  "Quality" VARCHAR2(50 BYTE),
  "LeafType" VARCHAR2(50 BYTE),
  "StyleSet" VARCHAR2(50 BYTE),
  "IsBuyout" NUMBER(10),
  "Weight" NUMBER(10,2),
  "Price" NUMBER(10,2),
  "IsPriced" NUMBER(10),
  "ErrorCode" NUMBER(10),
  "KnockDown" NUMBER(10),
  "Style" VARCHAR2(50 BYTE),
  "WindRated" NUMBER(10),
  "Size" VARCHAR2(50 BYTE),
  "KeyedAlike" NUMBER(10),
  "PanicHardware" NUMBER(10),
  "ChainStop" NUMBER(10),
  "Insulated" NUMBER(10),
  "FloridaApproval" NUMBER(10),
  "LocatedInLiner" NUMBER(10),
  "Glazing" VARCHAR2(50 BYTE),
  "KickPlate" NUMBER(10),
  "LeftSteelLine" NUMBER(10),
  "PartitionNumber" NUMBER(10),
  "LocateRightSideBay" NUMBER(10),
  "DistanceFromFloor" NUMBER(10,2),
  "DadeBrowardApproved" NUMBER(10),
  "SsbHinges" NUMBER(10),
  "AddAnchors" NUMBER(10),
  "LeafInsulated" NUMBER(10),
  "LeafsBothActive" NUMBER(10),
  "Alabel3hour" NUMBER(10),
  "AdaCompliant" NUMBER(10),
  "AdditionalAnchorsQty" NUMBER(10),
  "TrimColorValsparCode" VARCHAR2(50 BYTE),
  "TrimColorSpecialName" VARCHAR2(50 BYTE),
  "CreatedBy" NUMBER(10),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDeleted" VARCHAR2(1 BYTE),
  "ProjectId" NUMBER(10),
  CONSTRAINT "Pk_EDSPrice_IO_Doors_ProjectId" PRIMARY KEY ("DoorsId")
);