CREATE TABLE abs_mdi."EDSPrice_IO_Mezzanines" (
  "MezzaninesId" NUMBER(10) NOT NULL,
  "BuildingNumber" NUMBER(10),
  "MezzanineNumber" NUMBER(10),
  "JoistParallelToPurlins" NUMBER(10),
  "StartFrameline" NUMBER(10),
  "StopFrameline" NUMBER(10),
  "DistFromSW" NUMBER(10,2),
  "Width" NUMBER(10,2),
  "OpenDistFromSw" NUMBER(10,2),
  "OpenDistFromFrameline" NUMBER(10,2),
  "OpenWidthAlongEw" NUMBER(10,2),
  "OpenLengthAlongSw" NUMBER(10,2),
  "Design" NUMBER(10),
  "Beams" NUMBER(10),
  "Deck" NUMBER(10),
  "Joists" NUMBER(10),
  "SupportColumns" NUMBER(10),
  "EdgeAngle" NUMBER(10),
  "FloorThickness" NUMBER(10,2),
  "FloorHeight" NUMBER(10,2),
  "FloorMaterial" VARCHAR2(50 BYTE),
  "InsideClearBeams" NUMBER(10,2),
  "MaxBeamDepth" NUMBER(10,2),
  "InsideClearJoists" NUMBER(10,2),
  "MaxJoistDepth" NUMBER(10,2),
  "JoistShopcoat" VARCHAR2(50 BYTE),
  "JoistWelded" NUMBER(10),
  "JoistSpacing" NUMBER(10,2),
  "DeckType" VARCHAR2(50 BYTE),
  "DeckFinish" VARCHAR2(50 BYTE),
  "DeckFastened" NUMBER(10),
  "DeckIcboApproval" NUMBER(10),
  "DeckClosure" NUMBER(10),
  "LiveLoad" NUMBER(10,2),
  "DeadLoad" NUMBER(10,2),
  "CollateralLoad" NUMBER(10,2),
  "PartitionLoad" NUMBER(10,2),
  "QuoteNumber" VARCHAR2(50 BYTE),
  "QuoteYear" VARCHAR2(50 BYTE),
  "EstimatorInitials" VARCHAR2(50 BYTE),
  "ExpiresOn" VARCHAR2(50 BYTE),
  "Expired" NUMBER(10),
  "NoVendor" NUMBER(10),
  "PriceStar" NUMBER(10,2),
  "WeightStar" NUMBER(10,2),
  "PriceBeams" NUMBER(10,2),
  "WeightBeams" NUMBER(10,2),
  "PriceJoists" NUMBER(10,2),
  "WeightJoists" NUMBER(10,2),
  "VendorJoists" VARCHAR2(50 BYTE),
  "PriceDeck" NUMBER(10),
  "WeightDeck" NUMBER(10),
  "VendorDeck" VARCHAR2(50 BYTE),
  "Vibration" NUMBER(10),
  "DeckCoverage" VARCHAR2(50 BYTE),
  "HumanActivity" NUMBER(10),
  "MezzUse" VARCHAR2(50 BYTE),
  "MezzColSpacingSet" NUMBER(10),
  "StairwellWeight" NUMBER(10,2),
  "ClearToRafter" NUMBER(10,2),
  "LiveLoadReduction" NUMBER(10),
  "AttachmentToSupport" VARCHAR2(50 BYTE),
  "AttachmentToSidelap" VARCHAR2(50 BYTE),
  "AttachmentByStarSupport" NUMBER(10),
  "AttachmentByStarSidelap" NUMBER(10),
  "JoistType" VARCHAR2(50 BYTE),
  "JoistSpacingStandard" NUMBER(10),
  "JoistSpacingSpecified" VARCHAR2(255 BYTE),
  "IntMezzColumnType" VARCHAR2(50 BYTE),
  "ColumnBaseType" VARCHAR2(50 BYTE),
  "ColumnBaseHeight" NUMBER(10,2),
  "JoistSpacingCustom" NUMBER(10,2),
  "DeckDescription" VARCHAR2(50 BYTE),
  "DeckFinishWidth" VARCHAR2(50 BYTE),
  "DeckFinishType" VARCHAR2(50 BYTE),
  "DeckFinishGauge" VARCHAR2(50 BYTE),
  "DeckFinishFinish" VARCHAR2(50 BYTE),
  "HideWeightPrice" NUMBER(10),
  "CreatedBy" NUMBER(10),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDeleted" VARCHAR2(1 BYTE),
  "ProjectId" NUMBER(10),
  CONSTRAINT "Pk_EDSPrice_IO_Mezzanines_ProjectId" PRIMARY KEY ("MezzaninesId")
);