CREATE TABLE abs_mdi."EDSPrice_O_InteriorColumns" (
  "InteriorColumnsId" NUMBER(10) NOT NULL,
  "BuildingNumber" NUMBER(10),
  "Elevation" VARCHAR2(50 BYTE),
  "FramelineNumber" NUMBER(10),
  "Type" VARCHAR2(50 BYTE),
  "Rotation" NUMBER(10,2),
  "DistFromWall" NUMBER(10,2),
  "ColHeight" NUMBER(10,2),
  "PipeDiameter" NUMBER(10,2),
  "PipeThick" NUMBER(10,2),
  "TubeWidth" NUMBER(10,2),
  "TubeThickness" NUMBER(10,2),
  "HotRollWebDepth" NUMBER(10,2),
  "HotRollWebThick" NUMBER(10,2),
  "HotRollFlangeWidth" NUMBER(10,2),
  "HotRollFlangeThick" NUMBER(10,2),
  "BasePlateWidth" NUMBER(10,2),
  "BasePlateThick" NUMBER(10,2),
  "BasePlateDepth" NUMBER(10,2),
  "NumberOfABolts" NUMBER(10),
  "ABoltDiameter" NUMBER(10,2),
  "ABoltGauge" NUMBER(10,2),
  "ABoltSpacing" NUMBER(10,2),
  "CapPlateWidth" NUMBER(10,2),
  "CapPlateThick" NUMBER(10,2),
  "CapPlateDepth" NUMBER(10,2),
  "CapPlateBolts" NUMBER(10),
  "CapPlateBoltSize" NUMBER(10,2),
  "CapPlateBoltGauge" NUMBER(10,2),
  "CapPlateBoltSpacing" NUMBER(10,2),
  "NumberOfStiffeners" NUMBER(10),
  "StiffenerType" VARCHAR2(50 BYTE),
  "StiffenerWidth" NUMBER(10,2),
  "StiffenerThick" NUMBER(10,2),
  "StiffenerLength" NUMBER(10,2),
  "StiffenerAngle" NUMBER(10,2),
  "StiffenerOffset" NUMBER(10,2),
  "CreatedBy" NUMBER(10),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDeleted" VARCHAR2(1 BYTE),
  "ProjectId" NUMBER(10),
  CONSTRAINT "Pk_EDSPrice_O_InteriorColumns_ProjectId" PRIMARY KEY ("InteriorColumnsId"),
  CONSTRAINT eds_price_o_interiorcolumns_fk FOREIGN KEY ("BuildingNumber") REFERENCES abs_mdi."BuildingInformation" ("BuildingInformationId")
);