CREATE TABLE abs_mdi."EDSPrice_IO_SlideDoors" (
  "SlideDoorsId" NUMBER(10) NOT NULL,
  "BuildingNumber" NUMBER(10),
  "Elevation" VARCHAR2(50 BYTE),
  "BayNumber" NUMBER(10),
  "Material" VARCHAR2(50 BYTE),
  "Type" VARCHAR2(50 BYTE),
  "Width" NUMBER(10,2),
  "Height" NUMBER(10,2),
  "DistFromLeftCorner" NUMBER(10,2),
  "DistFromLeftCol" NUMBER(10,2),
  "HeaderHeight" NUMBER(10,2),
  "TrimColor" VARCHAR2(50 BYTE),
  "JambType" VARCHAR2(50 BYTE),
  "CeeDepth" NUMBER(10,2),
  "InsideFlangeWidth" NUMBER(10,2),
  "InsideFlangeThick" NUMBER(10,2),
  "OutsideFlangeWidth" NUMBER(10,2),
  "OutsideFlangeThick" NUMBER(10,2),
  "WebDepth" NUMBER(10,2),
  "WebThick" NUMBER(10,2),
  "DoubleJambs" NUMBER(10),
  "TrimOnly" NUMBER(10),
  "PanelCredit" NUMBER(10),
  "Clearance" NUMBER(10,2),
  "Slide" VARCHAR2(50 BYTE),
  "Direction" VARCHAR2(50 BYTE),
  "HoodFlash" NUMBER(10),
  "Weight" NUMBER(10,2),
  "Price" NUMBER(10,2),
  "IsPriced" NUMBER(10),
  "ErrorCode" NUMBER(10),
  "Quantity" NUMBER(10),
  "LeftSteelLine" NUMBER(10),
  "PartitionNumber" NUMBER(10),
  "LocateRightSideBay" NUMBER(10),
  "TrimColorValsparCode" VARCHAR2(50 BYTE),
  "TrimColorSpecialName" VARCHAR2(50 BYTE),
  "IsBuyout" NUMBER(10),
  "CreatedBy" NUMBER(10),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDeleted" VARCHAR2(1 BYTE),
  "ProjectId" NUMBER(10),
  CONSTRAINT "Pk_EDSPrice_IO_SlideDoors_ProjectId" PRIMARY KEY ("SlideDoorsId")
);