CREATE TABLE abs_mdi."EDSPrice_CAD_Express" (
  "ExpressId" NUMBER(10) NOT NULL,
  "ProjectId" NUMBER(10),
  "BuildingNumber" NUMBER(10),
  "Drawing" NUMBER(10),
  "PaperSize" NUMBER(10),
  "Scale" NUMBER(10),
  "Manufacturer" NUMBER(10),
  "FramelineXSection" NUMBER(10),
  "DrawingName" VARCHAR2(255 BYTE),
  "PF_Elevation" VARCHAR2(50 BYTE),
  "PF_BayNumber" NUMBER(10),
  "CreatedBy" NUMBER(10),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDeleted" VARCHAR2(1 BYTE),
  CONSTRAINT "EDSPrice_CAD_Express_PK" PRIMARY KEY ("ExpressId")
);