CREATE TABLE abs_mdi."EDSPrice_O_BuildingTotal" (
  "BuildingTotalId" NUMBER(10) NOT NULL,
  "BuildingNumber" NUMBER(10) NOT NULL,
  "AddLinesListWeight" NUMBER(10),
  "AddLinesListPrice" NUMBER(10,2),
  "AddLinesNetWeight" NUMBER(10),
  "AddLinesNetPrice" NUMBER(10,2),
  "BuyoutWeight" NUMBER(10),
  "BuyoutPrice" NUMBER(10,2),
  "DoorWeight" NUMBER(10),
  "DoorPrice" NUMBER(10,2),
  "DownSpoutsWeight" NUMBER(10),
  "DownSpoutsPrice" NUMBER(10,2),
  "EaveTrimWeight" NUMBER(10),
  "EaveTrimPrice" NUMBER(10,2),
  "FacadesWeight" NUMBER(10),
  "FacadesPrice" NUMBER(10,2),
  "FramedOpeningsWeight" NUMBER(10),
  "FramedOpeningsPrice" NUMBER(10,2),
  "GuttersWeight" NUMBER(10),
  "GuttersPrice" NUMBER(10,2),
  "InsulationAccessoriesWeight" NUMBER(10),
  "InsulationAccessoriesPrice" NUMBER(10,2),
  "InsulationTotalsWeight" NUMBER(10),
  "InsulationTotalsPrice" NUMBER(10,2),
  "LinersWeight" NUMBER(10),
  "LinersPrice" NUMBER(10,2),
  "LouverWeight" NUMBER(10),
  "LouverPrice" NUMBER(10,2),
  "PipeFlashWeight" NUMBER(10),
  "PipeFlashPrice" NUMBER(10,2),
  "SlideDoorsWeight" NUMBER(10),
  "SlideDoorsPrice" NUMBER(10,2),
  "SupportBeamsWeight" NUMBER(10),
  "SupportBeamsPrice" NUMBER(10,2),
  "TranslucentPanelsWeight" NUMBER(10),
  "TranslucentPanelsPrice" NUMBER(10,2),
  "ValleyGuttersWeight" NUMBER(10),
  "ValleyGuttersPrice" NUMBER(10,2),
  "VentsWeight" NUMBER(10),
  "VentsPrice" NUMBER(10,2),
  "WindowsWeight" NUMBER(10),
  "WindowsPrice" NUMBER(10,2),
  "MiscellaneousWeight" NUMBER(10),
  "MiscellaneousPrice" NUMBER(10,2),
  "Base_Total_Weight" NUMBER(10),
  "Base_Total_Price" NUMBER(10,2),
  "MezzNetWeight" NUMBER(10),
  "MezzNetPrice" NUMBER(10,2),
  "MezzListWeight" NUMBER(10),
  "MezzListPrice" NUMBER(10,2),
  "ComponentsWeight" NUMBER(10),
  "ComponentsPrice" NUMBER(10,2),
  "PartitionWeight" NUMBER(10),
  "PartitionPrice" NUMBER(10,2),
  "NetWeightIncludeFreight" NUMBER(10),
  "CreatedBy" NUMBER(10),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDeleted" VARCHAR2(1 BYTE),
  "ProjectId" NUMBER(10),
  CONSTRAINT "Pk_EDSPrice_O_BuildingTotal_ProjectId" PRIMARY KEY ("BuildingTotalId"),
  CONSTRAINT eds_price_o_buildingtotal_fk FOREIGN KEY ("BuildingNumber") REFERENCES abs_mdi."BuildingInformation" ("BuildingInformationId")
);