CREATE TABLE abs_mdi."EDSPrice_CAD_Options" (
  "OptionsId" NUMBER(10) NOT NULL,
  "ProjectId" NUMBER(10),
  "DrawingName" VARCHAR2(255 BYTE),
  "BrickHeight" NUMBER(10,2),
  "BrickWidth" NUMBER(10,2),
  "BrickThick" NUMBER(10,2),
  "BrickGap" NUMBER(10,2),
  "CustomPaperHeight" NUMBER(10,2),
  "CustomPaperWidth" NUMBER(10,2),
  "CustomBorderHeight" NUMBER(10,2),
  "CustomBorderWidth" NUMBER(10,2),
  "CustomTBlockLocation" VARCHAR2(255 BYTE),
  "CustomBackgroundLocation" VARCHAR2(255 BYTE),
  "IsMasonryHighDetail" NUMBER(10),
  "IsPanelHighDetail" NUMBER(10),
  "IsSteelHighDetail" NUMBER(10),
  "IsDrawingRenderReady" NUMBER(10),
  "WantMasonry" NUMBER(10),
  "WantPanel" NUMBER(10),
  "WantAccessories" NUMBER(10),
  "WantSteel" NUMBER(10),
  "WantLandscape" NUMBER(10),
  "3DRenderType" NUMBER(10),
  "3DViewHeight" NUMBER(10),
  "3DViewOrientation" NUMBER(10),
  "DimType" NUMBER(10),
  "DimScheme" NUMBER(10),
  "CadProgramToLaunch" NUMBER(10),
  "TBlockSize" NUMBER(10),
  "TBlockType" NUMBER(10),
  "DrawingSaveAsFileType" NUMBER(10),
  "DrawingScaleFactor" NUMBER(10),
  "Manufacturer" NUMBER(10),
  "CreatedBy" NUMBER(10),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDeleted" VARCHAR2(1 BYTE),
  CONSTRAINT "EDSPrice_CAD_Options_PK" PRIMARY KEY ("OptionsId")
);