CREATE TABLE abs_mdi."EDSPrice_O_EWColumns" (
  "EWColumnsId" NUMBER(10) NOT NULL,
  "BuildingNumber" NUMBER(10),
  "Elevation" VARCHAR2(50 BYTE),
  "ColNumber" NUMBER(10),
  "ColType" VARCHAR2(50 BYTE),
  "ColHeight" NUMBER(10,2),
  "InsideFlangeWidth" NUMBER(10,2),
  "InsideFlangeThick" NUMBER(10,2),
  "OutsideFlangeWidth" NUMBER(10,2),
  "OutsideFlangeThick" NUMBER(10,2),
  "WebDepth" NUMBER(10,2),
  "WebThick" NUMBER(10,2),
  "Rotated" VARCHAR2(1 BYTE),
  "ColName" VARCHAR2(255 BYTE),
  "CreatedBy" NUMBER(10),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDeleted" VARCHAR2(1 BYTE),
  "ProjectId" NUMBER(10),
  CONSTRAINT "Pk_EDSPrice_O_EWColumns_ProjectId" PRIMARY KEY ("EWColumnsId"),
  CONSTRAINT eds_price_o_ewcolumns_fk FOREIGN KEY ("BuildingNumber") REFERENCES abs_mdi."BuildingInformation" ("BuildingInformationId")
);