CREATE TABLE abs_mdi."EDSPrice_O_EWRafters" (
  "EWRaftersId" NUMBER(10) NOT NULL,
  "BuildingNumber" NUMBER(10),
  "Elevation" VARCHAR2(50 BYTE),
  "RafterNumber" NUMBER(10),
  "RafterLength" NUMBER(10,2),
  "RafterType" VARCHAR2(50 BYTE),
  "SetBack" NUMBER(10,2),
  "FlangeWidth" NUMBER(10,2),
  "FlangeThick" NUMBER(10,2),
  "WebDepth" NUMBER(10,2),
  "WebThick" NUMBER(10,2),
  "CreatedBy" NUMBER(10),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDeleted" VARCHAR2(1 BYTE),
  "ProjectId" NUMBER(10),
  CONSTRAINT "Pk_EDSPrice_O_EWRafters_ProjectId" PRIMARY KEY ("EWRaftersId"),
  CONSTRAINT eds_price_o_ewrafters_fk FOREIGN KEY ("BuildingNumber") REFERENCES abs_mdi."BuildingInformation" ("BuildingInformationId")
);