CREATE TABLE abs_mdi."EDSPrice_I_Payment" (
  "PaymentId" NUMBER DEFAULT abs_mdi."EDSPrice_I_Payment_SEQ"."NEXTVAL" NOT NULL,
  "AuthorizedSignature" VARCHAR2(50 BYTE),
  "OrderedBy" VARCHAR2(50 BYTE),
  "BuilderPO" VARCHAR2(50 BYTE),
  "CreditTerms" VARCHAR2(50 BYTE),
  "Bank" VARCHAR2(50 BYTE),
  "Teller" VARCHAR2(50 BYTE),
  "TaxExemptStatus" VARCHAR2(50 BYTE),
  "TaxExemptNumber" VARCHAR2(50 BYTE),
  "TaxIncluded" NUMBER(10),
  "Multiplier" NUMBER(10,8),
  "ProjectNumber" NUMBER(10),
  "IMPOverage" NUMBER(10),
  "ClarificationDayPhone" VARCHAR2(50 BYTE),
  "MultiplierAuthorization" VARCHAR2(50 BYTE),
  "GCName" VARCHAR2(50 BYTE),
  "GCState" VARCHAR2(50 BYTE),
  "GCCity" VARCHAR2(50 BYTE),
  "ErectorName" VARCHAR2(50 BYTE),
  "ErectorState" VARCHAR2(50 BYTE),
  "ErectorCity" VARCHAR2(50 BYTE),
  "LenderName" VARCHAR2(50 BYTE),
  "LenderState" VARCHAR2(50 BYTE),
  "LenderCity" VARCHAR2(50 BYTE),
  "LenderAddress" VARCHAR2(50 BYTE),
  "LenderZipcode" VARCHAR2(50 BYTE),
  "LenderPhone" VARCHAR2(50 BYTE),
  "LenderAddress2" VARCHAR2(50 BYTE),
  "IMPFreightPerBuilding" NUMBER(10),
  "ValidUntil" VARCHAR2(50 BYTE),
  "DateAuthorized" VARCHAR2(50 BYTE),
  "MultiplierBWXGenerated" NUMBER(10,2),
  "MultiplierStart" NUMBER(10,2),
  "MultiplierTarget" NUMBER(10,2),
  "MultiplierFloor" NUMBER(10,2),
  "MultiplierRequested" NUMBER(10,2),
  "MultiplierSuggested" NUMBER(10,2),
  "ProjectGuid" VARCHAR2(200 BYTE),
  "ProjectFile" VARCHAR2(255 BYTE),
  "CreatedBy" VARCHAR2(50 BYTE),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" VARCHAR2(50 BYTE),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDeleted" VARCHAR2(1 BYTE),
  "ProjectId" NUMBER(10),
  gccountry VARCHAR2(50 BYTE),
  erectorcountry VARCHAR2(50 BYTE),
  lendercountry VARCHAR2(50 BYTE),
  "EstimatorInitials" VARCHAR2(50 BYTE),
  CONSTRAINT "Pk_EDSPrice_I_Payment_ProjectId" PRIMARY KEY ("PaymentId")
);