CREATE TABLE abs_mdi."EDSPrice_IO_Curbs" (
  "CurbsId" NUMBER(10) NOT NULL,
  "BuildingNumber" NUMBER(10),
  "Quantity" NUMBER(10),
  "Elevation" VARCHAR2(50 BYTE),
  "Width" NUMBER(10,2),
  "Height" NUMBER(10,2),
  "DistFromLeftCorner" NUMBER(10,2),
  "DistFromWall" NUMBER(10,2),
  "InsideClearDim" NUMBER(10,2),
  "OutsideClearDim" NUMBER(10,2),
  "SupportedWeight" NUMBER(10,2),
  "PurlinPass" NUMBER(10),
  "BracingPass" NUMBER(10),
  "FramedOpening" NUMBER(10),
  "Insulated" NUMBER(10),
  "Finish" VARCHAR2(50 BYTE),
  "Weight" NUMBER(10,2),
  "Price" NUMBER(10,2),
  "IsPriced" NUMBER(10),
  "ErrorCode" NUMBER(10),
  "CreatedBy" NUMBER(10),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDeleted" VARCHAR2(1 BYTE),
  "ProjectId" NUMBER(10),
  CONSTRAINT "Pk_EDSPrice_IO_Curbs_ProjectId" PRIMARY KEY ("CurbsId")
);