CREATE TABLE abs_mdi."EDSPrice_O_FLSegments" (
  "FLSegmentsId" NUMBER(10) NOT NULL,
  "BuildingNumber" NUMBER(10),
  "Elevation" VARCHAR2(50 BYTE),
  "FramelineNumber" NUMBER(10),
  "SegmentNumber" NUMBER(10),
  "SegmentType" VARCHAR2(50 BYTE),
  "SegmentLength" NUMBER(10,2),
  "FlangeThickOutside" NUMBER(10,2),
  "FlangeThickInside" NUMBER(10,2),
  "FlangeWidthOutside" NUMBER(10,2),
  "FlangeWidthInside" NUMBER(10,2),
  "WebThick" NUMBER(10,2),
  "StartWebDepth" NUMBER(10,2),
  "EndWebDepth" NUMBER(10,2),
  "CreatedBy" NUMBER(10),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDeleted" VARCHAR2(1 BYTE),
  "ProjectId" NUMBER(10),
  CONSTRAINT "Pk_EDSPrice_O_FLSegments_ProjectId" PRIMARY KEY ("FLSegmentsId"),
  CONSTRAINT eds_price_o_flsegments_fk FOREIGN KEY ("BuildingNumber") REFERENCES abs_mdi."BuildingInformation" ("BuildingInformationId")
);