CREATE TABLE abs_mdi."EDSPrice_O_EWPlates" (
  "EWPlatesId" NUMBER(10) NOT NULL,
  "BuildingNumber" NUMBER(10),
  "Elevation" VARCHAR2(50 BYTE),
  "Type" VARCHAR2(50 BYTE),
  "ColNumber" NUMBER(10),
  "SegmentNumber" NUMBER(10),
  "Thick" NUMBER(10,2),
  "Width" NUMBER(10,2),
  "Depth" NUMBER(10,2),
  "ProjectionInside" NUMBER(10,2),
  "CreatedBy" NUMBER(10),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "ProjectId" NUMBER(10),
  "IsDeleted" VARCHAR2(1 BYTE),
  CONSTRAINT "Pk_EDSPrice_O_EWPlates_ProjectId" PRIMARY KEY ("EWPlatesId"),
  CONSTRAINT eds_price_o_ewplates_fk FOREIGN KEY ("BuildingNumber") REFERENCES abs_mdi."BuildingInformation" ("BuildingInformationId")
);