CREATE TABLE abs_mdi."EDSPrice_CAD_TitleBlock" (
  "TitleBlockId" NUMBER(10) NOT NULL,
  "ProjectId" NUMBER(10),
  "DrawingName" VARCHAR2(255 BYTE),
  "BuilderNumber" VARCHAR2(50 BYTE),
  "BuilderName" VARCHAR2(50 BYTE),
  "BuilderContact" VARCHAR2(50 BYTE),
  "BuilderAddress1" VARCHAR2(50 BYTE),
  "BuilderAddress2" VARCHAR2(50 BYTE),
  "BuilderCity" VARCHAR2(50 BYTE),
  "BuilderState" VARCHAR2(50 BYTE),
  "BuilderZip" VARCHAR2(50 BYTE),
  "BuilderCounty" VARCHAR2(50 BYTE),
  "BuilderCountry" VARCHAR2(50 BYTE),
  "BuilderEmail" VARCHAR2(255 BYTE),
  "BuilderWebSite" VARCHAR2(255 BYTE),
  "OwnerName" VARCHAR2(50 BYTE),
  "OwnerAddress1" VARCHAR2(50 BYTE),
  "OwnerAddress2" VARCHAR2(50 BYTE),
  "OwnerCity" VARCHAR2(50 BYTE),
  "OwnerState" VARCHAR2(50 BYTE),
  "OwnerZip" VARCHAR2(50 BYTE),
  "OwnerCounty" VARCHAR2(50 BYTE),
  "OwnerCountry" VARCHAR2(50 BYTE),
  "JobName" VARCHAR2(50 BYTE),
  "JobDateOfEstimate" VARCHAR2(50 BYTE),
  "JobEstimator" VARCHAR2(50 BYTE),
  "JobID" VARCHAR2(50 BYTE),
  "DrawingRevisionNumber" VARCHAR2(50 BYTE),
  "DrawingDate" VARCHAR2(50 BYTE),
  "Plant" VARCHAR2(50 BYTE),
  "CreatedBy" NUMBER(10),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDeleted" VARCHAR2(1 BYTE),
  CONSTRAINT "EDSPrice_CAD_TitleBlock_PK" PRIMARY KEY ("TitleBlockId")
);