CREATE TABLE abs_mdi."EDSPrice_IO_Downspouts" (
  "DownspoutsId" NUMBER(10) NOT NULL,
  "BuildingNumber" NUMBER(10),
  "Quantity" NUMBER(10),
  "Elevation" VARCHAR2(50 BYTE),
  "BayNumber" NUMBER(10),
  "DistFromLeftCorner" NUMBER(10,2),
  "DistFromLeftCol" NUMBER(10,2),
  "Length" NUMBER(10,2),
  "Color" VARCHAR2(50 BYTE),
  "Type" VARCHAR2(50 BYTE),
  "Elbows" NUMBER(10),
  "Drainage" NUMBER(10,2),
  "IsBuyout" NUMBER(10),
  "Weight" NUMBER(10,2),
  "Price" NUMBER(10,2),
  "IsPriced" NUMBER(10),
  "ErrorCode" NUMBER(10),
  "Thimbles" NUMBER(10),
  "CreatedBy" NUMBER(10),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDeleted" VARCHAR2(1 BYTE),
  "ProjectId" NUMBER(10),
  CONSTRAINT "Pk_EDSPrice_IO_Downspouts_ProjectId" PRIMARY KEY ("DownspoutsId")
);