CREATE TABLE abs_mdi."EDSPrice_I_Components" (
  "ComponentsId" NUMBER(10) NOT NULL,
  "ProjectId" NUMBER(10),
  "BasePartNumber" VARCHAR2(50 BYTE),
  "PartNumber" VARCHAR2(50 BYTE),
  "ItemCategory" VARCHAR2(50 BYTE),
  "Quantity" NUMBER(10),
  "Color" VARCHAR2(50 BYTE),
  "Length" NUMBER(10,2),
  "Gauge" NUMBER(10),
  "Side" VARCHAR2(50 BYTE),
  "UnitOfMeasure" VARCHAR2(50 BYTE),
  "Description" VARCHAR2(255 BYTE),
  "Mark" VARCHAR2(255 BYTE),
  "UnitWeight" NUMBER(10,2),
  "UnitPrice" NUMBER(10,2),
  "TotalWeight" NUMBER(10,2),
  "TotalPrice" NUMBER(10,2),
  "ShippingPlant" VARCHAR2(50 BYTE),
  "CreatedBy" NUMBER(10),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDeleted" VARCHAR2(1 BYTE),
  CONSTRAINT "EDSPrice_I_Components_PK" PRIMARY KEY ("ComponentsId")
);