CREATE TABLE abs_mdi."Escarpment" (
  "EscarpmentId" NUMBER(10) NOT NULL,
  "ProjectId" NUMBER(10),
  "BuildingNumber" NUMBER(10),
  "HillHeight" NUMBER(10),
  "Lh" NUMBER(10),
  "CrestDistance" NUMBER(10),
  "CrestUpwind" NUMBER(10),
  "FlatUpwindTerrain" NUMBER(10),
  "HillTallerBy2" NUMBER(10),
  "UpperHalfOfHill" NUMBER(10),
  "2ndRidgeOfHill" NUMBER(10),
  "TempString1" VARCHAR2(50 BYTE),
  "TempString2" VARCHAR2(50 BYTE),
  "TempDouble1" NUMBER(10,2),
  "TempDouble2" NUMBER(10,2),
  "TempInteger1" NUMBER(10),
  "TempInteger2" NUMBER(10),
  "Answers" NUMBER(20),
  "QuestionsAnswered" NUMBER(10),
  "Kzt" NUMBER(10),
  "CreatedBy" NUMBER(10),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDeleted" VARCHAR2(1 BYTE),
  CONSTRAINT "Escarpment_PK" PRIMARY KEY ("EscarpmentId")
);