CREATE TABLE abs_mdi."GeometryInformation" (
  "GeometryInformationId" NUMBER(10) NOT NULL,
  "BuildingInformationId" NUMBER(10),
  "BuildingWidth" NUMBER(20,8),
  "BuildingLength" NUMBER(20,8),
  "DistanceToRidgeSideWallB" NUMBER(20,8),
  "DistanceToRidgeSideWallD" NUMBER(20,8),
  "DistanceToRidgeSideWallA" NUMBER(20,8),
  "DistanceToRidgeSideWallC" NUMBER(20,8),
  "EaveHeightSideWallB" NUMBER(20,8),
  "EaveHeightSideWallD" NUMBER(20,8),
  "RoofSlopeSideWallB" NUMBER(20,4),
  "RoofSlopeSideWallD" NUMBER(20,4),
  "EaveHeightSideWallA" NUMBER(20,8),
  "EaveHeightSideWallC" NUMBER(20,8),
  "RoofSlopeSideWallA" NUMBER(20,4),
  "RoofSlopeSideWallC" NUMBER(20,4),
  "Swa" CHAR,
  "Swb" CHAR,
  "CreatedBy" NUMBER(5),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(5),
  "ModifiedDate" TIMESTAMP,
  "Category" VARCHAR2(50 BYTE),
  "CurrentBuilding" VARCHAR2(20 BYTE),
  "AvailableBuilding" NUMBER(5),
  "Elevation" CHAR,
  "XDistance" NUMBER(12,8),
  "YDistance" NUMBER(12,8),
  "OffsetDistance" VARCHAR2(20 BYTE),
  "StartColumn" NUMBER(10),
  "StopColumn" NUMBER(10),
  "XDirection" VARCHAR2(5 BYTE),
  "YDirection" VARCHAR2(5 BYTE),
  "AttachmentOffset" NUMBER(20,8),
  "PeakHeight" NUMBER(20,8),
  "WindEnclosure" VARCHAR2(50 BYTE),
  "AccessoryEnclosure" VARCHAR2(50 BYTE),
  "OAEnclosure" VARCHAR2(50 BYTE),
  "XCoordinate" NUMBER(12,8),
  "YCoordinate" NUMBER(12,8),
  "IsDeleted" VARCHAR2(1 BYTE),
  CONSTRAINT "GeometryInformation_PK" PRIMARY KEY ("GeometryInformationId"),
  CONSTRAINT "BuildingInformation_FK" FOREIGN KEY ("BuildingInformationId") REFERENCES abs_mdi."BuildingInformation" ("BuildingInformationId")
);