CREATE TABLE abs_mdi."Input_Endwalls_OpenArea" (
  "OptionId" NUMBER(10) NOT NULL,
  "BuildingNo" NUMBER(10),
  "ProjectId" NUMBER(10),
  "EndWallNo" NUMBER(10),
  "OpenAreaFor" VARCHAR2(20 BYTE),
  "WallType" VARCHAR2(20 BYTE),
  "AttanchedBuildingNo" VARCHAR2(20 BYTE),
  "Width" VARCHAR2(20 BYTE),
  "Height" VARCHAR2(20 BYTE),
  "IsFullWidth" CHAR,
  "IsPMaterialByOthers" CHAR,
  "OpenFor" NUMBER(10),
  "IsSheetedWall" CHAR,
  "MasonryReinforcement" NUMBER(10),
  "MasonryType" NUMBER(10),
  "TiltUp" NUMBER(10),
  "IsShearWall" CHAR,
  "ColumnBeBraced" CHAR,
  "NotDeductLinearPanel" CHAR,
  "NotDeductInsulation" CHAR,
  "DeductPanelTrim" CHAR,
  "IncludeJambFlash" CHAR,
  "IncludeHeaderFlash" CHAR,
  "Base" NUMBER(10),
  "FlashColor" VARCHAR2(20 BYTE),
  "MaterialThickness" VARCHAR2(20 BYTE),
  "MaterialWeight" VARCHAR2(20 BYTE),
  "DistanceFromSteelLinetoF" VARCHAR2(20 BYTE),
  "DistanceFromSteelLinetoJ" VARCHAR2(20 BYTE),
  "PercRemainingOpenForWind" VARCHAR2(20 BYTE),
  "SupportBeanByManufacturer" CHAR,
  "BeamLocation" NUMBER(10),
  "BeamType" NUMBER(10),
  "BeamDeflectionLenghth" NUMBER(10),
  "UseFalangeBracing" CHAR,
  "ConnectionSpaceOfWallAttachmentToSBeam" VARCHAR2(20 BYTE),
  "CreatedBy" NUMBER(10),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDeleted" CHAR,
  CONSTRAINT "Input_Endwalls_ColumnSpacingOptions_PK" PRIMARY KEY ("OptionId")
);