CREATE TABLE abs_mdi."Input_TrimColorSelections" (
  "TrimColorSelectionId" NUMBER(5) NOT NULL,
  "BuildingNumber" NUMBER(5),
  "RoofPanel" VARCHAR2(30 BYTE),
  "WallPanel" VARCHAR2(30 BYTE),
  "EaveFlash" VARCHAR2(30 BYTE),
  "GableFlash" VARCHAR2(30 BYTE),
  "CornerFlash" VARCHAR2(30 BYTE),
  "BaseFlash" VARCHAR2(30 BYTE),
  "AllOtherFlash" VARCHAR2(30 BYTE),
  "RoofGuarantee" VARCHAR2(30 BYTE),
  "WallGuarantee" VARCHAR2(30 BYTE),
  "PerforationGuarantee" NUMBER(5),
  "YearPaint" VARCHAR2(30 BYTE),
  "StructPaint" NUMBER(5),
  "Gutters" VARCHAR2(30 BYTE),
  "Downspouts" VARCHAR2(30 BYTE),
  "FinishWall" VARCHAR2(30 BYTE),
  "FinishRoof" VARCHAR2(30 BYTE),
  "FinishEave" VARCHAR2(30 BYTE),
  "FinishGable" VARCHAR2(30 BYTE),
  "FinishCorner" VARCHAR2(30 BYTE),
  "FinishAllOther" VARCHAR2(30 BYTE),
  "FinishBase" VARCHAR2(30 BYTE),
  "FinishGutter" VARCHAR2(30 BYTE),
  "FinishDownspouts" VARCHAR2(30 BYTE),
  "AllTrimSameColor" NUMBER(5),
  "RoofToRoof" VARCHAR2(30 BYTE),
  "RoofToWall" VARCHAR2(30 BYTE),
  "RoofInteriorSkin" VARCHAR2(30 BYTE),
  "WallInteriorSkin" VARCHAR2(30 BYTE),
  "RoofPanelValsparCode" VARCHAR2(30 BYTE),
  "RoofPanelSpecialName" VARCHAR2(30 BYTE),
  "WallPanelValsparCode" VARCHAR2(30 BYTE),
  "WallPanelSpecialName" VARCHAR2(30 BYTE),
  "EaveFlashValsparCode" VARCHAR2(30 BYTE),
  "EaveFlashSpecialName" VARCHAR2(30 BYTE),
  "GableFlashValsparCode" VARCHAR2(30 BYTE),
  "GableFlashSpecialName" VARCHAR2(30 BYTE),
  "CornerFlashValsparCode" VARCHAR2(30 BYTE),
  "CornerFlashSpecialName" VARCHAR2(30 BYTE),
  "BaseFlashValsparCode" VARCHAR2(30 BYTE),
  "BaseFlashSpecialName" VARCHAR2(30 BYTE),
  "AllOtherFlashValsparCode" VARCHAR2(30 BYTE),
  "AllOtherFlashSpecialName" VARCHAR2(30 BYTE),
  "GuttersValsparCode" VARCHAR2(30 BYTE),
  "GuttersSpecialName" VARCHAR2(30 BYTE),
  "DownspoutsValsparCode" VARCHAR2(30 BYTE),
  "DownspoutsSpecialName" VARCHAR2(30 BYTE),
  "RoofToRoofValsparCode" VARCHAR2(30 BYTE),
  "RoofToRoofSpecialName" VARCHAR2(30 BYTE),
  "RoofToWallValsparCode" VARCHAR2(30 BYTE),
  "RoofToWallSpecialName" VARCHAR2(30 BYTE),
  "RoofInteriorSkinValsparCode" VARCHAR2(30 BYTE),
  "RoofInteriorSkinSpecialName" VARCHAR2(30 BYTE),
  "WallInteriorSkinValsparCode" VARCHAR2(30 BYTE),
  "WallInteriorSkinSpecialName" VARCHAR2(30 BYTE),
  "WalkDoors" VARCHAR2(30 BYTE),
  "WalkDoorsValsparCode" VARCHAR2(30 BYTE),
  "WalkDoorsSpecialName" VARCHAR2(30 BYTE),
  "CreatedBy" NUMBER(5),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(5),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDelete" CHAR,
  "WallPanelText" VARCHAR2(50 BYTE),
  "WallPanelHashCode" VARCHAR2(50 BYTE),
  "WallInteriorText" VARCHAR2(50 BYTE),
  "WallInteriorHashCode" VARCHAR2(50 BYTE),
  "EaveFlashColor" VARCHAR2(50 BYTE),
  "EaveFlashHashCode" VARCHAR2(50 BYTE),
  "GableFlashColor" VARCHAR2(50 BYTE),
  "GableFlashHashCode" VARCHAR2(50 BYTE),
  "CornerFlashColor" VARCHAR2(50 BYTE),
  "CornerFlashHashCode" VARCHAR2(50 BYTE),
  "BaseFlashColor" VARCHAR2(50 BYTE),
  "BaseFlashHashCode" VARCHAR2(50 BYTE),
  "GuttersColor" VARCHAR2(50 BYTE),
  "GuttersHashCode" VARCHAR2(50 BYTE),
  "DownspoutsColor" VARCHAR2(50 BYTE),
  "DownspoutsHashCode" VARCHAR2(50 BYTE),
  "AllOtherFlashColor" VARCHAR2(50 BYTE),
  "AllOtherFlashHashCode" VARCHAR2(50 BYTE),
  "RoofToRoofColor" VARCHAR2(50 BYTE),
  "RoofToRoofHashCode" VARCHAR2(50 BYTE),
  "RoofToWallColor" VARCHAR2(50 BYTE),
  "RoofToWallHashCode" VARCHAR2(50 BYTE),
  "WalkDoorsColor" VARCHAR2(50 BYTE),
  "WalkDoorsHashCode" VARCHAR2(50 BYTE),
  CONSTRAINT "Trim_ColorSelections_PK" PRIMARY KEY ("TrimColorSelectionId")
);