CREATE TABLE abs_mdi."Input_AddLines" (
  "AddLinesId" NUMBER(10) NOT NULL,
  "BuildingInformationId" NUMBER(10),
  "Description" VARCHAR2(255 BYTE),
  "UnitWeight" NUMBER(10,2),
  "UnitPrice" NUMBER(10,2),
  "ListOrNet" VARCHAR2(20 BYTE),
  "ExpiresOn" VARCHAR2(10 BYTE),
  "QuoteNumber" VARCHAR2(20 BYTE),
  "QuoteYear" VARCHAR2(20 BYTE),
  "EstInitials" VARCHAR2(20 BYTE),
  "Guid" RAW(16),
  "Quantity" NUMBER(10,1),
  "Internal" NUMBER(10,1),
  "IncludeFreight" VARCHAR2(10 BYTE),
  "DontShowPriceWeight" CHAR,
  "IsSpecialized" CHAR,
  "ScreenType" VARCHAR2(20 BYTE),
  "TaxApplied" NUMBER(10),
  "AdjustmentFactor" NUMBER(10,2),
  "Expired" NUMBER(10,2),
  "Category" VARCHAR2(50 BYTE),
  "BuiltupWeight" NUMBER(10,2),
  "BuiltupPrice" NUMBER(10,2),
  "HotrolledWeight" NUMBER(10,2),
  "HotrolledPrice" NUMBER(10,2),
  "ColdformWeight" NUMBER(10,2),
  "ColdformPrice" NUMBER(10,2),
  "FabColdformWeight" NUMBER(10,2),
  "FabColdformPrice" NUMBER(10,2),
  "RoofpanelWeight" NUMBER(10,2),
  "RoofpanelPrice" NUMBER(10,2),
  "WallpanelWeight" NUMBER(10,2),
  "WallpanelPrice" NUMBER(10,2),
  "TrimWeight" NUMBER(10,2),
  "TrimPrice" NUMBER(10,2),
  "BuyoutsWeight" NUMBER(10,2),
  "BuyoutsPrice" NUMBER(10,2),
  "WarehouseWeight" NUMBER(10,2),
  "WarehousePrice" NUMBER(10,2),
  "OtherWeight" NUMBER(10,2),
  "OtherPrice" NUMBER(10,2),
  "AdditionalEngineering" NUMBER(10,2),
  "DrawingsCalcs" NUMBER(10,2),
  "WTWarranty" NUMBER(10,2),
  insulation NUMBER(10,2),
  "Freight" NUMBER(10,2),
  "FabricatedICF" NUMBER(10,2),
  "BuyoutMarkup" NUMBER(10,2),
  "DetailsByPercentage" NUMBER(10),
  "MezzanineNumber" NUMBER(10),
  "RmgPrice" NUMBER(10,2),
  "ProjectId" NUMBER(10),
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDelete" CHAR,
  "CreatedBy" NUMBER(10),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  CONSTRAINT "Input_AddLines_PK" PRIMARY KEY ("AddLinesId"),
  CONSTRAINT "UK_AddLines_Guid" UNIQUE ("Guid"),
  CONSTRAINT fkaddlines_buildinginformationid FOREIGN KEY ("BuildingInformationId") REFERENCES abs_mdi."BuildingInformation" ("BuildingInformationId")
);