CREATE TABLE abs_mdi."Input_Roof" (
  "RoofId" NUMBER(10) NOT NULL,
  "Type" VARCHAR2(50 BYTE),
  "Gauge" NUMBER(5),
  "ULRating" CHAR,
  "Width" VARCHAR2(10 BYTE),
  "Profile" VARCHAR2(50 BYTE),
  "Thick" VARCHAR2(10 BYTE),
  "Clip" VARCHAR2(100 BYTE),
  "NotByStar" VARCHAR2(50 BYTE),
  "StructScrews" VARCHAR2(50 BYTE),
  "StitchScrews" VARCHAR2(50 BYTE),
  "Material" VARCHAR2(50 BYTE),
  "ThermalBlock" NUMBER(10),
  "MetalRibClosure" NUMBER(10),
  "SealedRoof" NUMBER(10),
  "RidgePan" NUMBER(10),
  "AlignmentStrip" NUMBER(10),
  "ULLetter" NUMBER(10),
  "EavePanelExtension" NUMBER(10),
  "IsBuyout" CHAR,
  "SquareFeet" NUMBER(10,5),
  "ThermalBlockThickness" VARCHAR2(100 BYTE),
  "ProvideBlocks" NUMBER(10),
  "RoofFirst" NUMBER(10),
  "InsulationClips" NUMBER(10),
  "Weathertightness" NUMBER(10),
  "SealedEave" NUMBER(10),
  "ThickInsulation" NUMBER(10),
  "RTSSystem" NUMBER(10),
  "RTSFinish" VARCHAR2(50 BYTE),
  "RTSPanelType" VARCHAR2(50 BYTE),
  "RTSThickness" NUMBER(10),
  "RTSSpacing" NUMBER(10),
  "ThermalBlockType" VARCHAR2(50 BYTE),
  "FastenerType" VARCHAR2(100 BYTE),
  "FastenerHeadFinish" VARCHAR2(50 BYTE),
  "FastenerLength" VARCHAR2(50 BYTE),
  "WideTape" NUMBER(10),
  "EaveIcing" NUMBER(10),
  "Warranty" VARCHAR2(50 BYTE),
  "FactoryAppliedSealant" NUMBER(10),
  "WeathertightnessTerm" VARCHAR2(50 BYTE),
  "IMPAccLoads" NUMBER(10),
  "SeamerRental" NUMBER(10),
  "StainlessSteelCaps" NUMBER(10),
  "NonhandedErection" NUMBER(10),
  "Direction" NUMBER(10),
  "ProvideHandTools" NUMBER(10),
  "RTSPanelGauge" NUMBER(10),
  "FastenerVender" VARCHAR2(50 BYTE),
  "ExteriorSkinTexture" VARCHAR2(100 BYTE),
  "FMRating" NUMBER(10),
  "RoofNavNumber" VARCHAR2(100 BYTE),
  "WindRating" VARCHAR2(50 BYTE),
  hass5clamps NUMBER(10),
  "IMPPlant" NUMBER(10),
  "IMPLoads" NUMBER(10),
  "IncludeToolKit" NUMBER(10),
  "ColdStorageBuilding" NUMBER(10),
  "InteriorSkinProfile" VARCHAR2(50 BYTE),
  "InteriorSkinGauge" NUMBER(10),
  "InteriorSkinTexture" VARCHAR2(100 BYTE),
  "HasSnowRetentionSystem" NUMBER(10),
  "SnowRetentionRp1" NUMBER(10),
  "SnowRetentionRp2" NUMBER(10),
  "SnowRetentionRp3" NUMBER(10),
  "SnowRetentionRp4" NUMBER(10),
  "IncludeSnowClipPerPanel" NUMBER(10),
  "SnowClipQuantity" NUMBER(10),
  "ColorStripQuantity" NUMBER(10),
  "Rp1SnowLoad" NUMBER(20,8),
  "Rp2SnowLoad" NUMBER(20,8),
  "Rp3SnowLoad" NUMBER(20,8),
  "Rp4SnowLoad" NUMBER(20,8),
  "BuildingInformationId" NUMBER(10),
  "IpAddress" VARCHAR2(100 BYTE),
  "CreatedBy" NUMBER(10),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  "BURLoad" NUMBER(20,8),
  "FinishWarranty" CHAR,
  "RValue" VARCHAR2(100 BYTE),
  CONSTRAINT "Input_Roof_PK" PRIMARY KEY ("RoofId")
);