CREATE TABLE abs_mdi."Input_ShopCoat" (
  "ShopCoatId" NUMBER(10) NOT NULL,
  "BuildingInformationId" NUMBER(10),
  "GalvanizedSecondary" CHAR,
  "SealWelds" CHAR,
  "HotDippedPrimary" CHAR,
  "HotDippedPrice" NUMBER(10,2),
  "HotDippedWeight" NUMBER(10,2),
  "SealWeldsPrice" NUMBER(10,2),
  "SealWeldsWeight" NUMBER(10,2),
  "QuoteNumber" VARCHAR2(20 BYTE),
  "QuoteYear" VARCHAR2(20 BYTE),
  "EstimatorInitials" VARCHAR2(20 BYTE),
  "ExpiresOn" VARCHAR2(10 BYTE),
  "BoltFinish" VARCHAR2(20 BYTE),
  "CreatedBy" NUMBER(10),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  "IsDelete" CHAR,
  "IpAddress" VARCHAR2(20 BYTE),
  "ShopCoatDrpId" NUMBER(10),
  CONSTRAINT "Input_ShopCoat_PK" PRIMARY KEY ("ShopCoatId"),
  CONSTRAINT fk_buildinginformationid FOREIGN KEY ("BuildingInformationId") REFERENCES abs_mdi."BuildingInformation" ("BuildingInformationId")
);