CREATE TABLE abs_mdi."Insulation" (
  "InsulationId" NUMBER(5) NOT NULL,
  "BuildingNumber" NUMBER(4),
  "ElevationOnSW1" NUMBER(4),
  "ElevationOnSW2" NUMBER(4),
  "ElevationOnEW3" NUMBER(4),
  "ElevationOnEW4" NUMBER(4),
  "ElevationOnRoof" NUMBER(4),
  "Facing" VARCHAR2(50 BYTE),
  "Tabs" VARCHAR2(50 BYTE),
  "RoofThick" NUMBER(8,4),
  "WallThick" NUMBER(8,4),
  "RoofSqft" NUMBER(20,4),
  "WallSqft" NUMBER(8,4),
  "StarterRoll" NUMBER(8,4),
  "RunningRoll" NUMBER(8,4),
  "FinishRoll" NUMBER(8,4),
  "Weight" NUMBER(8,4),
  "Price" NUMBER(8,4),
  "IsPriced" NUMBER(4),
  "ErrorCode" NUMBER(4),
  "ThickRoofInsulation" NUMBER(4),
  "InsulationType" VARCHAR2(50 BYTE),
  "IncludeTape" NUMBER(4),
  "IncludeStaples" NUMBER(4),
  "ElevationOnPartition" NUMBER(4),
  "PartitionNumber" NUMBER(4),
  "ElevationOnEaveStrut" NUMBER(4),
  "SealedTapeTab" NUMBER(4),
  "FromWall" NUMBER(4),
  "DesignedRValue" NUMBER(8,4),
  "ByManufacturer" NUMBER(4),
  "OverPurlinGirt" NUMBER(4),
  "CavityPurlinBracable" NUMBER(4),
  "DesignedFacing" VARCHAR2(50 BYTE),
  "Markup" NUMBER(8,4),
  "CreatedBy" NUMBER(4),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(4),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDelete" CHAR,
  CONSTRAINT "Insulation_PK" PRIMARY KEY ("InsulationId")
);