CREATE TABLE abs_mdi."M_EDSPrice_IMPShortOrderCharges" (
  "PanelWidth" BINARY_DOUBLE NOT NULL,
  "Gauge" NUMBER NOT NULL,
  "ColorType" NVARCHAR2(50) NOT NULL,
  "Upto250" BINARY_DOUBLE,
  "Upto500" BINARY_DOUBLE,
  "Upto1000" BINARY_DOUBLE,
  "Upto1500" BINARY_DOUBLE,
  "Upto2500" BINARY_DOUBLE,
  "Upto3500" BINARY_DOUBLE,
  "Upto4500" BINARY_DOUBLE,
  "Upto5500" BINARY_DOUBLE,
  "Upto6000" BINARY_DOUBLE,
  PRIMARY KEY ("PanelWidth","Gauge","ColorType")
);