CREATE TABLE abs_mdi."M_EDSPrice_IMP_FreightRates" (
  "MaxMiles" BINARY_DOUBLE,
  "HamON" BINARY_DOUBLE,
  "RichVA" BINARY_DOUBLE,
  "JackMS" BINARY_DOUBLE,
  "LasVNV" BINARY_DOUBLE,
  "IndiIN" BINARY_DOUBLE,
  "LewTX" BINARY_DOUBLE,
  "LaredoTX" BINARY_DOUBLE
);