CREATE TABLE abs_mdi."M_EDSPrice_Program_DBCIDoors" (
  "Series" NVARCHAR2(50) NOT NULL,
  "Size" NVARCHAR2(50) NOT NULL,
  "MaxWindBNormal" BINARY_DOUBLE DEFAULT 0,
  "MaxWindCNormal" BINARY_DOUBLE DEFAULT 0,
  "MaxWindBHigh" BINARY_DOUBLE DEFAULT 0,
  "MaxWindCHigh" BINARY_DOUBLE DEFAULT 0,
  "Weight" BINARY_DOUBLE DEFAULT 0,
  "Price" BINARY_DOUBLE DEFAULT 0,
  PRIMARY KEY ("Series","Size")
);