CREATE TABLE abs_mdi."M_EDSPrice_Program_FlatlinerMarkup" (
  "Range1" BINARY_DOUBLE DEFAULT 0 NOT NULL,
  "Range2" BINARY_DOUBLE DEFAULT 0,
  "Range3" BINARY_DOUBLE DEFAULT 0,
  "MarkUp1" BINARY_DOUBLE DEFAULT 0,
  "MarkUp2" BINARY_DOUBLE DEFAULT 0,
  "MarkUp3" BINARY_DOUBLE DEFAULT 0,
  "MarkUp4" BINARY_DOUBLE DEFAULT 0,
  PRIMARY KEY ("Range1")
);