CREATE TABLE abs_mdi."M_EDSPrice_RMG_Adjustments" (
  "MonthYear" NVARCHAR2(50) NOT NULL,
  "Index" NVARCHAR2(50),
  "Builtup" BINARY_DOUBLE DEFAULT 0,
  "FabColdform" BINARY_DOUBLE DEFAULT 0,
  "Coldform" BINARY_DOUBLE DEFAULT 0,
  "HotRolled" BINARY_DOUBLE DEFAULT 0,
  "SSPanel" BINARY_DOUBLE DEFAULT 0,
  "Panel" BINARY_DOUBLE DEFAULT 0,
  "Trim" BINARY_DOUBLE DEFAULT 0,
  "Warehouse" BINARY_DOUBLE DEFAULT 0,
  "Buyouts" BINARY_DOUBLE DEFAULT 0,
  PRIMARY KEY ("MonthYear")
);