CREATE TABLE abs_mdi."M_PanelType" (
  "Id" NUMBER(5) NOT NULL,
  "Type" VARCHAR2(20 BYTE),
  "IsWall" CHAR,
  "IsDisableTrimStyleGutterTypeSize" NUMBER(2),
  "IsForDiaFormedTrim" NUMBER(2),
  "PanelImage" VARCHAR2(100 BYTE),
  "ExteriorColor" VARCHAR2(50 BYTE),
  "ExteriorColorText" VARCHAR2(50 BYTE),
  "ExteriorColorCode" VARCHAR2(50 BYTE),
  "ExteriorHashColorCode" VARCHAR2(50 BYTE),
  "InteriorColor" VARCHAR2(50 BYTE),
  "InteriorColorText" VARCHAR2(50 BYTE),
  "InteriorColorCode" VARCHAR2(50 BYTE),
  "InteriorHashColorCode" VARCHAR2(50 BYTE),
  "NotchAlt" VARCHAR2(25 BYTE),
  "IsDisable_Warranty" CHAR,
  "IsHide_ColdStorageBuilding" CHAR,
  "IsDisable_ReverseRolled" CHAR,
  "IsDisable_SealedWall" CHAR,
  "IsDisable_EaveClosureStrip" CHAR,
  "IsCheck_EaveClosureStrip" CHAR,
  "IsHide_RakeClosure" CHAR,
  "IsDisable_RakeClosure" CHAR,
  "IsCheck_RakeClosure" CHAR,
  "IsHide_FoamTape" CHAR,
  "IsCheck_SealedWall" CHAR,
  "IsDisable_Notch" CHAR,
  "IsCheck_Notch" CHAR,
  "IsDisable_Std" CHAR,
  "IsCheck_Std" CHAR,
  "IsHide_Alt" CHAR,
  "IsDisable_Alt" CHAR,
  "IsDisable_OutsideMetalClosure" CHAR,
  "IsHide_SidelapSealant" CHAR,
  "IsCheck_SidelapSealant" CHAR,
  "IsHideRUValue" CHAR,
  "BackPanel" CHAR,
  "FacadePanel" CHAR,
  "SoffitPanel" CHAR,
  PRIMARY KEY ("Id")
);