CREATE TABLE abs_mdi."M_Panel_Dropdown" (
  "Id" NUMBER(10) NOT NULL,
  "Value" VARCHAR2(70 BYTE),
  "PanelTypeId" NUMBER(10),
  "IsExterior" CHAR,
  "IsInterior" CHAR,
  "Gauge" CHAR,
  "Profile" CHAR,
  "Texture" CHAR,
  "Width" CHAR,
  "Thickness" CHAR,
  "FastenerType" CHAR,
  "FastenerHead" CHAR,
  "FastenerLength" CHAR,
  "Framing" CHAR,
  "Trim" CHAR,
  "Closure" CHAR,
  "FactoryApplied" CHAR,
  "RValue" NUMBER(10,2),
  "UValue" NUMBER(10,4),
  "TrimImage" VARCHAR2(100 BYTE),
  "NotchAlt" VARCHAR2(25 BYTE),
  "MappingId" NUMBER(10),
  "IsDefaultSelected" CHAR,
  "GroupId" NUMBER(10),
  "LinerGuage" CHAR,
  PRIMARY KEY ("Id"),
  FOREIGN KEY ("PanelTypeId") REFERENCES abs_mdi."M_PanelType" ("Id")
);