CREATE TABLE abs_mdi."MenuAdmin" (
  adminid NUMBER(10) NOT NULL,
  "AllowChildren" CHAR,
  "Content" NCLOB,
  "ImageVideoId" NUMBER(10),
  "IsActive" CHAR,
  "IsEditable" CHAR,
  "IsInherited" CHAR,
  "IsMovable" CHAR,
  "IsPartiallyLoaded" CHAR,
  "Name" VARCHAR2(50 BYTE),
  "Type" NUMBER(10),
  "Url" VARCHAR2(500 BYTE),
  "IsGroup" CHAR,
  "IsHttp" CHAR,
  "IsRouterPath" CHAR,
  "IsDelete" CHAR DEFAULT 'N',
  "ParentId" NUMBER(10),
  "CompanyId" NUMBER(10),
  "IsMobile" CHAR,
  "IsGear" CHAR,
  "IsDefault" CHAR,
  "HasEmbededVideo" CHAR,
  "CreatedBy" NUMBER,
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER,
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "SortOrder" NUMBER(10),
  "MenuAdminId" NUMBER,
  CONSTRAINT "MenuAdmin_PK" PRIMARY KEY (adminid)
);