CREATE TABLE abs_mdi."OE_Categories" (
  "BuildingNumber" NUMBER(10),
  "Source" VARCHAR2(50 BYTE),
  "BuiltupWeight" NUMBER(10,2),
  "BuiltupPrice" NUMBER(10,2),
  "BuiltupLabor" NUMBER(10,2),
  "HotrolledWeight" NUMBER(10,2),
  "HotrolledPrice" NUMBER(10,2),
  "HotrolledLabor" NUMBER(10,2),
  "ColdformWeight" NUMBER(10,2),
  "ColdformPrice" NUMBER(10,2),
  "ColdformLabor" NUMBER(10,2),
  "FabColdformWeight" NUMBER(10,2),
  "FabColdformPrice" NUMBER(10,2),
  "FabColdformLabor" NUMBER(10,2),
  "RoofpanelWeight" NUMBER(10,2),
  "RoofpanelPrice" NUMBER(10,2),
  "RoofpanelLabor" NUMBER(10,2),
  "WallpanelWeight" NUMBER(10,2),
  "WallpanelPrice" NUMBER(10,2),
  "WallpanelLabor" NUMBER(10,2),
  "TrimWeight" NUMBER(10,2),
  "TrimPrice" NUMBER(10,2),
  "TrimLabor" NUMBER(10,2),
  "BuyoutsWeight" NUMBER(10,2),
  "BuyoutsPrice" NUMBER(10,2),
  "BuyoutsLabor" NUMBER(10,2),
  "WarehouseWeight" NUMBER(10,2),
  "WarehousePrice" NUMBER(10,2),
  "WarehouseLabor" NUMBER(10,2),
  "RodsWeight" NUMBER(10,2),
  "RodsPrice" NUMBER(10,2),
  "RodsLabor" NUMBER(10,2),
  "HRAnglesWeight" NUMBER(10,2),
  "HRAnglesPrice" NUMBER(10,2),
  "HRAnglesLabor" NUMBER(10,2),
  "CFAnglesWeight" NUMBER(10,2),
  "CFAnglesPrice" NUMBER(10,2),
  "CFAnglesLabor" NUMBER(10,2),
  "GalvColdformWeight" NUMBER(10,2),
  "GalvColdformPrice" NUMBER(10,2),
  "GalvColdformLabor" NUMBER(10,2),
  "ProjectId" NUMBER(10),
  "CreatedBy" NUMBER(10),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDeleted" VARCHAR2(1 BYTE),
  "OE_CategoriesId" NUMBER(10) NOT NULL
);