CREATE TABLE abs_mdi."OpenAreas" (
  "Id" NUMBER DEFAULT (null),
  "BuildingNumber" NUMBER(10),
  "Elevation" VARCHAR2(20 BYTE),
  "BayNumber" NUMBER(10),
  "DistFromLeftCorner" NUMBER(20,8),
  "DistFromLeftColumn" NUMBER(20,8),
  "OpeningType" VARCHAR2(20 BYTE),
  "OpenEndwall" NUMBER(5),
  "OpeningWidth" NUMBER(20,8),
  "OpeningHeight" NUMBER(20,8),
  "MaterialType" VARCHAR2(20 BYTE),
  "MaterialWeight" NUMBER(20,8),
  "MaterialThickness" NUMBER(20,8),
  "DistSteelLinetoBeam" NUMBER(20,8),
  "DistSteelLinetoMaterial" NUMBER(20,8),
  "MasonryType" VARCHAR2(20 BYTE),
  "MaterialDirection" VARCHAR2(20 BYTE),
  "ShearWall" NUMBER(5),
  "PercentOpenforWind" NUMBER(20,8),
  "LeftJamb" NUMBER(5),
  "LeftJambFlash" NUMBER(5),
  "LeftJambFlangeWidth" NUMBER(20,8),
  "LeftJambFlangeThick" NUMBER(20,8),
  "LeftJambWebDepth" NUMBER(20,8),
  "LeftJambWebThick" NUMBER(20,8),
  "RightJamb" NUMBER(5),
  "RightJambFlash" NUMBER(5),
  "RightJambFlangeWidth" NUMBER(20,8),
  "RightJambFlangeThick" NUMBER(20,8),
  "RightJambWebDepth" NUMBER(20,8),
  "RightJambWebThick" NUMBER(20,8),
  "HeaderFlash" NUMBER(5),
  "HeaderFlashType" VARCHAR2(50 BYTE),
  "HeaderFlashColor" VARCHAR2(20 BYTE),
  "AttachmentNumber" NUMBER(5),
  "AllowableDrift" NUMBER(20,8),
  "BeamSelected" NUMBER(5),
  "BeamStartCol" NUMBER(5),
  "BeamStopCol" NUMBER(5),
  "BeamHeight" NUMBER(20,8),
  "BeamFlanges" NUMBER(5),
  "BeamWebThick" VARCHAR2(20 BYTE),
  "BeamWebDepth" NUMBER(20,8),
  "BeamFlangeThick" NUMBER(20,8),
  "BeamFlangeWidth" NUMBER(20,8),
  "BeamDeflection" NUMBER(20,8),
  "BeamAttachmentSpacing" NUMBER(20,8),
  "BeamSteelline" NUMBER(5),
  "BeamSection" VARCHAR2(20 BYTE),
  "BeamWeight" NUMBER(5),
  "BeamPrice" NUMBER(5),
  "BeamIsPriced" NUMBER(5),
  "BeamErrorCode" NUMBER(5),
  "LedgerAngle" NUMBER(5),
  "AllElevations" NUMBER(5),
  "ColumnBracing" VARCHAR2(20 BYTE),
  "NoOutsideColumns" NUMBER(5),
  "PanelsSpan" NUMBER(5),
  "NoFlangeBelow" NUMBER(20,8),
  "AllowableInsulation" NUMBER(20,8),
  "PartitionNumber" NUMBER(5),
  "DeductPanelsTrimOnly" NUMBER(5),
  "FullWidth" NUMBER(5),
  "ParapetByOther" NUMBER(5),
  "HeaderFlashColorValsparCode" VARCHAR2(20 BYTE),
  "HeaderFlashColorSpecialName" VARCHAR2(20 BYTE),
  "CreatedBy" NUMBER(5),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(5),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDeleted" CHAR
);