CREATE TABLE abs_mdi."PointLoads" (
  "PointLoadId" NUMBER(10) NOT NULL,
  "ProjectId" NUMBER(10),
  "BuildingNumber" NUMBER(10),
  "BayNumber" NUMBER(10),
  "DistFromWall" NUMBER(20,10),
  "DistFromFrame" NUMBER(20,10),
  "Type" VARCHAR2(50 BYTE),
  "Load" NUMBER(20,10),
  "Description" VARCHAR2(50 BYTE),
  "UnitLocation" VARCHAR2(50 BYTE),
  "InsideLength" NUMBER(20,10),
  "InsideWidth" NUMBER(20,10),
  "UnitDimension" NUMBER(20,10),
  "CutPurlins" NUMBER(10),
  "UnitLength" NUMBER(10),
  "UnitWidth" NUMBER(20,10),
  "UnitHeight" NUMBER(20,10),
  "NumBeams" NUMBER(10),
  "BeamByManufacturer" NUMBER(10),
  "Number" NUMBER(10),
  "IsCopy" VARCHAR2(1 BYTE),
  "OverlapOverride" VARCHAR2(1 BYTE),
  "CreatedBy" NUMBER(10),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDeleted" VARCHAR2(20 BYTE),
  CONSTRAINT "PointLoads_PK" PRIMARY KEY ("PointLoadId")
);