CREATE TABLE abs_mdi."Project" (
  "ProjectId" NUMBER(5) NOT NULL,
  "ProjectName" VARCHAR2(200 BYTE),
  "IsActive" CHAR,
  "IsDelete" CHAR,
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" VARCHAR2(50 BYTE),
  "ModifiedDate" TIMESTAMP,
  "BuildingsCount" NUMBER(5),
  "BuildingLocation" NVARCHAR2(200),
  "ProjectStatusId" NUMBER(5),
  "ExpiryDate" DATE,
  "Price" NUMBER(12,2),
  "UserId" VARCHAR2(50 BYTE),
  "CreatedBy" VARCHAR2(50 BYTE),
  "IpAddress" VARCHAR2(20 BYTE),
  "ProjectUseId" NUMBER(5),
  "RiskCategoryId" NUMBER(5),
  "CityLimit" VARCHAR2(20 BYTE),
  "MaterialOriginId" NUMBER(5),
  "Address1" VARCHAR2(500 BYTE),
  "Address2" VARCHAR2(500 BYTE),
  "City" VARCHAR2(200 BYTE),
  "Region" VARCHAR2(200 BYTE),
  "State" VARCHAR2(200 BYTE),
  "Country" VARCHAR2(500 BYTE),
  "ZipPostalCode" VARCHAR2(10 BYTE),
  "QuoteRequestDate" DATE,
  "PriceStatus" VARCHAR2(20 BYTE),
  "Latitude" VARCHAR2(50 BYTE),
  "Longitude" VARCHAR2(50 BYTE),
  "DesignCodeId" NUMBER(10),
  "DesignCodeName" NVARCHAR2(80),
  "ProjectUseCategoryid" NUMBER(10),
  "WindSpeed" FLOAT,
  "WindExposureId" NUMBER(10),
  "IsHurricaneCoastline" CHAR,
  "LiveLoad" FLOAT,
  "IsLiveLoadReductionAllowed" CHAR,
  "GroundSnow" FLOAT,
  "SnowExposureId" NUMBER(10),
  "MinimumSnowLoad" FLOAT,
  "Elevation" FLOAT,
  "RainIntensity" FLOAT,
  "SustainablilityGoalId" NUMBER(10),
  "IsClimateControlled" CHAR,
  "EnergyEfficiencyId" NUMBER(10),
  "IsAirInfiltrationRequired" CHAR,
  "CustomerNo" VARCHAR2(50 BYTE),
  "SeismicSa" FLOAT,
  "SeismicS1" FLOAT,
  "SeismicSnowLoad" VARCHAR2(20 BYTE),
  "SeismicSnowPercentage" NUMBER(6,3),
  "SiteClassId" NUMBER(10),
  "InputDimensional" VARCHAR2(20 BYTE),
  "InputEngineering" VARCHAR2(20 BYTE),
  "OutputDimensional" VARCHAR2(20 BYTE),
  "OutputEngineering" VARCHAR2(20 BYTE),
  "CurrencyDimensional" VARCHAR2(20 BYTE),
  "IsCanadaBasedDesignCode" CHAR,
  "IsDesignCodeIbc2012Based" CHAR,
  "RainLoad" FLOAT,
  "SeismicSa1Dot0" FLOAT,
  "SeismicSa2Dot0" FLOAT,
  "WindLoad" FLOAT,
  "IsUserDefinedSustainability" CHAR,
  "UserDefinedSustainability" NUMBER(6,3),
  "CompanyId" NUMBER(10),
  "CBBInquiryNumber" VARCHAR2(50 BYTE),
  "MinAnchorRodDiameter" VARCHAR2(5 BYTE),
  "TDIRequired" CHAR,
  "UsingSystemGeneratedRodPlan" CHAR,
  "EnteredBy" VARCHAR2(50 BYTE),
  "ProjectBuildingType" NUMBER(2) DEFAULT 0,
  "UserRoleId" NUMBER(4),
  "ProjectStage" VARCHAR2(50 BYTE),
  "IsArchive" CHAR DEFAULT ('N'),
  "UserType" VARCHAR2(20 BYTE),
  "IsProjectPriced" CHAR,
  "PriceDate" TIMESTAMP,
  "ProjectPriceDataPath" VARCHAR2(500 BYTE),
  "ExportedToOEDate" DATE,
  "ExportToEDSDate" DATE,
  "ReportPath" VARCHAR2(500 BYTE),
  "CADDrawingPath" VARCHAR2(500 BYTE),
  "JobNumber" VARCHAR2(100 BYTE),
  "Ignore_ufc" CHAR,
  "Warn_hot_dipped" CHAR,
  "RequestShipDate" DATE,
  "ConstructionDate" DATE,
  "AnchorRodDate" DATE,
  "SubmittedDate" DATE,
  "PGASeismic" FLOAT,
  "IsOverrideSeismicSa" CHAR DEFAULT 'N',
  "IsOverrideSeismicS1" CHAR DEFAULT 'N',
  "IsOverrideSeismicSa1Dot0" CHAR DEFAULT 'N',
  "IsOverrideSeismicSa2Dot0" CHAR DEFAULT 'N',
  "IsOverrideWindSpeed" CHAR DEFAULT 'N',
  "IsOverrideWindLoad" CHAR DEFAULT 'N',
  "IsOverrideLiveLoad" CHAR DEFAULT 'N',
  "IsOverrideGroundSnow" CHAR DEFAULT 'N',
  "IsOverrideRainIntensity" CHAR DEFAULT 'N',
  "IsOverrideRainLoad" CHAR DEFAULT 'N',
  "IsOverridePGASeismic" CHAR DEFAULT 'N',
  "WindLoadType" VARCHAR2(5 BYTE),
  "Complexity" NUMBER(10),
  "EstComplexity" NUMBER(10),
  "MBMAComplexity" NUMBER(10),
  "DesignPoints" NUMBER(10,2),
  "DraftingPoints" NUMBER(10,2),
  "UsingAnchorBolt" NUMBER(10),
  "ExportToEDSStatus" VARCHAR2(20 BYTE),
  "ExportToOEStatus" VARCHAR2(20 BYTE),
  "SeismicUseCategory" VARCHAR2(50 BYTE),
  "FinalAnchorRodDate" DATE,
  "ApprovalDate" DATE,
  "PermitDate" DATE,
  "FinalDate" DATE,
  "IsCorpEngineers" CHAR,
  "IsUFCAntiTerrorism" CHAR,
  "UFCAntiTerrorismListWeight" NUMBER(10,5),
  "UFCAntiTerrorismListPrice" NUMBER(10,5),
  "Mailed" VARCHAR2(50 BYTE),
  "Carrier" VARCHAR2(50 BYTE),
  "Account" VARCHAR2(50 BYTE),
  "ExpiresOn" DATE,
  "PricedBy" VARCHAR2(255 BYTE)
);