CREATE TABLE abs_mdi."Purchaser" (
  "PurchaserId" NUMBER(10) NOT NULL,
  "PurchaserName" VARCHAR2(50 BYTE),
  "Contact" VARCHAR2(50 BYTE),
  "Country" VARCHAR2(50 BYTE),
  "State" VARCHAR2(50 BYTE),
  "City" VARCHAR2(50 BYTE),
  "County" VARCHAR2(50 BYTE),
  "Address1" VARCHAR2(50 BYTE),
  "Address2" VARCHAR2(50 BYTE),
  "ZipCode" VARCHAR2(50 BYTE),
  "EmailAddress" VARCHAR2(50 BYTE),
  "PhoneNumber" VARCHAR2(50 BYTE),
  "OvernightCountry" VARCHAR2(50 BYTE),
  "OvernightState" VARCHAR2(50 BYTE),
  "OvernightCity" VARCHAR2(50 BYTE),
  "OvernightCounty" VARCHAR2(50 BYTE),
  "OvernightAddress1" VARCHAR2(50 BYTE),
  "OvernightAddress2" VARCHAR2(50 BYTE),
  "OvernightZipCode" VARCHAR2(50 BYTE),
  "FederalTaxIDNumber" VARCHAR2(50 BYTE),
  "CecoErection" VARCHAR2(50 BYTE),
  "SellerFurnish" NUMBER(10),
  "SellerErect" NUMBER(10),
  "FaxNumber" VARCHAR2(50 BYTE),
  "BuyerNumber" VARCHAR2(50 BYTE),
  "BuyerName" VARCHAR2(50 BYTE),
  "BuyerCareOf" VARCHAR2(50 BYTE),
  "BuyerCountry" VARCHAR2(50 BYTE),
  "BuyerIntSite" VARCHAR2(50 BYTE),
  "BuyerState" VARCHAR2(50 BYTE),
  "BuyerCounty" VARCHAR2(50 BYTE),
  "BuyerAddress" VARCHAR2(50 BYTE),
  "BuyerCity" VARCHAR2(50 BYTE),
  "BuyerZipCode" VARCHAR2(50 BYTE),
  "BuyerMailCountry" VARCHAR2(50 BYTE),
  "BuyerMailIntSite" VARCHAR2(50 BYTE),
  "BuyerMailState" VARCHAR2(50 BYTE),
  "BuyerMailCounty" VARCHAR2(50 BYTE),
  "BuyerMailAddress" VARCHAR2(50 BYTE),
  "BuyerMailCity" VARCHAR2(50 BYTE),
  "BuyerMailZipCode" VARCHAR2(50 BYTE),
  "BuyerContactName" VARCHAR2(50 BYTE),
  "BuyerEmail1" VARCHAR2(50 BYTE),
  "BuyerEmail2" VARCHAR2(50 BYTE),
  "BuyerDayPhone" VARCHAR2(50 BYTE),
  "BuyerFaxNumber" VARCHAR2(50 BYTE),
  "BuyerNightPhone" VARCHAR2(50 BYTE),
  "BuyerMobileNumber" VARCHAR2(50 BYTE),
  "CreatedBy" NUMBER(10),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  "IpAddress" VARCHAR2(20 BYTE),
  "IsDelete" CHAR,
  "ProjectId" NUMBER(10) NOT NULL,
  "ManagerName" VARCHAR2(50 BYTE),
  CONSTRAINT "Purchaser_PK" PRIMARY KEY ("PurchaserId")
);