CREATE TABLE abs_mdi."Skinning" (
  "SkinningID" NUMBER NOT NULL,
  "CompanyID" NUMBER,
  "ShowWelcomeText" CHAR,
  "ShowCompanyLogo" CHAR,
  "PrimaryColor" VARCHAR2(20 BYTE),
  "SecondaryColor" VARCHAR2(20 BYTE),
  "TertiaryColor" VARCHAR2(20 BYTE),
  "Accent1" VARCHAR2(20 BYTE),
  "Accent2" VARCHAR2(20 BYTE),
  "Accent3" VARCHAR2(20 BYTE),
  "Accent4" VARCHAR2(20 BYTE),
  "ActiveApproval" VARCHAR2(20 BYTE),
  "Cancelled" VARCHAR2(20 BYTE),
  "OnHold" VARCHAR2(20 BYTE),
  "Completed" VARCHAR2(20 BYTE),
  "UserId" NUMBER,
  "IpAddress" VARCHAR2(20 BYTE),
  "CreatedBy" NUMBER(10),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  "Accepted" VARCHAR2(20 BYTE),
  "Submitted" VARCHAR2(20 BYTE),
  "Unsubmitted" VARCHAR2(20 BYTE),
  "BrandColor" VARCHAR2(20 BYTE),
  "Color1" VARCHAR2(20 BYTE),
  "Color2" VARCHAR2(20 BYTE),
  "Color3" VARCHAR2(20 BYTE),
  "Color4" VARCHAR2(20 BYTE),
  "Color5" VARCHAR2(20 BYTE),
  "White" VARCHAR2(20 BYTE),
  "NotificationRed" VARCHAR2(20 BYTE),
  "DisabledState" VARCHAR2(20 BYTE),
  "NotesBackground" VARCHAR2(20 BYTE),
  "NotesIcon" VARCHAR2(20 BYTE),
  "LabelText" VARCHAR2(20 BYTE),
  PRIMARY KEY ("SkinningID")
);