CREATE TABLE abs_mdi."SupportBeams" (
  "SupportBeamsId" NUMBER NOT NULL,
  "BuildingNumber" NUMBER(10),
  "Elevation" VARCHAR2(50 BYTE),
  "BeamStartCol" NUMBER(5),
  "BeamStopCol" NUMBER(5),
  "BeamHeight" NUMBER(8,4),
  "BeamFlanges" NUMBER(5),
  "BeamWebThick" NUMBER(8,4),
  "BeamWebDepth" NUMBER(8,4),
  "BeamFlangeThick" NUMBER(8,4),
  "BeamFlangeWidth" NUMBER(8,4),
  "MaterialWeight" NUMBER(8,4),
  "MaterialThickness" NUMBER(8,4),
  "BeamDeflection" NUMBER(8,4),
  "BeamAttachmentSpacing" NUMBER(8,4),
  "BeamSteelline" NUMBER(5),
  "BeamSection" VARCHAR2(50 BYTE),
  "BeamWeight" NUMBER(8,4),
  "BeamPrice" NUMBER(8,4),
  "BeamIsPriced" NUMBER(5),
  "BeamErrorCode" NUMBER(5),
  "IsDelete" CHAR DEFAULT 'N',
  "IpAddress" VARCHAR2(20 BYTE),
  "CreatedBy" NUMBER(5),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(5),
  "ModifiedDate" TIMESTAMP,
  CONSTRAINT "SupportBeams_PK" PRIMARY KEY ("SupportBeamsId")
);