CREATE TABLE abs_mdi."USR_UserDetail" (
  "UserDetailId" NUMBER DEFAULT abs_mdi."USR_UserDetail_SEQ"."NEXTVAL" NOT NULL,
  "UserId" VARCHAR2(50 BYTE),
  "IsActive" CHAR,
  "ModuleName" VARCHAR2(10 BYTE),
  "CreatedBy" NUMBER(5),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(5),
  "ModifiedDate" TIMESTAMP,
  "EmployeeNo" NUMBER(5),
  "IsDelete" CHAR DEFAULT 'N',
  "CustomerNo" NUMBER(10),
  "IsRequireSignature" CHAR,
  "Notes" NVARCHAR2(1000),
  "MiddleName" VARCHAR2(50 BYTE),
  "IsCustomerAdmin" CHAR DEFAULT 'N' NOT NULL,
  "Bookmarks" CHAR DEFAULT 'Y' NOT NULL,
  "Orders" CHAR DEFAULT 'Y' NOT NULL,
  "Contacts" CHAR DEFAULT 'Y' NOT NULL,
  "Leads" CHAR DEFAULT 'Y' NOT NULL,
  "JobBoard" CHAR DEFAULT 'Y' NOT NULL,
  "UpcomingEvents" CHAR DEFAULT 'Y' NOT NULL,
  "Group" VARCHAR2(100 BYTE),
  "GroupId" VARCHAR2(40 BYTE),
  CONSTRAINT "UserDetail_PK" PRIMARY KEY ("UserDetailId")
);