CREATE TABLE abs_mdi.vv_building_info (
  builderid NUMBER(10),
  buildername VARCHAR2(100 BYTE),
  website VARCHAR2(100 BYTE),
  phone VARCHAR2(20 BYTE),
  fax VARCHAR2(20 BYTE),
  billtoaddress VARCHAR2(200 BYTE),
  billtocity VARCHAR2(100 BYTE),
  billtostate VARCHAR2(100 BYTE),
  billtopostalcode VARCHAR2(20 BYTE),
  billtocountry VARCHAR2(100 BYTE),
  shiptoaddress VARCHAR2(200 BYTE),
  shiptocity VARCHAR2(100 BYTE),
  shiptostate VARCHAR2(100 BYTE),
  shiptopostalcode VARCHAR2(20 BYTE),
  shiptocountry VARCHAR2(100 BYTE),
  primarycontact VARCHAR2(100 BYTE),
  customerno VARCHAR2(100 BYTE),
  createdby VARCHAR2(200 BYTE),
  createddate TIMESTAMP,
  modifiedby VARCHAR2(200 BYTE),
  modifieddate TIMESTAMP,
  ipaddress VARCHAR2(20 BYTE),
  companyid NUMBER(5)
);