CREATE TABLE abs_mdi.xx_shippingplants_agora (
  "PlantCode" NVARCHAR2(200),
  "IsActive" CHAR,
  "Name" NVARCHAR2(200),
  "Latitude" NUMBER(30,10),
  "Longitude" NUMBER(20,10),
  "IsCanadaApproved" CHAR,
  "PriceMultiplier" NUMBER(18,8),
  "IsExpressCapable" CHAR,
  "IsMbciPlant" CHAR,
  "MaximumWeightPerTruck" NUMBER(18,8),
  "MinimumFreightFee" NUMBER(18,8),
  "FreightSurcharge" NUMBER(18,8),
  "MinimumWeight" NUMBER(18,8),
  "FreightRate" NUMBER(18,8),
  "AdditionalPerTruckFee" NUMBER(18,8),
  "CpuAddressId" NUMBER(*,0),
  "IsCpuPlant" CHAR,
  "TruckTarpFee" NUMBER(18,8),
  "IsComponentsPlant" CHAR,
  "ComponentsLeadDays" NUMBER(10,2),
  "CreatedBy" NUMBER(10),
  "CreatedDate" TIMESTAMP,
  "ModifiedBy" NUMBER(10),
  "ModifiedDate" TIMESTAMP,
  "ShippingPlantId" NUMBER(10),
  "IpAddress" VARCHAR2(20 BYTE)
);