CREATE TABLE abs_mdi.xx_systemvariable (
  "SystemVariableId" NUMBER(10) NOT NULL,
  "MinimumPasswordLength" NUMBER(5),
  "LoginConfirmationDays" NUMBER(5),
  "PasswordResetConfirmationDays" NUMBER(3),
  "LoginRetries" NUMBER(2),
  "SessionTimeout" NUMBER(5),
  "MaximumAttachmentSize" NUMBER(9),
  "AcceptableAttachmentTypes" VARCHAR2(128 BYTE),
  "AcceptableLogoTypes" VARCHAR2(128 BYTE),
  "SystemVersion" VARCHAR2(128 BYTE),
  "CopyrightInformation" VARCHAR2(512 BYTE),
  "NoContentMessageOrders" VARCHAR2(512 BYTE),
  "NoContentMessageLeads" VARCHAR2(512 BYTE),
  "NoContentMessageContacts" VARCHAR2(512 BYTE),
  "NoContentMessageUpcomingEvents" VARCHAR2(512 BYTE),
  "NoContentMessageFeatureAnnouncements" VARCHAR2(512 BYTE),
  "NoContentMessageBuilderNews" VARCHAR2(512 BYTE),
  "NoContentMessageJobBoard" VARCHAR2(512 BYTE),
  "DailyNotificationTimeUtc" VARCHAR2(20 BYTE),
  "WeeklyNotificationTimeUtc" VARCHAR2(20 BYTE),
  "NotificationDayOfTheWeek" VARCHAR2(20 BYTE),
  "NotificationSliderSpeed" NUMBER(5),
  "FurthestShippingDays" NUMBER(5),
  "BuildingPricingVersionNumber" VARCHAR2(512 BYTE),
  "ThrottlingThreshold" NUMBER(5),
  "ThrottlingDelay" NUMBER(5),
  "CreatedBy" NUMBER(5) NOT NULL,
  "CreatedDate" TIMESTAMP NOT NULL,
  "ModifiedBy" NUMBER(5),
  "ModifiedDate" TIMESTAMP,
  "FramedOpeningClearanceTop" NUMBER(7,2),
  "FramedOpeningClearanceBottom" NUMBER(7,2),
  "FramedOpeningClearanceSides" NUMBER(7,2),
  "TopClearenceForMainFrameEndwallsForFramedOpening" NUMBER(7,2),
  "FramedOpeningSideClearenceForMainFrameEndwalls" NUMBER(7,2),
  "TopClearenceForMainFrameEndwallsForDbciDoor" NUMBER(7,2),
  "DbciDoorClearanceTop" NUMBER(7,2),
  "DbciDoorClearanceBottom" NUMBER(7,2),
  "FramedOpeningTopClearanceForBearingFrameEndwalls" NUMBER(7,2),
  "DbciDoorClearanceSides" NUMBER(7,2),
  "PortalFrameColumnDepth" NUMBER(7,2),
  "PortalFrameBeamDepth" NUMBER(7,2),
  "DbciDoorTopClearanceForBearingFrameEndwalls" NUMBER(7,2),
  "FramedOpeningSideClearanceForBearingFrameEndwalls" NUMBER(7,2),
  "MinValueForEndwallBSpecialSetback" NUMBER(7,2),
  "MaxValueForEndwallBSpecialSetback" NUMBER(7,2),
  "MinValueForEndwallDSpecialSetback" NUMBER(7,2),
  "MinimumCanopySoffitElevation" NUMBER(7,2),
  "ParapetMinimumDistanceAboveRoofLine" NUMBER(7,2),
  "MaximumVerticalClearanceRequirement" NUMBER(7,2),
  "ThreeWeekFee" NUMBER(7,2),
  "FerryFee" NUMBER(7,2),
  "DefaultMainFrameSetback" VARCHAR2(50 BYTE),
  "NumberOfItemsPerPage" NUMBER(7,2),
  "FurthestShippingDaysForComponent" NUMBER(7,2),
  "AgoraPurchaseOrderVersion" VARCHAR2(50 BYTE),
  "ComponentPurchaseOrderVersion" VARCHAR2(50 BYTE),
  "ComponentPricingVersion" VARCHAR2(50 BYTE),
  "IpAddress" VARCHAR2(20 BYTE),
  "NoContentMessageQuotes" VARCHAR2(50 BYTE),
  "FurthestShippingDaysBuilding" NUMBER(7,2),
  "DBCIDoorSideClearanceMainFrame" NUMBER(7,2),
  "DBCIDoorSideClearanceBearingFrame" NUMBER(7,2)
);