CREATE OR REPLACE TRIGGER abs_mdi."Accessories_WalkDoors_TRG" 
BEFORE INSERT ON abs_mdi."Accessories_WalkDoors" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."WalkDoorId" IS NULL THEN
      SELECT "Accessories_WalkDoors_SEQ".NEXTVAL INTO :NEW."WalkDoorId" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/