CREATE OR REPLACE TRIGGER abs_mdi."Accessories_Wainscot_TRG" 
BEFORE INSERT ON abs_mdi."ACCESORIES_WAINSCOT" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."WAINSCOTID" IS NULL THEN
      SELECT "Accessories_Wainscot_SEQ".NEXTVAL INTO :NEW."WAINSCOTID" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/