CREATE OR REPLACE TRIGGER abs_mdi."ACCESSORIES_LINER_ROOF_TRG" 
BEFORE INSERT ON abs_mdi."Accessories_Liner_Roof" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/