CREATE OR REPLACE TRIGGER abs_mdi."Accessories_Louvers_TRG" 
BEFORE INSERT ON abs_mdi."Accessories_Louvers" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."LouverId" IS NULL THEN
      SELECT "Accessories_Louvers_SEQ".NEXTVAL INTO :NEW."LouverId" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/