CREATE OR REPLACE TRIGGER abs_mdi."Accesories_RoofLTP_TRG" 
BEFORE INSERT ON abs_mdi."Accesories_RoofLTP" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."RoofLTPId" IS NULL THEN
      SELECT "Accesories_RoofLTP_SEQ".NEXTVAL INTO :NEW."RoofLTPId" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/