CREATE OR REPLACE TRIGGER abs_mdi."Accesories_WallLTP_TRG" 
BEFORE INSERT ON abs_mdi."Accesories_WallLTP" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."WallLTPId" IS NULL THEN
      SELECT "Accesories_WallLTP_SEQ".NEXTVAL INTO :NEW."WallLTPId" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/