CREATE OR REPLACE TRIGGER abs_mdi."Accesories_WallLTP_Size_TRG" 
BEFORE INSERT ON abs_mdi."Accesories_WallLTP_Size" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."Id" IS NULL THEN
      SELECT "Accesories_WallLTP_Size_SEQ1".NEXTVAL INTO :NEW."Id" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/