CREATE OR REPLACE TRIGGER abs_mdi."BFM_FrameLines_TRG" 
BEFORE INSERT ON abs_mdi."BFM_FrameLines" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."FrameLineId" IS NULL THEN
      SELECT "BFM_FrameLines_SEQ".NEXTVAL INTO :NEW."FrameLineId" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/