CREATE OR REPLACE TRIGGER abs_mdi."BFM_Modules_TRG" 
BEFORE INSERT ON abs_mdi."BFM_Modules" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."ModuleId" IS NULL THEN
      SELECT "BFM_Modules_SEQ".NEXTVAL INTO :NEW."ModuleId" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/