CREATE OR REPLACE TRIGGER abs_mdi."BFM_Columns_TRG" 
BEFORE INSERT ON abs_mdi."BFM_Columns" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."ColumnId" IS NULL THEN
      SELECT "BFM_Columns_SEQ".NEXTVAL INTO :NEW."ColumnId" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/