CREATE OR REPLACE TRIGGER abs_mdi."BFM_Groups_TRG" 
BEFORE INSERT ON abs_mdi."BFM_Groups" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."GroupId" IS NULL THEN
      SELECT "BFM_Groups_SEQ".NEXTVAL INTO :NEW."GroupId" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/