CREATE OR REPLACE TRIGGER abs_mdi."Bracing_TRG" 
BEFORE INSERT ON abs_mdi."Bracing" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."BracingId" IS NULL THEN
      SELECT "Bracing_SEQ".NEXTVAL INTO :NEW."BracingId" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/