CREATE OR REPLACE TRIGGER abs_mdi."BuildingInformation_TRG1" 
BEFORE INSERT ON abs_mdi."BuildingInformation" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/