CREATE OR REPLACE TRIGGER abs_mdi."CAD_Express_TRG1" 
BEFORE INSERT ON abs_mdi."CAD_Express" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."Id" IS NULL THEN
      SELECT "CAD_Express_SEQ1".NEXTVAL INTO :NEW."Id" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/