CREATE OR REPLACE TRIGGER abs_mdi."CAD_Options_TRG2" 
BEFORE INSERT ON abs_mdi."CAD_Options" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."Id" IS NULL THEN
      SELECT "CAD_Options_SEQ2".NEXTVAL INTO :NEW."Id" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/