CREATE OR REPLACE TRIGGER abs_mdi."CL_SoilType_TRG" 
BEFORE INSERT ON abs_mdi."CL_SoilType" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."Id" IS NULL THEN
      SELECT "CL_SoilType_SEQ".NEXTVAL INTO :NEW."Id" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/