CREATE OR REPLACE TRIGGER abs_mdi."CL_StateAvailability_TRG1" 
BEFORE INSERT ON abs_mdi."CL_StateAvailability" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."SAId" IS NULL THEN
      SELECT "CL_StateAvailability_SEQ1".NEXTVAL INTO :NEW."SAId" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/