CREATE OR REPLACE TRIGGER abs_mdi."ColorPanel_TRG" 
BEFORE INSERT ON abs_mdi."ColorPanel" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."ColorPanelId" IS NULL THEN
      SELECT "ColorPanel_SEQ".NEXTVAL INTO :NEW."ColorPanelId" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;


/