CREATE OR REPLACE TRIGGER abs_mdi."ColorMaster_TRG" 
BEFORE INSERT ON abs_mdi."ColorMaster" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."ColorId" IS NULL THEN
      SELECT "ColorMaster_SEQ".NEXTVAL INTO :NEW."ColorId" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;


/