CREATE OR REPLACE TRIGGER abs_mdi."ColorCodes_TRG" 
BEFORE INSERT ON abs_mdi."ColorCodes" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."ColorCodeId" IS NULL THEN
      SELECT "ColorCodes_SEQ".NEXTVAL INTO :NEW."ColorCodeId" FROM SYS.DUAL;
    END IF;
    IF INSERTING AND :NEW."Trim" IS NULL THEN
      SELECT "ColorCodes_SEQ".NEXTVAL INTO :NEW."Trim" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;


/