CREATE OR REPLACE TRIGGER abs_mdi."Countries_TRG" 
BEFORE INSERT ON abs_mdi."Countries" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."CountryId" IS NULL THEN
      SELECT "Countries_SEQ".NEXTVAL INTO :NEW."CountryId" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;



/