CREATE OR REPLACE TRIGGER abs_mdi."CS_LayerColor_TRG" 
BEFORE INSERT ON abs_mdi."CS_LayerColor" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."LayerColorId" IS NULL THEN
      SELECT "CS_LayerColor_SEQ".NEXTVAL INTO :NEW."LayerColorId" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/