CREATE OR REPLACE TRIGGER abs_mdi."DDP_EDSDB_SETTINGS_TRG1" 
BEFORE INSERT ON abs_mdi.DDP_EDSDB_SETTINGS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.MINFRAMEMOMENTBOLTDIA IS NULL THEN
      SELECT DDP_EDSDB_SETTINGS_SEQ.NEXTVAL INTO :NEW.MINFRAMEMOMENTBOLTDIA FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/