CREATE OR REPLACE TRIGGER abs_mdi."DDP_EDSDB_SETTINGS_TRG" 
BEFORE INSERT ON abs_mdi.DDP_EDSDB_SETTINGS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.SETTINGID IS NULL THEN
      SELECT DDP_EDS_SETTINGS_SEQ.NEXTVAL INTO :NEW.SETTINGID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/