CREATE OR REPLACE TRIGGER abs_mdi."DDP_DESIGNPACKAGECHECKLISTDETAILS_TRG" 
BEFORE INSERT OR UPDATE ON abs_mdi.DDP_DESIGNPACKAGECHECKLISTDETAILS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT DDP_DESIGNPACKAGECHECKLISTDETAILS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
    IF (:old."NAME" != :new."NAME") 
        THEN
            "DDP_HISTORYOP"(:new."MODIFIEDBY",'DDP_DESIGNPACKAGECHECKLISTDETAILS','NAME', :old."NAME", :new."NAME",:new."IPADDRESS",null,null); 
        END IF;
       IF (:old."PROJECTENGINEER" != :new."PROJECTENGINEER") 
        THEN
            "DDP_HISTORYOP"(:new."MODIFIEDBY",'DDP_DESIGNPACKAGECHECKLISTDETAILS','PROJECTENGINEER', :old."PROJECTENGINEER", :new."PROJECTENGINEER",:new."IPADDRESS",null,null); 
        END IF;   

     IF (:old."CHECKINGENGINEER" != :new."CHECKINGENGINEER") 
        THEN
            "DDP_HISTORYOP"(:new."MODIFIEDBY",'DDP_DESIGNPACKAGECHECKLISTDETAILS','CHECKINGENGINEER', :old."CHECKINGENGINEER", :new."CHECKINGENGINEER",:new."IPADDRESS",null,null); 
        END IF;

         IF (:old."NA" != :new."NA") 
        THEN
            "DDP_HISTORYOP"(:new."MODIFIEDBY",'DDP_DESIGNPACKAGECHECKLISTDETAILS','NA', :old."NA", :new."NA",:new."IPADDRESS",null,null); 
        END IF;

  END COLUMN_SEQUENCES;
END;

/