CREATE OR REPLACE TRIGGER abs_mdi."DDP_EDSDB_GENINFO_TRG2" 
BEFORE INSERT ON abs_mdi.DDP_EDSDB_GENINFO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.SHIP_TO_ZIP_CODE IS NULL THEN
      SELECT DDP_EDSDB_GENINFO_SEQ.NEXTVAL INTO :NEW.SHIP_TO_ZIP_CODE FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/