CREATE OR REPLACE TRIGGER abs_mdi."DDP_DEFAULTNOTESONDRAWINGCATEGORY_TRG" 
BEFORE INSERT OR UPDATE ON  abs_mdi.DDP_DEFAULTNOTESONDRAWINGCATEGORY 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CATEGORYID IS NULL THEN
      SELECT DDP_DEFAULTNOTESONDRAWINGCATEGORY_SEQ.NEXTVAL INTO :NEW.CATEGORYID FROM SYS.DUAL;
    END IF;
      IF (:old."CATEGORYNAME" != :new."CATEGORYNAME") 
        THEN
            DDP_HISTORYOP(:new."MODIFIEDBY",'DDP_DEFAULTNOTESONDRAWINGCATEGORY','CATEGORYNAME',:old."CATEGORYNAME", :new."CATEGORYNAME", :new."IPADDRESS",null,null ); 
        END IF;
         IF (:old."ORDERPRIORITY" != :new."ORDERPRIORITY") 
        THEN
            DDP_HISTORYOP(:new."MODIFIEDBY",'DDP_DEFAULTNOTESONDRAWINGCATEGORY','ORDERPRIORITY',:old."ORDERPRIORITY", :new."ORDERPRIORITY", :new."IPADDRESS",null,null ); 
        END IF; 

        IF (:old."ISDELETE" != :new."ISDELETE") 
        THEN
            DDP_HISTORYOP(:new."MODIFIEDBY",'DDP_DEFAULTNOTESONDRAWINGCATEGORY','ISDELETE',:old."ISDELETE", :new."ISDELETE", :new."IPADDRESS",null,null ); 
        END IF;
  END COLUMN_SEQUENCES;
END;

/