CREATE OR REPLACE TRIGGER abs_mdi."DDP_ENGINEERJUDGEMENT_TRG4" 
BEFORE INSERT OR UPDATE ON abs_mdi.DDP_ENGINEERJUDGEMENT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ENGINEERINGJUDGEMENTSID IS NULL THEN
      SELECT DDP_ENGINEERJUDGEMENT_SEQ.NEXTVAL INTO :NEW.ENGINEERINGJUDGEMENTSID FROM SYS.DUAL;
    END IF;
    IF INSERTING AND :NEW.DDPSSERVERID IS NULL THEN
      SELECT DDP_ENGINEERJUDGEMENT_SEQ.NEXTVAL INTO :NEW.DDPSSERVERID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/