CREATE OR REPLACE TRIGGER abs_mdi."DDP_DESIGNPACKAGECHECKLIST_TRG" 
BEFORE INSERT OR UPDATE ON abs_mdi.DDP_DESIGNPACKAGECHECKLIST 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;

/