CREATE OR REPLACE TRIGGER abs_mdi."DDP_JOBPREFIXES_TRG" 
BEFORE INSERT OR UPDATE ON abs_mdi.DDP_JOBPREFIXES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.JOBPREFIXID IS NULL THEN
      SELECT DDP_JOBPREFIXES_SEQ.NEXTVAL INTO :NEW.JOBPREFIXID FROM SYS.DUAL;
    END IF;
     IF (:old."PREFIX" != :new."PREFIX") 
        THEN
            "DDP_HISTORYOP"(:new."MODIFIEDBY",'DDP_JOBPREFIXES','PREFIX', :old."PREFIX", :new."PREFIX",:new."IPADDRESS",null,null); 
        END IF;
        IF (:old."ISDEFAULT" != :new."ISDEFAULT") 
        THEN
            "DDP_HISTORYOP"(:new."MODIFIEDBY",'DDP_JOBPREFIXES','ISDEFAULT', :old."ISDEFAULT", :new."ISDEFAULT",:new."IPADDRESS",null,null); 
        END IF;
        IF (:old."ISDELETE" != :new."ISDELETE") 
        THEN
            "DDP_HISTORYOP"(:new."MODIFIEDBY",'DDP_JOBPREFIXES','ISDELETE', :old."ISDELETE", :new."ISDELETE",:new."IPADDRESS",null,null); 
        END IF;
  END COLUMN_SEQUENCES;
END;

/