CREATE OR REPLACE TRIGGER abs_mdi."DDP_LOCTEMPLATES_TRG" 
BEFORE INSERT OR UPDATE ON abs_mdi.DDP_LOCTEMPLATES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.LOCTEMPLATEID IS NULL THEN
      SELECT DDP_LOCTEMPLATES_SEQ.NEXTVAL INTO :NEW.LOCTEMPLATEID FROM SYS.DUAL;
    END IF;

  END COLUMN_SEQUENCES;
END;

/