CREATE OR REPLACE TRIGGER abs_mdi."DDP_USERCUSTOMNOTES_TRG" 
BEFORE INSERT OR UPDATE ON abs_mdi.DDP_USERCUSTOMNOTES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CUSTOMNOTESID IS NULL THEN
      SELECT DDP_USERCUSTOMNOTES_SEQ.NEXTVAL INTO :NEW.CUSTOMNOTESID FROM SYS.DUAL;
    END IF;

     IF (:old."CUSTOMNOTE" != :new."CUSTOMNOTE") 
        THEN
            "DDP_HISTORYOP"(:new."MODIFIEDBY",'DDP_USERCUSTOMNOTES','CUSTOMNOTE', :old."CUSTOMNOTE", :new."CUSTOMNOTE",:new."IPADDRESS",null,null); 
        END IF;

           IF (:old."ISDELETE" != :new."ISDELETE") 
        THEN
            "DDP_HISTORYOP"(:new."MODIFIEDBY",'DDP_USERCUSTOMNOTES','ISDELETE', :old."ISDELETE", :new."ISDELETE",:new."IPADDRESS",null,null); 
        END IF;
  END COLUMN_SEQUENCES;
END;

/