CREATE OR REPLACE TRIGGER abs_mdi."DDP_BUILDINGLOADS_TRG" 
BEFORE INSERT ON abs_mdi.DDP_BUILDINGLOADS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.COMMENTS IS NULL THEN
      SELECT DDP_BUILDINGLOADS_SEQ.NEXTVAL INTO :NEW.COMMENTS FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/