CREATE OR REPLACE TRIGGER abs_mdi."DDP_BUILDINGLOADS_TRG1" 
BEFORE INSERT OR UPDATE ON abs_mdi.DDP_BUILDINGLOADS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;

/