CREATE OR REPLACE TRIGGER abs_mdi."DDP_EDSDB_BOXLAYGEOM_TRG1" 
BEFORE INSERT OR UPDATE ON abs_mdi.DDP_EDSDB_BOXLAYGEOM 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.BOXLAYGEOMID IS NULL THEN
      SELECT DDP_EDSDB_BOXLAYGEOM_SEQ.NEXTVAL INTO :NEW.BOXLAYGEOMID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/