CREATE OR REPLACE TRIGGER abs_mdi."EDSPrice_O_Reports_TRG" 
BEFORE INSERT ON abs_mdi."EDSPrice_O_Reports" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."ReportsId" IS NULL THEN
      SELECT "EDSPrice_O_Reports_SEQ".NEXTVAL INTO :NEW."ReportsId" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/