CREATE OR REPLACE TRIGGER abs_mdi."EDSPrice_Testing_TRG" 
BEFORE INSERT ON abs_mdi."EDSPrice_Testing" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."Id" IS NULL THEN
      SELECT "EDSPrice_Testing_SEQ".NEXTVAL INTO :NEW."Id" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/