CREATE OR REPLACE TRIGGER abs_mdi."EDSPrice_IO_MezzanineOpening_TRG1" 
BEFORE INSERT ON abs_mdi."EDSPrice_IO_MezzanineOpening" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."MezzanineOpeningId" IS NULL THEN
      SELECT "EDSPrice_IO_MezzanineOpening_SEQ1".NEXTVAL INTO :NEW."MezzanineOpeningId" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/