CREATE OR REPLACE TRIGGER abs_mdi."EDSPrice_O_Deflections_TRG3" 
BEFORE INSERT ON abs_mdi."EDSPrice_O_Deflections" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."DeflectionsId" IS NULL THEN
      SELECT "EDSPrice_O_Deflections_SEQ2".NEXTVAL INTO :NEW."DeflectionsId" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/