CREATE OR REPLACE TRIGGER abs_mdi."EDSPrice_O_EWPlates_TRG1" 
BEFORE INSERT ON abs_mdi."EDSPrice_O_EWPlates" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."EWPlatesId" IS NULL THEN
      SELECT "EDSPrice_O_EWPlates_SEQ".NEXTVAL INTO :NEW."EWPlatesId" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/