CREATE OR REPLACE TRIGGER abs_mdi."EDSPrice_O_Pricing_TRG2" 
BEFORE INSERT ON abs_mdi."EDSPrice_O_Pricing" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."PricingId" IS NULL THEN
      SELECT "EDSPrice_O_Pricing_SEQ".NEXTVAL INTO :NEW."PricingId" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/