CREATE OR REPLACE TRIGGER abs_mdi."EDSPrice_IO_Mezzanines_TRG1" 
BEFORE INSERT ON abs_mdi."EDSPrice_IO_Mezzanines" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."MezzaninesId" IS NULL THEN
      SELECT "EDSPrice_IO_Mezzanines_SEQ1".NEXTVAL INTO :NEW."MezzaninesId" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/