CREATE OR REPLACE TRIGGER abs_mdi."EDSPrice_O_AnchorBolts_TRG" 
BEFORE INSERT ON abs_mdi."EDSPrice_O_AnchorBolts" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;

/