CREATE OR REPLACE TRIGGER abs_mdi."EDSPrice_CAD_Advanced_TRG" 
BEFORE INSERT ON abs_mdi."EDSPrice_CAD_Advanced" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;

/