CREATE OR REPLACE TRIGGER abs_mdi."EDSPrice_O_XBracing_TRG" 
BEFORE INSERT ON abs_mdi."EDSPrice_O_XBracing" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."XBracingId" IS NULL THEN
      SELECT "EDSPrice_O_XBracing_SEQ".NEXTVAL INTO :NEW."XBracingId" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/