CREATE OR REPLACE TRIGGER abs_mdi."EDSPrice_O_DesignData_TRG" 
BEFORE INSERT ON abs_mdi."EDSPrice_O_DesignData" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;

/