CREATE OR REPLACE TRIGGER abs_mdi."EDSPrice_O_ErrorReports_TRG1" 
BEFORE INSERT ON abs_mdi."EDSPrice_O_ErrorReports" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."ErrorReportsId" IS NULL THEN
      SELECT "EDSPrice_O_ErrorReports_SEQ1".NEXTVAL INTO :NEW."ErrorReportsId" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/