CREATE OR REPLACE TRIGGER abs_mdi."EDSPrice_O_RMGData_TRG" 
BEFORE INSERT ON abs_mdi."EDSPrice_O_RMGData" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."RMGDataId" IS NULL THEN
      SELECT "EDSPrice_O_RMGData_SEQ".NEXTVAL INTO :NEW."RMGDataId" FROM SYS.DUAL;
    END IF;

    DECLARE n NUMBER;
    BEGIN
        SELECT COUNT(1) AS a INTO n FROM "EDSPrice_O_RMGData" WHERE "RMGDataId" = :NEW."RMGDataId";

        IF INSERTING AND n > 0 THEN
            SELECT (MAX("RMGDataId")+1) INTO :NEW."RMGDataId" FROM "EDSPrice_O_RMGData";
        END IF;
    END;
  END COLUMN_SEQUENCES;
END;

/