CREATE OR REPLACE TRIGGER abs_mdi."EDSPrice_O_Errors_TRG" 
BEFORE INSERT ON abs_mdi."EDSPrice_O_Errors" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."ErrorsId" IS NULL THEN
      SELECT "EDSPrice_O_Errors_SEQ".NEXTVAL INTO :NEW."ErrorsId" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/