CREATE OR REPLACE TRIGGER abs_mdi."EndWallPotalFrame_TRG1" 
BEFORE INSERT ON abs_mdi."EndWallPotalFrame" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."EndWallProtalFrameId" IS NULL THEN
      SELECT "EndWallPotalFrame_SEQ1".NEXTVAL INTO :NEW."EndWallProtalFrameId" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;


/