CREATE OR REPLACE TRIGGER abs_mdi."Groups_Users_TRG" 
BEFORE INSERT ON abs_mdi."Groups_Users" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."GroupUserId" IS NULL THEN
      SELECT "Groups_Users_SEQ".NEXTVAL INTO :NEW."GroupUserId" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/