CREATE OR REPLACE TRIGGER abs_mdi."I_Address_TRG" 
BEFORE INSERT ON abs_mdi."I_Address" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."AddressId" IS NULL THEN
      SELECT "I_Address_SEQ".NEXTVAL INTO :NEW."AddressId" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/