CREATE OR REPLACE TRIGGER abs_mdi."Input_RoofMaster_TRG" 
BEFORE INSERT ON abs_mdi."Input_RoofMaster" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."RoofPanelId" IS NULL THEN
      SELECT "Input_RoofMaster_SEQ".NEXTVAL INTO :NEW."RoofPanelId" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/