CREATE OR REPLACE TRIGGER abs_mdi."Input_ShopCoat_TRG" 
BEFORE INSERT ON abs_mdi."Input_ShopCoat" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."ShopCoatId" IS NULL THEN
      SELECT "Input_ShopCoat_SEQ".NEXTVAL INTO :NEW."ShopCoatId" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/