CREATE OR REPLACE TRIGGER abs_mdi."Input_Endwalls_ColumnSpacing_TRG" 
BEFORE INSERT ON abs_mdi."Input_Endwalls_ColumnSpacing" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CSID IS NULL THEN
      SELECT "Input_Endwalls_ColumnSpacing_SEQ".NEXTVAL INTO :NEW.CSID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;


/