CREATE OR REPLACE TRIGGER abs_mdi."Input_Owner_TRG" 
BEFORE INSERT ON abs_mdi."Input_Owner" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."Id" IS NULL THEN
      SELECT "Input_Owner_SEQ".NEXTVAL INTO :NEW."Id" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/