CREATE OR REPLACE TRIGGER abs_mdi."Input_Trim_TRG" 
BEFORE INSERT ON abs_mdi."Input_Trim" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."TrimId" IS NULL THEN
      SELECT "Input_Trim_SEQ".NEXTVAL INTO :NEW."TrimId" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;


/