CREATE OR REPLACE TRIGGER abs_mdi."Input_Endwall_TRG" 
BEFORE INSERT ON abs_mdi."Input_Endwall" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."EndWallID" IS NULL THEN
      SELECT "Input_Endwall_SEQ".NEXTVAL INTO :NEW."EndWallID" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;


/