CREATE OR REPLACE TRIGGER abs_mdi."Input_AddLines_TRG" 
BEFORE INSERT ON abs_mdi."Input_AddLines" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."AddLinesId" IS NULL THEN
      SELECT "Input_AddLines_SEQ".NEXTVAL INTO :NEW."AddLinesId" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/