CREATE OR REPLACE TRIGGER abs_mdi."Input_Wall_TRG" 
BEFORE INSERT ON abs_mdi."Input_Wall" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."WallId" IS NULL THEN
      SELECT "Input_Wall_SEQ".NEXTVAL INTO :NEW."WallId" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/