CREATE OR REPLACE TRIGGER abs_mdi."Input_GirtsBaySpacing_TRG" 
BEFORE INSERT ON abs_mdi."Input_GirtsBaySpacing" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."GirtSpacingId" IS NULL THEN
      SELECT "Input_GirtsBaySpacing_SEQ".NEXTVAL INTO :NEW."GirtSpacingId" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/