CREATE OR REPLACE TRIGGER abs_mdi."InsulationMaster_TRG" 
BEFORE INSERT ON abs_mdi."InsulationMaster" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."Id" IS NULL THEN
      SELECT "InsulationMaster_SEQ".NEXTVAL INTO :NEW."Id" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/