CREATE OR REPLACE TRIGGER abs_mdi."Job_Board_TRG" 
BEFORE INSERT ON abs_mdi."Jobs" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."JobId" IS NULL THEN
      SELECT "Job_Board_SEQ".NEXTVAL INTO :NEW."JobId" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/