CREATE OR REPLACE TRIGGER abs_mdi."Jobs_TRG" 
BEFORE INSERT ON abs_mdi."Jobs" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."ProjectName" IS NULL THEN
      SELECT "Jobs_SEQ".NEXTVAL INTO :NEW."ProjectName" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/