CREATE OR REPLACE TRIGGER abs_mdi."M_AddlineHeader_TRG" 
BEFORE INSERT ON abs_mdi."M_NetAddlineHeader" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."Id" IS NULL THEN
      SELECT "M_AddlineHeader_SEQ".NEXTVAL INTO :NEW."Id" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/