CREATE OR REPLACE TRIGGER abs_mdi."M_Facade_Type_TRG" 
BEFORE INSERT ON abs_mdi."M_Facade_Type" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."Id" IS NULL THEN
      SELECT "M_Facade_Type_SEQ".NEXTVAL INTO :NEW."Id" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/