CREATE OR REPLACE TRIGGER abs_mdi."MBSAccessoriesGuid_TRG" 
BEFORE INSERT ON abs_mdi."MBSAccessoriesGuid" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."MBSAccessoriesId" IS NULL THEN
      SELECT "MBSAccessoriesGuid_SEQ".NEXTVAL INTO :NEW."MBSAccessoriesId" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/