CREATE OR REPLACE TRIGGER abs_mdi."MBSBuildingPrice_TRG" 
BEFORE INSERT ON abs_mdi."MBSBuildingPrice" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."Id" IS NULL THEN
      SELECT "MBSBuildingPrice_SEQ1".NEXTVAL INTO :NEW."Id" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/