CREATE OR REPLACE TRIGGER abs_mdi."MenuPage_TRG" 
BEFORE INSERT ON abs_mdi."MenuPage" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."MenuPageId" IS NULL THEN
      SELECT "MenuPage_SEQ".NEXTVAL INTO :NEW."MenuPageId" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;



/