CREATE OR REPLACE TRIGGER abs_mdi."MenuAdmin_TRG" 
BEFORE INSERT ON abs_mdi."MenuAdmin" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ADMINID IS NULL THEN
      SELECT "MenuAdmin_SEQ".NEXTVAL INTO :NEW.ADMINID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;



/