CREATE OR REPLACE TRIGGER abs_mdi."OE_Categories_TRG" 
BEFORE INSERT ON abs_mdi."OE_Categories" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."OE_CategoriesId" IS NULL THEN
      SELECT "OE_Categories_SEQ".NEXTVAL INTO :NEW."OE_CategoriesId" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/