CREATE OR REPLACE TRIGGER abs_mdi."ONC_TRG" 
BEFORE INSERT ON abs_mdi.ONC 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."SkinningID" IS NULL THEN
      SELECT ONC_SEQ.NEXTVAL INTO :NEW."SkinningID" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;



/