CREATE OR REPLACE TRIGGER abs_mdi."Photos_TRG" 
BEFORE INSERT ON abs_mdi."Photos" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."PhotosId" IS NULL THEN
      SELECT "Photos_SEQ".NEXTVAL INTO :NEW."PhotosId" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;



/