CREATE OR REPLACE TRIGGER abs_mdi."Project_TRG" 
BEFORE INSERT ON abs_mdi."Project" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."ProjectId" IS NULL THEN
      SELECT "Project_SEQ".NEXTVAL INTO :NEW."ProjectId" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;


/