CREATE OR REPLACE TRIGGER abs_mdi."Purchaser_TRG" 
BEFORE INSERT ON abs_mdi."Purchaser" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."PurchaserId" IS NULL THEN
      SELECT "Purchaser_SEQ1".NEXTVAL INTO :NEW."PurchaserId" FROM SYS.DUAL;
    END IF;
 
  END COLUMN_SEQUENCES;
END;
/