CREATE OR REPLACE TRIGGER abs_mdi."SBSAdmin_TRG" 
BEFORE INSERT ON abs_mdi."SBSAdmin" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."SBSAdminId" IS NULL THEN
      SELECT "SBSAdmin_SEQ".NEXTVAL INTO :NEW."SBSAdminId" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;



/