CREATE OR REPLACE TRIGGER abs_mdi."SHIPPLANTCOUNTRIESTOSHIP_TRG" 
BEFORE INSERT ON abs_mdi."ShipPlantCountriesToShip" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;



/