CREATE OR REPLACE TRIGGER abs_mdi."ShippingPlantGrouping_TRG" 
BEFORE INSERT ON abs_mdi."ShippingPlantGrouping" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT "ShippingPlantGrouping_SEQ".NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;



/