CREATE OR REPLACE TRIGGER abs_mdi."ShipByComponents_TRG" 
BEFORE INSERT ON abs_mdi."ShipByComponents" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."ShipById" IS NULL THEN
      SELECT "ShipByComponents_SEQ1".NEXTVAL INTO :NEW."ShipById" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;



/