CREATE OR REPLACE TRIGGER abs_mdi."Shipping_TRG" 
BEFORE INSERT ON abs_mdi."Shipping" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."ShippingId" IS NULL THEN
      SELECT "Shipping_SEQ".NEXTVAL INTO :NEW."ShippingId" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/