CREATE OR REPLACE TRIGGER abs_mdi."Skinning_TRG1" 
BEFORE INSERT ON abs_mdi."Skinning" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."SkinningID" IS NULL THEN
      SELECT "Skinning_SEQ3".NEXTVAL INTO :NEW."SkinningID" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/