CREATE OR REPLACE TRIGGER abs_mdi."TableOfTables_TRG" 
BEFORE INSERT ON abs_mdi."TableOfTables" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."Id" IS NULL THEN
      SELECT "TableOfTables_SEQ".NEXTVAL INTO :NEW."Id" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;



/