CREATE OR REPLACE TRIGGER abs_mdi."Test_Table_TRG1" 
BEFORE INSERT ON abs_mdi."Test_Table" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."UserId" IS NULL THEN
      SELECT "Test_Table_SEQ1".NEXTVAL INTO :NEW."UserId" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/