CREATE OR REPLACE TRIGGER abs_mdi."USR_UserDetail_TRG" 
BEFORE INSERT ON abs_mdi."USR_UserDetail" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW."UserDetailId" IS NULL THEN
      SELECT "USR_UserDetail_SEQ".NEXTVAL INTO :NEW."UserDetailId" FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;


/