CREATE OR REPLACE TRIGGER abs_mdi."WEBLINKSMASTER_TRG1" 
BEFORE INSERT ON abs_mdi.WEBLINKSMASTER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.WEBLINKID IS NULL THEN
      SELECT WEBLINKSMASTER_SEQ1.NEXTVAL INTO :NEW.WEBLINKID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/