CREATE OR REPLACE TYPE abs_mdi."OT_BUILDINGCOMPLEXITYLEADDAY"                                          AS OBJECT 
( 
    BUILDINGCOMPLEXITYLEADDAYSID NUMBER(5),
    BUILDINGQUOTETYPEID NUMBER(5),
    CLASSMASTERID NUMBER(5),
    CLASSINPUT NUMBER(5,2)
)
/