CREATE OR REPLACE PROCEDURE abs_mdi."ACCESORIES_WINDOWS_CREATE" 
(
    BuildingNumber        IN   NUMBER,
    Quantity              IN   NUMBER,
    Elevation             IN   VARCHAR2,
    BayNumber             IN   NUMBER,
    WindowType            IN   VARCHAR2,
    SillHeight            IN   NUMBER,
    HeaderHeight          IN   NUMBER,
    Width                 IN   NUMBER,
    DistFromLeftCorner    IN   NUMBER,
    DistFromLeftCol       IN   NUMBER,
    TrimColor             IN   CHAR,
    WindowColor           IN   VARCHAR2,
    SubFraming            IN   NUMBER,
    GlassType             IN   VARCHAR2,
    Quality               IN   VARCHAR2,
    IsBuyout              IN   NUMBER,
    Weight                IN   NUMBER,
    Price                 IN   NUMBER,
    IsPriced              IN   NUMBER,
    ErrorCode             IN   NUMBER,
    InsulatedGlass        IN   CHAR,
    FrameFinish           IN   VARCHAR2,
    LocatedInLiner        IN   CHAR,
    LeftSteelLine         IN   NUMBER,
    PartitionNumber       IN   NUMBER,
    WindowCategory        IN   VARCHAR2,
    InsulationRetainerKit IN   CHAR,
    CWindowRating         IN   CHAR,
    WindowSize            IN   VARCHAR2,
    BracedBay             IN   NUMBER,
    UserId                IN   NUMBER DEFAULT NULL,
    IpAddress             IN   VARCHAR2,
    ProjectId             IN   NUMBER,
    IncludeFramedOpening  IN   CHAR,
    IsLocate              IN   CHAR,
    OutputId              OUT  NUMBER
)
AS 
BEGIN
  INSERT INTO "Accesories_Windows" (
  "BuildingNumber",
    "Quantity",
    "Elevation",
    "BayNumber",
    "Type",
    "SillHeight",
    "HeaderHeight",
    "Width",
    "DistFromLeftCorner",
    "DistFromLeftCol",
    "TrimColor",
    "WindowColor",
    "SubFraming",
    "GlassType",
    "Quality",
    "IsBuyout",
    "Weight",
    "Price",
    "IsPriced",
    "ErrorCode",
    "InsulatedGlass",
    "FrameFinish",
    "LocatedInLiner",
    "LeftSteelLine",
    "PartitionNumber",
    "WindowCategory",
    "InsulationRetainerKit",
    "CWindowRating",
    "WindowSize",
    "BracedBay",
    "CreatedBy",
    "CreatedDate",
    "IpAddress",
    "ProjectId",
    "IncludeFramedOpening",
    "IsLocate"
  )
  VALUES(
    BuildingNumber,
      Quantity,             
      Elevation,            
      BayNumber,           
      WindowType,                  
      SillHeight,          
      HeaderHeight,          
      Width,                
      DistFromLeftCorner,   
      DistFromLeftCol,       
      TrimColor,           
      WindowColor,          
      SubFraming,           
      GlassType,            
      Quality,              
      IsBuyout,             
      Weight,                
      Price,                 
      IsPriced,             
      ErrorCode,             
      InsulatedGlass,        
      FrameFinish,           
      LocatedInLiner,      
      LeftSteelLine,        
      PartitionNumber,      
      WindowCategory,
      InsulationRetainerKit,
      CWindowRating,         
      WindowSize,            
      BracedBay,         
      UserId,              
      CURRENT_TIMESTAMP,
      IpAddress,
      ProjectId,
      IncludeFramedOpening,
      IsLocate
  )
  RETURNING "WindowId" INTO OutputId;
END ACCESORIES_WINDOWS_CREATE;
/