CREATE OR REPLACE PROCEDURE abs_mdi."ACCESORIES_EDSPRICE_COUNTY_CITIES_SELECT" 
(
    OUTPUT_TABLE OUT  SYS_REFCURSOR
)
AS
BEGIN
    OPEN OUTPUT_TABLE FOR SELECT
         "State",
         "County",
         "City"
    FROM
        "M_EDSPrice_County_Cities";
END ACCESORIES_EDSPRICE_COUNTY_CITIES_SELECT;
/