CREATE OR REPLACE PROCEDURE abs_mdi."ACCESSORIES_MEZZANINESPACING_UPDATE" (
    MezzanineSpacingId IN NUMBER,
    MezzaninesId IN NUMBER,
     BuildingNumber   IN   NUMBER,
    ProjectId        IN   NUMBER,
    MezzanineNumber    IN   NUMBER,
    FramelineNumber IN  NUMBER , 
	 AlltheSame IN  NUMBER , 
	 Spacing1  IN NUMBER , 
	 Spacing2 IN NUMBER , 
	 Spacing3 IN NUMBER , 
	 Spacing4 IN NUMBER , 
	 Spacing5 IN NUMBER , 
	 Spacing6 IN NUMBER , 
	 Spacing7 IN NUMBER , 
	 Spacing8 IN NUMBER , 
	 Spacing9 IN NUMBER , 
	 Spacing10 IN NUMBER , 
	 Spacing11 IN NUMBER , 
	 Spacing12 IN NUMBER , 
	 Spacing13 IN NUMBER , 
	 Spacing14 IN NUMBER , 
	 Spacing15 IN NUMBER , 
	 Spacing16 IN NUMBER , 
	 Spacing17 IN NUMBER , 
	 Spacing18 IN NUMBER , 
	 Spacing19 IN NUMBER , 
	 Spacing20 IN NUMBER , 
	 Spacing21 IN NUMBER , 
	 Spacing22 IN NUMBER , 
	 Spacing23 IN NUMBER , 
	 Spacing24 IN NUMBER , 
	 Spacing25 IN NUMBER , 
	 Spacing26 IN NUMBER , 
	 Spacing27 IN NUMBER , 
	 Spacing28 IN NUMBER , 
	 Spacing29 IN NUMBER , 
	 Spacing30 IN NUMBER , 
     ForLongitudinal IN CHAR,
    UserId          IN  NUMBER DEFAULT NULL,
    IpAddress       IN  VARCHAR2
) AS
BEGIN
    UPDATE "EDSPrice_IO_MezzanineSpacing"
    SET
    "BuildingNumber" = BuildingNumber,
    "ProjectId" = ProjectId,
	"MezzanineNumber"=  MezzanineNumber,
     "FramelineNumber"=FramelineNumber , 
	 "AlltheSame"=AlltheSame, 
	 "Spacing1"  =Spacing1 , 
	 "Spacing2"=Spacing2, 
	 "Spacing3" =Spacing3, 
	 "Spacing4" = Spacing4, 
	 "Spacing5"=Spacing5, 
	 "Spacing6" =Spacing6 , 
	 "Spacing7"= Spacing7, 
	 "Spacing8"=Spacing8 , 
	 "Spacing9"= Spacing9 , 
	 "Spacing10"=Spacing10, 
	 "Spacing11"= Spacing11, 
	 "Spacing12" =Spacing12 , 
	 "Spacing13" = Spacing13, 
	 "Spacing14" =Spacing14, 
	 "Spacing15"=Spacing15, 
	 "Spacing16"=Spacing16 , 
	 "Spacing17" = Spacing17, 
	 "Spacing18"=Spacing18, 
	 "Spacing19"= Spacing19, 
	 "Spacing20"= Spacing20, 
	 "Spacing21"=Spacing21 , 
	 "Spacing22"=Spacing22, 
	 "Spacing23"=Spacing23, 
	 "Spacing24"= Spacing24, 
	 "Spacing25"=Spacing25, 
	 "Spacing26"=Spacing26 , 
	 "Spacing27" =Spacing27, 
	 "Spacing28"= Spacing28, 
	 "Spacing29"=Spacing29 , 
	 "Spacing30"=Spacing30, 
    "ForLongitudinal" = ForLongitudinal,
        "ModifiedBy" = UserId,
        "ModifiedDate" = CURRENT_TIMESTAMP,
        "IpAddress" = IpAddress
    WHERE
        "MezzanineSpacingId" = MezzanineSpacingId;
END ACCESSORIES_MezzanineSpacing_UPDATE;
/