CREATE OR REPLACE PROCEDURE abs_mdi."ACCESSORIES_MEZZANINES_CREATE" (
    BuildingNumber                          IN NUMBER,
    ProjectId                               IN NUMBER,
    MezzanineNumber                         IN NUMBER,
    JoistParallelToPurlins                  IN NUMBER,
    StartFrameline                          IN NUMBER,
    StopFrameline                           IN NUMBER,
    DistFromSW                              IN NUMBER,
    Width                                   IN NUMBER,
    OpenDistFromSw                          IN NUMBER,
    OpenDistFromFrameline                   IN NUMBER,
    OpenWidthAlongEw                        IN NUMBER,
    OpenLengthAlongSw                       IN NUMBER,
    Design                                  IN NUMBER,
    Beams                                   IN NUMBER,
    Deck                                    IN NUMBER,
    Joists                                  IN NUMBER,
    SupportColumns                          IN NUMBER,
    EdgeAngle                               IN NUMBER,
    FloorThickness                          IN NUMBER,
    FloorHeight                             IN NUMBER,
    FloorMaterial                           IN VARCHAR2,
    InsideClearBeams                        IN NUMBER,
    MaxBeamDepth                            IN NUMBER,
    InsideClearJoists                       IN NUMBER,
    MaxJoistDepth                           IN NUMBER,
    JoistShopcoat                           IN VARCHAR2,
    JoistWelded                             IN NUMBER,
    JoistSpacing                            IN NUMBER,
    DeckType                                IN VARCHAR2,
	DeckFinish		                        IN VARCHAR2,
	DeckFastened                            IN NUMBER,
	DeckIcboApproval                        IN NUMBER, 
	DeckClosure                             IN NUMBER, 
	LiveLoad                                IN NUMBER , 
	DeadLoad  								IN NUMBER, 
	CollateralLoad  						IN NUMBER, 
	PartitionLoad 							IN NUMBER , 
	QuoteNumber 							IN VARCHAR2 , 
	QuoteYear 								IN VARCHAR2 , 
	EstimatorInitials 						IN VARCHAR2 , 
	ExpiresOn 								IN VARCHAR2 , 
	Expired 								IN NUMBER , 
	NoVendor								IN NUMBER , 
	PriceStar 								IN NUMBER , 
	WeightStar 								IN NUMBER , 
	PriceBeams 								IN NUMBER , 
	WeightBeams								IN NUMBER , 
	PriceJoists								IN NUMBER , 
	WeightJoists 							IN NUMBER , 
	VendorJoists 							IN VARCHAR2 , 
	PriceDeck 								IN NUMBER , 
	WeightDeck 								IN NUMBER , 
	VendorDeck 								IN VARCHAR2 , 
	Vibration 								IN NUMBER , 
	DeckCoverage 							IN VARCHAR2 , 
	HumanActivity 							IN NUMBER , 
	MezzUse 								IN VARCHAR2 , 
	MezzColSpacingSet 						IN NUMBER , 
	StairwellWeight 						IN NUMBER , 
	ClearToRafter 							IN NUMBER , 
	LiveLoadReduction 						IN NUMBER , 
	AttachmentToSupport 					IN VARCHAR2 , 
	AttachmentToSidelap 					IN VARCHAR2 , 
	AttachmentByStarSupport 				IN NUMBER , 
	AttachmentByStarSidelap 				IN NUMBER , 
	JoistType 								IN VARCHAR2 , 
	JoistSpacingStandard 					IN NUMBER , 
	JoistSpacingSpecified 					IN VARCHAR2 , 
	IntMezzColumnType 						IN VARCHAR2 , 
	ColumnBaseType 							IN VARCHAR2 , 
	ColumnBaseHeight 						IN NUMBER , 
	JoistSpacingCustom  					IN NUMBER , 
	DeckDescription 						IN VARCHAR2 , 
	DeckFinishWidth 						IN VARCHAR2 , 
	DeckFinishType 							IN VARCHAR2 , 
	DeckFinishGauge 						IN VARCHAR2 , 
	DeckFinishFinish						IN VARCHAR2 , 
	HideWeightPrice 						IN NUMBER , 
    IpAddress     							IN VARCHAR2,
    OutputId   OUT  NUMBER
	) AS
    
    MezzanineCount NUMBER ;

BEGIN
            SELECT
            COUNT("MezzaninesId") into MezzanineCount
            FROM
            "EDSPrice_IO_Mezzanines"
            WHERE
            "BuildingNumber" = BuildingNumber
            AND "IsDelete" = 'N';
   INSERT INTO  "EDSPrice_IO_Mezzanines"  (
    "BuildingNumber" ,
    "ProjectId"    ,
    "MezzanineNumber"  ,
    "JoistParallelToPurlins"  ,
    "StartFrameline" ,
    "StopFrameline"  ,
    "DistFromSW" ,
    "Width"  ,
    "OpenDistFromSw"  ,
    "OpenDistFromFrameline"  ,
    "OpenWidthAlongEw" ,
    "OpenLengthAlongSw" ,
    "Design",
    "Beams",
    "Deck" ,
    "Joists" ,
    "SupportColumns",
     "EdgeAngle" ,
    "FloorThickness" ,
    "FloorHeight"  ,
    "FloorMaterial" ,
    "InsideClearBeams",
    "MaxBeamDepth"  ,
    "InsideClearJoists"  ,
     "MaxJoistDepth",
    "JoistShopcoat",
    "JoistWelded" ,
    "JoistSpacing"  ,
    "DeckType" ,
	"DeckFinish",
	"DeckFastened"  ,
	"DeckIcboApproval", 
	"DeckClosure", 
	"LiveLoad", 
	"DeadLoad" , 
	"CollateralLoad", 
	 "PartitionLoad"  , 
	 "QuoteNumber"  , 
	 "QuoteYear"  , 
	 "EstimatorInitials" , 
	 "ExpiresOn" , 
	 "Expired", 
	 "NoVendor" , 
	 "PriceStar" , 
	 "WeightStar"  , 
	 "PriceBeams"  , 
	 "WeightBeams"  , 
	 "PriceJoists" , 
    "WeightJoists"  , 
	 "VendorJoists"  , 
	 "PriceDeck" , 
	 "WeightDeck"  , 
	 "VendorDeck" , 
	 "Vibration"  , 
	 "DeckCoverage" , 
	 "HumanActivity" , 
	 "MezzUse"     , 
	 "MezzColSpacingSet"    , 
	 "StairwellWeight"    , 
	 "ClearToRafter"    , 
	 "LiveLoadReduction"     , 
	 "AttachmentToSupport"     , 
	 "AttachmentToSidelap"     , 
	 "AttachmentByStarSupport"   , 
	 "AttachmentByStarSidelap"    , 
	 "JoistType"    , 
	 "JoistSpacingStandard"     , 
	 "JoistSpacingSpecified"    , 
	 "IntMezzColumnType"    , 
	 "ColumnBaseType"     , 
	 "ColumnBaseHeight"   , 
	 "JoistSpacingCustom"     , 
	 "DeckDescription"     , 
	 "DeckFinishWidth"     , 
	 "DeckFinishType"    , 
	 "DeckFinishGauge"   , 
	 "DeckFinishFinish"    , 
	"HideWeightPrice"    , 
     "CreatedDate" ,
     "IpAddress" ,
     "IsDelete"
    ) 
    VALUES (  
    BuildingNumber ,
    ProjectId    ,
    MezzanineCount + 1,
    JoistParallelToPurlins  ,
    StartFrameline ,
    StopFrameline  ,
    DistFromSW ,
    Width  ,
    OpenDistFromSw  ,
    OpenDistFromFrameline  ,
    OpenWidthAlongEw ,
    OpenLengthAlongSw ,
    Design,
    Beams,
    Deck ,
    Joists ,
    SupportColumns ,
    EdgeAngle ,
    FloorThickness ,
    FloorHeight  ,
    FloorMaterial ,
    InsideClearBeams,
    MaxBeamDepth  ,
    InsideClearJoists  ,
    MaxJoistDepth ,
    JoistShopcoat,
    JoistWelded ,
    JoistSpacing  ,
    DeckType ,
	DeckFinish,
	DeckFastened  ,
	DeckIcboApproval, 
	DeckClosure, 
	LiveLoad, 
	DeadLoad , 
	CollateralLoad, 
	 PartitionLoad  , 
	 QuoteNumber  , 
	 QuoteYear  , 
	 EstimatorInitials , 
	 ExpiresOn , 
	 Expired, 
	 NoVendor , 
	 PriceStar , 
	 WeightStar  , 
	 PriceBeams  , 
	 WeightBeams  , 
	 PriceJoists , 
	 WeightJoists  , 
	 VendorJoists  , 
	 PriceDeck , 
	 WeightDeck  , 
	 VendorDeck , 
	 Vibration  , 
	 DeckCoverage , 
	 HumanActivity , 
	 MezzUse     , 
	 MezzColSpacingSet    , 
	 StairwellWeight    , 
	 ClearToRafter     , 
	 LiveLoadReduction     , 
	 AttachmentToSupport     , 
	 AttachmentToSidelap     , 
	 AttachmentByStarSupport    , 
	 AttachmentByStarSidelap    , 
	 JoistType    , 
	 JoistSpacingStandard     , 
	 JoistSpacingSpecified     , 
	 IntMezzColumnType    , 
	 ColumnBaseType     , 
	 ColumnBaseHeight   , 
	 JoistSpacingCustom     , 
	 DeckDescription     , 
	 DeckFinishWidth     , 
	 DeckFinishType    , 
	 DeckFinishGauge    , 
	 DeckFinishFinish    , 
	 HideWeightPrice     , 
      CURRENT_TIMESTAMP,
      IpAddress,
      'N'
    ) RETURNING  "MezzaninesId"  INTO OutputId;
END ACCESSORIES_Mezzanines_CREATE;
/