CREATE OR REPLACE PROCEDURE abs_mdi."ACCESSORYCANOPY_UPDATE" 
(
    AccessoriesCanopyId IN	NUMBER,
    BuildingNumber IN NUMBER,
    ProjectId IN NUMBER,
    Select_Elevation IN	VARCHAR2,
    StartColumn IN	NUMBER,
    StopColumn IN	NUMBER,
    CanopyType IN	VARCHAR2,
    Projection IN	NUMBER,
    Slope IN	NUMBER,
    Panel IN	VARCHAR2,
    SoffitPanelColor IN	VARCHAR2,
    SoffitGaudge IN	NUMBER,
    ReturnDownspouts IN	CHAR,
    Gutter IN	CHAR,
    RoofTieTrimColor IN	VARCHAR2,
    CanopyCornerTrimColor IN 	VARCHAR2,
    CanopySillCapTrimColor IN	VARCHAR2,
    SoffitTrimColor IN	VARCHAR2,
    SoffitPanelType IN	VARCHAR2,
    CanopyPanelColor IN	VARCHAR2,
    CanopyPanelGauge IN	NUMBER,
    CanopySSClipType IN	VARCHAR2,
    ThermalBlockType IN	VARCHAR2,
    ExtendRoofInsulation IN	CHAR,
    GutterType IN	NUMBER,
    GutterSize IN	NUMBER,
    DownspoutDrops IN	NUMBER,
    IncludeElbow IN	CHAR,
    DownspoutHeight IN	NUMBER,
    GutterColor IN	VARCHAR2,
    DownspoutColor IN	VARCHAR2,
    SoffitFramingClearance IN	NUMBER,
    HasSnowRetentionSystem IN	CHAR,
    IncludeSnowClipPerPanel IN	CHAR,
    SnowClipQuantity IN	NUMBER,
    ColorStripQuantity IN	NUMBER,
    RoofPanelType IN	VARCHAR2,
    ReverseRollSoffit IN	CHAR,
    ReverseRollFace IN CHAR,
    DistFromLeftCorner  IN	NUMBER,
    Length IN	NUMBER,
    HeightLocation IN	NUMBER,
    SoffitPanel IN	NUMBER,
    SoffitTrim IN	NUMBER,
    AtEave IN	CHAR,
    PanelFinish IN	VARCHAR2,
    CanopyFacingSpecial IN	NUMBER,
    CanopyFacingWeight IN	NUMBER,
    CanopyFacingDeflection IN	NUMBER,
    SoffitFacingSpecial IN	NUMBER,
    SoffitFacingWeight IN	NUMBER,
    SoffitFacingDeflection IN	NUMBER,
    Price IN	NUMBER,
    Weight IN	NUMBER,
    ErrorCode IN	NUMBER,
    PriceMBCI IN	NUMBER,
    WeightMBCI IN	NUMBER,
    DesignIndex IN	NUMBER,
    MainBuildingGutter IN	NUMBER,
    RoofSquareFeet IN	NUMBER,
    WallSquareFeet IN	NUMBER,
    SoffitSquareFeet IN	NUMBER,
    HeightOfFace IN	NUMBER,
    SoffitPanelColorValsparCode IN	VARCHAR2,
    SoffitPanelColorSpecialName IN	VARCHAR2,
    RoofTieTrimColorValsparCode IN	VARCHAR2,
    RoofTieTrimColorSpecialName IN	VARCHAR2,
    CanopyCornerTrimColorValsparCode IN	VARCHAR2,
    CanopyCornerTrimColorSpecialName IN	VARCHAR2,
    CanopySillTrimColorValsparCode IN	VARCHAR2,
    CanopySillTrimColorSpecialName IN	VARCHAR2,
    SoffitTrimColorValsparCode IN	VARCHAR2,
    SoffitTrimColorSpecialName IN	VARCHAR2,
    PanelColorValsparCode IN VARCHAR2,
    PanelColorSpecialName IN VARCHAR2,
    GutterColorValsparCode IN VARCHAR2,
    GutterColorSpecialName IN VARCHAR2,
    DownspoutColorValsparCode IN VARCHAR2,
    DownspoutColorSpecialName IN VARCHAR2,
    SoffitPanelColorValsparText IN	VARCHAR2,
    SoffitPanelColorValsparHashCode IN	VARCHAR2,
    RoofTieTrimColorValsparText IN	VARCHAR2,
    RoofTieTrimColorValsparHashCode IN	VARCHAR2,
    CanopyCornerTrimColorValsparText IN	VARCHAR2,
    CanopyCornerTrimColorValsparHashCode IN	VARCHAR2,
    CanopySillCapTrimColorValsparText IN	VARCHAR2,
    CanopySillCapTrimColorValsparHashCode IN	VARCHAR2,
    SoffitTrimColorValsparText IN	VARCHAR2,
    SoffitTrimColorValsparHashCode IN	VARCHAR2,
    PanelColorValsparText IN VARCHAR2,
    PanelColorValsparHashCode IN VARCHAR2,
    GutterColorValsparText IN VARCHAR2,
    GutterColorValsparHashCode IN VARCHAR2,
    DownspoutColorValsparText IN VARCHAR2,
    DownspoutColorValsparHashCode IN VARCHAR2,
    IncludeSagAngles IN	CHAR,
    SnowLoad IN	NUMBER,
    UserId IN NUMBER  ,
    IpAddress IN VARCHAR2,
    IsDelete IN VARCHAR2 DEFAULT 'N'
)
AS 
BEGIN
   UPDATE "Accessories_Canopy" SET
     	"Select_Elevation" = Select_Elevation,
    "StartColumn" = StartColumn,
    "StopColumn" = StopColumn,
    "CanopyType" = CanopyType,
    "Projection" = Projection,
    "Slope" = Slope,
    "Panel" = Panel,
    "SoffitPanelColor" = SoffitPanelColor,
    "SoffitGaudge" = SoffitGaudge,
    "ReturnDownspouts" = ReturnDownspouts,
    "Gutter" = Gutter,
    "RoofTieTrimColor" = RoofTieTrimColor,
    "CanopyCornerTrimColor" = CanopyCornerTrimColor,
    "CanopySillCapTrimColor" = CanopySillCapTrimColor,
    "SoffitTrimColor" = SoffitTrimColor,
    "SoffitPanelType" = SoffitPanelType,
    "CanopyPanelColor" = CanopyPanelColor,
    "CanopyPanelGauge" = CanopyPanelGauge,
    "CanopySSClipType" = CanopySSClipType,
    "ThermalBlockType" = ThermalBlockType,
    "ExtendRoofInsulation" = ExtendRoofInsulation,
    "GutterType" = GutterType,
    "GutterSize" = GutterSize,
    "DownspoutDrops" = DownspoutDrops,
    "IncludeElbow" = IncludeElbow,
    "DownspoutHeight" = DownspoutHeight,
    "GutterColor" = GutterColor,
    "DownspoutColor" = DownspoutColor,
    "SoffitFramingClearance" = SoffitFramingClearance,
    "HasSnowRetentionSystem" = HasSnowRetentionSystem,
    "IncludeSnowClipPerPanel" = IncludeSnowClipPerPanel,
    "SnowClipQuantity" = SnowClipQuantity,
    "ColorStripQuantity" = ColorStripQuantity,
    "RoofPanelType" = RoofPanelType,
    "ReverseRollSoffit" = ReverseRollSoffit,
    "ReverseRollFace" = ReverseRollFace,
    "Length" = Length,
    "HeightLocation" = HeightLocation,
    "SoffitPanel" = SoffitPanel,
    "SoffitTrim" = SoffitTrim,
    "AtEave"=AtEave,
    "PanelFinish"=PanelFinish,
    "CanopyFacingSpecial"=CanopyFacingSpecial,
    "CanopyFacingWeight"=CanopyFacingWeight,
    "CanopyFacingDeflection"=CanopyFacingDeflection,
    "SoffitFacingSpecial"=SoffitFacingSpecial,
    "SoffitFacingWeight"=SoffitFacingWeight,
    "SoffitFacingDeflection"=SoffitFacingDeflection,
    "Price"=Price,
    "Weight"=Weight,
    "ErrorCode"=ErrorCode,
    "PriceMBCI"=PriceMBCI,
    "WeightMBCI"=WeightMBCI,
    "DesignIndex"=DesignIndex,
    "MainBuildingGutter"=MainBuildingGutter,
    "RoofSquareFeet"=RoofSquareFeet,
    "WallSquareFeet"=WallSquareFeet,
    "SoffitSquareFeet"=SoffitSquareFeet,
    "HeightOfFace"=HeightOfFace,
    "SoffitPanelColorValsparCode"=SoffitPanelColorValsparCode,
    "SoffitPanelColorValsparHashCode"=SoffitPanelColorValsparHashCode,
    "RoofTieTrimColorValsparCode"=RoofTieTrimColorValsparCode,
    "RoofTieTrimColorSpecialName"=RoofTieTrimColorSpecialName,
    "CanopyCornerTrimColorValsparCode"=CanopyCornerTrimColorValsparCode,
    "CanopyCornerTrimColorSpecialName"=CanopyCornerTrimColorSpecialName,
    "CanopySillTrimColorValsparCode"=CanopySillTrimColorValsparCode,
    "CanopySillTrimColorSpecialName"=CanopySillTrimColorSpecialName,
    "SoffitTrimColorValsparCode"=SoffitTrimColorValsparCode,
    "SoffitTrimColorSpecialName"=SoffitTrimColorSpecialName,
    "PanelColorValsparCode"=PanelColorValsparCode,
    "PanelColorSpecialName"=PanelColorSpecialName,
    "GutterColorValsparCode"=GutterColorValsparCode,
    "GutterColorSpecialName"=GutterColorSpecialName,
    "DownspoutColorValsparCode"=DownspoutColorValsparCode,
    "DownspoutColorSpecialName"=DownspoutColorSpecialName,
    "SoffitPanelColorValsparText"=SoffitPanelColorValsparText,
    "SoffitPanelColorSpecialName"=SoffitPanelColorSpecialName,
    "RoofTieTrimColorValsparText"=RoofTieTrimColorValsparText,
    "RoofTieTrimColorValsparHashCode"=RoofTieTrimColorValsparHashCode,
    "CanopyCornerTrimColorValsparText"=CanopyCornerTrimColorValsparText,
    "CanopyCornerTrimColorValsparHashCode"=CanopyCornerTrimColorValsparHashCode,
    "CanopySillCapTrimColorValsparText"=CanopySillCapTrimColorValsparText,
    "CanopySillCapTrimColorValsparHashCode"=CanopySillCapTrimColorValsparHashCode,
    "SoffitTrimColorValsparText"=SoffitTrimColorValsparText,
    "SoffitTrimColorValsparHashCode"=SoffitTrimColorValsparHashCode,
    "PanelColorValsparText"=PanelColorValsparText,
    "PanelColorValsparHashCode"=PanelColorValsparHashCode,
    "GutterColorValsparText"=GutterColorValsparText,
    "GutterColorValsparHashCode"=GutterColorValsparHashCode,
    "DownspoutColorValsparText"=DownspoutColorValsparText,
    "DownspoutColorValsparHashCode"=DownspoutColorValsparHashCode,
    "IncludeSagAngles"=IncludeSagAngles,
    "IpAddress" = IpAddress,
    "ModifiedBy"=UserId, 
    "ModifiedDate"=CURRENT_TIMESTAMP,
    "IsDelete" = IsDelete,
    "DistFromLeftCorner"=DistFromLeftCorner,
    "SnowLoad"=SnowLoad,
    "ProjectId"=ProjectId
  WHERE "AccessoriesCanopyId"=AccessoriesCanopyId;
END ACCESSORYCANOPY_UPDATE;
/