CREATE OR REPLACE PROCEDURE abs_mdi."ACCESSORYLOUVERS_COPY" 
(  
    ProjectId IN	NUMBER,
    BuildingId IN	NUMBER,
    Quantity IN	NUMBER,
    Elevation IN	CHAR,
    BayNumber IN	NUMBER,
    SillHeight IN	NUMBER,
    HeaderHeight IN	NUMBER,
    Width IN	NUMBER,
    DistFromLeftCorner IN NUMBER,
    DistFromLeftCol IN	NUMBER,
    TrimColor IN	VARCHAR2,
    LouverColor IN 	VARCHAR2,
    SubFraming IN	NUMBER,
    Type IN	VARCHAR2,
    LouverSize IN	VARCHAR2,
    LocatedInLiner IN	CHAR,
    IncludeFramedOpening IN	CHAR,
    RunOfLouvers IN	CHAR,
    PartitionNumber IN	NUMBER,
    BracedBay IN	NUMBER,
    LouverColorValsparCode IN	VARCHAR2,
    LouverColorSpecialName IN	VARCHAR2,
    TrimColorValsparCode IN	VARCHAR2,
    TrimColorSpecialName IN	VARCHAR2,
    IpAddress IN	VARCHAR2,
    UserId IN NUMBER,
    OutputId OUT NUMBER
)
AS 
BEGIN
    INSERT INTO "Accessories_Louvers" 
    ( "ProjectId",
        "BuildingId",
        "Quantity",
        "Elevation",
        "BayNumber",
        "SillHeight",
        "HeaderHeight",
        "Width",
        "DistFromLeftCorner",
        "DistFromLeftCol",
        "TrimColor",
        "LouverColor",
        "SubFraming",
        "Type",
        "LouverSize",
        "LocatedInLiner",
        "IncludeFramedOpening",
        "RunOfLouvers",
        "PartitionNumber",
        "BracedBay",
        "LouverColorValsparCode",
        "LouverColorSpecialName",
        "TrimColorValsparCode",
        "TrimColorSpecialName",
        "IpAddress",
        "IsDelete",
        "CreatedBy",
        "CreatedDate"
    )
    VALUES
    ( ProjectId,
        BuildingId,
        Quantity,
        Elevation,
        BayNumber,
        SillHeight,
        HeaderHeight,
        Width,
        DistFromLeftCorner,
        DistFromLeftCol,
        TrimColor,
        LouverColor,
        SubFraming,
        Type,
        LouverSize,
        LocatedInLiner,
        IncludeFramedOpening,
        RunOfLouvers,
        PartitionNumber,
        BracedBay,
        LouverColorValsparCode,
        LouverColorSpecialName,
        TrimColorValsparCode,
        TrimColorSpecialName,
        IpAddress,
        'N',
		UserId,
		CURRENT_TIMESTAMP
    )
    RETURNING "LouverId" into OutputId;
END ACCESSORYLOUVERS_COPY;
/