CREATE OR REPLACE PROCEDURE abs_mdi."ACCESSORYFRAMEOPENING_COPY" 
(  
	BuildingNumber  IN  NUMBER,
	ProjectId  IN  NUMBER,
	Elevation  IN  CHAR,
	BayNumber  IN  NUMBER,
	Material  IN  VARCHAR2,
	Type  IN  VARCHAR2,
	Width  IN  NUMBER,
	Height  IN  NUMBER,
	DistFromLeftCorner  IN  NUMBER,
	DistFromLeftCol  IN  NUMBER,
	SillHeight  IN  NUMBER,
	HeaderHeight  IN  NUMBER,
	HeaderType  IN  VARCHAR2,
	JambType  IN  VARCHAR2,
	CeeDepth  IN  NUMBER,
	InsideFlangeWidth  IN  NUMBER,
	InsideFlangeThick  IN  NUMBER,
	OutsideFlangeWidth  IN  NUMBER,
	OutsideFlangeThick  IN  NUMBER,
	WebDepth  IN  NUMBER,
	WebThick  IN  NUMBER,
	DoubleJambs  IN  CHAR,
	FourSided  IN  CHAR,
	TrimOnly  IN  CHAR,
	PanelCredit  IN  CHAR,
	Clearance  IN  NUMBER,
	Weight  IN  NUMBER,
	Price  IN  NUMBER,
	IsPriced  IN  CHAR,
	ErrorCode  IN  NUMBER,
	ClosureTrim  IN  NUMBER,
	ClosureTrimSize  IN  NUMBER,
	ClosureTrimColor  IN  VARCHAR2,
	ClosureTrimColorValsparCode  IN  VARCHAR2,
	ClosureTrimColorSpecialName  IN  VARCHAR2,
	DoNotCutGirts  IN  CHAR,
	OverheadDoor  IN  CHAR,
	Quantity  IN  NUMBER,
	PreGalvanizedFraming  IN  CHAR,
	FullCoverHeadTrim  IN  CHAR,
	DoubleHeader  IN  CHAR,
	DoNotCutPanel  IN  CHAR,
	LocatedInLiner  IN  CHAR,
	LeftSteelLine  IN  CHAR,
	PartitionNumber  IN  NUMBER,
	ClipAttachment  IN  VARCHAR2,
	BracingBay  IN  NUMBER,
	IpAddress  IN  VARCHAR2,
	UserId  IN  NUMBER,
	OutputId  OUT  NUMBER
)
AS 
BEGIN
    INSERT INTO "Accessories_FramedOpening" 
    ( "BuildingNumber",
		"ProjectId",
		"Elevation",
		"BayNumber",
		"Material",
		"Type",
		"Width",
		"Height",
		"DistFromLeftCorner",
		"DistFromLeftCol",
		"SillHeight",
		"HeaderHeight",
		"HeaderType",
		"JambType",
		"CeeDepth",
		"InsideFlangeWidth",
		"InsideFlangeThick",
		"OutsideFlangeWidth",
		"OutsideFlangeThick",
		"WebDepth",
		"WebThick",
		"DoubleJambs",
		"FourSided",
		"TrimOnly",
		"PanelCredit",
		"Clearance",
		"Weight",
		"Price",
		"IsPriced",
		"ErrorCode",
		"ClosureTrim",
		"ClosureTrimSize",
		"ClosureTrimColor",
		"ClosureTrimColorValsparCode",
		"ClosureTrimColorSpecialName",
		"DoNotCutGirts",
		"OverheadDoor",
		"Quantity",
		"PreGalvanizedFraming",
		"FullCoverHeadTrim",
		"DoubleHeader",
		"DoNotCutPanel",
		"LocatedInLiner",
		"LeftSteelLine",
		"PartitionNumber",
		"ClipAttachment",
		"BracingBay",
		"IpAddress",
        "IsDelete",
        "CreatedBy",
        "CreatedDate"
    )
    VALUES
    (   BuildingNumber,
		ProjectId,
		Elevation,
		BayNumber,
		Material,
		Type,
		Width,
		Height,
		DistFromLeftCorner,
		DistFromLeftCol,
		SillHeight,
		HeaderHeight,
		HeaderType,
		JambType,
		CeeDepth,
		InsideFlangeWidth,
		InsideFlangeThick,
		OutsideFlangeWidth,
		OutsideFlangeThick,
		WebDepth,
		WebThick,
		DoubleJambs,
		FourSided,
		TrimOnly,
		PanelCredit,
		Clearance,
		Weight,
		Price,
		IsPriced,
		ErrorCode,
		ClosureTrim,
		ClosureTrimSize,
		ClosureTrimColor,
		ClosureTrimColorValsparCode,
		ClosureTrimColorSpecialName,
		DoNotCutGirts,
		OverheadDoor,
		Quantity,
		PreGalvanizedFraming,
		FullCoverHeadTrim,
		DoubleHeader,
		DoNotCutPanel,
		LocatedInLiner,
		LeftSteelLine,
		PartitionNumber,
		ClipAttachment,
		BracingBay,
		IpAddress,
        'N',
		UserId,
		CURRENT_TIMESTAMP
    )
    RETURNING "FramedOpeningId" into OutputId;
END ACCESSORYFRAMEOPENING_COPY;
/