CREATE OR REPLACE PROCEDURE abs_mdi."ACCESSORIES_WALLLINER_CREATE" 
(       
/*   Created By    Hiren Prajapati    
     Created Date  23-09-2021
     Description   This stored Procedure used to Insert Accessories_Liners.
*/
    --    LinerId IN  NUMBER,
   BuildingNumber IN  NUMBER,
   ProjectId      IN  NUMBER,
    --    Elevation,
    --    BayNumber,
    --    DistFromLeftCorner,
    --    DistFromLeftCol,
    FullHeight IN  NUMBER,
    Height IN  NUMBER,
    Length IN  NUMBER,
    PanelType IN  NUMBER,
    PanelGauge IN  NUMBER,
    PanelColor  IN  VARCHAR2,
    --    JambTrim,
    --    FramedOpeningTrim,
    --    CapTrim,
    --    ColTrim,
    --    BaseAngle,
    --    SheetAngle,
    --    BaseChannel,
    --    Weight,
    --    Price,
    --    IsPriced,
    --    ErrorCode,
    --    FlashColor,
    --    OptionalLinerFlash,
    BaseType  IN  VARCHAR2,
    CapTrimColor  IN  VARCHAR2,
    PurlinTrimColor  IN  VARCHAR2,
    InsideCornerTrimColor  IN  VARCHAR2,
    ColumnTieTrimColor  IN  VARCHAR2,
    --    RidgeTrimGauge,
    --    RidgeTrimFinish,
    --    RidgeTrimColor,
    --    RafterTieTrimGauge,
    --    RafterTieTrimFinish,
    --    RafterTieTrimColor,
    --    EaveToWallTrimGauge,
    --    EaveToWallTrimFinish,
    --    EaveToWallTrimColor,
    --    PanelFinish,
    --    Width,
    --    LinerCoverage,
    --    StartColumn,
    --    StopColumn,
    --    XFrom,
    --    XTo,
    --    YFrom,
    --    YTo,
    ReverseRoll  IN  VARCHAR2,
    --    WeightMBCI,
    --    PriceMBCI,
    --    TopTermination,
    --    PartitionNumber,
    FullLength IN  NUMBER,
    --    GirtNote,
    FastenerHeadFinish IN  NUMBER,
    FastenerLength IN  NUMBER,
    PanelColorValsparCode  IN  VARCHAR2,
    PanelColorSpecialName  IN  VARCHAR2,
    --    FlashColorValsparCode,
    --    FlashColorSpecialName,
    CapTrimColorValsparCode  IN  VARCHAR2,
    CapTrimColorSpecialName  IN  VARCHAR2,
    PurlinTrimColorValsparCode  IN  VARCHAR2,
    PurlinTrimColorSpecialName  IN  VARCHAR2,
    InsideCornerTrimColorValsparCode  IN  VARCHAR2,
    InsideCornerTrimColorSpecialName  IN  VARCHAR2,
    ColumnTieTrimColorValsparCode  IN  VARCHAR2,
    ColumnTieTrimColorSpecialName  IN  VARCHAR2,
    --    RidgeTrimColorValsparCode,
    --    RidgeTrimColorSpecialName,
    --    RafterTieTrimColorValsparCode,
    --    RafterTieTrimColorSpecialName,
    --    EaveToWallTrimColorValsparCode,
    --    EaveToWallTrimColorSpecialName,
    UserId IN  NUMBER,
    --    CreatedDate,
    --    ModifiedBy IN  NUMBER,
    --  ModifiedDate,
    IpAddress IN  VARCHAR,
    --    IsDelete,
    --    Qty IN  NUMBER,
    OutputId  OUT  NUMBER
)
AS 
BEGIN          
INSERT INTO "Accessories_Liners" (
--    "LinerId",
    "BuildingNumber",
    "ProjectId",
--    "Elevation",
--    "BayNumber",
--    "DistFromLeftCorner",
--    "DistFromLeftCol",
    "FullHeight",
    "Height",
    "Length",
    "PanelType",
    "PanelGauge",
    "PanelColor",
--    "JambTrim",
--    "FramedOpeningTrim",
--    "CapTrim",
--    "ColTrim",
--    "BaseAngle",
--    "SheetAngle",
--    "BaseChannel",
--    "Weight",
--    "Price",
--    "IsPriced",
--    "ErrorCode",
--    "FlashColor",
--    "OptionalLinerFlash",
    "BaseType",
    "CapTrimColor",
    "PurlinTrimColor",
    "InsideCornerTrimColor",
    "ColumnTieTrimColor",
--    "RidgeTrimGauge",
--    "RidgeTrimFinish",
--    "RidgeTrimColor",
--    "RafterTieTrimGauge",
--    "RafterTieTrimFinish",
--    "RafterTieTrimColor",
--    "EaveToWallTrimGauge",
--    "EaveToWallTrimFinish",
--    "EaveToWallTrimColor",
--    "PanelFinish",
--    "Width",
--    "LinerCoverage",
--    "StartColumn",
--    "StopColumn",
--    "XFrom",
--    "XTo",
--    "YFrom",
--    "YTo",
    "ReverseRoll",
--    "WeightMBCI",
--    "PriceMBCI",
--    "TopTermination",
--    "PartitionNumber",
    "FullLength",
--    "GirtNote",
    "FastenerHeadFinish",
    "FastenerLength",
    "PanelColorValsparCode",
    "PanelColorSpecialName",
--    "FlashColorValsparCode",
--    "FlashColorSpecialName",
    "CapTrimColorValsparCode",
    "CapTrimColorSpecialName",
    "PurlinTrimColorValsparCode",
    "PurlinTrimColorSpecialName",
    "InsideCornerTrimColorValsparCode",
    "InsideCornerTrimColorSpecialName",
    "ColumnTieTrimColorValsparCode",
    "ColumnTieTrimColorSpecialName",
--    "RidgeTrimColorValsparCode",
--    "RidgeTrimColorSpecialName",
--    "RafterTieTrimColorValsparCode",
--    "RafterTieTrimColorSpecialName",
--    "EaveToWallTrimColorValsparCode",
--    "EaveToWallTrimColorSpecialName",
   "CreatedBy",
   "CreatedDate",
--    "ModifiedBy",
--    "ModifiedDate",
   "IpAddress"
--    "IsDelete",
--    "Qty"
) VALUES (
    --    LinerId,
    BuildingNumber,
    ProjectId,
    --    Elevation,
    --    BayNumber,
    --    DistFromLeftCorner,
    --    DistFromLeftCol,
    FullHeight,
    Height,
    Length,
    PanelType,
    PanelGauge,
    PanelColor,
    --    JambTrim,
    --    FramedOpeningTrim,
    --    CapTrim,
    --    ColTrim,
    --    BaseAngle,
    --    SheetAngle,
    --    BaseChannel,
    --    Weight,
    --    Price,
    --    IsPriced,
    --    ErrorCode,
    --    FlashColor,
    --    OptionalLinerFlash,
    BaseType,
    CapTrimColor,
    PurlinTrimColor,
    InsideCornerTrimColor,
    ColumnTieTrimColor,
    --    RidgeTrimGauge,
    --    RidgeTrimFinish,
    --    RidgeTrimColor,
    --    RafterTieTrimGauge,
    --    RafterTieTrimFinish,
    --    RafterTieTrimColor,
    --    EaveToWallTrimGauge,
    --    EaveToWallTrimFinish,
    --    EaveToWallTrimColor,
    --    PanelFinish,
    --    Width,
    --    LinerCoverage,
    --    StartColumn,
    --    StopColumn,
    --    XFrom,
    --    XTo,
    --    YFrom,
    --    YTo,
    ReverseRoll,
    --    WeightMBCI,
    --    PriceMBCI,
    --    TopTermination,
    --    PartitionNumber,
    FullLength,
    --    GirtNote,
    FastenerHeadFinish,
    FastenerLength,
    PanelColorValsparCode,
    PanelColorSpecialName,
    --    FlashColorValsparCode,
    --    FlashColorSpecialName,
    CapTrimColorValsparCode,
    CapTrimColorSpecialName,
    PurlinTrimColorValsparCode,
    PurlinTrimColorSpecialName,
    InsideCornerTrimColorValsparCode,
    InsideCornerTrimColorSpecialName,
    ColumnTieTrimColorValsparCode,
    ColumnTieTrimColorSpecialName,
    --    RidgeTrimColorValsparCode,
    --    RidgeTrimColorSpecialName,
    --    RafterTieTrimColorValsparCode,
    --    RafterTieTrimColorSpecialName,
    --    EaveToWallTrimColorValsparCode,
    --    EaveToWallTrimColorSpecialName,
    UserId,
    CURRENT_TIMESTAMP,
    --    ModifiedBy,
    --    ModifiedDate,
    IpAddress
    --    IsDelete,
    --    Qty 
) RETURNING "LinerId" INTO OutputId;
END ACCESSORIES_WALLLINER_CREATE;
/