CREATE OR REPLACE PROCEDURE abs_mdi."ACCESSORIES_RUBBERPIPEFLASH_SIZE_SELECT" 
(
Output_Data OUT SYS_REFCURSOR
)
AS 
BEGIN
OPEN Output_Data FOR 
SELECT
    "Id",
    "Size"
FROM
    "Accessories_RubberPipeFlash_Size";
END ACCESSORIES_RUBBERPIPEFLASH_SIZE_SELECT;
/