CREATE OR REPLACE PROCEDURE abs_mdi."ACCESORIES_MEZZANINES_SELECT" (
    MezzaninesId    IN   NUMBER,
    Mezzanines_Data  OUT  SYS_REFCURSOR
) AS
BEGIN
    OPEN Mezzanines_Data FOR SELECT
     "MezzaninesId",
    "BuildingNumber",
	"ProjectId",
    "MezzanineNumber"  ,
    "JoistParallelToPurlins"  ,
    "StartFrameline" ,
    "StopFrameline"  ,
    "DistFromSW" ,
   "Width"  ,
    "OpenDistFromSw"  ,
    "OpenDistFromFrameline"  ,
    "OpenWidthAlongEw" ,
    "OpenLengthAlongSw" ,
    "Design",
    "Beams",
    "Deck" ,
    "Joists" ,
    "SupportColumns",
   "EdgeAngle" ,
    "FloorThickness" ,
    "FloorHeight"  ,
    "FloorMaterial" ,
    "InsideClearBeams",
    "MaxBeamDepth"  ,
    "InsideClearJoists"  ,
   "MaxJoistDepth",
    "JoistShopcoat",
    "JoistWelded" ,
    "JoistSpacing"  ,
    "DeckType" ,
	"DeckFinish",
	"DeckFastened"  ,
	"DeckIcboApproval", 
	"DeckClosure", 
	"LiveLoad", 
	"DeadLoad" , 
	"CollateralLoad", 
	 "PartitionLoad"  , 
	 "QuoteNumber"  , 
	 "QuoteYear"  , 
	 "EstimatorInitials" , 
	 "ExpiresOn" , 
	 "Expired", 
	 "NoVendor" , 
	 "PriceStar" , 
	 "WeightStar"  , 
	 "PriceBeams"  , 
	 "WeightBeams"  , 
	 "PriceJoists" , 
	"WeightJoists"  , 
	 "VendorJoists"  , 
	 "PriceDeck" , 
	 "WeightDeck"  , 
	 "VendorDeck" , 
	 "Vibration"  , 
	 "DeckCoverage" , 
	 "HumanActivity" , 
	 "MezzUse"     , 
	 "MezzColSpacingSet"    , 
	 "StairwellWeight"    , 
	 "ClearToRafter"    , 
	 "LiveLoadReduction"     , 
	 "AttachmentToSupport"     , 
	 "AttachmentToSidelap"     , 
	 "AttachmentByStarSupport"   , 
	 "AttachmentByStarSidelap"    , 
	 "JoistType"    , 
	 "JoistSpacingStandard"     , 
	 "JoistSpacingSpecified"    , 
	 "IntMezzColumnType"    , 
	 "ColumnBaseType"     , 
	 "ColumnBaseHeight"   , 
	 "JoistSpacingCustom"     , 
	 "DeckDescription"     , 
	 "DeckFinishWidth"     , 
	 "DeckFinishType"    , 
	 "DeckFinishGauge"   , 
	 "DeckFinishFinish"    , 
	"HideWeightPrice"    
 FROM
    "EDSPrice_IO_Mezzanines"
    WHERE
    "MezzaninesId" = MezzaninesId AND "IsDelete" = 'N';
END ACCESORIES_Mezzanines_SELECT ;
/