CREATE OR REPLACE PROCEDURE abs_mdi."Accessories_Wallliner_Update" (
    WallLinerId IN NUMBER,
    BuildingNumber   IN   NUMBER,
    ProjectId        IN   NUMBER,
    Length    IN   VARCHAR2,
    Height      IN   VARCHAR2,
    FullLength       IN   CHAR,
    FullHeight            IN   CHAR,
    PanelType        IN   NUMBER,
    PanelGauge       IN   NUMBER,
    ReverseRoll      IN   CHAR,
    PanelColor       IN   VARCHAR2,
    PanelColorValsparCode  IN   VARCHAR2,
    PanelColorSpecialName  IN   VARCHAR2,
    BaseType         IN   NUMBER,
    CapTrimColor         IN   VARCHAR2,
    CapTrimColorValsparCode       IN   VARCHAR2,
    CapTrimColorSpecialName       IN   VARCHAR2,
    PurlinTrimColor       IN   VARCHAR2,
    PurlinTrimColorValsparCode       IN   VARCHAR2,
    PurlinTrimColorSpecialName       IN   VARCHAR2,
    InsideCornerTrimColor           IN   VARCHAR2,
    InsideCornerTrimColorValsparCode          IN   VARCHAR2,
    InsideCornerTrimColorSpecialName      IN   VARCHAR2,
    ColumnTieTrimColor           IN   VARCHAR2,
    ColumnTieTrimColorValsparCode          IN   VARCHAR2,
    ColumnTieTrimColorSpecialName      IN   VARCHAR2,
    FastenerHeadFinish     IN   NUMBER,
    FastenerLength       IN   NUMBER,
    CreatedBy     IN   NUMBER,
    CreatedDate     IN   TIMESTAMP,
    ModifiedBy       IN   NUMBER,
    ModifiedDate     IN   TIMESTAMP,
    IpAddress     IN   VARCHAR2,
    IsDelete       IN   CHAR,
    Qty         IN   NUMBER) AS 
BEGIN
  UPDATE "Accessories_Liner_Wall"
    SET
    
        "BuildingNumber" = BuildingNumber,
        "ProjectId" = ProjectId,
        "Length" = Length,
        "Height" = Height,
        "FullLength" = FullLength,
        "FullHeight" = FullHeight,
        "PanelType" = PanelType,
        "PanelGauge" = PanelGauge,
        "ReverseRoll" = ReverseRoll,
        "PanelColor" = PanelColor,
        "PanelColorValsparCode" = PanelColorValsparCode,
        "PanelColorSpecialName" = PanelColorSpecialName,
        "BaseType" = BaseType,
        "CapTrimColor" = CapTrimColor,
        "CapTrimColorValsparCode" = CapTrimColorValsparCode,
        "CapTrimColorSpecialName" = CapTrimColorSpecialName,
        "PurlinTrimColor" = PurlinTrimColor,
        "PurlinTrimColorValsparCode" = PurlinTrimColorValsparCode,
        "PurlinTrimColorSpecialName" = PurlinTrimColorSpecialName,
        "InsideCornerTrimColor" = InsideCornerTrimColor,
        "InsideCornerTrimColorValsparCode" = InsideCornerTrimColorValsparCode,
        "InsideCornerTrimColorSpecialName" = InsideCornerTrimColorSpecialName,
        "ColumnTieTrimColor" = ColumnTieTrimColor,
        "ColumnTieTrimColorValsparCode" = ColumnTieTrimColorValsparCode,
        "ColumnTieTrimColorSpecialName" = ColumnTieTrimColorSpecialName,
        "FastenerHeadFinish" = FastenerHeadFinish,
        "FastenerLength" = FastenerLength,
        "CreatedBy" = CreatedBy,
        "CreatedDate" = CreatedDate,
        "ModifiedBy" = ModifiedBy,
        "ModifiedDate" = ModifiedDate,
        "IpAddress" = IpAddress,
        "IsDelete" = IsDelete,
        "Qty" = Qty
    WHERE
        "WallLinerId" = WallLinerId;
END "Accessories_Wallliner_Update";
/