CREATE OR REPLACE PROCEDURE abs_mdi."ACCESSORIES_ROOFLINER_UPDATE" (
RoofLinerId IN NUMBER,
    BuildingNumber   IN   NUMBER,
    ProjectId        IN   NUMBER,
    LinerCoverage    IN   NUMBER,
    StartColumn      IN   NUMBER,
    StopColumn       IN   NUMBER,
    XFrom            IN   VARCHAR2,
    XTo              IN   VARCHAR2,
    YFrom            IN   VARCHAR2,
    YTo              IN   VARCHAR2,
    PanelType        IN   NUMBER,
    PanelGauge       IN   NUMBER,
    ReverseRoll      IN   Varchar2,
    PanelColor       IN   VARCHAR2,
    PanelColorValsparCode  IN   VARCHAR2,
    PanelColorSpecialName  IN   VARCHAR2,
    RidgeTrimGauge         IN   NUMBER,
    RafterTieTrimGauge     IN   NUMBER,
    EaveToWallTrimGauge    IN   NUMBER,
    RidgeTrimColor         IN   VARCHAR2,
    RidgeTrimColorSpecialName       IN   VARCHAR2,
    RidgeTrimColorValsparCode       IN   VARCHAR2,
    EaveToWallTrimColor       IN   VARCHAR2,
    EaveToWallTrimColorValsparCode       IN   VARCHAR2,
    EaveToWallTrimColorSpecialName       IN   VARCHAR2,
    RafterTieTrimColor           IN   VARCHAR2,
    RafterTieTrimColorValsparCode          IN   VARCHAR2,
    RafterTieTrimColorSpecialName      IN   VARCHAR2,
    FastenerHeadFinish     IN   NUMBER,
    FastenerLength       IN   NUMBER,
    PanelFinish          IN   VARCHAR2,
    RidgeTrimFinish          IN   VARCHAR2,
    RafterTieTrimFinish          IN   VARCHAR2,
    EaveToWallTrimFinish          IN   VARCHAR2,
    ModifiedBy       IN   NUMBER,
    IpAddress     IN   VARCHAR2,
    Qty         IN   NUMBER) AS 
BEGIN
    UPDATE "Accessories_Liners"
    SET
    
        "BuildingNumber" = BuildingNumber,
        "ProjectId" = ProjectId,
        "LinerCoverage" = LinerCoverage,
        "StartColumn" = StartColumn,
        "StopColumn" = StopColumn,
        "XFrom" = XFrom,
        "XTo" = XTo,
        "YFrom" = YFrom,
        "YTo" = YTo,
        "PanelType" = PanelType,
        "PanelGauge" = PanelGauge,
        "ReverseRoll" = ReverseRoll,
        "PanelColor" = PanelColor,
        "PanelColorValsparCode" = PanelColorValsparCode,
        "PanelColorSpecialName" = PanelColorSpecialName,
        "RidgeTrimGauge" = RidgeTrimGauge,
        "RafterTieTrimGauge" = RafterTieTrimGauge,
        "EaveToWallTrimGauge" = EaveToWallTrimGauge,
        "RidgeTrimColor" = RidgeTrimColor,
        "RidgeTrimColorSpecialName" = RidgeTrimColorSpecialName,
        "RidgeTrimColorValsparCode" = RidgeTrimColorValsparCode,
        "EaveToWallTrimColor" = EaveToWallTrimColor,
        "EaveToWallTrimColorValsparCode" = EaveToWallTrimColorValsparCode,
        "EaveToWallTrimColorSpecialName" = EaveToWallTrimColorSpecialName,
        "RafterTieTrimColor" = RafterTieTrimColor,
        "RafterTieTrimColorValsparCode" = RafterTieTrimColorValsparCode,
        "RafterTieTrimColorSpecialName" = RafterTieTrimColorSpecialName,
        "FastenerHeadFinish" = FastenerHeadFinish,
        "FastenerLength" = FastenerLength,
        "PanelFinish" = PanelFinish,
        "RidgeTrimFinish" = RidgeTrimFinish,
        "RafterTieTrimFinish" = RafterTieTrimFinish,
        "EaveToWallTrimFinish" = EaveToWallTrimFinish,
        "ModifiedBy" = ModifiedBy,
        "ModifiedDate" = CURRENT_TIMESTAMP,
        "IpAddress" = IpAddress,
        "Qty" = Qty
    WHERE
        "LinerId" = RoofLinerId;
END ACCESSORIES_ROOFLINER_UPDATE;
/