CREATE OR REPLACE PROCEDURE abs_mdi."ACCESSORIES_FACADE_CREATE" (
/*   Created By    Dipali Patel    
     Created Date  25-08-2021
     Description   This stored Procedure used to Insert Accesories_Facade.
*/
    ProjectId	                    IN NUMBER,
    BuildingInformationId	        IN NUMBER,
    Elevation	                    IN VARCHAR2,
    StartCol	                    IN NUMBER,
    StopCol	                        IN NUMBER,
    DistFromLeftCorner	            IN NUMBER,
    Length	                        IN NUMBER,
    Type	                        IN VARCHAR2,
    Projection	                    IN NUMBER,
    Height	                        IN NUMBER,
    Gutter	                        IN CHAR,
    Slant	                        IN NUMBER,
    PanelType	                    IN VARCHAR2,
    PanelGauge	                    IN NUMBER,
    PanelFinish	                    IN VARCHAR2,
    SoffitPanelType	                IN VARCHAR2,
    SoffitPanelGauge	            IN NUMBER,
    SoffitPanelFinish	            IN VARCHAR2,
    FacadePanel	                    IN CHAR,
    SoffitPanel	                    IN CHAR,
    SoffitElevation	                IN NUMBER,
    BackPanelType	                IN VARCHAR2,
    BackPanelGauge	                IN NUMBER,
    BackPanelColor	                IN VARCHAR2,
    SillCapTrim	                    IN VARCHAR2,
    CornerTrim	                    IN VARCHAR2,
    SoffitTrim	                    IN VARCHAR2,
    FacadeFacingSpecial	            IN NUMBER,
    FacadeFacingWeight	            IN NUMBER,
    FacadeFacingDeflection	        IN NUMBER,
    SoffitFacingSpecial	            IN NUMBER,
    SoffitFacingWeight	            IN NUMBER,
    SoffitFacingDeflection	        IN NUMBER,
    ReverseRollFace	                IN NUMBER,
    ReverseRollBack	                IN NUMBER,
    ReverseRollSoffit	            IN NUMBER,
    PanelFinishValsparCode	        IN VARCHAR2,
    PanelFinishSpecialName	        IN VARCHAR2,
    SoffitPanelFinishValsparCode	IN VARCHAR2,
    SoffitPanelFinishSpecialName	IN VARCHAR2,
    BackPanelColorValsparCode	    IN VARCHAR2,
    BackPanelColorSpecialName	    IN VARCHAR2,
    SillCapTrimValsparCode	        IN VARCHAR2,
    SillCapTrimSpecialName	        IN VARCHAR2,
    CornerTrimValsparCode	        IN VARCHAR2,
    CornerTrimSpecialName	        IN VARCHAR2,
    SoffitTrimValsparCode	        IN VARCHAR2,
    SoffitTrimSpecialName	        IN VARCHAR2,
    UserId                          IN NUMBER DEFAULT NULL,
    IpAddress                       IN VARCHAR2,
    OutputId                        OUT NUMBER
) AS
BEGIN
    INSERT INTO "Accessories_Facade" (
        "ProjectId",
        "BuildingInformationId",
        "Elevation",
        "StartCol",
        "StopCol",
        "DistFromLeftCorner",
        "Length",
        "Type",
        "Projection",
        "Height",
        "Gutter",
        "Slant",
        "PanelType",
        "PanelGauge",
        "PanelFinish",
        "SoffitPanelType",
        "SoffitPanelGauge",
        "SoffitPanelFinish",
        "FacadePanel",
        "SoffitPanel",
        "SoffitElevation",
        "BackPanelType",
        "BackPanelGauge",
        "BackPanelColor",
        "SillCapTrim",
        "CornerTrim",
        "SoffitTrim",
        "FacadeFacingSpecial",
        "FacadeFacingWeight",
        "FacadeFacingDeflection",
        "SoffitFacingSpecial",
        "SoffitFacingWeight",
        "SoffitFacingDeflection",
        "ReverseRollFace",
        "ReverseRollBack",
        "ReverseRollSoffit",
        "PanelFinishValsparCode",
        "PanelFinishSpecialName",
        "SoffitPanelFinishValsparCode",
        "SoffitPanelFinishSpecialName",
        "BackPanelColorValsparCode",
        "BackPanelColorSpecialName",
        "SillCapTrimValsparCode",
        "SillCapTrimSpecialName",
        "CornerTrimValsparCode",
        "CornerTrimSpecialName",
        "SoffitTrimValsparCode",
        "SoffitTrimSpecialName",
        "IsDelete",
        "CreatedBy",
        "CreatedDate",
        "IpAddress"
            ) 
    VALUES (
        ProjectId,
        BuildingInformationId,
        Elevation,
        StartCol,
        StopCol,
        DistFromLeftCorner,
        Length,
        Type,
        Projection,
        Height,
        Gutter,
        Slant,
        PanelType,
        PanelGauge,
        PanelFinish,
        SoffitPanelType,
        SoffitPanelGauge,
        SoffitPanelFinish,
        FacadePanel,
        SoffitPanel,
        SoffitElevation,
        BackPanelType,
        BackPanelGauge,
        BackPanelColor,
        SillCapTrim,
        CornerTrim,
        SoffitTrim,
        FacadeFacingSpecial,
        FacadeFacingWeight,
        FacadeFacingDeflection,
        SoffitFacingSpecial,
        SoffitFacingWeight,
        SoffitFacingDeflection,
        ReverseRollFace,
        ReverseRollBack,
        ReverseRollSoffit,
        PanelFinishValsparCode,
        PanelFinishSpecialName,
        SoffitPanelFinishValsparCode,
        SoffitPanelFinishSpecialName,
        BackPanelColorValsparCode,
        BackPanelColorSpecialName,
        SillCapTrimValsparCode,
        SillCapTrimSpecialName,
        CornerTrimValsparCode,
        CornerTrimSpecialName,
        SoffitTrimValsparCode,
        SoffitTrimSpecialName,
        'N',
        UserId,
        CURRENT_TIMESTAMP,
        IpAddress
    ) RETURNING "FacadeId" INTO OutputId;
END ACCESSORIES_FACADE_CREATE;
/