CREATE OR REPLACE PROCEDURE abs_mdi."ACCESSORIES_WALLLINER_UPDATE" 
( 
/*   Created By    Hiren Prajapati    
     Created Date  23-09-2021
     Description   This stored Procedure used to Update Wallliner.
*/     
   LinerId IN  NUMBER,
   BuildingNumber IN  NUMBER,
   ProjectId IN  NUMBER,
    --    Elevation,
    --    BayNumber,
    --    DistFromLeftCorner,
    --    DistFromLeftCol,
    FullHeight IN  NUMBER,
    Height IN  NUMBER,
    Length IN  NUMBER,
    PanelType IN  NUMBER,
    PanelGauge IN  NUMBER,
    PanelColor  IN  VARCHAR2,
    --    JambTrim,
    --    FramedOpeningTrim,
    --    CapTrim,
    --    ColTrim,
    --    BaseAngle,
    --    SheetAngle,
    --    BaseChannel,
    --    Weight,
    --    Price,
    --    IsPriced,
    --    ErrorCode,
    --    FlashColor,
    --    OptionalLinerFlash,
    BaseType  IN  VARCHAR2,
    CapTrimColor  IN  VARCHAR2,
    PurlinTrimColor  IN  VARCHAR2,
    InsideCornerTrimColor  IN  VARCHAR2,
    ColumnTieTrimColor  IN  VARCHAR2,
    --    RidgeTrimGauge,
    --    RidgeTrimFinish,
    --    RidgeTrimColor,
    --    RafterTieTrimGauge,
    --    RafterTieTrimFinish,
    --    RafterTieTrimColor,
    --    EaveToWallTrimGauge,
    --    EaveToWallTrimFinish,
    --    EaveToWallTrimColor,
    --    PanelFinish,
    --    Width,
    --    LinerCoverage,
    --    StartColumn,
    --    StopColumn,
    --    XFrom,
    --    XTo,
    --    YFrom,
    --    YTo,
    ReverseRoll  IN  VARCHAR2,
    --    WeightMBCI,
    --    PriceMBCI,
    --    TopTermination,
    --    PartitionNumber,
    FullLength IN  NUMBER,
    --    GirtNote,
    FastenerHeadFinish IN  NUMBER,
    FastenerLength IN  NUMBER,
    PanelColorValsparCode  IN  VARCHAR2,
    PanelColorSpecialName  IN  VARCHAR2,
    --    FlashColorValsparCode,
    --    FlashColorSpecialName,
    CapTrimColorValsparCode  IN  VARCHAR2,
    CapTrimColorSpecialName  IN  VARCHAR2,
    PurlinTrimColorValsparCode  IN  VARCHAR2,
    PurlinTrimColorSpecialName  IN  VARCHAR2,
    InsideCornerTrimColorValsparCode  IN  VARCHAR2,
    InsideCornerTrimColorSpecialName  IN  VARCHAR2,
    ColumnTieTrimColorValsparCode  IN  VARCHAR2,
    ColumnTieTrimColorSpecialName  IN  VARCHAR2,
    --    RidgeTrimColorValsparCode,
    --    RidgeTrimColorSpecialName,
    --    RafterTieTrimColorValsparCode,
    --    RafterTieTrimColorSpecialName,
    --    EaveToWallTrimColorValsparCode,
    --    EaveToWallTrimColorSpecialName,
    --    CreatedBy,
    --    CreatedDate,
    UserId IN  NUMBER,
    --  ModifiedDate,
    IpAddress IN  VARCHAR
    --    IsDelete,
    --    Qty IN  NUMBER,
)
AS 
BEGIN
UPDATE "Accessories_Liners" SET   
--    "LinerId" = LinerId,
    "BuildingNumber" = BuildingNumber,
    "ProjectId" = ProjectId,
--    "Elevation",
--    "BayNumber",
--    "DistFromLeftCorner",
--    "DistFromLeftCol",
    "FullHeight" = FullHeight,
    "Height" = Height,
    "Length" = Length,
    "PanelType" = PanelType,
    "PanelGauge" = PanelGauge,
    "PanelColor" = PanelColor,
--    "JambTrim",
--    "FramedOpeningTrim",
--    "CapTrim",
--    "ColTrim",
--    "BaseAngle",
--    "SheetAngle",
--    "BaseChannel",
--    "Weight",
--    "Price",
--    "IsPriced",
--    "ErrorCode",
--    "FlashColor",
--    "OptionalLinerFlash",
    "BaseType" = BaseType,
    "CapTrimColor" = CapTrimColor,
    "PurlinTrimColor" = PurlinTrimColor,
    "InsideCornerTrimColor" = InsideCornerTrimColor,
    "ColumnTieTrimColor" = ColumnTieTrimColor,
--    "RidgeTrimGauge",
--    "RidgeTrimFinish",
--    "RidgeTrimColor",
--    "RafterTieTrimGauge",
--    "RafterTieTrimFinish",
--    "RafterTieTrimColor",
--    "EaveToWallTrimGauge",
--    "EaveToWallTrimFinish",
--    "EaveToWallTrimColor",
--    "PanelFinish",
--    "Width",
--    "LinerCoverage",
--    "StartColumn",
--    "StopColumn",
--    "XFrom",
--    "XTo",
--    "YFrom",
--    "YTo",
    "ReverseRoll" = ReverseRoll,
--    "WeightMBCI",
--    "PriceMBCI",
--    "TopTermination",
--    "PartitionNumber",
    "FullLength" = FullLength,
--    "GirtNote",
    "FastenerHeadFinish" = FastenerHeadFinish,
    "FastenerLength" = FastenerLength,
    "PanelColorValsparCode" = PanelColorValsparCode,
    "PanelColorSpecialName" = PanelColorSpecialName,
--    "FlashColorValsparCode",
--    "FlashColorSpecialName",
    "CapTrimColorValsparCode" = CapTrimColorValsparCode,
    "CapTrimColorSpecialName" = CapTrimColorSpecialName,
    "PurlinTrimColorValsparCode" = PurlinTrimColorValsparCode,
    "PurlinTrimColorSpecialName" = PurlinTrimColorSpecialName,
    "InsideCornerTrimColorValsparCode" = InsideCornerTrimColorValsparCode,
    "InsideCornerTrimColorSpecialName" = InsideCornerTrimColorSpecialName,
    "ColumnTieTrimColorValsparCode" = ColumnTieTrimColorValsparCode,
    "ColumnTieTrimColorSpecialName" = ColumnTieTrimColorSpecialName,
--    "RidgeTrimColorValsparCode",
--    "RidgeTrimColorSpecialName",
--    "RafterTieTrimColorValsparCode",
--    "RafterTieTrimColorSpecialName",
--    "EaveToWallTrimColorValsparCode",
--    "EaveToWallTrimColorSpecialName",
--    "CreatedBy",
--    "CreatedDate",
    "ModifiedBy" = UserId,
    "ModifiedDate" = CURRENT_TIMESTAMP,
    "IpAddress" = IpAddress
--    "IsDelete",
--    "Qty"
 WHERE "LinerId" = LinerId;    
END ACCESSORIES_WALLLINER_UPDATE;
/