CREATE OR REPLACE PROCEDURE abs_mdi."ACCESORIES_CRANES_INSERT" (
/*   Created By    Meet Kaneriya    
     Created Date  08-11-2021
     Description   This stored Procedure used to Insert Accesories_Cranes.
*/
    ProjectId	                                    IN NUMBER,
    BuildingId	                                    IN NUMBER,
    StartFrameline	                                IN VARCHAR2,
    StopFrameLine	                                IN NUMBER,
    SType	                                        IN VARCHAR2,
    Control	                                        IN VARCHAR2,
    Quantity	                                    IN NUMBER,
    Tonnage1	                                    IN NUMBER,
    Tonnage2	                                    IN NUMBER,
    CraneClass	                                    IN VARCHAR2,
    Brackets	                                    IN CHAR,
    RunwayBeam	                                    IN CHAR,
    Rail	                                        IN CHAR,
    RoofSupportBeams	                            IN CHAR,
    SeperateSupportCol	                            IN CHAR,
    Stops	                                        IN CHAR,
    Bracing	                                        IN CHAR,
    NameBrand	                                    IN VARCHAR2,
    GirderType	                                    IN VARCHAR2,
    BridgeWeight1	                                IN NUMBER,
    BridgeWeight2	                                IN NUMBER,
    WheelSpacing1	                                IN NUMBER,
    WheelSpacing2	                                IN NUMBER,
    HoistWeight1	                                IN NUMBER,
    HoistWeight2	                                IN NUMBER,
    BracketLength	                                IN NUMBER,
    RunwayBeamSize	                                IN NUMBER,
    DistanceBetweenCranes	                        IN NUMBER,
    CenterlineOfRunwayBeamToSteelline	            IN NUMBER,
    CenterlineToCenterlineOfRails	                IN NUMBER,
    ColBaseToTopOfRail	                            IN NUMBER,
    ClearanceFromTopRailToBottomRafter	            IN NUMBER,
    ClearanceFromRailToInsideFlangeCol	            IN NUMBER,
    ManufacturerRailSize	                        IN NUMBER,
    TruckWheelDiameter	                            IN NUMBER,
    VerticalDeflection	                            IN NUMBER,
    HorizontalDeflection	                        IN NUMBER,
    FutureLineStart1	                            IN NUMBER,
    FutureLinestart2	                            IN NUMBER,
    DistanceToBack	                                IN NUMBER,
    SteelYield	                                    IN NUMBER,
    RailWeight	                                    IN NUMBER,
    CecoStandard	                                IN NUMBER,
    ModuleNumber	                                IN NUMBER,
    UsingMfgCraneData	                            IN NUMBER,
    AuxiliaryHoist1                                 IN NUMBER,
    AuxiliaryHoist2                                 IN NUMBER,
    TrolleyType                                     IN VARCHAR2,
    HoistType                                       IN VARCHAR2,
    UserAccept                                      IN NUMBER,
    MinimumHookDistance                             IN NUMBER,
    LeftOverhang1                                   IN NUMBER,
    LeftOverhang2                                   IN NUMBER,
    RightOverhang1                                  IN NUMBER,
    RightOverhang2                                  IN NUMBER,
    CraneNumber1                                    IN NUMBER,
    CraneNumber2                                    IN NUMBER,
    UserId                                          IN NUMBER DEFAULT NULL,
    IpAddress                                       IN VARCHAR2,
    OutputId                                        OUT NUMBER
) AS 
BEGIN

INSERT INTO "Accessories_Cranes" (
        "ProjectId",
        "BuildingId",
        "StartFrameline",
        "StopFrameLine",
        "SType",
        "Control",
        "Quantity",
        "Tonnage1",
        "Tonnage2",
        "CraneClass",
        "Brackets",
        "RunwayBeam",
        "Rail",
        "RoofSupportBeams",
        "SeperateSupportCol",
        "Stops",
        "Bracing",
        "NameBrand",
        "GirderType",
        "BridgeWeight1",
        "BridgeWeight2",
        "WheelSpacing1",
        "WheelSpacing2",
        "HoistWeight1",
        "HoistWeight2",
        "BracketLength",
        "RunwayBeamSize",
        "DistanceBetweenCranes",
        "CenterlineOfRunwayBeamToSteelline",
        "CenterlineToCenterlineOfRails",
        "ColBaseToTopOfRail",
        "ClearanceFromTopRailToBottomRafter",
        "ClearanceFromRailToInsideFlangeCol",
        "ManufacturerRailSize",
        "TruckWheelDiameter",
        "VerticalDeflection",
        "HorizontalDeflection",
        "FutureLineStart1",
        "FutureLinestart2",
        "DistanceToBack",
        "SteelYield",
        "RailWeight",
        "CecoStandard",
        "ModuleNumber",
        "UsingMfgCraneData",
        "AuxiliaryHoist1",
        "AuxiliaryHoist2",
        "TrolleyType",
        "HoistType",
        "UserAccept",
        "MinimumHookDistance",
        "LeftOverhang1",
        "LeftOverhang2",
        "RightOverhang1",
        "RightOverhang2",
        "CraneNumber1",
        "CraneNumber2",
        "IsDelete",
        "CreatedBy",
        "CreatedDate",
        "IpAddress"
            ) 
    VALUES (
        ProjectId,	                                    
        BuildingId,	                                   
        StartFrameline,	                            
        StopFrameLine,	                             
        SType,	                                       
        Control,	                                        
        Quantity,	                                  
        Tonnage1,	                                   
        Tonnage2,	                                    
        CraneClass,	                                   
        Brackets,	                                    
        RunwayBeam,	                                    
        Rail,	                                       
        RoofSupportBeams,	                           
        SeperateSupportCol,	                          
        Stops,	                                        
        Bracing,	                                       
        NameBrand,	                                    
        GirderType,	                                    
        BridgeWeight1,	                                
        BridgeWeight2,	                               
        WheelSpacing1,	                               
        WheelSpacing2,	                                
        HoistWeight1,	                                
        HoistWeight2,	                               
        BracketLength,	                               
        RunwayBeamSize,	                                
        DistanceBetweenCranes,	                      
        CenterlineOfRunwayBeamToSteelline,	           
        CenterlineToCenterlineOfRails,	                
        ColBaseToTopOfRail,	                           
        ClearanceFromTopRailToBottomRafter,	            
        ClearanceFromRailToInsideFlangeCol,	            
        ManufacturerRailSize,	                      
        TruckWheelDiameter,	                           
        VerticalDeflection,	                            
        HorizontalDeflection,	                       
        FutureLineStart1,	                            
        FutureLinestart2,	                            
        DistanceToBack,	                               
        SteelYield,	                                   
        RailWeight,	                                   
        CecoStandard,	                               
        ModuleNumber,	                              
        UsingMfgCraneData,	                            
        AuxiliaryHoist1,                               
        AuxiliaryHoist2,                                
        TrolleyType,                                     
        HoistType,                                       
        UserAccept,                                    
        MinimumHookDistance,                            
        LeftOverhang1,                                 
        LeftOverhang2,                                
        RightOverhang1,                                
        RightOverhang2, 
        CraneNumber1,
        CraneNumber2,
        'N',
        UserId,
        CURRENT_TIMESTAMP,
        IpAddress
    )RETURNING "CraneId" INTO OutputId;
   
END ACCESORIES_CRANES_INSERT;
/