CREATE OR REPLACE PROCEDURE abs_mdi."ACCESSORIES_ROOFLINER_CREATE" (
    BuildingNumber   IN   NUMBER,
    ProjectId        IN   NUMBER,
    LinerCoverage    IN   NUMBER,
    StartColumn      IN   NUMBER,
    StopColumn       IN   NUMBER,
    XFrom            IN   VARCHAR2,
    XTo              IN   VARCHAR2,
    YFrom            IN   VARCHAR2,
    YTo              IN   VARCHAR2,
    PanelType        IN   NUMBER,
    PanelGauge       IN   NUMBER,
    ReverseRoll      IN   VARCHAR2,
    PanelColor       IN   VARCHAR2,
    PanelColorValsparCode  IN   VARCHAR2,
    PanelColorSpecialName  IN   VARCHAR2,
    RidgeTrimGauge         IN   NUMBER,
    RafterTieTrimGauge     IN   NUMBER,
    EaveToWallTrimGauge    IN   NUMBER,
    RidgeTrimColor         IN   VARCHAR2,
    RidgeTrimColorSpecialName       IN   VARCHAR2,
    RidgeTrimColorValsparCode       IN   VARCHAR2,
    EaveToWallTrimColor       IN   VARCHAR2,
    EaveToWallTrimColorValsparCode       IN   VARCHAR2,
    EaveToWallTrimColorSpecialName       IN   VARCHAR2,
    RafterTieTrimColor           IN   VARCHAR2,
    RafterTieTrimColorValsparCode          IN   VARCHAR2,
    RafterTieTrimColorSpecialName      IN   VARCHAR2,
    FastenerHeadFinish     IN   NUMBER,
    FastenerLength       IN   NUMBER,  
    PanelFinish          IN   VARCHAR2,
    RidgeTrimFinish          IN   VARCHAR2,
    RafterTieTrimFinish          IN   VARCHAR2,
    EaveToWallTrimFinish          IN   VARCHAR2,
    CreatedBy     IN   NUMBER,
    IpAddress     IN   VARCHAR2,
    OutputId   OUT  NUMBER) AS
BEGIN
   INSERT INTO "Accessories_Liners" (
    "BuildingNumber",
    "ProjectId",
    "Elevation",
    "LinerCoverage",
    "StartColumn",
    "StopColumn",
    "XFrom",
    "XTo",
    "YFrom",
    "YTo",
    "PanelType",
    "PanelGauge",
    "ReverseRoll",
    "PanelColor",
    "PanelColorValsparCode",
    "PanelColorSpecialName",
    "RidgeTrimGauge",
    "RafterTieTrimGauge",
    "EaveToWallTrimGauge",
    "RidgeTrimColor",
    "RidgeTrimColorSpecialName",
    "RidgeTrimColorValsparCode",
    "EaveToWallTrimColor",
    "EaveToWallTrimColorValsparCode",
    "EaveToWallTrimColorSpecialName",
    "RafterTieTrimColor",
    "RafterTieTrimColorValsparCode",
    "RafterTieTrimColorSpecialName",
    "FastenerHeadFinish",
    "FastenerLength",
    "PanelFinish",
    "RidgeTrimFinish",
    "RafterTieTrimFinish",
    "EaveToWallTrimFinish",
    "CreatedBy",
    "CreatedDate",
    "ModifiedBy",
    "IpAddress",
    "IsDelete",
    "Qty"
    ) 
    VALUES (  
      BuildingNumber,
      ProjectId,
      'R',
      LinerCoverage,
      StartColumn,
      StopColumn,
      XFrom,
      XTo,
      YFrom,
      YTo,
      PanelType,
      PanelGauge,
      ReverseRoll,
      PanelColor,
      PanelColorValsparCode,
      PanelColorSpecialName,
      RidgeTrimGauge,
      RafterTieTrimGauge,
      EaveToWallTrimGauge,
      RidgeTrimColor,
      RidgeTrimColorSpecialName,
      RidgeTrimColorValsparCode,
      EaveToWallTrimColor,
      EaveToWallTrimColorValsparCode,
      EaveToWallTrimColorSpecialName,
      RafterTieTrimColor,
      RafterTieTrimColorValsparCode,
      RafterTieTrimColorSpecialName,
      FastenerHeadFinish,
      FastenerLength,
      PanelFinish,
      RidgeTrimFinish,
      RafterTieTrimFinish,
      EaveToWallTrimFinish,
      CreatedBy,
      CURRENT_TIMESTAMP,
      0,
      IpAddress,
      'N',
      1
    ) RETURNING "LinerId" INTO OutputId;
END ACCESSORIES_ROOFLINER_CREATE;
/