CREATE OR REPLACE PROCEDURE abs_mdi."CAD_OPTIONS_UPDATE" (
ProjectId IN   NUMBER,
OptionsDimScaleAdd IN   NUMBER,
OptionsIsMasonryHighDetail IN   NUMBER,
OptionsIsPanelHighDetail IN   NUMBER,
OptionsIsSteelHighDetail IN   NUMBER,
OptionsWantMasonry IN   NUMBER,
OptionsWantPanel IN   NUMBER,
OptionsWantSteel IN   NUMBER,
OptionsWantLandscape IN   NUMBER,
OptionsWantAccessories IN   NUMBER,
Options3dDetail IN   NUMBER,
OptionsTitleBlockType IN   NUMBER,
OptionsTitleBlockSize IN   NUMBER,
Options3dViewHeight IN   NUMBER,
Options3dViewOrientation IN   NUMBER,
OptionsCadProgram IN   NUMBER,
OptionsDimScheme IN   NUMBER,
OptionsDimType IN   NUMBER,
OptionsCustomPaperHeight IN   NUMBER,
OptionsCustomPaperWidth IN   NUMBER,
OptionsCustomBorderHeight IN   NUMBER,
OptionsCustomBorderWidth IN   NUMBER,
OptionsCustomTitleBlockLocation IN   NUMBER,
OptoinsCustomBackGroundLocation IN   NUMBER,
OptionsDrawingsScaleFactor IN   NUMBER,
OptionsDWGSaveDirectory IN   VARCHAR2,
DrawingName IN   VARCHAR2,
BuilderNumber IN   VARCHAR2,
BuilderName IN   VARCHAR2,
BuilderContact IN   VARCHAR2,
BuilderAddress1 IN   VARCHAR2,
BuilderAddress2 IN   VARCHAR2,
BuilderCity IN   VARCHAR2,
BuilderState IN   VARCHAR2,
BuilderZip IN   VARCHAR2,
BuilderCounty IN   VARCHAR2,
BuilderCountry IN   VARCHAR2,
BuilderEmail IN   VARCHAR2,
BuilderWebSite IN   VARCHAR2,
OwnerName IN   VARCHAR2,
OwnerAddress1 IN   VARCHAR2,
OwnerAddress2 IN   VARCHAR2,
OwnerCity IN   VARCHAR2,
OwnerState IN   VARCHAR2,
OwnerZip IN   VARCHAR2,
OwnerCounty IN   VARCHAR2,
OwnerCountry IN   VARCHAR2,
JobName IN   VARCHAR2,
JobDateOfEstimate IN   VARCHAR2,
JobEstimator IN   VARCHAR2,
JobID IN   VARCHAR2,
DrawingRevisionNumber IN   VARCHAR2,
DrawingDate IN   VARCHAR2,
Plant IN   VARCHAR2,
UserId IN VARCHAR2 DEFAULT NULL,
IpAddress IN VARCHAR2
) AS
BEGIN
UPDATE "CAD_Options"
SET
"OptionsDimScaleAdd" = OptionsDimScaleAdd,
"OptionsIsMasonryHighDetail" = OptionsIsMasonryHighDetail,
"OptionsIsPanelHighDetail" = OptionsIsPanelHighDetail,
"OptionsIsSteelHighDetail" = OptionsIsSteelHighDetail,
"OptionsWantMasonry" = OptionsWantMasonry,
"OptionsWantPanel" = OptionsWantPanel,
"OptionsWantSteel" = OptionsWantSteel,
"OptionsWantLandscape" = 1,
"OptionsWantAccessories" = OptionsWantAccessories,
"Options3dDetail" = Options3dDetail,
"OptionsTitleBlockType" = OptionsTitleBlockType,
"OptionsTitleBlockSize" = OptionsTitleBlockSize,
"Options3dViewHeight" = Options3dViewHeight,
"Options3dViewOrientation" = Options3dViewOrientation,
"OptionsCadProgram" = 2,
"OptionsDimScheme" = OptionsDimScheme,
"OptionsDimType" = OptionsDimType,
"OptionsCustomPaperHeight" = OptionsCustomPaperHeight,
"OptionsCustomPaperWidth" = OptionsCustomPaperWidth,
"OptionsCustomBorderHeight" = OptionsCustomBorderHeight,
"OptionsCustomBorderWidth" = OptionsCustomBorderWidth,
"OptionsCustomTitleBlockLocation" = OptionsCustomTitleBlockLocation,
"OptoinsCustomBackGroundLocation" = OptoinsCustomBackGroundLocation,
"OptionsDrawingsScaleFactor" = 3,
"OptionsDWGSaveDirectory" = OptionsDWGSaveDirectory,
"ModifiedBy" = UserId,
"ModifiedDate" = CURRENT_TIMESTAMP,
"IpAddress" = IpAddress
WHERE
"ProjectId" = ProjectId;
UPDATE "CAD_TitleBlock"
SET
"DrawingName" = DrawingName,
"BuilderNumber" = BuilderNumber,
"BuilderName" = BuilderName,
"BuilderContact" = BuilderContact,
"BuilderAddress1" = BuilderAddress1,
"BuilderAddress2" = BuilderAddress2,
"BuilderCity" = BuilderCity,
"BuilderState" = BuilderState,
"BuilderZip" = BuilderZip,
"BuilderCounty" = BuilderCounty,
"BuilderCountry" = BuilderCountry,
"BuilderEmail" = BuilderEmail,
"BuilderWebSite" = BuilderWebSite,
"OwnerName" = OwnerName,
"OwnerAddress1" = OwnerAddress1,
"OwnerAddress2" = OwnerAddress2,
"OwnerCity" = OwnerCity,
"OwnerState" = OwnerState,
"OwnerZip" = OwnerZip,
"OwnerCounty" = OwnerCounty,
"OwnerCountry" = OwnerCountry,
"JobName" = JobName,
"JobDateOfEstimate" = JobDateOfEstimate,
"JobEstimator" = JobEstimator,
"JobID" = JobID,
"DrawingRevisionNumber" = DrawingRevisionNumber,
"DrawingDate" = DrawingDate,
"Plant" = Plant,
"ModifiedBy" = UserId,
"ModifiedDate" = CURRENT_TIMESTAMP,
"IpAddress" = IpAddress
WHERE
"ProjectId" = ProjectId;
END CAD_OPTIONS_UPDATE;
/