CREATE OR REPLACE PROCEDURE abs_mdi."CL_OCCUPANCY_GETBYOCCUPANCYID" 
(
    OUTPUT_TABLE OUT  SYS_REFCURSOR
)
AS
BEGIN
OPEN OUTPUT_TABLE FOR SELECT
    "OccupancyId",
    "OccupancyValue",
    "SortOrder",
    "IsActive"
FROM
    "CL_Occupancy" where "IsActive"='Y';
END "CL_OCCUPANCY_GETBYOCCUPANCYID";
/