CREATE OR REPLACE PROCEDURE abs_mdi."DDP_ENGINEERINGJUDGEMENTS_SELECT" 
/*   Created By Ashlesha Diwate
      Created Date   27-4-2021
      Description   This stored Procedure used to get  data  from  DDP_ENGINEERJUDGEMENT table  */
(
  V_JobNumber IN NVARCHAR2,
  V_DDPSSERVERID IN NUMBER,
    Output_Data OUT SYS_REFCURSOR
)
AS 
BEGIN
  OPEN Output_Data FOR
    SELECT
    ENGINEERINGJUDGEMENTSID,
    JOBNUMBER,
    DESIGNCRITERIACOMMENT,
    ISDESIGNCRITERIAYES,
    ISDESIGNCRITERIANO,
    DESIGNCRITERIASIGNINGENGINEER,
    ORDERREQUIREMENTCOMMENT,
    ORDERREQUIREMENTSIGNINGENGINEER,
    SYSTEMGENERATEDDESIGNCHANGECOMMENT,
    SYSTEMGENERATEDDESIGNCHANGESIGNINGENGINEER,
    WORKDONEOUTSIDECOMMENT,
    WORKDONEOUTSIDESIGNINGENGINEER,
    SYSTEMMESSAGECOMMENT,
    SYSTEMMESSAGESIGNINGENGINEER,
    CHECKINGENGINEERNAME,
    CHECKINGENGINEERDATE,
    PROJECTENGINEERNAME,
    PROJECTENGINEERDATE,
    SIGNINGENGINEERNAME,
    SIGNINGENGINEERDATE,
    CREATEDDATE,
    IPAddress,
    DDPSSERVERID
    FROM
        DDP_ENGINEERJUDGEMENT 
    WHERE 
        (LOWER(JOBNUMBER)= LOWER(V_JobNumber) and DDPSSERVERID = V_DDPSSERVERID);
END DDP_ENGINEERINGJUDGEMENTS_SELECT;
/