CREATE OR REPLACE PROCEDURE abs_mdi."DDP_BUILDINGLOADS_SAVE" 
/*   Created By Ashlesha Diwate
      Created Date   16-6-2021
      Description   This stored Procedure used to insert into  DDP_Buildingloads table  */
(
    Var_BUILDINGNAME IN NVARCHAR2, 
	Var_LOADAPPLICATIONCATEGORY IN NVARCHAR2, 
	Var_LOADINDEX IN NUMBER, 
    Var_PLANENAME IN NVARCHAR2, 
	Var_FRAMENAME IN NVARCHAR2, 
	Var_TYPE IN NVARCHAR2, 
	Var_MEMBERID IN NVARCHAR2 , 
	Var_COORDINATESYSTEM IN NVARCHAR2, 
	Var_GROUPNAME IN NVARCHAR2, 
	Var_DIRECTION IN NVARCHAR2, 
	Var_XLOCATION IN NUMBER, 
	Var_YLOCATION IN NUMBER, 
	Var_LENGTH IN NUMBER ,
	Var_WIDTH IN NUMBER, 
	Var_STARTINTENSITY IN NUMBER, 
	Var_ENDINTENSITY IN NUMBER,
	Var_APPLYFRAMES VARCHAR2, 
	Var_APPLYSECONDARY VARCHAR2, 
	Var_APPLYPANELS VARCHAR2, 
	Var_ORIENTATION VARCHAR2, 
	Var_ECCENTRICITY NUMBER, 
	Var_ECCENTRICITYTYPE VARCHAR2, 
	Var_COMMENTS NVARCHAR2, 
    OutputId OUT NUMBER
) AS 
BEGIN
   
    INSERT INTO DDP_BUILDINGLOADS(
      BUILDINGNAME,   
     LOADAPPLICATIONCATEGORY,  
     LOADINDEX, 
     PLANENAME, 
	 FRAMENAME, 
	 BTYPE,   
	 MEMBERID,  
	 COORDINATESYSTEM,  
	 GROUPNAME, 
	 DIRECTION, 
	 XLOCATION, 
	 YLOCATION , 
	 BLENGTH, 
	 WIDTH, 
	 STARTINTENSITY  , 
	 ENDINTENSITY  , 
	 APPLYFRAMES , 
	 APPLYSECONDARY  , 
	 APPLYPANELS , 
	 ORIENTATION  , 
	 ECCENTRICITY , 
	 ECCENTRICITYTYPE , 
    COMMENTS  
    )
    VALUES(
      Var_BUILDINGNAME,   
	Var_LOADAPPLICATIONCATEGORY,  
	Var_LOADINDEX, 
    Var_PLANENAME, 
	Var_FRAMENAME, 
	Var_TYPE,   
	Var_MEMBERID,  
	Var_COORDINATESYSTEM,  
	Var_GROUPNAME, 
	Var_DIRECTION, 
	Var_XLOCATION, 
	Var_YLOCATION , 
	Var_LENGTH  , 
	Var_WIDTH  , 
	Var_STARTINTENSITY  , 
	Var_ENDINTENSITY  , 
	Var_APPLYFRAMES , 
	Var_APPLYSECONDARY  , 
	Var_APPLYPANELS , 
	Var_ORIENTATION  , 
	Var_ECCENTRICITY , 
	Var_ECCENTRICITYTYPE , 
	Var_COMMENTS 
    )
    RETURNING  BUILDINGLOADSID into OutputId;
END DDP_BUILDINGLOADS_SAVE;
/