CREATE OR REPLACE PROCEDURE abs_mdi."DDP_EDSDB_VERSION_INSERT" 
/*   Created By    Mayuresh Jagtap
     Created Date   24-08-2021
     Description   This stored Procedure used in the DDP and used for insert records in EDSDB_VERSION table */
(		
		EDSDB_VERSION IN NUMBER,
		IPADDRESS IN VARCHAR2,
		EDSDBBLDGVERID IN NUMBER
) AS 
BEGIN
		INSERT INTO DDP_EDSDB_VERSION (
		EDSDB_VERSION,
		CREATEDDATE,
		ISDELETE,
		IPADDRESS,
		EDSDBBLDGVERID
) 		
VALUES 
(
		EDSDB_VERSION,
		CURRENT_TIMESTAMP,
		'N',
		IPADDRESS,
		EDSDBBLDGVERID
);
END DDP_EDSDB_VERSION_INSERT;
/