CREATE OR REPLACE PROCEDURE abs_mdi."DDP_LOCENGINEERS_SELECT" (
/*   Created By Mayuresh Jagtap
      Created Date   30-11-2021
      Description   This stored Procedure used to Update data to DDP_LOCEngineer table  */
    V_JOBNUMBER IN VARCHAR2,
    V_DDPSERVERID IN NUMBER,
    V_OUTPUT_LOCENGINEERS  OUT  SYS_REFCURSOR
)
AS
BEGIN
    OPEN V_OUTPUT_LOCENGINEERS FOR SELECT
        LOC_ENGINEERS_ID,
        DDPSERVERID,
        JOBNUMBER,
        PROJENG_INITIAL,
        PROJENG_NAME,
        CHECKENG_INITIAL,
        CHECKENG_NAME,
        SEALENG_INITIAL,
        SEALENG_NAME,
        CREATEDBY,
        CREATEDDATE,
        MODIFIEDBY,
        MODIFIEDDATE,
        ISDELETE,
        IPADDRESS
    FROM
        DDP_LOC_ENGINEERS
    WHERE
        LOWER(JOBNUMBER) = LOWER(V_JOBNUMBER)
    AND DDPSERVERID = V_DDPSERVERID AND ISDELETE = 'N';
END DDP_LOCENGINEERS_SELECT;
/