CREATE OR REPLACE PROCEDURE abs_mdi."DDP_DESIGNPACKAGECHECKLIST_SELECT" 
/*   Created By Dnyaneshwar Kuchekar  
      Created Date   2-3-2021
      Description   This stored Procedure used to get data to DDP_DESIGNPACKAGECHECKLISTDETAILS table  */
(
    V_JobNumber IN VARCHAR2,
    V_DDPSSERVERID IN NUMBER,
    OUTPUT_DESIGNCHECKLIST OUT SYS_REFCURSOR,
    OUTPUT_DESIGNCHECKLISTDETAILS OUT SYS_REFCURSOR
)
AS 
BEGIN
  OPEN OUTPUT_DESIGNCHECKLIST FOR
    SELECT
        ID,
        JOBNUMBER,
        PROJECTENGINEERINITIAL,
        CHECKINGENGINEERINITIAL,
        PROJECTENGINEERDATE,
        CHECKINGENGINEERDATE,
        RTODWITHNOCHANGES,
        CHANGESANDRTOD,
        CHANGESANDRESUBMITFORRECHECK,
        CONTACTMEFORFURTHERDISCUSSION,
        DDPSSERVERID
    FROM
        DDP_DESIGNPACKAGECHECKLIST 
    WHERE 
        (LOWER(JOBNUMBER)= LOWER(V_JobNumber) and DDPSSERVERID = V_DDPSSERVERID) ;
OPEN OUTPUT_DESIGNCHECKLISTDETAILS FOR
    SELECT
        dd.ID,
        dd.CHECKLISTID,
        dd.NAME,
        dd.PROJECTENGINEER,
        dd.CHECKINGENGINEER,
        dd.NA
    FROM
        DDP_DESIGNPACKAGECHECKLISTDETAILS dd INNER JOIN  DDP_DESIGNPACKAGECHECKLIST d
        ON dd.CHECKLISTID = d.ID
    WHERE 
       LOWER(d.JOBNUMBER) = LOWER(V_JobNumber) and d.DDPSSERVERID = V_DDPSSERVERID ;
END DDP_DESIGNPACKAGECHECKLIST_SELECT;
/