CREATE OR REPLACE PROCEDURE abs_mdi."DDP_DEFAULTNOTESONDRAWINGSUBCATEGORY_INSERT" 
/*   Created By Foram Menpara
      Created Date   16-07-2021
      Description   This stored Procedure used to INSERT the data  in  table DDP_DEFAULTNOTESONDRAWINGSUBCATEGORY  */
(
   -- V_ORDERPRIORITY IN NUMBER,
    V_CATEGORYID IN NUMBER,
    V_SUBCATEGORYNAME in VARCHAR2,
    V_UserId IN NUMBER, 
    V_IPADDRESS IN VARCHAR2,
    OutputId OUT NUMBER
) AS
BEGIN
    INSERT INTO "DDP_DEFAULTNOTESONDRAWINGSUBCATEGORY"(
        "ORDERPRIORITY",
        "CATEGORYID",
        "SUBCATEGORYNAME",
        "CREATEDBY",
        "CREATEDDATE",
        "IPADDRESS"
    ) 
VALUES 
	(
       -- V_ORDERPRIORITY,
       (select max("ORDERPRIORITY") + 1 from "DDP_DEFAULTNOTESONDRAWINGSUBCATEGORY" where "CATEGORYID" = V_CATEGORYID),
        V_CATEGORYID,
        V_SUBCATEGORYNAME,
        V_UserId,
        CURRENT_TIMESTAMP,
        V_IPADDRESS
    )	 RETURNING "SUBCATEGORYID" into OutputId;
END DDP_DEFAULTNOTESONDRAWINGSUBCATEGORY_INSERT;
/