CREATE OR REPLACE PROCEDURE abs_mdi."DDP_ENGINEERINGJUDGEMENTS_UPDATE" 
/*   Created By Ashlesha Diwate
      Created Date   27-4-2021
      Description   This stored Procedure used to update  data  from  DDP_ENGINEERJUDGEMENT table  */
(
    V_ENGINEERINGJUDGEMENTSID IN NUMBER,
	V_JOBNUMBER IN VARCHAR2, 
	V_DESIGNCRITERIACOMMENT IN NCLOB, 
	V_ISDESIGNCRITERIAYES IN CHAR,
    V_ISDESIGNCRITERIANO IN CHAR,
	V_DESIGNCRITERIASIGNINGENGINEER IN CHAR,
	V_ORDERREQUIREMENTCOMMENT IN NCLOB, 
	V_ORDERREQUIREMENTSIGNINGENGINEER IN CHAR, 
	V_SYSTEMGENERATEDDESIGNCHANGECOMMENT IN NCLOB, 
	V_SYSTEMGENERATEDDESIGNCHANGESIGNINGENGINEER IN CHAR, 
	V_WORKDONEOUTSIDECOMMENT IN NCLOB, 
	V_WORKDONEOUTSIDESIGNINGENGINEER IN CHAR, 
	V_SYSTEMMESSAGECOMMENT IN NCLOB, 
	V_SYSTEMMESSAGESIGNINGENGINEER IN CHAR, 
	V_CHECKINGENGINEERNAME IN VARCHAR2, 
	V_CHECKINGENGINEERDATE IN TIMESTAMP, 
	V_PROJECTENGINEERNAME IN VARCHAR2, 
	V_PROJECTENGINEERDATE IN TIMESTAMP, 
	V_SIGNINGENGINEERNAME IN VARCHAR2, 
    V_SIGNINGENGINEERDATE IN TIMESTAMP, 
	V_UserId IN NUMBER, 
    V_DDPSSERVERID IN NUMBER,
	V_IPADDRESS IN VARCHAR2
    
)
AS 
BEGIN
   UPDATE  DDP_ENGINEERJUDGEMENT SET
    JOBNUMBER=V_JOBNUMBER,
    DESIGNCRITERIACOMMENT=V_DESIGNCRITERIACOMMENT,
    ISDESIGNCRITERIAYES=V_ISDESIGNCRITERIAYES,
    ISDESIGNCRITERIANO=V_ISDESIGNCRITERIANO,
    DESIGNCRITERIASIGNINGENGINEER=V_DESIGNCRITERIASIGNINGENGINEER,
    ORDERREQUIREMENTCOMMENT=V_ORDERREQUIREMENTCOMMENT,
    ORDERREQUIREMENTSIGNINGENGINEER=V_ORDERREQUIREMENTSIGNINGENGINEER,
    SYSTEMGENERATEDDESIGNCHANGECOMMENT=V_SYSTEMGENERATEDDESIGNCHANGECOMMENT,
    SYSTEMGENERATEDDESIGNCHANGESIGNINGENGINEER=V_SYSTEMGENERATEDDESIGNCHANGESIGNINGENGINEER,
    WORKDONEOUTSIDECOMMENT=V_WORKDONEOUTSIDECOMMENT,
    WORKDONEOUTSIDESIGNINGENGINEER=V_WORKDONEOUTSIDESIGNINGENGINEER,
    SYSTEMMESSAGECOMMENT=V_SYSTEMMESSAGECOMMENT,
    SYSTEMMESSAGESIGNINGENGINEER=V_SYSTEMMESSAGESIGNINGENGINEER,
    CHECKINGENGINEERNAME=V_CHECKINGENGINEERNAME,
    CHECKINGENGINEERDATE=V_CHECKINGENGINEERDATE,
    PROJECTENGINEERNAME=V_PROJECTENGINEERNAME,
    PROJECTENGINEERDATE=V_PROJECTENGINEERDATE,
    SIGNINGENGINEERNAME=V_SIGNINGENGINEERNAME,
    SIGNINGENGINEERDATE=V_SIGNINGENGINEERDATE,
    MODIFIEDBY=V_UserId,
    MODIFIEDDATE=  CURRENT_TIMESTAMP,
    DDPSSERVERID=   V_DDPSSERVERID,
   IPAddress=V_IPADDRESS
        WHERE ENGINEERINGJUDGEMENTSID = V_ENGINEERINGJUDGEMENTSID;
END DDP_ENGINEERINGJUDGEMENTS_UPDATE;
/