CREATE OR REPLACE PROCEDURE abs_mdi."DDP_LOCENGINEERSMODEL_UPDATE" 
/*   Created By Mayuresh Jagtap
      Created Date   30-11-2021
      Description   This stored Procedure used to Update data to DDP_LOCEngineer table  */
(
    V_LOC_ENGINEERS_ID IN NUMBER,
    V_PROJENG_INITIAL  IN VARCHAR2,
    V_PROJENG_NAME  IN VARCHAR2,
    V_CHECKENG_INITIAL  IN VARCHAR2,
    V_CHECKENG_NAME  IN VARCHAR2,
    V_SEALENG_INITIAL  IN VARCHAR2,
    V_SEALENG_NAME  IN VARCHAR2,
    V_MODIFIEDBY IN NUMBER,
    V_IPADDRESS IN VARCHAR2
)
AS    
BEGIN
    UPDATE DDP_LOC_ENGINEERS
    SET
        PROJENG_INITIAL = V_PROJENG_INITIAL,
        PROJENG_NAME = V_PROJENG_NAME,
        CHECKENG_INITIAL = V_CHECKENG_INITIAL,
        CHECKENG_NAME = V_CHECKENG_NAME,
        SEALENG_INITIAL = V_SEALENG_INITIAL,
        SEALENG_NAME = V_SEALENG_NAME,
        MODIFIEDBY = V_MODIFIEDBY,
        MODIFIEDDATE = CURRENT_TIMESTAMP,
        IPADDRESS = V_IPADDRESS
    WHERE
        LOC_ENGINEERS_ID = V_LOC_ENGINEERS_ID and ISDELETE = 'N';
END DDP_LOCENGINEERSMODEL_UPDATE;
/