CREATE OR REPLACE PROCEDURE abs_mdi."DDP_DEFAULTNOTESONDRAWINGCATEGORY_UPDATE" 
 /*   Created By Foram Menpara
      Created Date   16-07-2021
      Description   This stored Procedure used to update the data  in  table DDP_DEFAULTNOTESONDRAWINGCATEGORY  */
(
    V_CATEGORYID IN NUMBER,
    V_CATEGORYNAME IN VARCHAR2,
    -- V_ORDERPRIORITY IN NUMBER,
     V_UserId IN NUMBER,
     V_IPADDRESS IN VARCHAR2
)AS 
BEGIN
   UPDATE  "DDP_DEFAULTNOTESONDRAWINGCATEGORY" SET
               "CATEGORYNAME" = V_CATEGORYNAME,
              -- "ORDERPRIORITY" = V_ORDERPRIORITY,
               "MODIFIEDBY" = V_UserId,
               "MODIFIEDDATE" =  CURRENT_TIMESTAMP
        WHERE "CATEGORYID" = V_CATEGORYID AND ISDELETE = 'N';
END DDP_DEFAULTNOTESONDRAWINGCATEGORY_UPDATE;
/