CREATE OR REPLACE PROCEDURE abs_mdi."DDP_ENGINEERINGJUDGEMENTS_SAVE" 
/*   Created By Ashlesha Diwate
      Created Date   27-4-2021
      Description   This stored Procedure used to insert data  into  DDP_ENGINEERJUDGEMENT table  */
(
	V_JOBNUMBER IN VARCHAR2, 
	V_DESIGNCRITERIACOMMENT IN NCLOB, 
	V_ISDESIGNCRITERIAYES IN CHAR,
    V_ISDESIGNCRITERIANO IN CHAR,
	V_DESIGNCRITERIASIGNINGENGINEER IN CHAR,
	V_ORDERREQUIREMENTCOMMENT IN NCLOB, 
	V_ORDERREQUIREMENTSIGNINGENGINEER IN CHAR, 
	V_SYSTEMGENERATEDDESIGNCHANGECOMMENT IN NCLOB, 
	V_SYSTEMGENERATEDDESIGNCHANGESIGNINGENGINEER IN CHAR, 
	V_WORKDONEOUTSIDECOMMENT IN NCLOB, 
	V_WORKDONEOUTSIDESIGNINGENGINEER IN CHAR, 
	V_SYSTEMMESSAGECOMMENT IN NCLOB, 
	V_SYSTEMMESSAGESIGNINGENGINEER IN CHAR, 
	V_CHECKINGENGINEERNAME IN VARCHAR2, 
	V_CHECKINGENGINEERDATE IN TIMESTAMP, 
	V_PROJECTENGINEERNAME IN VARCHAR2, 
	V_PROJECTENGINEERDATE IN TIMESTAMP, 
	V_SIGNINGENGINEERNAME IN VARCHAR2, 
    V_SIGNINGENGINEERDATE IN TIMESTAMP, 
	V_UserId IN NUMBER, 
	--V_CREATEDDATE IN TIMESTAMP, 
	V_IPADDRESS IN VARCHAR2,
    V_DDPSSERVERID IN NUMBER,
    OutputId OUT NUMBER
        )
 AS 
BEGIN
   
    INSERT INTO DDP_ENGINEERJUDGEMENT(
    JOBNUMBER,
    DESIGNCRITERIACOMMENT,
    ISDESIGNCRITERIAYES,
    ISDESIGNCRITERIANO,
    DESIGNCRITERIASIGNINGENGINEER,
    ORDERREQUIREMENTCOMMENT,
    ORDERREQUIREMENTSIGNINGENGINEER,
    SYSTEMGENERATEDDESIGNCHANGECOMMENT,
    SYSTEMGENERATEDDESIGNCHANGESIGNINGENGINEER,
    WORKDONEOUTSIDECOMMENT,
    WORKDONEOUTSIDESIGNINGENGINEER,
    SYSTEMMESSAGECOMMENT,
    SYSTEMMESSAGESIGNINGENGINEER,
    CHECKINGENGINEERNAME,
    CHECKINGENGINEERDATE,
    PROJECTENGINEERNAME,
    PROJECTENGINEERDATE,
    SIGNINGENGINEERNAME,
    SIGNINGENGINEERDATE,
    CREATEDBY,
    CREATEDDATE,
   -- MODIFIEDBY,
   -- MODIFIEDDATE,
     IPAddress,
     DDPSSERVERID
   )
    
    VALUES(
    V_JOBNUMBER,
    V_DESIGNCRITERIACOMMENT,
    V_ISDESIGNCRITERIAYES,
    V_ISDESIGNCRITERIANO,
    V_DESIGNCRITERIASIGNINGENGINEER,
    V_ORDERREQUIREMENTCOMMENT,
    V_ORDERREQUIREMENTSIGNINGENGINEER,
    V_SYSTEMGENERATEDDESIGNCHANGECOMMENT,
    V_SYSTEMGENERATEDDESIGNCHANGESIGNINGENGINEER,
    V_WORKDONEOUTSIDECOMMENT,
    V_WORKDONEOUTSIDESIGNINGENGINEER,
    V_SYSTEMMESSAGECOMMENT,
    V_SYSTEMMESSAGESIGNINGENGINEER,
    V_CHECKINGENGINEERNAME,
    V_CHECKINGENGINEERDATE,
    V_PROJECTENGINEERNAME,
    V_PROJECTENGINEERDATE,
    V_SIGNINGENGINEERNAME,
    V_SIGNINGENGINEERDATE,
    V_UserId,
    CURRENT_TIMESTAMP,
    --null,
  --  null,
   V_IPAddress,
   V_DDPSSERVERID
   )
    RETURNING ENGINEERINGJUDGEMENTSID into OutputId;
END DDP_ENGINEERINGJUDGEMENTS_SAVE;
/