CREATE OR REPLACE PROCEDURE abs_mdi."DDP_BUILDINGLOADS_UPDATE" 
/*   Created By Ashlesha Diwate
      Created Date   16-6-2021
      Description   This stored Procedure used to update into  DDP_Buildingloads table  */
(
    Var_BUILDINGID IN NUMBER,
    Var_BUILDINGNAME IN NVARCHAR2, 
	Var_LOADAPPLICATIONCATEGORY IN NVARCHAR2, 
	Var_LOADINDEX IN NUMBER, 
    Var_PLANENAME IN NVARCHAR2, 
	Var_FRAMENAME IN NVARCHAR2, 
	Var_TYPE IN NVARCHAR2, 
	Var_MEMBERID IN NVARCHAR2 , 
	Var_COORDINATESYSTEM IN NVARCHAR2, 
	Var_GROUPNAME IN NVARCHAR2, 
	Var_DIRECTION IN NVARCHAR2, 
	Var_XLOCATION IN NUMBER, 
	Var_YLOCATION IN NUMBER, 
	Var_LENGTH IN NUMBER ,
	Var_WIDTH IN NUMBER, 
	Var_STARTINTENSITY IN NUMBER, 
	Var_ENDINTENSITY IN NUMBER,
	Var_APPLYFRAMES VARCHAR2, 
	Var_APPLYSECONDARY VARCHAR2, 
	Var_APPLYPANELS VARCHAR2, 
	Var_ORIENTATION VARCHAR2, 
	Var_ECCENTRICITY NUMBER, 
	Var_ECCENTRICITYTYPE VARCHAR2, 
	Var_COMMENTS NVARCHAR2 
)
AS 
BEGIN
UPDATE  DDP_BUILDINGLOADS SET
     BUILDINGNAME= Var_BUILDINGNAME,   
     LOADAPPLICATIONCATEGORY=	Var_LOADAPPLICATIONCATEGORY,  
     LOADINDEX=Var_LOADINDEX, 
     PLANENAME=Var_PLANENAME, 
	 FRAMENAME=Var_FRAMENAME, 
	 BTYPE=Var_TYPE,   
	 MEMBERID=Var_MEMBERID,  
	 COORDINATESYSTEM=Var_COORDINATESYSTEM,  
	 GROUPNAME=Var_GROUPNAME, 
	 DIRECTION=Var_DIRECTION, 
	 XLOCATION=Var_XLOCATION, 
	 YLOCATION =Var_YLOCATION, 
	 BLENGTH=Var_LENGTH, 
	 WIDTH=Var_WIDTH, 
	 STARTINTENSITY=Var_STARTINTENSITY  , 
	 ENDINTENSITY=Var_ENDINTENSITY  , 
	 APPLYFRAMES=Var_APPLYFRAMES , 
	 APPLYSECONDARY=Var_APPLYSECONDARY  , 
	 APPLYPANELS=Var_APPLYPANELS , 
	 ORIENTATION =Var_ORIENTATION , 
	 ECCENTRICITY=Var_ECCENTRICITY , 
	 ECCENTRICITYTYPE=	Var_ECCENTRICITYTYPE , 
    COMMENTS=Var_COMMENTS  
    	  
    where BUILDINGLOADSID=Var_BUILDINGID;
END DDP_BUILDINGLOADS_UPDATE;
/