CREATE OR REPLACE PROCEDURE abs_mdi."ENDWALLS_OPENAREA_UPDATE" 
(       
    OptionId IN NUMBER,
    BuildingNo IN NUMBER,
    ProjectId IN NUMBER,
    EndWallNo IN NUMBER,
    OpenAreaFor IN VARCHAR2,
    WallType IN VARCHAR2,
    AttanchedBuildingNo IN VARCHAR2,
    Width IN VARCHAR2,
    Height IN VARCHAR2,
    IsFullWidth IN CHAR,
    IsPMaterialByOthers IN CHAR,
    OpenFor IN NUMBER,
    IsSheetedWall IN CHAR,
    MasonryReinforcement IN NUMBER,
    MasonryType IN NUMBER,
    TiltUp IN NUMBER,
    IsShearWall IN CHAR,
    ColumnBeBraced IN CHAR,
    NotDeductLinearPanel IN CHAR,
    NotDeductInsulation IN CHAR,
    DeductPanelTrim IN CHAR,
    IncludeJambFlash IN CHAR,
    IncludeHeaderFlash IN CHAR,
    Base IN NUMBER,
    FlashColor IN VARCHAR2,
    MaterialThickness IN VARCHAR2,
    MaterialWeight IN VARCHAR2,
    DistanceFromSteelLinetoF IN VARCHAR2,
    DistanceFromSteelLinetoJ IN VARCHAR2,
    PercRemainingOpenForWind IN VARCHAR2,
    SupportBeanByManufacturer IN CHAR,
    BeamLocation IN NUMBER,
    BeamType IN NUMBER,
    BeamDeflectionLenghth IN NUMBER,
    UseFalangeBracing IN CHAR,
    ConnectionSpaceOfWallAttachmentToSBeam IN VARCHAR2,
    ModifiedBy IN NUMBER,
    IpAddress IN VARCHAR2,
    OutputId OUT NUMBER
)
AS 
BEGIN
UPDATE "Input_Endwalls_OpenArea" SET        
    "BuildingNo" = BuildingNo,
    "ProjectId" = ProjectId,
    "EndWallNo" = EndWallNo,
    "OpenAreaFor" = OpenAreaFor,
    "WallType" = WallType,
    "AttanchedBuildingNo" = AttanchedBuildingNo,
    "Width" = Width,
    "Height" = Height,
    "IsFullWidth" = IsFullWidth,
    "IsPMaterialByOthers" = IsPMaterialByOthers,
    "OpenFor" = OpenFor,
    "IsSheetedWall" = IsSheetedWall,
    "MasonryReinforcement" = MasonryReinforcement,
    "MasonryType" = MasonryType,
    "TiltUp" = TiltUp,
    "IsShearWall" = IsShearWall,
    "ColumnBeBraced" = ColumnBeBraced,
    "NotDeductLinearPanel" = NotDeductLinearPanel,
    "NotDeductInsulation" = NotDeductInsulation,
    "DeductPanelTrim" = DeductPanelTrim,
    "IncludeJambFlash" = IncludeJambFlash,
    "IncludeHeaderFlash" = IncludeHeaderFlash,
    "Base" = Base,
    "FlashColor" = FlashColor,
    "MaterialThickness" = MaterialThickness,
    "MaterialWeight" = MaterialWeight,
    "DistanceFromSteelLinetoF" = DistanceFromSteelLinetoF,
    "DistanceFromSteelLinetoJ" = DistanceFromSteelLinetoJ,
    "PercRemainingOpenForWind" = PercRemainingOpenForWind,
    "SupportBeanByManufacturer" = SupportBeanByManufacturer,
    "BeamLocation" = BeamLocation,
    "BeamType" = BeamType,
    "BeamDeflectionLenghth" = BeamDeflectionLenghth,
    "UseFalangeBracing" = UseFalangeBracing,
    "ConnectionSpaceOfWallAttachmentToSBeam" = ConnectionSpaceOfWallAttachmentToSBeam,
    "ModifiedBy" = ModifiedBy,
    "ModifiedDate" = CURRENT_TIMESTAMP,
    "IpAddress" = IpAddress
 WHERE "BuildingNo" = BuildingNo and "ProjectId" = ProjectId and "EndWallNo" = EndWallNo;
    
END ENDWALLS_OPENAREA_UPDATE;
/