CREATE OR REPLACE PROCEDURE abs_mdi."GETWEBLINKS_SELECT" (
WEBLINKID     IN   NUMBER,
WebLink_Data  OUT  SYS_REFCURSOR
)
AS
BEGIN
OPEN WebLink_Data FOR SELECT
  "WEBLINKID",
  "TABS",
  "WEBLINKS",
  "EXTRA_MATERIAL"
  FROM 
  "WEBLINKSMASTER"
where "WEBLINKID"="WEBLINKID";
END GETWEBLINKS_SELECT;
/