CREATE OR REPLACE PROCEDURE abs_mdi."GIRTSBAYSPACING_CREATE" 
(
    BuildingInformationId IN NUMBER,
    SW1Style IN NUMBER,
    SW2Style IN NUMBER,
    EW1Style IN NUMBER,
    EW2Style IN NUMBER,
    RoofPurlinStyle IN NUMBER,
    SW1Depth IN NUMBER,
    SW2Depth IN NUMBER,
    EW1Depth IN NUMBER,
    EW2Depth IN NUMBER,
    RoofPurlinDepth IN NUMBER,
    SW1Optimize IN CHAR DEFAULT 'N',
    SW2Optimize IN CHAR DEFAULT 'N',
    EW1Optimize IN CHAR DEFAULT 'N',
    EW2Optimize IN CHAR DEFAULT 'N',
    RoofPurlinOptimize IN CHAR DEFAULT 'N',
    RoofBaySpacing IN NUMBER,
    WallBaySpacing IN VARCHAR2 DEFAULT NULL,
    GirtSpacing IN VARCHAR2 DEFAULT NULL,
    PurlinSpacing IN VARCHAR2 DEFAULT NULL,
    LBPMinDepth IN FLOAT,
    LBPMaxDepth IN FLOAT,
    UserId IN NUMBER,
    IpAddress IN VARCHAR2 DEFAULT NULL,
    OptimizePurlin IN NUMBER DEFAULT 0,
    OutputId OUT NUMBER
)
AS 
BEGIN
     INSERT INTO "Input_GirtsBaySpacing"
     (
        "BuildingInformationId",
        "SW1Style",
        "SW2Style",
        "EW1Style",
        "EW2Style",
        "RoofPurlinStyle",
        "SW1Depth",
        "SW2Depth",
        "EW1Depth",
        "EW2Depth",
        "RoofPurlinDepth",
        "SW1Optimize",
        "SW2Optimize",
        "EW1Optimize",
        "EW2Optimize",
        "RoofPurlinOptimize",
        "RoofBaySpacing",
        "WallBaySpacing",
        "GirtSpacing",
        "PurlinSpacing",
        "LBPMinDepth",
        "LBPMaxDepth",
        "CreatedBy",
        "CreatedDate",
        "IsDelete",
        "IpAddress",
        "OptimizePurlin"
     )
     VALUES
     (
        BuildingInformationId,
        SW1Style,
        SW2Style,
        EW1Style,
        EW2Style,
        RoofPurlinStyle,
        SW1Depth,
        SW2Depth,
        EW1Depth,
        EW2Depth,
        RoofPurlinDepth,
        SW1Optimize,
        SW2Optimize,
        EW1Optimize,
        EW2Optimize,
        RoofPurlinOptimize,
        RoofBaySpacing,
        WallBaySpacing,
        GirtSpacing,
        PurlinSpacing,
        LBPMinDepth,
        LBPMaxDepth,
        UserId,
        CURRENT_TIMESTAMP,
        'N',
        IpAddress,
        OptimizePurlin
     )
     RETURNING "GirtSpacingId" into OutputId;
END GirtsBaySpacing_Create;
/