CREATE OR REPLACE PROCEDURE abs_mdi."IOERECTIONDATA_CREATE" 
(
    ProjectId IN NUMBER,
    ProjectNumber IN NUMBER,
    LaborDivision1PayScale IN NUMBER,
    LaborDivision2PayScale IN NUMBER,
    LaborDivision3PayScale IN NUMBER,
    LaborDivision4PayScale IN NUMBER,
    LaborDivision5PayScale IN NUMBER,
    LaborDivision1Hours IN NUMBER,
    LaborDivision2Hours IN NUMBER,
    LaborDivision3Hours IN NUMBER,
    LaborDivision4Hours IN NUMBER,
    LaborDivision5Hours IN NUMBER,
    LaborDivision1Total IN NUMBER,
    LaborDivision2Total IN NUMBER,
    LaborDivision3Total IN NUMBER,
    LaborDivision4Total IN NUMBER,
    LaborDivision5Total IN NUMBER,
    TravelExpenses IN NUMBER,
    Subsistence IN NUMBER,
    EquipmentRental IN NUMBER,
    OtherExpenses IN NUMBER,
    TotalManHours IN NUMBER,
    TotalExpense IN NUMBER,
    UserId IN NUMBER DEFAULT NULL,
    IpAddress IN VARCHAR2,
    OutputId OUT NUMBER
)
AS 
BEGIN
     INSERT INTO "EDSPrice_IO_ErectionData"
     (
        "ProjectId",
        "ProjectNumber",
        "LaborDivision1PayScale",
        "LaborDivision2PayScale",
        "LaborDivision3PayScale",
        "LaborDivision4PayScale",
        "LaborDivision5PayScale",
        "LaborDivision1Hours",
        "LaborDivision2Hours",
        "LaborDivision3Hours",
        "LaborDivision4Hours",
        "LaborDivision5Hours",
        "LaborDivision1Total",
        "LaborDivision2Total",
        "LaborDivision3Total",
        "LaborDivision4Total",
        "LaborDivision5Total",
        "TravelExpenses",
        "Subsistence",
        "EquipmentRental",
        "OtherExpenses",
        "TotalManHours",
        "TotalExpense",
        "CreatedBy",
        "CreatedDate",
        "IpAddress",
        "IsDeleted"
     )
     VALUES
     (
        ProjectId,
        ProjectNumber,
        LaborDivision1PayScale,
        LaborDivision2PayScale,
        LaborDivision3PayScale,
        LaborDivision4PayScale,
        LaborDivision5PayScale,
        LaborDivision1Hours,
        LaborDivision2Hours,
        LaborDivision3Hours,
        LaborDivision4Hours,
        LaborDivision5Hours,
        LaborDivision1Total,
        LaborDivision2Total,
        LaborDivision3Total,
        LaborDivision4Total,
        LaborDivision5Total,
        TravelExpenses,
        Subsistence,
        EquipmentRental,
        OtherExpenses,
        TotalManHours,
        TotalExpense,
        UserId,
        CURRENT_TIMESTAMP,
        IpAddress,
        'N'
     )
     RETURNING "ErectionDataId" INTO OutputId;
END IOErectionData_Create;
/