CREATE OR REPLACE PROCEDURE abs_mdi."MEZZANINEADDLINES_UPDATE" 
(
    AddLinesId IN NUMBER,
    BuildingInformationId IN NUMBER,
    Description IN VARCHAR2 DEFAULT NULL,
    UnitWeight IN NUMBER,
    UnitPrice IN NUMBER,
    ListOrNet IN VARCHAR2 DEFAULT NULL,
    ExpiresOn IN VARCHAR2 DEFAULT NULL,
    QuoteNumber IN VARCHAR2 DEFAULT NULL,
    QuoteYear IN VARCHAR2 DEFAULT NULL,
    EstInitials IN VARCHAR2 DEFAULT NULL,
    Guid IN RAW DEFAULT NULL,
    Quantity IN NUMBER,
    Internal IN NUMBER,
    IncludeFreight IN VARCHAR2 DEFAULT NULL,
    DontShowPriceWeight IN CHAR,
    IsSpecialized IN CHAR,
    ScreenType IN VARCHAR2 DEFAULT NULL,
	TaxApplied IN NUMBER,
	AdjustmentFactor IN NUMBER,
	Expired IN NUMBER,
	Category IN VARCHAR2,
	BuiltupWeight IN NUMBER,
	BuiltupPrice IN NUMBER,
	HotrolledWeight IN NUMBER,
	HotrolledPrice IN NUMBER,
	ColdformWeight IN NUMBER,
	ColdformPrice IN NUMBER,
	FabColdformWeight IN NUMBER,
	FabColdformPrice IN NUMBER,
	RoofpanelWeight IN NUMBER,
	RoofpanelPrice IN NUMBER,
	WallpanelWeight IN NUMBER,
	WallpanelPrice IN NUMBER,
	TrimWeight IN NUMBER,
	TrimPrice IN NUMBER,
	BuyoutsWeight IN NUMBER,
	BuyoutsPrice IN NUMBER,
	WarehouseWeight IN NUMBER,
	WarehousePrice IN NUMBER,
	OtherWeight IN NUMBER,
	OtherPrice IN NUMBER,
	AdditionalEngineering IN NUMBER,
	DrawingsCalcs IN NUMBER,
	WTWarranty IN NUMBER,
	Insulation IN NUMBER,
	Freight IN NUMBER,
	FabricatedICF IN NUMBER,
	BuyoutMarkup IN NUMBER,
	DetailsByPercentage IN NUMBER,
	MezzanineNumber IN NUMBER,
	RmgPrice IN NUMBER,
    IpAddress IN VARCHAR2,
    UserId IN NUMBER,
    ProjectId IN NUMBER
)
AS 
BEGIN
   UPDATE "Input_AddLines"
	  SET	
		"BuildingInformationId" = BuildingInformationId,
		"Description" = Description,
		"UnitWeight" = UnitWeight,
		"UnitPrice" = UnitPrice,
		"ListOrNet" = ListOrNet,
		"ExpiresOn" = ExpiresOn,
		"QuoteNumber" = QuoteNumber,
		"QuoteYear" = QuoteYear,
		"EstInitials" = EstInitials,
		"Guid" = Guid,
		"Quantity" = Quantity,
		"Internal" = Internal,
		"IncludeFreight" = IncludeFreight,
		"DontShowPriceWeight" = DontShowPriceWeight,
		"IsSpecialized" = IsSpecialized,
		"ScreenType" = ScreenType,
		"TaxApplied" = TaxApplied,
		"AdjustmentFactor" = AdjustmentFactor,
		"Expired" = Expired,
		"Category" = Category,
		"BuiltupWeight" = BuiltupWeight,
		"BuiltupPrice" = BuiltupPrice,
		"HotrolledWeight" = HotrolledWeight,
		"HotrolledPrice" = HotrolledPrice,
		"ColdformWeight" = ColdformWeight,
		"ColdformPrice" = ColdformPrice,
		"FabColdformWeight" = FabColdformWeight,
		"FabColdformPrice" = FabColdformPrice,
		"RoofpanelWeight" = RoofpanelWeight,
		"RoofpanelPrice" = RoofpanelPrice,
		"WallpanelWeight" = WallpanelWeight,
		"WallpanelPrice" = WallpanelPrice,
		"TrimWeight" = TrimWeight,
		"TrimPrice" = TrimPrice,
		"BuyoutsWeight" = BuyoutsWeight,
		"BuyoutsPrice" = BuyoutsPrice,
		"WarehouseWeight" = WarehouseWeight,
		"WarehousePrice" = WarehousePrice,
		"OtherWeight" = OtherWeight,
		"OtherPrice" = OtherPrice,
		"AdditionalEngineering" = AdditionalEngineering,
		"DrawingsCalcs" = DrawingsCalcs,
		"WTWarranty" = WTWarranty,
		"INSULATION" = Insulation,
		"Freight" = Freight,
		"FabricatedICF" = FabricatedICF,
		"BuyoutMarkup" = BuyoutMarkup,
		"DetailsByPercentage" = DetailsByPercentage,
		"MezzanineNumber" = MezzanineNumber,
		"RmgPrice" = RmgPrice,
        "ModifiedBy" = UserId,
        "ModifiedDate" = CURRENT_TIMESTAMP,
        "IpAddress" = IpAddress,
        "ProjectId" = ProjectId
		
     WHERE
        "MezzanineNumber" = MezzanineNumber;
        
END MEZZANINEADDLINES_UPDATE;
/