CREATE OR REPLACE PROCEDURE abs_mdi."MISCADDLINES_CREATE" 
(
    BuildingInformationId IN NUMBER,
    Description IN VARCHAR2 DEFAULT NULL,
    UnitWeight IN NUMBER,
    UnitPrice IN NUMBER,
    ListOrNet IN VARCHAR2 DEFAULT NULL,
    ExpiresOn IN VARCHAR2 DEFAULT NULL,
    QuoteNumber IN VARCHAR2 DEFAULT NULL,
    QuoteYear IN VARCHAR2 DEFAULT NULL,
    EstInitials IN VARCHAR2 DEFAULT NULL,
    Quantity IN NUMBER,
    Internal IN NUMBER,
    Guid IN RAW,
    IncludeFreight IN VARCHAR2 DEFAULT NULL,
    DontShowPriceWeight IN CHAR,
    IsSpecialized IN CHAR,
    ScreenType IN VARCHAR2 DEFAULT NULL,
	TaxApplied IN NUMBER,
	AdjustmentFactor IN NUMBER,
	Expired IN NUMBER,
	Category IN VARCHAR2,
	BuiltupWeight IN NUMBER,
	BuiltupPrice IN NUMBER,
	HotrolledWeight IN NUMBER,
	HotrolledPrice IN NUMBER,
	ColdformWeight IN NUMBER,
	ColdformPrice IN NUMBER,
	FabColdformWeight IN NUMBER,
	FabColdformPrice IN NUMBER,
	RoofpanelWeight IN NUMBER,
	RoofpanelPrice IN NUMBER,
	WallpanelWeight IN NUMBER,
	WallpanelPrice IN NUMBER,
	TrimWeight IN NUMBER,
	TrimPrice IN NUMBER,
	BuyoutsWeight IN NUMBER,
	BuyoutsPrice IN NUMBER,
	WarehouseWeight IN NUMBER,
	WarehousePrice IN NUMBER,
	OtherWeight IN NUMBER,
	OtherPrice IN NUMBER,
	AdditionalEngineering IN NUMBER,
	DrawingsCalcs IN NUMBER,
	WTWarranty IN NUMBER,
	Insulation IN NUMBER,
	Freight IN NUMBER,
	FabricatedICF IN NUMBER,
	BuyoutMarkup IN NUMBER,
	DetailsByPercentage IN NUMBER,
	MezzanineNumber IN NUMBER,
	RmgPrice IN NUMBER,
    UserId IN NUMBER DEFAULT NULL,
    IpAddress IN VARCHAR2,
	ProjectId IN NUMBER,
    OutputId OUT NUMBER
)
AS 
BEGIN
     INSERT INTO "Input_AddLines"
     (
		"BuildingInformationId",
		"Description",
		"UnitWeight",
		"UnitPrice",
		"ListOrNet",
		"ExpiresOn",
		"QuoteNumber",
		"QuoteYear",
		"EstInitials",
		"Quantity",
		"Internal",
        "Guid",
		"IncludeFreight",
		"DontShowPriceWeight",
		"IsSpecialized",
		"ScreenType",
		"TaxApplied",
		"AdjustmentFactor",
		"Expired",
		"Category",
		"BuiltupWeight",
		"BuiltupPrice",
		"HotrolledWeight",
		"HotrolledPrice",
		"ColdformWeight",
		"ColdformPrice",
		"FabColdformWeight",
		"FabColdformPrice",
		"RoofpanelWeight",
		"RoofpanelPrice",
		"WallpanelWeight",
		"WallpanelPrice",
		"TrimWeight",
		"TrimPrice",
		"BuyoutsWeight",
		"BuyoutsPrice",
		"WarehouseWeight",
		"WarehousePrice",
		"OtherWeight",
		"OtherPrice",
		"AdditionalEngineering",
		"DrawingsCalcs",
		"WTWarranty",
		"INSULATION",
		"Freight",
		"FabricatedICF",
		"BuyoutMarkup",
		"DetailsByPercentage",
		"MezzanineNumber",
		"RmgPrice",
        "IpAddress",
        "IsDelete",
        "CreatedBy",
        "CreatedDate",
		"ProjectId"
     )
     VALUES
     (
        BuildingInformationId,
        Description,
        UnitWeight,
        UnitPrice,
        ListOrNet,
        ExpiresOn,
        QuoteNumber,
        QuoteYear,
        EstInitials,
        Quantity,
        Internal,
        Guid,
        IncludeFreight,
        DontShowPriceWeight,
        IsSpecialized,
        ScreenType,
		TaxApplied,
		AdjustmentFactor,
		Expired,
		Category,
		BuiltupWeight,
		BuiltupPrice,
		HotrolledWeight,
		HotrolledPrice,
		ColdformWeight,
		ColdformPrice,
		FabColdformWeight,
		FabColdformPrice,
		RoofpanelWeight,
		RoofpanelPrice,
		WallpanelWeight,
		WallpanelPrice,
		TrimWeight,
		TrimPrice,
		BuyoutsWeight,
		BuyoutsPrice,
		WarehouseWeight,
		WarehousePrice,
		OtherWeight,
		OtherPrice,
		AdditionalEngineering,
		DrawingsCalcs,
		WTWarranty,
		Insulation,
		Freight,
		FabricatedICF,
		BuyoutMarkup,
		DetailsByPercentage,
		MezzanineNumber,
		RmgPrice,
        IpAddress,
        'N',
        UserId,
        CURRENT_TIMESTAMP,
		ProjectId
     )
     RETURNING "AddLinesId" INTO OutputId;
END MiscAddLines_Create;
/