CREATE OR REPLACE PROCEDURE abs_mdi."OPENAREAS_SELECT" 
(
    ID IN NUMBER,
    Output_Data OUT SYS_REFCURSOR
)
AS 
BEGIN
  OPEN Output_Data FOR 
      SELECT 
        "OA"."Id",
        "OA"."BuildingNumber",
        "BI"."BuildingLabel",
        "BI"."BuildingName",
        "OA"."Elevation",
        "OA"."BayNumber",
        "OA"."DistFromLeftCorner",
        "OA"."DistFromLeftColumn",
        "OA"."OpeningType",
        "OA"."OpenEndwall",
        "OA"."OpeningWidth",
        "OA"."OpeningHeight",
        "OA"."MaterialType",
        "OA"."MaterialWeight",
        "OA"."MaterialThickness",
        "OA"."DistSteelLinetoBeam",
        "OA"."DistSteelLinetoMaterial",
        "OA"."MasonryType",
        "OA"."MaterialDirection",
        "OA"."ShearWall",
        "OA"."PercentOpenforWind",
        "OA"."LeftJamb",
        "OA"."LeftJambFlash",
        "OA"."LeftJambFlangeWidth",
        "OA"."LeftJambFlangeThick",
        "OA"."LeftJambWebDepth",
        "OA"."LeftJambWebThick",
        "OA"."RightJamb",
        "OA"."RightJambFlash",
        "OA"."RightJambFlangeWidth",
        "OA"."RightJambFlangeThick",
        "OA"."RightJambWebDepth",
        "OA"."RightJambWebThick",
        "OA"."HeaderFlash",
        "OA"."HeaderFlashType",
        "OA"."HeaderFlashColor",
        "OA"."AttachmentNumber",
        "OA"."AllowableDrift",
        "OA"."BeamSelected",
        "OA"."BeamStartCol",
        "OA"."BeamStopCol",
        "OA"."BeamHeight",
        "OA"."BeamFlanges",
        "OA"."BeamWebThick",
        "OA"."BeamWebDepth",
        "OA"."BeamFlangeThick",
        "OA"."BeamFlangeWidth",
        "OA"."BeamDeflection",
        "OA"."BeamAttachmentSpacing",
        "OA"."BeamSteelline",
        "OA"."BeamSection",
        "OA"."BeamWeight",
        "OA"."BeamPrice",
        "OA"."BeamIsPriced",
        "OA"."BeamErrorCode",
        "OA"."LedgerAngle",
        "OA"."AllElevations",
        "OA"."ColumnBracing",
        "OA"."NoOutsideColumns",
        "OA"."PanelsSpan",
        "OA"."NoFlangeBelow",
        "OA"."AllowableInsulation",
        "OA"."PartitionNumber",
        "OA"."DeductPanelsTrimOnly",
        "OA"."FullWidth",
        "OA"."ParapetByOther",
        "OA"."HeaderFlashColorValsparCode",
        "OA"."HeaderFlashColorSpecialName",
        --"SupportBeanByManufacturer",
        --"BeamLocation",
        --"BeamType",
        "OA"."IpAddress",
        "OA"."IsDeleted"
      FROM "OpenAreas" OA
      INNER JOIN "BuildingInformation" BI ON "BI"."BuildingInformationId" = "OA"."BuildingNumber"
       WHERE "OA"."Id" = Id;
END OPENAREAS_SELECT;
/