CREATE OR REPLACE PROCEDURE abs_mdi."OPENAREAS_CREATE" 
(       
	BuildingNumber IN NUMBER,
	Elevation IN VARCHAR2,
	BayNumber IN NUMBER,
	DistFromLeftCorner IN DECIMAL,
	DistFromLeftColumn IN DECIMAL,
	OpeningType IN VARCHAR2,
	OpenEndwall IN NUMBER,
	OpeningWidth IN DECIMAL,
	OpeningHeight IN DECIMAL,
	MaterialType IN VARCHAR2,
	MaterialWeight IN DECIMAL,
	MaterialThickness IN DECIMAL,
	DistSteelLinetoBeam IN DECIMAL,
	DistSteelLinetoMaterial IN DECIMAL,
	MasonryType IN VARCHAR2,
	MaterialDirection IN VARCHAR2,
	ShearWall IN NUMBER,
	PercentOpenforWind IN DECIMAL,
	LeftJamb IN NUMBER,
	LeftJambFlash IN NUMBER,
	LeftJambFlangeWidth IN DECIMAL,
	LeftJambFlangeThick IN DECIMAL,
	LeftJambWebDepth IN DECIMAL,
	LeftJambWebThick IN DECIMAL,
	RightJamb IN NUMBER,
	RightJambFlash IN NUMBER,
	RightJambFlangeWidth IN DECIMAL,
	RightJambFlangeThick IN DECIMAL,
	RightJambWebDepth IN DECIMAL,
	RightJambWebThick IN DECIMAL,
	HeaderFlash IN NUMBER,
	HeaderFlashType IN VARCHAR2,
	HeaderFlashColor IN VARCHAR2,
	AttachmentNumber IN NUMBER,
	AllowableDrift IN DECIMAL,
	BeamSelected IN NUMBER,
	BeamStartCol IN NUMBER,
	BeamStopCol IN NUMBER,
	BeamHeight IN DECIMAL,
	BeamFlanges IN NUMBER,
	BeamWebThick IN VARCHAR2,
	BeamWebDepth IN DECIMAL,
	BeamFlangeThick IN DECIMAL,
	BeamFlangeWidth IN DECIMAL,
	BeamDeflection IN DECIMAL,
	BeamAttachmentSpacing IN DECIMAL,
	BeamSteelline IN NUMBER,
	BeamSection IN VARCHAR2,
	BeamWeight IN NUMBER,
	BeamPrice IN NUMBER,
	BeamIsPriced IN NUMBER,
	BeamErrorCode IN NUMBER,
	LedgerAngle IN NUMBER,
	AllElevations IN NUMBER,
	ColumnBracing IN VARCHAR2,
	NoOutsideColumns IN NUMBER,
	PanelsSpan IN NUMBER,
	NoFlangeBelow IN DECIMAL,
	AllowableInsulation IN DECIMAL,
	PartitionNumber IN NUMBER,
	DeductPanelsTrimOnly IN NUMBER,
	FullWidth IN NUMBER,
	ParapetByOther IN NUMBER,
	HeaderFlashColorValsparCode IN VARCHAR2,
	HeaderFlashColorSpecialName IN VARCHAR2,
    CreatedBy IN NUMBER,
    IpAddress IN VARCHAR2,
    OutputId OUT NUMBER
)
AS 
BEGIN
    INSERT INTO "OpenAreas" 
    (
        "BuildingNumber",
        "Elevation",
        "BayNumber",
        "DistFromLeftCorner",
        "DistFromLeftColumn",
        "OpeningType",
        "OpenEndwall",
        "OpeningWidth",
        "OpeningHeight",
        "MaterialType",
        "MaterialWeight",
        "MaterialThickness",
        "DistSteelLinetoBeam",
        "DistSteelLinetoMaterial",
        "MasonryType",
        "MaterialDirection",
        "ShearWall",
        "PercentOpenforWind",
        "LeftJamb",
        "LeftJambFlash",
        "LeftJambFlangeWidth",
        "LeftJambFlangeThick",
        "LeftJambWebDepth",
        "LeftJambWebThick",
        "RightJamb",
        "RightJambFlash",
        "RightJambFlangeWidth",
        "RightJambFlangeThick",
        "RightJambWebDepth",
        "RightJambWebThick",
        "HeaderFlash",
        "HeaderFlashType",
        "HeaderFlashColor",
        "AttachmentNumber",
        "AllowableDrift",
        "BeamSelected",
        "BeamStartCol",
        "BeamStopCol",
        "BeamHeight",
        "BeamFlanges",
        "BeamWebThick",
        "BeamWebDepth",
        "BeamFlangeThick",
        "BeamFlangeWidth",
        "BeamDeflection",
        "BeamAttachmentSpacing",
        "BeamSteelline",
        "BeamSection",
        "BeamWeight",
        "BeamPrice",
        "BeamIsPriced",
        "BeamErrorCode",
        "LedgerAngle",
        "AllElevations",
        "ColumnBracing",
        "NoOutsideColumns",
        "PanelsSpan",
        "NoFlangeBelow",
        "AllowableInsulation",
        "PartitionNumber",
        "DeductPanelsTrimOnly",
        "FullWidth",
        "ParapetByOther",
        "HeaderFlashColorValsparCode",
        "HeaderFlashColorSpecialName",
        "IsDeleted",
        "CreatedBy",
        "CreatedDate",
        "IpAddress"
    )
    VALUES
    (
		BuildingNumber,
		Elevation,
		BayNumber,
		DistFromLeftCorner,
		DistFromLeftColumn,
		OpeningType,
		OpenEndwall,
		OpeningWidth,
		OpeningHeight,
		MaterialType,
		MaterialWeight,
		MaterialThickness,
		DistSteelLinetoBeam,
		DistSteelLinetoMaterial,
		MasonryType,
		MaterialDirection,
		ShearWall,
		PercentOpenforWind,
		LeftJamb,
		LeftJambFlash,
		LeftJambFlangeWidth,
		LeftJambFlangeThick,
		LeftJambWebDepth,
		LeftJambWebThick,
		RightJamb,
		RightJambFlash,
		RightJambFlangeWidth,
		RightJambFlangeThick,
		RightJambWebDepth,
		RightJambWebThick,
		HeaderFlash,
		HeaderFlashType,
		HeaderFlashColor,
		AttachmentNumber,
		AllowableDrift,
		BeamSelected,
		BeamStartCol,
		BeamStopCol,
		BeamHeight,
		BeamFlanges,
		BeamWebThick,
		BeamWebDepth,
		BeamFlangeThick,
		BeamFlangeWidth,
		BeamDeflection,
		BeamAttachmentSpacing,
		BeamSteelline,
		BeamSection,
		BeamWeight,
		BeamPrice,
		BeamIsPriced,
		BeamErrorCode,
		LedgerAngle,
		AllElevations,
		ColumnBracing,
		NoOutsideColumns,
		PanelsSpan,
		NoFlangeBelow,
		AllowableInsulation,
		PartitionNumber,
		DeductPanelsTrimOnly,
		FullWidth,
		ParapetByOther,
		HeaderFlashColorValsparCode,
		HeaderFlashColorSpecialName,
        'N',
        CreatedBy,
        CURRENT_TIMESTAMP,
        IpAddress
    )
    RETURNING "Id" into OutputId;
    
END OPENAREAS_CREATE;
/