CREATE OR REPLACE PROCEDURE abs_mdi."PROJECT_UPDATE" (
    ProjectId                    IN  NUMBER,
    ProjectName                  IN  VARCHAR2,
    ProjectStatusId              IN  NUMBER,
    ProjectUseId                 IN  NUMBER,
    RiskCategoryId               IN  NUMBER,
    CityLimit                    IN  VARCHAR2,
    MaterialOriginId             IN  NUMBER,
    Address1                     IN  VARCHAR2,
    Address2                     IN  VARCHAR2,
    City                         IN  VARCHAR2,
    Region                       IN  VARCHAR2,
    State                        IN  VARCHAR2,
    Country                      IN  VARCHAR2,
    ZipPostalCode                IN  VARCHAR2,
    IpAddress                    IN  VARCHAR2,
    QuoteRequestDate             IN  VARCHAR2,
    PriceStatus                  IN  VARCHAR2,
    Latitude                     IN  VARCHAR2,
    Longitude                    IN  VARCHAR2,
    UserId                       IN  VARCHAR2,
    DesignCodeId                 IN  NUMBER,
    DesignCodeName               IN  NVARCHAR2,
    ProjectUseCategoryId         IN  NUMBER,
    WindSpeed                    IN  FLOAT,
    WindExposureId               IN  NUMBER,
    IsHurricaneCoastline         IN  CHAR,
    LiveLoad                     IN  FLOAT,
    IsLiveLoadReductionAllowed   IN  CHAR,
    GroundSnow                   IN  FLOAT,
    SnowExposureId               IN  NUMBER,
    MinimumSnowLoad              IN  FLOAT,
    Elevation                    IN  FLOAT,
    RainIntensity                IN  FLOAT,
    SustainablilityGoalId        IN  NUMBER,
    IsClimateControlled          IN  CHAR,
    EnergyEfficiencyId           IN  NUMBER,
    IsAirInfiltrationRequired    IN  CHAR,
    CustomerNo                   IN  VARCHAR2,
    SeismicSa                    IN  FLOAT,
    SeismicS1                    IN  FLOAT,
    SeismicSnowLoad              IN  VARCHAR2,
    SeismicSnowPercentage        IN  NUMBER,
    SiteClassId                  IN  NUMBER,
    InputDimensional             IN  VARCHAR2,
    InputEngineering             IN  VARCHAR2,
    OutputDimensional            IN  VARCHAR2,
    OutputEngineering            IN  VARCHAR2,
    CurrencyDimensional          IN  VARCHAR2,
    IsCanadaBasedDesignCode      IN  CHAR,
    IsDesignCodeIbc2012Based     IN  CHAR,
    RainLoad                     IN  FLOAT,
    SeismicSa1Dot0               IN  FLOAT,
    SeismicSa2Dot0               IN  FLOAT,
    WindLoad                     IN  FLOAT,
    IsUserDefinedSustainability  IN  CHAR,
    UserDefinedSustainability    IN  NUMBER,
    CBBInquiryNumber             IN  VARCHAR,
    MinAnchorRodDiameter         IN  VARCHAR,
    TDIRequired                  IN  CHAR,
    UsingSystemGeneratedRodPlan  IN  CHAR,
    EnteredBy                    IN  VARCHAR,
    PGASeismic                   IN   FLOAT default 0,
    IsOverrideSeismicSa          IN   CHAR default 'N',
    IsOverrideSeismicS1          IN   CHAR default 'N',
    IsOverrideSeismicSa1Dot0     IN   CHAR default 'N',
    IsOverrideSeismicSa2Dot0     IN   CHAR default 'N',
    IsOverrideWindSpeed          IN   CHAR default 'N',
    IsOverrideWindLoad           IN   CHAR default 'N',
    IsOverrideLiveLoad           IN   CHAR default 'N',
    IsOverrideGroundSnow         IN   CHAR default 'N',
    IsOverrideRainIntensity      IN   CHAR default 'N',
    IsOverrideRainLoad           IN   CHAR default 'N',
    IsOverridePGASeismic         IN   CHAR default 'N',
    WindLoadType                 IN   VARCHAR DEFAULT 'mph'
) AS
BEGIN
    UPDATE "Project"
    SET
        "ProjectName" = ProjectName,
        "ProjectStatusId" = ProjectStatusId,
        "ProjectUseId" = ProjectUseId,
        "RiskCategoryId" = RiskCategoryId,
        "CityLimit" = CityLimit,
        "MaterialOriginId" = MaterialOriginId,
        "Address1" = Address1,
        "Address2" = Address2,
        "City" = City,
        "Region" = Region,
        "State" = State,
        "Country" = Country,
        "ZipPostalCode" = ZipPostalCode,
        "IpAddress" = "IpAddress",
        "QuoteRequestDate" = TO_DATE(QuoteRequestDate, 'MM/DD/YYYY'),
        "PriceStatus" = PriceStatus,
        "Latitude" = Latitude,
        "Longitude" = Longitude,
        "ModifiedBy" = UserId,
        "ModifiedDate" = CURRENT_TIMESTAMP,
        "DesignCodeId" = DesignCodeId,
        "DesignCodeName" = DesignCodeName,
        "ProjectUseCategoryid" = ProjectUseCategoryId,
        "WindSpeed" = WindSpeed,
        "WindExposureId" = WindExposureId,
        "IsHurricaneCoastline" = IsHurricaneCoastline,
        "LiveLoad" = LiveLoad,
        "IsLiveLoadReductionAllowed" = IsLiveLoadReductionAllowed,
        "GroundSnow" = GroundSnow,
        "SnowExposureId" = SnowExposureId,
        "MinimumSnowLoad" = MinimumSnowLoad,
        "Elevation" = Elevation,
        "RainIntensity" = RainIntensity,
        "SustainablilityGoalId" = SustainablilityGoalId,
        "IsClimateControlled" = IsClimateControlled,
        "EnergyEfficiencyId" = EnergyEfficiencyId,
        "IsAirInfiltrationRequired" = IsAirInfiltrationRequired,
        "CustomerNo" = CustomerNo,
        "SeismicSa" = SeismicSa,
        "SeismicS1" = SeismicS1,
        "SeismicSnowLoad" = SeismicSnowLoad,
        "SeismicSnowPercentage" = SeismicSnowPercentage,
        "SiteClassId" = SiteClassId,
        "InputDimensional" = InputDimensional,
        "InputEngineering" = InputEngineering,
        "OutputDimensional" = OutputDimensional,
        "OutputEngineering" = OutputEngineering,
        "CurrencyDimensional" = CurrencyDimensional,
        "IsCanadaBasedDesignCode" = IsCanadaBasedDesignCode,
        "IsDesignCodeIbc2012Based" = IsDesignCodeIbc2012Based,
        "RainLoad" = RainLoad,
        "SeismicSa1Dot0" = SeismicSa1Dot0,
        "SeismicSa2Dot0" = SeismicSa2Dot0,
        "WindLoad" = WindLoad,
        "IsUserDefinedSustainability" = IsUserDefinedSustainability,
        "UserDefinedSustainability" = UserDefinedSustainability,
        "CBBInquiryNumber" = CBBInquiryNumber,
        "MinAnchorRodDiameter" = MinAnchorRodDiameter,
        "TDIRequired" = TDIRequired,
        "UsingSystemGeneratedRodPlan" = UsingSystemGeneratedRodPlan,
        "EnteredBy" = EnteredBy,
        "PGASeismic" = PGASeismic,
        "IsOverrideSeismicSa" = IsOverrideSeismicSa,
        "IsOverrideSeismicS1" = IsOverrideSeismicS1,
        "IsOverrideSeismicSa1Dot0" = IsOverrideSeismicSa1Dot0,
        "IsOverrideSeismicSa2Dot0" = IsOverrideSeismicSa2Dot0,
        "IsOverrideWindSpeed" = IsOverrideWindSpeed,
        "IsOverrideWindLoad" = IsOverrideWindLoad,
        "IsOverrideLiveLoad" = IsOverrideLiveLoad,
        "IsOverrideGroundSnow" = IsOverrideGroundSnow,
        "IsOverrideRainIntensity" = IsOverrideRainIntensity,
        "IsOverrideRainLoad" = IsOverrideRainLoad,
        "IsOverridePGASeismic" = IsOverridePGASeismic,
        "WindLoadType" = WindLoadType
    WHERE
        "ProjectId" = ProjectId;
END Project_Update;
/