CREATE OR REPLACE PROCEDURE abs_mdi.Project_Create (
    ProjectName                  IN   VARCHAR2,
    ProjectStatusId              IN   NUMBER,
    RiskCategoryId               IN   NUMBER,
    ProjectUseId                 IN   NUMBER,
    MaterialOriginId             IN   NUMBER,
    CityLimit                    IN   VARCHAR2,
    Address1                     IN   VARCHAR2,
    Address2                     IN   VARCHAR2,
    City                         IN   VARCHAR2,
    Region                       IN   VARCHAR2,
    State                        IN   VARCHAR2,
    ZipPostalCode                IN   VARCHAR2,
    Country                      IN   VARCHAR2,
    QuoteRequestDate             IN   VARCHAR2,
    PriceStatus                  IN   VARCHAR2,
    Latitude                     IN   VARCHAR2,
    Longitude                    IN   VARCHAR2,
    IpAddress                    IN   VARCHAR2,
    CustomerNo                   IN   VARCHAR2,
    UserId                       IN   VARCHAR2,
    DesignCodeId                 IN   NUMBER,
    DesignCodeName               IN   NVARCHAR2,
    ProjectUseCategoryId         IN   NUMBER,
    WindSpeed                    IN   FLOAT,
    WindExposureId               IN   NUMBER,
    IsHurricaneCoastline         IN   CHAR,
    LiveLoad                     IN   FLOAT,
    IsLiveLoadReductionAllowed   IN   CHAR,
    GroundSnow                   IN   FLOAT,
    SnowExposureId               IN   NUMBER,
    MinimumSnowLoad              IN   FLOAT,
    Elevation                    IN   FLOAT,
    RainIntensity                IN   FLOAT,
    SustainablilityGoalId        IN   NUMBER,
    IsClimateControlled          IN   CHAR,
    EnergyEfficiencyId           IN   NUMBER,
    IsAirInfiltrationRequired    IN   CHAR,
    SeismicSa                    IN   FLOAT,
    SeismicS1                    IN   FLOAT,
    SeismicSnowLoad              IN   VARCHAR2,
    SeismicSnowPercentage        IN   NUMBER,
    SiteClassId                  IN   NUMBER,
    InputDimensional             IN   VARCHAR2,
    InputEngineering             IN   VARCHAR2,
    OutputDimensional            IN   VARCHAR2,
    OutputEngineering            IN   VARCHAR2,
    CurrencyDimensional          IN   VARCHAR2,
    IsCanadaBasedDesignCode      IN   CHAR,
    IsDesignCodeIbc2012Based     IN   CHAR,
    RainLoad                     IN   FLOAT,
    SeismicSa1Dot0               IN   FLOAT,
    SeismicSa2Dot0               IN   FLOAT,
    WindLoad                     IN   FLOAT,
    IsUserDefinedSustainability  IN   CHAR,
    UserDefinedSustainability    IN   NUMBER,
    CompanyId                    IN   NUMBER,
    CBBInquiryNumber             IN   VARCHAR,
    MinAnchorRodDiameter         IN   VARCHAR,
    TDIRequired                  IN   CHAR,
    UsingSystemGeneratedRodPlan  IN   CHAR,
    EnteredBy                    IN   VARCHAR,
    UserRoleId                   IN   NUMBER,
    PGASeismic                   IN   FLOAT DEFAULT 0,
    IsOverrideSeismicSa          IN   CHAR DEFAULT 'N',
    IsOverrideSeismicS1          IN   CHAR DEFAULT 'N',
    IsOverrideSeismicSa1Dot0     IN   CHAR DEFAULT 'N',
    IsOverrideSeismicSa2Dot0     IN   CHAR DEFAULT 'N',
    IsOverrideWindSpeed          IN   CHAR DEFAULT 'N',
    IsOverrideWindLoad           IN   CHAR DEFAULT 'N',
    IsOverrideLiveLoad           IN   CHAR DEFAULT 'N',
    IsOverrideGroundSnow         IN   CHAR DEFAULT 'N',
    IsOverrideRainIntensity      IN   CHAR DEFAULT 'N',
    IsOverrideRainLoad           IN   CHAR DEFAULT 'N',
    IsOverridePGASeismic         IN   CHAR DEFAULT 'N',
    UserType                     IN   VARCHAR DEFAULT NULL,
    WindLoadType                 IN   VARCHAR DEFAULT 'mph',
    IsModified IN CHAR DEFAULT NULL,
    IsSeismicForSchools IN CHAR DEFAULT NULL,
    CityDataLocation    IN VARCHAR DEFAULT NULL,    
    IsIntlJobsite                IN   CHAR DEFAULT NULL,
    OutputId                     OUT  NUMBER,
    OutputPaymentId              OUT  NUMBER
) AS
    ProjectBuildingType NUMBER;
    CustomerName Varchar2(50);
    IsCustomerLogin NUMBER;
    UserDetailId NUMBER;
    CustomerId NUMBER;
   	Customer_No NUMBER;
BEGIN
	SELECT count(nvl("CustomerNo",0)), "UserDetailId"  INTO IsCustomerLogin,UserDetailId  FROM "USR_UserDetail" WHERE "UserId" = UserId AND "IsDelete" = 'N';
	IF IsCustomerLogin > 0 THEN 	
		SELECT "CustomerId" INTO CustomerId FROM "USR_Brand_Customer" WHERE "UserDetailId" = UserDetailId AND rownum=1;
		SELECT "CustomerNo" INTO Customer_No FROM "Customer" WHERE "CustomerID"  = CustomerId AND "CompanyId"  = CompanyId AND rownum=1;
	END IF;
	
    SELECT
        bap."ProjectBuildingType"
    INTO ProjectBuildingType
    FROM
             "BuilderAccessPermission" bap
        INNER JOIN "USR_PER_BuilderAccess"  pb ON pb."BuilderAccessPermissionId" = bap."BuilderAccessPermissionId"
        INNER JOIN "USR_UserDetail"         U ON U."UserDetailId" = pb."UserDetailId"
                                         AND pb."BrandId" = CompanyId
                                         AND pb."PermissionGroupId" = UserRoleId
                                         AND U."UserId" = UserId AND rownum = 1;

    INSERT INTO "Project" (
        "ProjectName",
        "ProjectStatusId",
        "RiskCategoryId",
        "ProjectUseId",
        "MaterialOriginId",
        "CityLimit",
        "IsIntlJobsite",
        "Address1",
        "Address2",
        "City",
        "Region",
        "State",
        "ZipPostalCode",
        "Country",
        "QuoteRequestDate",
        "PriceStatus",
        "Latitude",
        "Longitude",
        "UserId",
        "CreatedDate",
        "CustomerNo",
        "IpAddress",
        "IsDelete",
        "IsActive",
        "DesignCodeId",
        "DesignCodeName",
        "ProjectUseCategoryid",
        "WindSpeed",
        "WindExposureId",
        "IsHurricaneCoastline",
        "LiveLoad",
        "IsLiveLoadReductionAllowed",
        "GroundSnow",
        "SnowExposureId",
        "MinimumSnowLoad",
        "Elevation",
        "RainIntensity",
        "SustainablilityGoalId",
        "IsClimateControlled",
        "EnergyEfficiencyId",
        "IsAirInfiltrationRequired",
        "SeismicSa",
        "SeismicS1",
        "SeismicSnowLoad",
        "SeismicSnowPercentage",
        "SiteClassId",
        "InputDimensional",
        "InputEngineering",
        "OutputDimensional",
        "OutputEngineering",
        "CurrencyDimensional",
        "IsCanadaBasedDesignCode",
        "IsDesignCodeIbc2012Based",
        "RainLoad",
        "SeismicSa1Dot0",
        "SeismicSa2Dot0",
        "WindLoad",
        "IsUserDefinedSustainability",
        "UserDefinedSustainability",
        "CompanyId",
        "CBBInquiryNumber",
        "MinAnchorRodDiameter",
        "TDIRequired",
        "UsingSystemGeneratedRodPlan",
        "EnteredBy",
        "UserRoleId",
        "ProjectBuildingType",
        "ProjectStage",
        "PGASeismic",
        "IsOverrideSeismicSa",
        "IsOverrideSeismicS1",
        "IsOverrideSeismicSa1Dot0",
        "IsOverrideSeismicSa2Dot0",
        "IsOverrideWindSpeed",
        "IsOverrideWindLoad",
        "IsOverrideLiveLoad",
        "IsOverrideGroundSnow",
        "IsOverrideRainIntensity",
        "IsOverrideRainLoad",
        "IsOverridePGASeismic",
        "UserType",
        "WindLoadType",
        "IsSeismicForSchools",
        "CityDataLocation"        
    ) VALUES (
        ProjectName,
        ProjectStatusId,
        RiskCategoryId,
        ProjectUseId,
        MaterialOriginId,
        CityLimit,
        IsIntlJobsite,
        Address1,
        Address2,
        City,
        Region,
        State,
        ZipPostalCode,
        Country,
        TO_DATE(QuoteRequestDate, 'MM/DD/YYYY'),
        PriceStatus,
        Latitude,
        Longitude,
        UserId,
        CURRENT_TIMESTAMP,
        CASE WHEN IsCustomerLogin > 0 THEN CAST(Customer_No AS varchar2(50)) ELSE CustomerNo END,
        IpAddress,
        'N',
        'Y',
        DesignCodeId,
        DesignCodeName,
        ProjectUseCategoryId,
        WindSpeed,
        WindExposureId,
        IsHurricaneCoastline,
        LiveLoad,
        IsLiveLoadReductionAllowed,
        GroundSnow,
        SnowExposureId,
        MinimumSnowLoad,
        Elevation,
        RainIntensity,
        SustainablilityGoalId,
        IsClimateControlled,
        EnergyEfficiencyId,
        IsAirInfiltrationRequired,
        SeismicSa,
        SeismicS1,
        SeismicSnowLoad,
        SeismicSnowPercentage,
        SiteClassId,
        InputDimensional,
        InputEngineering,
        OutputDimensional,
        OutputEngineering,
        CurrencyDimensional,
        IsCanadaBasedDesignCode,
        IsDesignCodeIbc2012Based,
        RainLoad,
        SeismicSa1Dot0,
        SeismicSa2Dot0,
        WindLoad,
        IsUserDefinedSustainability,
        UserDefinedSustainability,
        CompanyId,
        CBBInquiryNumber,
        MinAnchorRodDiameter,
        TDIRequired,
        UsingSystemGeneratedRodPlan,
        EnteredBy,
        UserRoleId,
        ProjectBuildingType,
        'In Progress',
        PGASeismic,
        IsOverrideSeismicSa,
        IsOverrideSeismicS1,
        IsOverrideSeismicSa1Dot0,
        IsOverrideSeismicSa2Dot0,
        IsOverrideWindSpeed,
        IsOverrideWindLoad,
        IsOverrideLiveLoad,
        IsOverrideGroundSnow,
        IsOverrideRainIntensity,
        IsOverrideRainLoad,
        IsOverridePGASeismic,
        UserType,
        WindLoadType,
        IsSeismicForSchools,
        CityDataLocation
    ) RETURNING "ProjectId" INTO OutputId;

    INSERT INTO "EDSPrice_O_ProjectTotal" (
        "ProjectNumber",
        "BaseTotalWeight",
        "BaseTotalPrice",
        "AccessoryTotalWeight",
        "AccessoryTotalPrice",
        "ListAddlinesWeight",
        "ListAddlinesPrice",
        "NetAddlinesWeight",
        "NetAddlinesPrice",
        "BuyoutsWeight",
        "BuyoutsPrice",
        "DiscountWeight",
        "DiscountPrice",
        "MultiplierWeight",
        "MultiplierPrice",
        "InsulationWeight",
        "InsulationPrice",
        "IncompletePricing",
        "ProcessingCharges",
        "Surcharge",
        "MezzNetWeight",
        "MezzNetPrice",
        "MezzListWeight",
        "MezzListPrice",
        "ComponentsWeight",
        "ComponentsPrice",
        "FreightPrice",
        "FreightWeight",
        "FreightRate1",
        "FreightRate2",
        "FreightLoads1",
        "FreightLoads2",
        "SalesTax",
        "FreightMiles1",
        "FreightMiles2",
        "SalesTaxPercent",
        "DunnageWeight",
        "ErectionPrice",
        "AdditionalCut",
        "SingleArticleTax",
        "FreightTaxable",
        "TotalSellFobPlant",
        "TotalFreight",
        "TotalTax",
        "GrandTotal",
        "StandardMultiplier",
        "SellingPrice",
        "TransferCost",
        "NetAddlinesWeightFreight",
        "SubmittalPackagesPrice",
        "RegionalAdjustment",
        "IPSFreightPrice",
        "IPSFreightWeight",
        "IPSFreightRate",
        "IPSFreightLoads",
        "AuthorizedAdjustment",
        "TotalGrossMargin",
        "ComponentsListWeight",
        "ComponentsListPrice",
        "ListMargin",
        "NetMargin",
        "LBPFreightPrice",
        "LBPFreightWeight",
        "LBPFreightRate",
        "LBPFreightLoads",
        "ListMarginPercentage",
        "NetMarginPercentage",
        "ProjectId"
    ) VALUES (
        OutputId,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        OutputId
    );

    INSERT INTO "EDSPrice_O_Deflections" ( "ProjectId" ) VALUES ( OutputId );

    INSERT INTO "EDSPrice_O_RMGData" ( "ProjectId" ) VALUES ( OutputId );

    INSERT INTO "EDSPrice_O_Buyouts" ( "ProjectId" ) VALUES ( OutputId );

    INSERT INTO "EDSPrice_I_Payment" (
            "ProjectId",
            "CreditTerms",
            "TaxExemptStatus",
            "CreatedBy",
            "IpAddress"
        ) VALUES (
            OutputId,
            'To Be Determined',
            'Taxable',
            UserId,
            IpAddress
        ) RETURNING "PaymentId" INTO OutputPaymentId;

    if CustomerNo != '0' then
    begin
        select "CustomerName" into CustomerName from "Customer" where "CustomerNo" = CustomerNo and "CompanyId" = CompanyId and rownum =1;
        INSERT INTO "Purchaser" ("ProjectId","BuyerNumber","BuyerName","CreatedBy","CreatedDate","IpAddress","IsDelete") 
        values(OutputId,CustomerNo,CustomerName,0,CURRENT_TIMESTAMP,IpAddress,'N');
    end;
    END IF;

    IF IsModified = 'Y' 
     THEN
     update "Project"
     SET 
     "IsPriceReset" = 'Y',
     "ProjectStage" = 'In Progress',
	 "Price" = 0
     WHERE "ProjectId"= (select "ProjectId" from "Project" WHERE "ProjectName" = ProjectName)  AND "IsPriceReset" = 'N';

     END IF;

    IF IsIntlJobsite = 'Y' or State = 'AK' or  State = 'HI' then
         update "Project" SET "national_accounts" = 'Y' WHERE "ProjectId" = OutputId;
    END IF;
END Project_Create;
/