CREATE OR REPLACE PROCEDURE abs_mdi."ROOF_SELECT" 
(
   --RoofId IN NUMBER,
   BuildingInformationId IN NUMBER,
   Output_Data OUT SYS_REFCURSOR
)
AS 
BEGIN
    OPEN Output_Data FOR
     SELECT 
            Roof."RoofId",
            Roof."Type",
            Roof."Width",
            Roof."ULRating",
            Roof."Thick",
            Roof."Profile",
            Roof."Gauge",
            Roof."InteriorSkinProfile",
            Roof."InteriorSkinGauge",
            Roof."InteriorSkinTexture",
            Roof."IncludeToolKit",
            Roof."ProvideHandTools",
            Roof."ColdStorageBuilding",
            Roof."FactoryAppliedSealant",
            Roof."FastenerType",
            Roof."FastenerHeadFinish",
            Roof."FastenerLength",
            Roof."Warranty",
            Roof."WeathertightnessTerm",
            Roof."HasSnowRetentionSystem",
            Roof."SnowRetentionRp1",
            Roof."SnowRetentionRp2",
            Roof."SnowRetentionRp3",
            Roof."SnowRetentionRp4",
            Roof."ThermalBlockType",
            Roof."FMRating",
            Roof."EaveIcing",
            Roof."WideTape",
            Roof."Clip",
            Roof."StructScrews",
            Roof."StitchScrews",
            Roof."Material",
            Roof."ThermalBlock",
            Roof."MetalRibClosure",
            Roof."SealedRoof",
            Roof."RidgePan",
            Roof."AlignmentStrip",
            Roof."ULLetter",
            Roof."EavePanelExtension",
            --Roof."IsBuyout",
            Roof."SquareFeet",
            Roof."ThermalBlockThickness",
            Roof."ProvideBlocks",
            Roof."RoofFirst",
            Roof."InsulationClips",
            Roof."Weathertightness",
            Roof."SealedEave",
            Roof."ThickInsulation",
            Roof."RTSSystem",
            Roof."RTSFinish",
            Roof."RTSPanelType",
            Roof."RTSThickness",
            Roof."RTSSpacing", 
            Roof."RTSPanelGauge",
            Roof."SeamerRental",
            Roof."BuildingInformationId",
            Roof."BURLoad",
            Roof."NotByStar",
            Roof."IncludeSnowClipPerPanel",
            Roof."SnowClipQuantity",
            Roof."ExteriorSkinTexture",
            Roof."FinishWarranty",
            Roof."RValue",
            Roof."Rp1SnowLoad",
            Roof."Rp2SnowLoad",
            Roof."Rp3SnowLoad",
            Roof."Rp4SnowLoad",
            ColorSel."RoofPanel",
            ColorSel."RoofPanelValsparCode",
            ColorSel."RoofPanelSpecialName",
            ColorSel."RoofInteriorSkin",
            ColorSel."RoofInteriorSkinValsparCode",
            ColorSel."RoofInteriorSkinSpecialName"
         FROM "Input_Roof" Roof 
         JOIN "BuildingInformation" Info ON Roof."BuildingInformationId"=Info."BuildingInformationId"
         JOIN "Input_TrimColorSelections" ColorSel ON Roof."BuildingInformationId"=ColorSel."BuildingNumber"
         WHERE Roof."BuildingInformationId" = BuildingInformationId ; 
END ROOF_SELECT;
/