CREATE OR REPLACE PROCEDURE abs_mdi."SP_TEST" 
(
    P_TABLE_IN IN CUSTOM_TYPE_ARRAY--,
    --P_RESULT_OUT OUT SYS_REFCURSOR 
) AS 
--P_TABLE_IN CUSTOM_TYPE_ARRAY;
BEGIN
   -- OPEN P_RESULT_OUT FOR
    INSERT INTO TT(a1,a2)
    SELECT attribute1, attribute2 --INTO TT.a1, TT.a2
    FROM TABLE(P_TABLE_IN);
END SP_TEST;
/