CREATE OR REPLACE PROCEDURE abs_mdi."SYSTEMVARIABLES_CREATE" 
(       
        MinimumPasswordLength IN NUMBER,
        LoginConfirmationDays IN NUMBER,
        PasswordResetConfirmationDays IN NUMBER,
        LoginRetries IN NUMBER,
        SessionTimeout IN NUMBER,
        MaximumAttachmentSize IN NUMBER,
        AcceptableAttachmentTypes IN VARCHAR2,
        AcceptableLogoTypes IN VARCHAR2,
        SystemVersion IN VARCHAR2,
        CopyrightInformation IN VARCHAR2,
        NoContentMessageOrders IN VARCHAR2,
        NoContentMessageQuotes IN VARCHAR2,
        NoContentMessageLeads IN VARCHAR2,
        NoContentMessageContacts IN VARCHAR2,
        NoContentMessageUpcomingEvents IN VARCHAR2,
        NoContentMessageFeatureAnnouncements IN VARCHAR2,
        NoContentMessageBuilderNews IN VARCHAR2,
        NoContentMessageJobBoard IN VARCHAR2,
        DailyNotificationTimeUtc IN VARCHAR2,
        WeeklyNotificationTimeUtc IN VARCHAR2,
        NotificationDayOfTheWeek IN VARCHAR2,
        NotificationSliderSpeed IN NUMBER,
        ThrottlingThreshold IN NUMBER,
        ThrottlingDelay IN NUMBER,
        UserId IN NUMBER,
        IpAddress IN VARCHAR2,
        OutputId OUT NUMBER
)
AS 
BEGIN
        
    INSERT INTO "SystemVariable" (
        "MinimumPasswordLength",
        "LoginConfirmationDays",
        "PasswordResetConfirmationDays",
        "LoginRetries",
        "SessionTimeout",
        "MaximumAttachmentSize",
        "AcceptableAttachmentTypes",
        "AcceptableLogoTypes",
        "SystemVersion",
        "CopyrightInformation",
        "NoContentMessageOrders",
        "NoContentMessageQuotes",
        "NoContentMessageLeads",
        "NoContentMessageContacts",
        "NoContentMessageUpcomingEvents",
        "NoContentMessageFeatureAnnouncements",
        "NoContentMessageBuilderNews",
        "NoContentMessageJobBoard",
        "DailyNotificationTimeUtc",
        "WeeklyNotificationTimeUtc",
        "NotificationDayOfTheWeek",
        "NotificationSliderSpeed",
        "ThrottlingThreshold",
        "ThrottlingDelay",
        "CreatedBy",
        "CreatedDate", 
        "IpAddress"
    ) VALUES (
        MinimumPasswordLength,
        LoginConfirmationDays,
        PasswordResetConfirmationDays,
        LoginRetries,
        SessionTimeout,
        MaximumAttachmentSize,
        AcceptableAttachmentTypes,
        AcceptableLogoTypes,
        SystemVersion,
        CopyrightInformation,
        NoContentMessageOrders,
        NoContentMessageQuotes,
        NoContentMessageLeads,
        NoContentMessageContacts,
        NoContentMessageUpcomingEvents,
        NoContentMessageFeatureAnnouncements,
        NoContentMessageBuilderNews,
        NoContentMessageJobBoard,
        DailyNotificationTimeUtc,
        WeeklyNotificationTimeUtc,
        NotificationDayOfTheWeek,
        NotificationSliderSpeed,
        ThrottlingThreshold,
        ThrottlingDelay,
        UserId,
        CURRENT_TIMESTAMP,
        IpAddress
    )
    RETURNING "SystemVariableId" into OutputId;
     
END SYSTEMVARIABLES_CREATE;
/