CREATE OR REPLACE PROCEDURE abs_mdi."TRIMCOLORSELECTION_CREATE" 
(
    BuildingNumber IN NUMBER,
    RoofPanel IN VARCHAR2,
    WallPanel IN VARCHAR2,
    EaveFlash IN VARCHAR2,
    GableFlash IN VARCHAR2,
    CornerFlash IN VARCHAR2,
    BaseFlash IN VARCHAR2,
    AllOtherFlash IN VARCHAR2,
    RoofGuarantee IN VARCHAR2,
    WallGuarantee IN VARCHAR2,
    PerforationGuarantee IN NUMBER,
    YearPaint IN VARCHAR2,
    StructPaint IN NUMBER,
    Gutters IN VARCHAR2,
    Downspouts IN VARCHAR2,
    FinishWall IN VARCHAR2,
    FinishRoof IN VARCHAR2,
    FinishEave IN VARCHAR2,
    FinishGable IN VARCHAR2,
    FinishCorner IN VARCHAR2,
    FinishAllOther IN VARCHAR2,
    FinishBase IN VARCHAR2,
    FinishGutter IN VARCHAR2,
    FinishDownspouts IN VARCHAR2,
    AllTrimSameColor IN NUMBER,
    RoofToRoof IN VARCHAR2,
    RoofToWall IN VARCHAR2,
    RoofInteriorSkin IN VARCHAR2,
    WallInteriorSkin IN VARCHAR2,
    RoofPanelValsparCode IN VARCHAR2,
    RoofPanelSpecialName IN VARCHAR2,
    WallPanelValsparCode IN VARCHAR2,
    WallPanelSpecialName IN VARCHAR2,
    EaveFlashValsparCode IN VARCHAR2,
    EaveFlashSpecialName IN VARCHAR2,
    GableFlashValsparCode IN VARCHAR2,
    GableFlashSpecialName IN VARCHAR2,
    CornerFlashValsparCode IN VARCHAR2,
    CornerFlashSpecialName IN VARCHAR2,
    BaseFlashValsparCode IN VARCHAR2,
    BaseFlashSpecialName IN VARCHAR2,
    AllOtherFlashValsparCode IN VARCHAR2,
    AllOtherFlashSpecialName IN VARCHAR2,
    GuttersValsparCode IN VARCHAR2,
    GuttersSpecialName IN VARCHAR2,
    DownspoutsValsparCode IN VARCHAR2,
    DownspoutsSpecialName IN VARCHAR2,
    RoofToRoofValsparCode IN VARCHAR2,
    RoofToRoofSpecialName IN VARCHAR2,
    RoofToWallValsparCode IN VARCHAR2,
    RoofToWallSpecialName IN VARCHAR2,
    RoofInteriorSkinValsparCode IN VARCHAR2,
    RoofInteriorSkinSpecialName IN VARCHAR2,
    WallInteriorSkinValsparCode IN VARCHAR2,
    WallInteriorSkinSpecialName IN VARCHAR2,
    WalkDoors IN VARCHAR2,
    WalkDoorsValsparCode IN VARCHAR2,
    WalkDoorsSpecialName IN VARCHAR2,
    CreatedBy IN NUMBER,
    IpAddress IN VARCHAR2,
    OutputId OUT NUMBER
)
AS 
BEGIN
    INSERT INTO "Input_TrimColorSelections"
    (
        "BuildingNumber",
        "RoofPanel",
        "WallPanel",
        "EaveFlash",
        "GableFlash",
        "CornerFlash",
        "BaseFlash",
        "AllOtherFlash",
        "RoofGuarantee",
        "WallGuarantee",
        "PerforationGuarantee",
        "YearPaint",
        "StructPaint",
        "Gutters",
        "Downspouts",
        "FinishWall",
        "FinishRoof",
        "FinishEave",
        "FinishGable",
        "FinishCorner",
        "FinishAllOther",
        "FinishBase",
        "FinishGutter",
        "FinishDownspouts",
        "AllTrimSameColor",
        "RoofToRoof",
        "RoofToWall",
        "RoofInteriorSkin",
        "WallInteriorSkin",
        "RoofPanelValsparCode",
        "RoofPanelSpecialName",
        "WallPanelValsparCode",
        "WallPanelSpecialName",
        "EaveFlashValsparCode",
        "EaveFlashSpecialName",
        "GableFlashValsparCode",
        "GableFlashSpecialName",
        "CornerFlashValsparCode",
        "CornerFlashSpecialName",
        "BaseFlashValsparCode",
        "BaseFlashSpecialName",
        "AllOtherFlashValsparCode",
        "AllOtherFlashSpecialName",
        "GuttersValsparCode",
        "GuttersSpecialName",
        "DownspoutsValsparCode",
        "DownspoutsSpecialName",
        "RoofToRoofValsparCode",
        "RoofToRoofSpecialName",
        "RoofToWallValsparCode",
        "RoofToWallSpecialName",
        "RoofInteriorSkinValsparCode",
        "RoofInteriorSkinSpecialName",
        "WallInteriorSkinValsparCode",
        "WallInteriorSkinSpecialName",
        "WalkDoors",
        "WalkDoorsValsparCode",
        "WalkDoorsSpecialName",
        "IsDelete",
        "CreatedBy",
        "CreatedDate",
        "IpAddress"
    )
    VALUES
    (
        BuildingNumber,
        RoofPanel,
        WallPanel,
        EaveFlash,
        GableFlash,
        CornerFlash,
        BaseFlash,
        AllOtherFlash,
        RoofGuarantee,
        WallGuarantee,
        PerforationGuarantee,
        YearPaint,
        StructPaint,
        Gutters,
        Downspouts,
        FinishWall,
        FinishRoof,
        FinishEave,
        FinishGable,
        FinishCorner,
        FinishAllOther,
        FinishBase,
        FinishGutter,
        FinishDownspouts,
        AllTrimSameColor,
        RoofToRoof,
        RoofToWall,
        RoofInteriorSkin,
        WallInteriorSkin,
        RoofPanelValsparCode,
        RoofPanelSpecialName,
        WallPanelValsparCode,
        WallPanelSpecialName,
        EaveFlashValsparCode,
        EaveFlashSpecialName,
        GableFlashValsparCode,
        GableFlashSpecialName,
        CornerFlashValsparCode,
        CornerFlashSpecialName,
        BaseFlashValsparCode,
        BaseFlashSpecialName,
        AllOtherFlashValsparCode,
        AllOtherFlashSpecialName,
        GuttersValsparCode,
        GuttersSpecialName,
        DownspoutsValsparCode,
        DownspoutsSpecialName,
        RoofToRoofValsparCode,
        RoofToRoofSpecialName,
        RoofToWallValsparCode,
        RoofToWallSpecialName,
        RoofInteriorSkinValsparCode,
        RoofInteriorSkinSpecialName,
        WallInteriorSkinValsparCode,
        WallInteriorSkinSpecialName,
        WalkDoors,
        WalkDoorsValsparCode,
        WalkDoorsSpecialName,
        'N',
        CreatedBy,
        CURRENT_TIMESTAMP,
        IpAddress
    )
    RETURNING "TrimColorSelectionId" into OutputId;
    
END TRIMCOLORSELECTION_CREATE;
/