CREATE OR REPLACE PROCEDURE abs_mdi."TRIM_SETCOLOR" 
(       
   
    BuildingNumber IN NUMBER,   
    ModifiedBy IN NUMBER,
    IpAddress IN VARCHAR2,   
    EaveFlash IN VARCHAR2,
    GableFlash IN VARCHAR2,
    CornerFlash IN VARCHAR2,
    BaseFlash IN VARCHAR2,
    AllOtherFlash IN VARCHAR2,
    Gutters IN VARCHAR2,
    Downspouts IN VARCHAR2,
    AllTrimSameColor IN NUMBER,
    RoofToRoof IN VARCHAR2,
    RoofToWall IN VARCHAR2,
    EaveFlashValsparCode IN VARCHAR2,
    EaveFlashSpecialName IN VARCHAR2,
    GableFlashValsparCode IN VARCHAR2,
    GableFlashSpecialName IN VARCHAR2,
    CornerFlashValsparCode IN VARCHAR2,
    CornerFlashSpecialName IN VARCHAR2,
    BaseFlashValsparCode IN VARCHAR2,
    BaseFlashSpecialName IN VARCHAR2,
    AllOtherFlashValsparCode IN VARCHAR2,
    AllOtherFlashSpecialName IN VARCHAR2,
    GuttersValsparCode IN VARCHAR2,
    GuttersSpecialName IN VARCHAR2,
    DownspoutsValsparCode IN VARCHAR2,
    DownspoutsSpecialName IN VARCHAR2,
    RoofToRoofValsparCode IN VARCHAR2,
    RoofToRoofSpecialName IN VARCHAR2,
    RoofToWallValsparCode IN VARCHAR2,
    RoofToWallSpecialName IN VARCHAR2,
    WalkDoors IN VARCHAR2,
    WalkDoorsValsparCode IN VARCHAR2,
    WalkDoorsSpecialName IN VARCHAR2,
    EaveFlashColor IN VARCHAR2,
    EaveFlashHashCode IN VARCHAR2,
    GableFlashColor IN VARCHAR2,
    GableFlashHashCode IN VARCHAR2,
    CornerFlashColor IN VARCHAR2,
    CornerFlashHashCode IN VARCHAR2,
    BaseFlashColor IN VARCHAR2,
    BaseFlashHashCode IN VARCHAR2,
    GuttersColor IN VARCHAR2,
    GuttersHashCode IN VARCHAR2,
    DownspoutsColor IN VARCHAR2,
    DownspoutsHashCode IN VARCHAR2,
    AllOtherFlashColor IN VARCHAR2,
    AllOtherFlashHashCode IN VARCHAR2,
    RoofToRoofColor IN VARCHAR2,
    RoofToRoofHashCode IN VARCHAR2,
    RoofToWallColor IN VARCHAR2,
    RoofToWallHashCode IN VARCHAR2,
    WalkDoorsColor IN VARCHAR2,
    WalkDoorsHashCode IN VARCHAR2,
    
    RoofGuarantee IN VARCHAR2,
    WallGuarantee IN VARCHAR2,
    PerforationGuarantee IN Number
)
IS  
TotalCount number; 
BEGIN

    select count(*) into TotalCount from "Input_TrimColorSelections" WHERE "BuildingNumber" = BuildingNumber;-- and "IsDelete" != 'Y';
    if TotalCount != 0 then
        begin            
            UPDATE "Input_TrimColorSelections" SET        
                "BuildingNumber" = BuildingNumber,           
                "EaveFlash" = EaveFlash,
                "GableFlash" = GableFlash,
                "CornerFlash" = CornerFlash,
                "BaseFlash" = BaseFlash,
                "AllOtherFlash" = AllOtherFlash,
                "Gutters" = Gutters,
                "Downspouts" = Downspouts,               
                "AllTrimSameColor" = AllTrimSameColor,
                "RoofToRoof" = RoofToRoof,
                "RoofToWall" = RoofToWall,
                "EaveFlashValsparCode" = EaveFlashValsparCode,
                "EaveFlashSpecialName" = EaveFlashSpecialName,
                "GableFlashValsparCode" = GableFlashValsparCode,
                "GableFlashSpecialName" = GableFlashSpecialName,
                "CornerFlashValsparCode" = CornerFlashValsparCode,
                "CornerFlashSpecialName" = CornerFlashSpecialName,
                "BaseFlashValsparCode" = BaseFlashValsparCode,
                "BaseFlashSpecialName" = BaseFlashSpecialName,
                "AllOtherFlashValsparCode" = AllOtherFlashValsparCode,
                "AllOtherFlashSpecialName" = AllOtherFlashSpecialName,
                "GuttersValsparCode" = GuttersValsparCode,
                "GuttersSpecialName" = GuttersSpecialName,
                "DownspoutsValsparCode" = DownspoutsValsparCode,
                "DownspoutsSpecialName" = DownspoutsSpecialName,
                "RoofToRoofValsparCode" = RoofToRoofValsparCode,
                "RoofToRoofSpecialName" = RoofToRoofSpecialName,
                "RoofToWallValsparCode" = RoofToWallValsparCode,
                "RoofToWallSpecialName" = RoofToWallSpecialName,              
                "WalkDoors" = WalkDoors,
                "WalkDoorsValsparCode" = WalkDoorsValsparCode,
                "WalkDoorsSpecialName" = WalkDoorsSpecialName,   
                "EaveFlashColor" = EaveFlashColor,
                "EaveFlashHashCode" = EaveFlashHashCode,
                "GableFlashColor" = GableFlashColor,
                "GableFlashHashCode" = GableFlashHashCode,
                "CornerFlashColor" = CornerFlashColor,
                "CornerFlashHashCode" = CornerFlashHashCode,
                "BaseFlashColor" = BaseFlashColor,
                "BaseFlashHashCode" = BaseFlashHashCode,
                "GuttersColor" = GuttersColor,
                "GuttersHashCode" = GuttersHashCode,
                "DownspoutsColor" = DownspoutsColor,
                "DownspoutsHashCode" = DownspoutsHashCode,
                "AllOtherFlashColor" = AllOtherFlashColor,
                "AllOtherFlashHashCode" = AllOtherFlashHashCode,
                "RoofToRoofColor" = RoofToRoofColor,
                "RoofToRoofHashCode" = RoofToRoofHashCode,
                "RoofToWallColor" = RoofToWallColor,
                "RoofToWallHashCode" = RoofToWallHashCode,
                "WalkDoorsColor" = WalkDoorsColor,
                "WalkDoorsHashCode" = WalkDoorsHashCode,
                "ModifiedBy" = ModifiedBy,
                "ModifiedDate" = CURRENT_TIMESTAMP,
                "IpAddress" = IpAddress,
                "RoofGuarantee" = RoofGuarantee,
                "WallGuarantee" = WallGuarantee,
                "PerforationGuarantee" = PerforationGuarantee
             WHERE "BuildingNumber" = BuildingNumber;
        end;
    ELSE
        begin
            INSERT INTO "Input_TrimColorSelections"
            (
                "BuildingNumber",
                "EaveFlash",
                "GableFlash",
                "CornerFlash",
                "BaseFlash",
                "AllOtherFlash",              
                "Gutters",
                "Downspouts",          
                "AllTrimSameColor",
                "RoofToRoof",
                "RoofToWall",           
                "EaveFlashValsparCode",
                "EaveFlashSpecialName",
                "GableFlashValsparCode",
                "GableFlashSpecialName",
                "CornerFlashValsparCode",
                "CornerFlashSpecialName",
                "BaseFlashValsparCode",
                "BaseFlashSpecialName",
                "AllOtherFlashValsparCode",
                "AllOtherFlashSpecialName",
                "GuttersValsparCode",
                "GuttersSpecialName",
                "DownspoutsValsparCode",
                "DownspoutsSpecialName",
                "RoofToRoofValsparCode",
                "RoofToRoofSpecialName",
                "RoofToWallValsparCode",
                "RoofToWallSpecialName",              
                "WalkDoors",
                "WalkDoorsValsparCode",
                "WalkDoorsSpecialName",
                "EaveFlashColor",
                "EaveFlashHashCode",
                "GableFlashColor",
                "GableFlashHashCode",
                "CornerFlashColor",
                "CornerFlashHashCode",
                "BaseFlashColor",
                "BaseFlashHashCode",
                "GuttersColor",
                "GuttersHashCode",
                "DownspoutsColor",
                "DownspoutsHashCode",
                "AllOtherFlashColor",
                "AllOtherFlashHashCode",
                "RoofToRoofColor",
                "RoofToRoofHashCode",
                "RoofToWallColor",
                "RoofToWallHashCode",
                "WalkDoorsColor",
                "WalkDoorsHashCode",
                "CreatedBy",
                "CreatedDate",
                "RoofGuarantee",
                "WallGuarantee",
                "PerforationGuarantee"
            )
            VALUES
            (
                BuildingNumber,
                EaveFlash,
                GableFlash,
                CornerFlash,
                BaseFlash,
                AllOtherFlash,
                Gutters,
                Downspouts,
                AllTrimSameColor,
                RoofToRoof,
                RoofToWall,
                WalkDoors,            
                EaveFlashValsparCode,
                EaveFlashSpecialName,
                GableFlashValsparCode,
                GableFlashSpecialName,
                CornerFlashValsparCode,
                CornerFlashSpecialName,
                BaseFlashValsparCode,
                BaseFlashSpecialName,
                AllOtherFlashValsparCode,
                AllOtherFlashSpecialName,
                GuttersValsparCode,
                GuttersSpecialName,
                DownspoutsValsparCode,
                DownspoutsSpecialName,
                RoofToRoofValsparCode,
                RoofToRoofSpecialName,
                RoofToWallValsparCode,
                RoofToWallSpecialName,
                WalkDoorsValsparCode,
                WalkDoorsSpecialName,
                EaveFlashColor,
                EaveFlashHashCode,
                GableFlashColor,
                GableFlashHashCode,
                CornerFlashColor,
                CornerFlashHashCode,
                BaseFlashColor,
                BaseFlashHashCode,
                GuttersColor,
                GuttersHashCode,
                DownspoutsColor,
                DownspoutsHashCode,
                AllOtherFlashColor,
                AllOtherFlashHashCode,
                RoofToRoofColor,
                RoofToRoofHashCode,
                RoofToWallColor,
                RoofToWallHashCode,
                WalkDoorsColor,
                WalkDoorsHashCode,
                ModifiedBy,
                CURRENT_TIMESTAMP,
                RoofGuarantee,
                WallGuarantee,
                PerforationGuarantee
            );
        end;     
    end if;
END TRIM_SETCOLOR;
/